mudler/LocalAI

api/api.go

Thanks to @deadprogram for noticing it!

Fix comment typo

---

Makefile
README.md
api/api.go
go.mod
go.sum
pkg/model/loader.go

This is a first stab at supporting cerebras GPT2 model family, for instance with: https://huggingface.co/lxe/Cerebras-GPT-2.7B-Alpaca-SP-ggml
```
~/_git/LocalAI cerebras* 1m 7s
base ❯ curl http://localhost:8080/v1/completions -H "Content-Type: application/json" -d '{
"model": "cerebras",
"prompt": "long time ago, in a galaxy far away",
"temperature": 0.9
}'
{"model":"cerebras","choices":[{"text":", a young man named Isaac Newton was given a great gift. He was given the power to solve the most difficult problems of his time. This was an incredible honor, but it was also a great burden to bear.\n\nOver the years, Isaac Newton has become the most famous mathematician of all time. He has inspired generations of mathematicians, engineers, scientists, and other scientists to explore and …
```

Add support for cerebras

---

Makefile
README.md
api/api.go
go.mod
go.sum
main.go
pkg/model/loader.go

A first stab at supporting stableLM (note, didn't tested with a model, as I don't have HW for converting, and no ggml models are available at the moment publicly)
Fixes #47

Add support for stablelm

---

README.md
api/api.go
api/api_test.go

this returns OpenAI errors to be compliant to the API and update docs with a gpt4all-j example.

feat: Return OpenAI errors and update docs

---

README.md

adding social commentary section with few more links

Anton readme

---

README.md

It is unclear or not if can be used commercially and under which terms

docs: clarify GPT4ALL-J licensing

---

Dockerfile
Makefile
entrypoint.sh

feat: make images to build sources on start

---

README.md
examples/discord-bot/README.md
examples/discord-bot/docker-compose.yaml
prompt-templates/wizardlm.tmpl

- Update helm chart instructions
- Add discord-bot container image
- add example with wizardlm template

docs: enhancements

---

examples/README.md
examples/slack-bot/.env.example
examples/slack-bot/README.md
examples/slack-bot/docker-compose.yaml
examples/slack-bot/models

Adds a slack bot integration example

docs: Add slack-bot example

---

api/openai.go

feat: support slices or strings in the prompt completion endpoint

---

api/openai.go
examples/README.md
examples/langchain-python/README.md
examples/langchain-python/docker-compose.yaml
examples/langchain-python/models
examples/langchain-python/test.py

Returns the usage struct in the API call, and provides a small sample on how to run LocalAI with langchain.
Fixes: https://github.com/go-skynet/LocalAI/issues/159

Return usage in the API responses

---

main.go

LocalAI looks in the top level directory by default, but models are in the models/ directory

Looks for models in $CWD/models/ dir by default

---

api/openai.go
api/prediction.go
examples/README.md
examples/rwkv/Dockerfile.build
examples/rwkv/README.md
examples/rwkv/docker-compose.yaml
examples/rwkv/models/gpt-3.5-turbo.yaml
examples/rwkv/models/rwkv_chat.tmpl
examples/rwkv/models/rwkv_completion.tmpl

This includes a fix for an oversight :facepalm: that was not allowing the rwkv to add any output. I'll try to add a test in the CI for it. also added a full example on how to use rwkv.

rwkv fixes and examples

---

.gitignore
examples/langchain/PY.Dockerfile
examples/langchain/README.md
examples/langchain/langchainjs-localai-example/package-lock.json
examples/langchain/langchainjs-localai-example/package.json
examples/langchain/langchainpy-localai-example/full_demo.py
examples/langchain/langchainpy-localai-example/requirements.txt
examples/langchain/models/gpt-3.5-turbo.yaml

Langchain has some updates upstream worth grabbing - notably, this bumps us over to the full_demo.py which doesn't warn for using the outdated API.

Langchain Example Updates

---

Makefile

Supersedes https://github.com/go-skynet/LocalAI/pull/257

bump: update whisper.cpp

---

Makefile
api/api_test.go
tests/fixtures/rwkv.yaml
tests/fixtures/rwkv_chat.tmpl
tests/fixtures/rwkv_completion.tmpl

Attempt to add a simple rwkv test

tests: add rwkv

---

.github/workflows/bump_deps.yaml
README.md
api/openai.go

- ci fixes for PR auto-bumps
- small docs updates
- do not automatically map roles unless set (`user`/`assistant` was injected automatically if no roles were specified in the config file)
- allow to generate multiple images ( respect the `n` option )

Minor fixes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

This adds a basic template for creating issues

github: add ISSUE_TEMPLATE

---

Makefile

Thanks to @Thireus for noticing it!
See: https://github.com/go-skynet/LocalAI/pull/258

fix: add LLAMA_CUBLAS on BUILD_TYPE=cublas

---

.github/PULL_REQUEST_TEMPLATE.md
.github/stale.yml

This PR only includes configuration for PRs and issues.

feat: add PR template and stale configuration

---

examples/chatbot-ui/models/gpt-3.5-turbo.yaml
examples/langchain/models/gpt-3.5-turbo.yaml
examples/query_data/models/gpt-3.5-turbo.yaml
examples/rwkv/models/gpt-3.5-turbo.yaml

examples: remove threads from example models

---

api/api.go
api/api_test.go
api/openai.go
api/options.go
main.go

This PR fixes #324 . Allows to enable/disable cors and to set a default allow origins.

feat: allow to set cors

---

Dockerfile
Dockerfile.dev

Otherwise applying models might fail if ca-certs aren't in the image (dev)

fix: make sure ca-certificates is present in the container images

---

main.go

fix: re-enable start API message

---

README.md

https://github.com/go-skynet/helm-charts/pull/6 changed the structure of the helm chart values. This commit updates the README to reflect the new structure.

chore: update README to include new Helm values

---

Makefile

Allows to set `STATIC=true` to build static binaries

feat: add static builds

---

api/api.go

feat: add /healthz and /readyz endpoints for kubernetes

---

README.md

docs: Add Mods to projects list

---

Makefile

In some cases rwkv hallucinates and makes the test flaky

ci: set flakeAttempts

---

Dockerfile
Dockerfile.dev

This adds the HEALTHCHECK instruction so docker can tell when the service is healthy

image: add HEALTHCHECK

---

Makefile

fix: fix the make run target

---

.github/workflows/image.yml
Dockerfile

feat: add ffmpeg images

---

.github/workflows/image.yml

Minor issues from #492 . Thanks to @sebastien-prudhomme for catching those up!

fix: correctly assign ffmpeg image tag

---

examples/README.md
examples/telegram-bot/README.md
examples/telegram-bot/docker-compose.yml

This adds an example to run a telegram bot powered by LocalAI (instead of ChatGPT)

examples(telegram): add

---

examples/telegram-bot/docker-compose.yml

example(telegram): drop mongodb

---

Dockerfile

Unifies duplicated `Dockerfile` build commands into a single `requirements` step

Dockerfile: unify duplicated requirements into single step

---

api/config.go
api/openai.go
api/prediction.go

This adds `typical_p` to the model settings and the API calls

feat: add typical_p to model parameters

---

Dockerfile
Makefile

Reverts go-skynet/LocalAI#590
@samm81 this seems to break images - how did you tested it? See #615

Revert "Docker preserve sources"

---

examples/README.md
examples/k8sgpt/README.md
examples/k8sgpt/broken-pod.yaml
examples/k8sgpt/values.yaml

example(k8sgpt): Add k8sgpt example

---

api/config.go
api/prediction.go

Add LowVRAM option parameter

---

examples/README.md
examples/slack-qa-bot/.env.example
examples/slack-qa-bot/README.md
examples/slack-qa-bot/deployment.yaml
examples/slack-qa-bot/docker-compose.yml

example(slack-qa-bot): Add slack QA bot example

---

pkg/gallery/models.go
pkg/gallery/request.go

fix: add omitempty where needed

---

Makefile
api/api.go
internal/version.go
main.go

feat: Add '/version' endpoint and display it in the CLI

---

api/openai.go

fix: return index and delta in stream token

---

pkg/whisper/whisper.go

fix: adapt whisper to bindings updates

---

Makefile

fix(deps): bump go-llama.cpp

---

README.md

Update README with sponsors section

---

.github/workflows/bump_deps.yaml
Makefile
api/api_test.go
cmd/grpc/llama-grammar/main.go
go.mod
pkg/grpc/llm/llama-grammar/llama.go
pkg/grpc/llm/llama/llama.go
pkg/model/initializers.go

The llama-master backend now is just "llama" and the grammar backend is extracted to llama-grammar. Also changes tests so we test the functions only with the specific backend.

refactor: rename "llama-master" and "llama"

---

examples/telegram-bot/docker-compose.yml

Linting for command in docker-compose, since it's obviously a typo 

[Telegram-bot example] Fix lint for command docker-compose

---

api/openai/api.go
api/openai/chat.go
api/openai/completion.go

fix: make completions endpoint more close to OpenAI specification

---

examples/langchain-chroma/query.py
examples/langchain-chroma/store.py

This PR fixes missing openai_api_base on langchain-chroma example

fix missing openai_api_base on langchain-chroma example

---

README.md

Added "BMO Chatbot" to "Projects already using LocalAI to run local models" section."

Added "BMO Chatbot" to "Projects already using LocalAI to run local models" section."

---

README.md
examples/k8sgpt/README.md
examples/k8sgpt/values.yaml

fix(examples): use pinned versions in the k8sgpt example

---

README.md

feat: Update logo

---

examples/k8sgpt/README.md

Update to working k8sgpt + localai example in documentation

---

pkg/grammar/json_schema.go
pkg/grammar/json_schema_test.go

feat: update integer, number and string rules - allow primitives as root types

---

.env

This commit provides a little extra guidance for users when deciding whether to select cublas, openblas, or clblas.

docs: base-Update comments in .env for cublas, openblas, clblas

---

Dockerfile

fix: upgrade pip

---

pkg/backend/llm/llama/llama.go

we were otherwise expecting absolute paths. this make it relative to the model file (as someone would expect)

fix(llama): resolve lora adapters correctly from the model file

---

extra/grpc/diffusers/backend_diffusers.py

Loras that have no alpha would crash otherwise

fix(diffusers): correctly check alpha

---

api/api.go
api/localai/gallery.go

feat: expose all the jobs via `/models/jobs` endpoint

---

extra/grpc/vall-e-x/ttsvalle.py

fix(vall-e-x): make audiopath relative to models

---

.env
Makefile

feat(llama.cpp): update

---

extra/grpc/vllm/backend_vllm.py

This PR fixes vllm when called with a request with an empty top_p

fix(vllm): set default top_p with vllm

---

.env
extra/grpc/autogptq/autogptq.py
extra/grpc/bark/ttsbark.py
extra/grpc/diffusers/backend_diffusers.py
extra/grpc/exllama/exllama.py
extra/grpc/huggingface/huggingface.py
extra/grpc/vall-e-x/ttsvalle.py
extra/grpc/vllm/backend_vllm.py

this allows to customize the maximum number of grpc workers for python backends

feat(python-grpc): allow to set max workers with PYTHON_GRPC_MAX_WORKERS

---

CONTRIBUTING.md

Add the CONTRIBUTING.md

---

.github/workflows/test.yml

ci: cleanup worker

---

main.go

This PR adds the tts (Text to Speach) command to the localai binary.
This PR is related to the issue #816

feat: add tts command line subcommand

---

main.go

Adding the transcript subcommand to the localai binary
This PR is related to #816

Adding transcript subcommand

---

.github/workflows/test-gpu.yml
Dockerfile
Makefile
tests/e2e-fixtures/gpu.yaml
tests/e2e/e2e_suite_test.go
tests/e2e/e2e_test.go

This PR fixes https://github.com/go-skynet/LocalAI/issues/1116

ci: add GPU tests

---

.gitignore

Ignore binary and cloned folder

Update .gitignore for backend/llama.cpp

---

examples/configurations/llava/llava.yaml

This pr changes the llava yaml file to be inline with site and gallery yaml formatting
<!--
Thank you for contributing to LocalAI!

llava.yaml (yaml format standardization)

---

.github/workflows/image.yml

ci(core): add -core images without python deps

---

README.md
docs/content/_index.en.md
docs/content/features/_index.en.md
docs/content/features/gpt-vision.md
docs/content/model-compatibility/vall-e-x.md
docs/content/model-compatibility/vllm.md

docs: Add llava, update hot topics

---

Makefile

This PR fixes https://github.com/mudler/LocalAI/issues/1317

fix: propagate CMAKE_ARGS when building grpc

---

docs/content/features/GPU-acceleration.md
docs/content/getting_started/_index.en.md

I'm trying to get up-to-date the docs, this is just a warm-up :)

docs: Update getting started and GPU section

---

docs/content/getting_started/_index.en.md
docs/content/howtos/easy-setup-docker-cpu.md
docs/content/howtos/easy-setup-docker-gpu.md

Brings the sites images up to date with the newest main copy of Localai

docs: site update fixing old image text / How To update updating GPU and CPU docker pages

---

.github/workflows/test-extra.yml
Makefile
backend/python/diffusers/Makefile
backend/python/diffusers/backend_diffusers.py
backend/python/diffusers/test.py
backend/python/diffusers/test.sh
backend/python/sentencetransformers/test_sentencetransformers.py

This adds a simple test for diffusers and adds a CI job to run it

tests: add diffusers tests

---

docs/content/build/_index.en.md

Added documentation for a working rocm build on archlinux
This PR fixes #404
- [ x ] Yes, I signed my commits.

Documentation for Hipblas

---

Makefile
backend/cpp/llama/Makefile
backend/cpp/llama/grpc-server.cpp

update(llama.cpp): update server, correctly propagate LLAMA_VERSION

---

examples/configurations/README.md
examples/configurations/mixtral/mixtral
examples/configurations/mixtral/mixtral-chat
examples/configurations/mixtral/mixtral.yaml

This PR fixes #1421 . It adds an example to setup mixtral instructor

docs(mixtral): add mixtral example

---

Makefile

Revert ":arrow_up: Update donomii/go-rwkv.cpp"

---

backend/python/exllama2/exllama2_backend.py

Fixes exllama2 backend
`stderr AttributeError: 'BackendServicer' object has no attribute 'seed'`
and
`stderr NameError: name 't' is not defined`

fix: exllama2 backend

---

.github/workflows/release.yaml
.github/workflows/test.yml
backend/cpp/llama/CMakeLists.txt

trying to consume grpc from packages instead of re-compiling it from scratch each time

ci(apple): speedups

---

api/openai/image.go

fix(image-gen): remove default to stablediffusion

---

docs/data/version.json

Update version.json (2.3.0)

---

examples/configurations/README.md
examples/configurations/phi-2.yaml

docs(phi-2): add example

---

.github/workflows/image.yml
.github/workflows/image_build.yml

ci(dockerhub): push images also to dockerhub

---

docs/content/build/_index.en.md

This PR fixes https://github.com/mudler/LocalAI/issues/1581#issuecomment-1893907218, https://github.com/mudler/LocalAI/issues/1327#issuecomment-1849855841, https://github.com/mudler/LocalAI/issues/1327#issue-2009910717, https://github.com/mudler/LocalAI/issues/1274#issue-1988907920

docs: missing golang requirement for local build for debian

---

docs/content/docs/faq.md
docs/content/docs/features/GPU-acceleration.md
docs/content/docs/features/_index.en.md
docs/content/docs/features/audio-to-text.md
docs/content/docs/features/constrained_grammars.md
docs/content/docs/features/embeddings.md
docs/content/docs/features/gpt-vision.md
docs/content/docs/features/image-generation.md
docs/content/docs/features/openai-functions.md
docs/content/docs/features/text-generation.md
docs/content/docs/features/text-to-audio.md
docs/content/docs/reference/compatibility-table.md

docs: re-use original permalinks

---

backend/python/mamba/backend_mamba.py
backend/python/vllm/backend_vllm.py
docs/content/docs/getting-started/quickstart.md
embedded/models/mamba-chat.yaml

vllm: add max_tokens, wire up stream event (fixes https://github.com/mudler/LocalAI/issues/1609)
mamba: fixups, adding examples for mamba-chat
This PR is part of #1588 

feat(extra-backends): Improvements, adding mamba example

---

backend/cpp/llama/grpc-server.cpp

integrate changes from llama.cpp
This PR fixes #1467
Merged the Changes from https://github.com/ggerganov/llama.cpp/blob/master/examples/server/server.cpp
Hardcoded params.cont_batching to true! on line 2471 should this be loaded from env like LLAMACPP_PARALLEL?
- [ x] Yes, I signed my commits.

fix(llama.cpp): Enable parallel requests

---

backend/cpp/llama/grpc-server.cpp

This PR is a follow-up of #1616

fix(llama.cpp): enable cont batching when parallel is set

---

api/api.go
api/options/options.go
embedded/embedded.go
main.go
pkg/startup/model_preload.go
pkg/startup/model_preload_test.go

feat(startup): fetch model definition remotely

---

README.md

This PR fixes HTTP links in README

Fix HTTP links in README.md

---

.github/workflows/image_build.yml

This PR tries to fix red CI on image builds in jobs being worked out on free runners.

ci: cleanup worker before run

---

.github/workflows/test-extra.yml
Dockerfile

Revert "fix(Dockerfile): sycl dependencies"

---

Dockerfile
api/backend/tts.go
api/config/config.go
api/ctx/fiber.go
api/localai/localai.go
api/openai/chat.go
api/openai/completion.go
api/openai/edit.go
api/openai/embeddings.go
api/openai/image.go
api/openai/request.go
api/openai/transcription.go
backend/python/vall-e-x/install.sh
docs/content/docs/features/GPU-acceleration.md
examples/kubernetes/deployment-intel-arc.yaml
examples/kubernetes/deployment.yaml
main.go

This PR fixes https://github.com/mudler/LocalAI/issues/1611
```yaml
name: cloned
backend: valle-x-test
parameters:
model: "cloned-voice"
vall-e:
audio_path: "path-to-wav-source.wav"
```
test it:
```
curl http://localhost:8080/tts -H "Content-Type: application/json" -d '{         
"model": "cloned",
"input":"Hello, this is a test!"
}'
```

feat(tts): respect YAMLs config file, add sycl docs/examples

---

backend/python/vall-e-x/ttsvalle.py
docs/content/docs/features/text-to-audio.md

Voice cloning was broken - it had few regressions due to refactors, but this now works.
I've tested it e2e in runpod.
Updating also the docs

fix(vall-e-x): Fix voice cloning

---

backend/python/common-env/transformers/transformers-nvidia.yml

Add TTS dependency for cuda based builds fixes #1727

---

core/schema/openai.go

Fixes https://github.com/mudler/LocalAI/issues/1744

fix(sse): do not omit empty finish_reason

---

api/openai/chat.go

As we now return parallel function results, we need to handle the case no action was selected at all, or either we have invalid JSON as result

fix(functions): handle correctly when there are no results

---

Makefile

This PR re-adds back tests after https://github.com/mudler/LocalAI/pull/1728
cc @dave-gray101

fix(tests): re-enable tests after code move

---

README.md
docs/content/docs/integrations.md

This pr updates the link on the readme that is under integrations and the integrations page
the readme says "integrations" but really the link should be under how to install or something like that. I am not sure where to best put it.

Edit links in readme and integrations page

---

backend/python/common-env/transformers/transformers-nvidia.yml
backend/python/common-env/transformers/transformers-rocm.yml
backend/python/common-env/transformers/transformers.yml

Minimal changes to versions to update sentence-transformers to the latest version.
#1783
May need more testing, Unable to test build on "rocm" built successfully on default and cublas using master.
- [ x ] Yes, I signed my commits.

depedencies(sentencentranformers): update dependencies

---

.env
docker-compose.yaml

This PR fixes the docker compose main example and aligns it to the new features. There is no need to specify a command and we can replace it with the model list.

fix(docker-compose): update docker compose file

---

docs/content/docs/features/text-generation.md

docs(transformers): add docs section about transformers

---

pkg/model/initializers.go

This is a follow-up of https://github.com/mudler/LocalAI/pull/1845

fix(go-llama): use llama-cpp as default

---

backend/cpp/llama/grpc-server.cpp

fix(llama.cpp): fix eos without cache

---

docs/content/docs/getting-started/build.md

This PR adds documentation for a source build on mac.

docs(mac): improve documentation for mac build

---

.github/workflows/image.yml
.github/workflows/image_build.yml
Dockerfile.aio
Makefile
aio/cpu/README.md
aio/cpu/embeddings.yaml
aio/entrypoint.sh
aio/gpu-8g/embeddings.yaml
aio/gpu-8g/image-gen.yaml

feat(aio): entrypoint, update workflows

---

embedded/models/bakllava.yaml
embedded/models/cerbero.yaml
embedded/models/llava-1.5.yaml
embedded/models/llava-1.6-mistral.yaml
embedded/models/llava-1.6-vicuna.yaml
embedded/models/phi-2-chat.yaml

This PR adds new models to the embedded library

feat(models): add phi-2-chat, llava-1.6, bakllava, cerbero

---

.github/workflows/image.yml

Adds tags for hipblas and Intel GPUs
Closes #1855

ci(aio): publish hipblas and Intel GPU images

---

pkg/model/loader.go
pkg/model/watchdog.go

fix(watchdog): use ShutdownModel instead of StopModel

---

swagger/docs.go
swagger/swagger.json
swagger/swagger.yaml

feat(swagger): update

---

aio/entrypoint.sh
docs/content/docs/reference/aio-images.md

fix(aio): correctly detect intel systems

---

aio/gpu-8g/text-to-text.yaml
aio/intel/text-to-text.yaml
core/http/endpoints/openai/chat.go
embedded/models/hermes-2-pro-mistral.yaml

Otherwise it would have been not possible to correctly detect if either tools or functions were called

fix(tools): correctly render tools response in templates

---

aio/cpu/text-to-text.yaml
aio/gpu-8g/text-to-text.yaml
aio/intel/text-to-text.yaml
embedded/models/hermes-2-pro-mistral.yaml

fix(hermes-2-pro-mistral): add stopword for toolcall

---

core/config/backend_config.go
core/http/endpoints/openai/request.go

fix(functions): respect when selected from string

---

.github/workflows/image.yml
.github/workflows/image_build.yml

This PR fixes #1906 (or, it tries!)

fix(ci): manually tag latest images

---

.github/workflows/image_build.yml

ci: push latest images for dockerhub

---

backend/python/common-env/transformers/install.sh

Some models benefit from having FlashAttention installed, e.g. Command-R with vLLM backend currently displays the following with LocalAI master:
```
11:35PM DBG GRPC(CohereForAI/c4ai-command-r-v01-127.0.0.1:36135): stdout INFO 04-10 23:35:40 selector.py:51] Cannot use FlashAttention because the package is not found. Please install it for better performance.
11:35PM DBG GRPC(CohereForAI/c4ai-command-r-v01-127.0.0.1:36135): stdout INFO 04-10 23:35:40 selector.py:25] Using XFormers backend.
```
With this PR, the following is displayed:
```
11:57PM DBG GRPC(CohereForAI/c4ai-command-r-v01-127.0.0.1:36083): stdout INFO 04-10 23:57:37 selector.py:16] Using FlashAttention backend.
```
This PR fixes #1994
Looks like there is a version of FlashAttention for …

feat: add flash-attn in nvidia and rocm envs

---

core/http/api_test.go
core/http/endpoints/localai/gallery.go
core/services/gallery.go
docs/content/docs/features/model-gallery.md
pkg/gallery/op.go

feat(gallery): support ConfigURLs

---

.github/workflows/release.yaml

ci: fix release pipeline missing dependencies

---

.github/workflows/dependabot_auto.yml
.github/workflows/localaibot_automerge.yml

minor fix - bump some checkout@v3 to checkout@v4 to match and clean up warnings

fix - correct checkout versions

---

docs/content/docs/overview.md

docs: fix stores link

---

pkg/model/loader_test.go
pkg/model/model_suite_test.go

tests: add template tests

---

.github/workflows/generate_grpc_cache.yaml
.github/workflows/image-pr.yml
.github/workflows/image.yml
.github/workflows/image_build.yml
Dockerfile

This adds a new workflow "generate and publish GRPC docker caches" which can be run as-needed to generate a GRPC docker cache associated with the master branch.  This will allow builds for the master branch, and other branches/PRs off the master branch to that cache.  This should resolve the issue where a cache generated by one branch cannot use a cache generated by a sibling branch (only cached generated by itself, or by parent branches).
It also adjusts the other builds to leverage this cache, and not generate caches on their own, which should reduce the cache churning, which was resulting in excessive cache misses.
It also adds the ability to specify a different base image to use for the GRPC build, this allows us to pre-build GRPC using a standard ubuntu:22.04 image, …

feat: better control of GRPC docker cache

---

aio/cpu/text-to-text.yaml
aio/gpu-8g/text-to-text.yaml
aio/intel/text-to-text.yaml
embedded/models/hermes-2-pro-mistral.yaml
embedded/models/llama3-instruct.yaml
pkg/model/loader_test.go

This PR adds llama3 to the embedded models. 
I'm also prepping to move the gallery over here so it's easier to maintain.

models(llama3): add llama3 to embedded models

---

core/cli/run.go
gallery/bert-embeddings.yaml
gallery/index.yaml
gallery/stablediffusion.yaml
gallery/tinydream.yaml
gallery/virtual.yaml
gallery/whisper-base.yaml
main.go

my plan is:
- add back the gallery directly here so it's easier to maintain and keep track of things (this PR)
- add the models in embedded into the gallery
- create a very barebone interface in the webui so models can be searched/installed from the gallery (hence why #2077, as I started to need to add UI routes )

models(gallery): add gallery

---

backend/backend.proto
backend/python/vllm/backend_vllm.py
core/backend/options.go
core/config/backend_config.go

Add tensor_parallel_size setting to vllm setting items

---

core/cli/models.go

fix: typo in models.go

---

backend/python/transformers/transformers_server.py

This PR enhances the reliability of our integration with the OpenAI API by improving the handling of the max_tokens parameter in requests to the transformer backend.
As per the OpenAI [API documentation](https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens), `max_tokens` is an optional parameter. To ensure optimal performance, this PR proposes using the maximum context size minus the prompt tokens as the default value, rather than the current arbitrary value of 200. This change allows for more efficient processing while still enabling users to override the default by specifying a custom `max_tokens` value for each request.

Transformers Backend: max_tokens adherence to OpenAI API

---

.dockerignore
.gitignore
Dockerfile
core/http/endpoints/openai/assistant.go

Clean up some low-hanging fruit that SonarQube identified.

Fix cleanup sonarqube findings

---

core/http/elements/gallery.go
core/http/routes/ui.go
core/http/views/models.html

Show image if present, URL, tags, and better display buttons

feat(models-ui): minor visual enhancements

---

backend/python/diffusers/diffusers-rocm.yml
backend/python/diffusers/diffusers.yml

the opencv issue noted in #2107
tested by installing on a running pod, rebuild is a toughy
there are still ongoing issues however this allows the txt2vid pipeline to complete
not sure if we want to version lock this package so i left it open
I have yet to figure out what exactly the problem is that prevents the generated frames from being appended to the image after sorting the opencv issue. 
maybe if we could fix this so that it generates an mp4 and have it all stuck together with ffmpeg or something.

Incl ocv pkg for diffsusers utils

---

aio/cpu/text-to-text.yaml
aio/gpu-8g/text-to-text.yaml
aio/intel/text-to-text.yaml
embedded/models/hermes-2-pro-mistral.yaml
gallery/hermes-2-pro-mistral.yaml
gallery/index.yaml
gallery/noromaid.yaml
gallery/parler-tts.yaml
gallery/rerankers.yaml
pkg/model/loader_test.go

Adds few models to the gallery

models(gallery): add new models to the gallery

---

core/startup/config_file_watcher.go

This fixes the new api_keys.json polling fallback.  Previously it was not pointing to the correct filepath, so every poll interval the apiKeys would be set to whatever was present and discovered at startup.
Also added a little bit of trace level logging as part of the debugging process and decided to leave it in place just in case.

fix: api key polling was not using correct filepath

---

gallery/index.yaml

This is mostly to have alternative quants that fits smaller GPUs

models(gallery): add variants of llama3 70b

---

core/backend/options.go
core/startup/startup.go
embedded/embedded.go
examples/semantic-todo/main.go
main.go
pkg/assets/list.go
pkg/grpc/server.go

first group of error handlers to reduce security scanner warning noise level
This category makes up the bulk of the warnings (versus warnings), and I don't want to touch everything at once. Picked a random subset of ones with obvious handlers.

fix: security scanner warning noise: error handlers part 1

---

gallery/index.yaml

This PR adds https://huggingface.co/Weyaxi/Einstein-v6.1-Llama3-8B to the model gallery

models(gallery): add Einstein v6.1

---

gallery/index.yaml

This PR adds SOVL: https://huggingface.co/Lewdiculous/SOVL_Llama3_8B-GGUF-IQ-Imatrix

models(gallery): add SOVL

---

gallery/index.yaml

This PR adds Average normie: https://huggingface.co/Lewdiculous/Average_Normie_l3_v1_8B-GGUF-IQ-Imatrix

models(gallery): add average_normie

---

gallery/index.yaml

This PR adds https://huggingface.co/Sao10K/L3-Solana-8B-v1-GGUF

models(gallery): add solana

---

gallery/index.yaml

This PR adds https://huggingface.co/Lewdiculous/Poppy_Porpoise-v0.7-L3-8B-GGUF-IQ-Imatrix to the gallery

models(gallery): add poppy porpoise

---

gallery/index.yaml

This PR adds https://huggingface.co/Undi95/Llama-3-LewdPlay-8B-evo-GGUF to the gallery

models(gallery): add Undi95/Llama-3-LewdPlay-8B-evo-GGUF

---

gallery/index.yaml
gallery/llama3-instruct.yaml

This PR adds https://huggingface.co/BioMistral/BioMistral-7B

models(gallery): add biomistral-7b

---

README.md
docs/content/docs/advanced/_index.en.md
docs/content/docs/features/model-gallery.md
docs/content/docs/features/reranker.md
docs/content/docs/features/text-to-audio.md
docs/content/docs/integrations.md
docs/content/docs/overview.md
docs/content/docs/reference/_index.en.md

Adds rerankers documentation, update gallery docs

docs: update gallery, add rerankers

---

docs/content/docs/getting-started/build.md

1. Updated the model from `gpt4all-j` to `phi-2`, the latter one has only half the size of the original, easier to download
2. Added one additional trouble shooting entry
This PR fixes https://github.com/mudler/LocalAI/issues/1720

Issue-1720: Updated `Build on mac` documentations

---

.github/bump_docs.sh

This PR fixes #2175 and all its friends

fix: github bump_docs.sh regex to drop emoji and other text

---

gallery/index.yaml
gallery/openvino.yaml

This PR adds the following OpenVINO models to the gallery:
- https://huggingface.co/fakezeta/llama-3-8b-instruct-ov-int8
- https://huggingface.co/fakezeta/Phi-3-mini-128k-instruct-ov-int8
- https://huggingface.co/fakezeta/Starling-LM-7B-beta-openvino-int8
- https://huggingface.co/fakezeta/Not-WizardLM-2-7B-ov-int8
Thanks @fakezeta for providing the models/configuration and, especially for taking care of the OpenVINO support in LocalAI!

models(gallery): add openvino models

---

Dockerfile

This adds one more target to the dockerfile to give a home to a BUILD_TYPE specific target.  The targets are now as follows:
- requirements-core - Common to ALL images
- requirements-extras - Image adjustments for IMAGE_TYPE=extras
- requirements-drivers - Image adjustments specific to different BUILD_TYPE values. This is built on top of either requirements-core or requirements-extras per IMAGE_TYPE
- grpc - The GRPC build cache
- builder - Performs LocalAI compilation. This is now built on top of requirements-drivers
- final - The actual build target. This is now built on top of requirements-drivers
The only major difference is moving the cublas and clblas sections into requirements-drivers. I also found a couple of RUN commands that we could …

feat: organize Dockerfile into distinct sections

---

gallery/index.yaml

This PR adds https://huggingface.co/Orenguteng/Llama-3-8B-LexiFun-Uncensored-V1-GGUF to the gallery

models(gallery): add lexifun

---

gallery/index.yaml

This PR adds https://huggingface.co/lightblue/suzume-llama-3-8B-multilingual-gguf to the gallery

models(gallery): add suzume-llama-3-8B-multilingual-gguf

---

gallery/index.yaml
gallery/wizardlm2.yaml

This PR adds WizardLM2 7b: https://huggingface.co/MaziyarPanahi/WizardLM-2-7B-GGUF

models(gallery): add wizardlm2

---

gallery/index.yaml

This PR adds https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-8B-GGUF

models(gallery): Add Hermes-2-Pro-Llama-3-8B-GGUF

---

aio/cpu/text-to-text.yaml
aio/gpu-8g/text-to-text.yaml
aio/intel/text-to-text.yaml

This PR switches the AIO default LLM to hermes-2-pro based on llama3

feat(aio): switch to llama3-based for LLM

---

core/http/static/chat.js
core/http/static/general.css
core/http/views/chat.html

This PR enables multi-line messages (and adds some style to the prompt):

feat(ui): support multilineand style `ul`

---

gallery/index.yaml
gallery/moondream.yaml

This PR fixes some typos and adds https://huggingface.co/vikhyatk/moondream2!

models(gallery): add moondream2

---

gallery/index.yaml

This PR adds https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-gguf to the gallery

models(gallery): add llama3-llava

---

core/http/views/partials/navbar.html

This is a small PR to make sure the navbar is displayed properly also on smaller screens

fix(webui): display small navbar with smaller screens

---

gallery/index.yaml

This PR adds https://huggingface.co/rombodawg/Llama-3-8B-Instruct-Coder to the gallery

models(gallery): add llama3-instruct-coder

---

gallery/index.yaml

This PR adds https://huggingface.co/NeverSleep/Llama-3-Lumimaid-8B-v0.1-GGUF

models(gallery): add lumimaid

---

core/http/app_test.go

This PR actually checks the response URL from image gen in `app_test.go`

test: check the response URL during image gen in `app_test.go`

---

backend/python/transformers/transformers_server.py

OpenVINO docs suggest to disable winograd convolutions on GPU while working on a fine tuned model because inference may give an inaccuracy and performance drop on GPU.
https://docs.openvino.ai/2024/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device.html
Winograd convolutions were always disabled giving error when inference device was CPU. 
This commit implement logic to disable Winograd convolutions only if CPU or NPU are declared.

fix: OpenVINO winograd always disabled

---

README.md

Added ShellOracle, a smart terminal shell command generation utility, to README community integrations section.

Update readme: add ShellOracle to community integrations

---

docs/content/docs/getting-started/build.md

This PR fixes some missing Homebrew dependencies

Add missing Homebrew dependencies

---

gallery/index.yaml

This PR adds https://huggingface.co/Lewdiculous/Llama-3-Soliloquy-8B-v2-GGUF-IQ-Imatrix to the gallery

models(gallery): Add Soliloquy

---

core/http/elements/gallery.go
core/http/endpoints/localai/welcome.go
core/http/endpoints/openai/request.go
core/http/routes/ui.go
core/http/static/chat.js
core/http/static/general.css
core/http/views/chat.html
core/http/views/index.html
core/http/views/models.html
pkg/gallery/request.go
pkg/xsync/map.go

As per the title + make also the models in the index clickable, and display as table
Fixes #2257

feat(ui): prompt for chat, support vision, enhancements

---

gallery/index.yaml

This PR adds https://huggingface.co/bartowski/Tess-2.0-Llama-3-8B-GGUF

models(gallery): add tess

---

gallery/index.yaml

This PR adds https://huggingface.co/Lewdiculous/Kunocchini-7b-128k-test-GGUF-Imatrix

models(gallery): add kunocchini

---

gallery/index.yaml

This PR adds https://huggingface.co/Lewdiculous/Aurora_l3_8B-GGUF-IQ-Imatrix to the gallery

models(gallery): add aurora

---

gallery/index.yaml

This PR adds https://huggingface.co/bartowski/Tiamat-8b-1.2-Llama-3-DPO-GGUF

models(gallery): add tiamat

---

.github/checksum_checker.sh
.github/workflows/checksum_checker.yaml

This PR  is an attempt to have a pipeline that checks automatically the checksum of the files - this is an attempt as for now that seems to work locally, but needs some tests on the pipelines here

ci: add checksum checker pipeline

---

gallery/index.yaml

This PR adds https://huggingface.co/fakezeta/Llama3-Aloe-8B-Alpha-ov-int8 from @fakezeta !

models(gallery): add aloe

---

Makefile

build: do not specify a BUILD_ID by default

---

examples/semantic-todo/README.md

docs: Update semantic-todo/README.md

---

gallery/index.yaml

This PR adds https://huggingface.co/xxx777xxxASD/L3-ChaoticSoliloquy-v1.5-4x8B

models(gallery): add l3-chaoticsoliloquy-v1.5-4x8b

---

gallery/index.yaml

This PR adds https://huggingface.co/johnsnowlabs/JSL-MedLlama-3-8B-v2.0

models(gallery): add jsl-medllama-3-8b-v2.0

---

gallery/index.yaml

This PR adds https://huggingface.co/LoneStriker/Llama-3-Refueled-GGUF

models(gallery): add llama-3-refueled

---

gallery/index.yaml

adds https://huggingface.co/TheSkullery/Aura-Llama-Abliterated

models(gallery): add aura-llama-Abliterated

---

gallery/index.yaml

models(gallery): add lumimaidv2

---

gallery/index.yaml

This PR adds orthocopter https://huggingface.co/Lewdiculous/Orthocopter_8B-GGUF-Imatrix

models(gallery): add orthocopter

---

gallery/hermes-2-pro-mistral.yaml
gallery/index.yaml

This PR adds https://huggingface.co/NousResearch/Hermes-2-Theta-Llama-3-8B-GGUF to the gallery

models(gallery): add hermes-2-theta-llama-3-8b

---

gallery/chatml.yaml
gallery/index.yaml

This PR adds:
- https://huggingface.co/upendrab/llama-3-sqlcoder-8b-Q4_K_M-GGUF
- https://huggingface.co/01-ai/Yi-1.5-6B-Chat
- https://huggingface.co/bartowski/SFR-Iterative-DPO-LLaMA-3-8B-R-GGUF
- https://huggingface.co/01-ai/Yi-1.5-6B-Chat
- https://huggingface.co/defog/llama-3-sqlcoder-8b

models(gallery): add yi 6/9b, sqlcoder, sfr-iterative-dpo

---

gallery/index.yaml

This PR adds https://huggingface.co/swap-uniba/LLaMAntino-3-ANITA-8B-Inst-DPO-ITA to the gallery

models(gallery): add anita

---

gallery/index.yaml

This PR adds https://huggingface.co/Sao10K/L3-8B-Stheno-v3.1

models(gallery): add stheno

---

gallery/index.yaml

fix(gallery): checksum Meta-Llama-3-70B-Instruct.Q4_K_M.gguf - #2364

---

core/config/backend_config.go
gallery/index.yaml

This PR fixes adds phi-3-medium

models(gallery): add phi-3-medium-4k-instruct

---

gallery/chatml-hercules.yaml
gallery/index.yaml

This PR adds two new models to the collection:
- https://huggingface.co/nold/HelpingAI-9B-GGUF
- https://huggingface.co/bartowski/Llama-3-Hercules-5.0-8B-GGUF

models(gallery): add hercules and helpingAI

---

.gitignore
aio/cpu/text-to-text.yaml
aio/gpu-8g/text-to-text.yaml
aio/intel/text-to-text.yaml
gallery/command-r.yaml
gallery/hermes-2-pro-mistral.yaml
gallery/index.yaml
gallery/mistral-0.3.yaml
pkg/functions/grammar_json_schema.go
pkg/functions/grammar_json_schema_test.go
pkg/functions/options.go
pkg/functions/parse.go

Add also `disable_parallel_new_lines` to disable newlines in the JSON output when forcing parallel tools. Some models (like mistral) might be very sensible to that when being used for function calling.

models(gallery): add mistral-0.3 and command-r, update functions

---

.github/workflows/release.yaml

SD build ci was missing the release stage

ci: fix sd release

---

gallery/index.yaml

This PR adds https://huggingface.co/mudler/Mirai-Nova-Llama3-LocalAI-8B-v0.1
Mirai Nova is a generalized model which is fine-tuned to work well with LocalAI's JSON grammars functionalities

models(gallery): add Mirai Nova

---

gallery/index.yaml

models(gallery): add minicpm

---

gallery/index.yaml

This PR adds https://huggingface.co/Lewdiculous/Poppy_Porpoise-0.85-L3-8B-GGUF-IQ-Imatrix

models(gallery): add poppy porpoise 0.85

---

gallery/index.yaml

This PR adds https://huggingface.co/fearlessdots/Llama-3-Alpha-Centauri-v0.1-GGUF

models(gallery): add alpha centauri

---

gallery/index.yaml
gallery/phi-3-chat.yaml

models(gallery): add cream-phi-13b

---

gallery/index.yaml

models(gallery): add stheno-mahou

---

backend/python/autogptq/requirements-intel.txt
backend/python/bark/requirements-intel.txt
backend/python/coqui/requirements-intel.txt
backend/python/diffusers/requirements-intel.txt
backend/python/parler-tts/requirements-intel.txt
backend/python/petals/requirements-intel.txt
backend/python/rerankers/requirements-intel.txt
backend/python/sentencetransformers/requirements-intel.txt
backend/python/transformers-musicgen/requirements-intel.txt
backend/python/transformers/requirements-intel.txt
backend/python/vall-e-x/requirements-intel.txt
backend/python/vllm/requirements-intel.txt

fix: pin version of setuptools for intel builds to work around #2406

---

gallery/index.yaml

models(gallery): add iterative-dpo, fix minicpm

---

.github/workflows/generate_grpc_cache.yaml

ci(grpc-cache): also arm64

---

Makefile

This adds more support for hipblas GPU_TARGETS
Related to #1592

feat(hipblas): extend default hipblas GPU_TARGETS

---

gallery/index.yaml

This PR adds https://huggingface.co/Hastagaras/Halu-8B-Llama3-Blackroot

models(gallery): add halu

---

gallery/index.yaml

models(gallery): add neuraldaredevil

---

core/http/endpoints/openai/completion.go
gallery/index.yaml

This PR adds codestral, and allows to template systemprompt from the model config/request

models(gallery): add Codestral

---

.github/workflows/release.yaml
gallery/index.yaml

This PR adds mopeymule to the gallery

models(gallery): add mopeymule

---

gallery/index.yaml

This PR adds Anjir https://huggingface.co/mradermacher/Anjir-8B-L3-i1-GGUF

models(gallery): add anjir

---

gallery/index.yaml

models(gallery): add ultron

---

gallery/index.yaml

This PR adds https://huggingface.co/Lewdiculous/Poppy_Porpoise-1.0-L3-8B-GGUF-IQ-Imatrix

models(gallery): add poppy porpoise 1.0

---

gallery/index.yaml

This PR adds https://huggingface.co/Lewdiculous/Neural-SOVLish-Devil-8B-L3-GGUF-IQ-Imatrix

models(gallery): add Neural SOVLish Devil

---

.github/workflows/release.yaml
.github/workflows/test.yml
Dockerfile
docs/content/docs/getting-started/build.md

ci: pin build-time protoc

---

gallery/index.yaml
gallery/whisper-base.yaml

This PR adds all the whisper variants to the gallery

models(gallery): add all whisper variants

---

gallery/index.yaml

This PR adds /Lewdiculous/Fimbulvetr-11B-v2-GGUF-IQ-Imatrix

models(gallery): add fimbulvetr iqmatrix version

---

gallery/index.yaml

This PR adds the new versions of poppy porpoise

models(gallery): add new poppy porpoise versions

---

docs/content/docs/features/distributed_inferencing.md
docs/content/docs/features/gpt-vision.md

Also change icons on GPT vision page
This PR fixes #2469

docs: fix p2p commands

---

core/http/elements/gallery.go

Do not let the description text to clutter, also highlight the model names

feat(webui): enhance card visibility

---

backend/python/transformers/backend.py
backend/python/transformers/requirements.txt
backend/python/transformers/run.sh

CUDA not working after #2286.
Refactored the code to be more polish
This PR fixes missing libraries and error in CUDA environment.

bugfix: CUDA acceleration not working

---

README.md

This PR adds premai.io as our sponsors ! :partying_face: this helps us **doubling** our current CI workpower and access to a GPU for testing!
Note: I didn't setup the workers yet, but likely will attach them over the week / weekend!

README: update sponsors list

---

gallery/index.yaml

This PR adds dolphin-2.9.2-phi-3 abliterated

models(gallery): add dolphin-2.9.2-phi-3-Medium-abliterated

---

gallery/index.yaml

models(gallery): add phi-3-4x4b

---

gallery/index.yaml

This PR adds llama-3-instruct-8b-SimPO-ExPO

models(gallery): add llama-3-instruct-8b-SimPO-ExPO

---

gallery/index.yaml

models(gallery): add Llama-3-Yggdrasil-2.0-8B

---

gallery/index.yaml

This PR adds  l3-8b-stheno-v3.2-iq-imatrix

models(gallery): add l3-8b-stheno-v3.2-iq-imatrix

---

gallery/index.yaml

This PR adds https://huggingface.co/aifeifei798/llama3-8B-aifeifei-1.0

models(gallery): add llama3-8B-aifeifei-1.0-iq-imatrix

---

gallery/index.yaml

This PR adds rawr_llama3_8b-iq-imatrix

models(gallery): add rawr_llama3_8b-iq-imatrix

---

gallery/index.yaml

This PR adds llama3-8b-feifei-1.0-iq-imatrix

models(gallery): add llama3-8b-feifei-1.0-iq-imatrix

---

core/config/guesser.go

This PR adds automatic model configuration for CommandR-based models

feat(defaults): add defaults for Command-R models

---

README.md

Add integrations

---

gallery/index.yaml

This PR adds https://huggingface.co/aifeifei798/llama3-8B-aifeifei-1.2

models(gallery): add llama3-8B-aifeifei-1.2-iq-imatrix

---

gallery/index.yaml

This PR adds https://huggingface.co/SteelQuants/L3-Aethora-15B-Q4_K_M-GGUF

models(gallery): add l3-aethora-15b

---

gallery/index.yaml

This PR adds https://huggingface.co/HiroseKoichi/Llama-Salad-8x8B

models(gallery): add llama-salad-8x8b

---

gallery/index.yaml

This PR adds  https://huggingface.co/Lewdiculous/Average_Normie_l3_v1_8B-GGUF-IQ-Imatrix

models(gallery): add average_normie_v3.69_8b-iq-imatrix

---

gallery/index.yaml

This PR adds https://huggingface.co/Lewdiculous/duloxetine-4b-v1-GGUF-IQ-Imatrix

models(gallery): add duloxetine

---

gallery/index.yaml

This PR adds https://huggingface.co/bartowski/badger-lambda-llama-3-8b-GGUF just freshly cooked by @bartowski1182 :) :pray:

models(gallery): add badger-lambda-llama-3-8b

---

.github/ci/modelslist.go

This PR adds  image lazy loading to https://models.localai.io

docs(gallery): lazy-load images

---

pkg/assets/extract.go

When offering fallback libs, use the proper env var for darwin
Note: this does not include the libraries itself, but only sets the proper env var for the libs to be picked up on darwin. For the library itself will follow up another PR
Related to #2562

feat(binary): support extracted bundled libs on darwin

---

.github/workflows/release.yaml
Makefile
pkg/assets/extract.go

This PR fixes #2562.
Tested on GHA - seems to work
Depends on #2563 
I've just added all the libs that `otool -L` shows - I'm not sure about runtime.

feat(darwin): embed grpc libs

---

docs/content/docs/getting-started/container-images.md

Fix standard image latest Docker tags

---

gallery/index.yaml

This PR  adds https://huggingface.co/YeungNLP/firefly-gemma-7b

models(gallery): add firefly-gemma-7b

---

gallery/index.yaml

This PR adds dolphin models based on qwen2

models(gallery): add dolphin-qwen

---

gallery/index.yaml

models(gallery): add tess-v2.5-phi-3-medium-128k-14b

---

gallery/index.yaml

models(gallery): add hathor_stable-v0.2-l3-8b

---

gallery/index.yaml

This PR adds https://huggingface.co/macadeliccc/Samantha-Qwen2-7B

models(gallery): add samantha-qwen2

---

core/http/views/talk.html

Minor enhancements to the talk page

feat(talk): display an informative box, better colors

---

gallery/index.yaml

This PR adds https://huggingface.co/Lewdiculous/L3-Umbral-Mind-RP-v1.0-8B-GGUF-IQ-Imatrix

models(gallery): add l3-umbral-mind-rp-v1.0-8b-iq-imatrix

---

gallery/index.yaml

This PR adds https://huggingface.co/DeepMount00/Qwen2-1.5B-Ita-GGUF

models(gallery): add qwen2-1.5b-ita

---

docs/static/install.sh

fix(install.sh): move ARCH detection so it works also for mac

---

backend/backend.proto
backend/go/transcribe/transcript.go
backend/go/transcribe/whisper.go
core/backend/transcript.go
core/cli/transcript.go
core/http/endpoints/openai/transcription.go
core/schema/prediction.go

feat(whisper): add translate option

---

pkg/functions/options.go
pkg/functions/parse.go

feat(grammar): expose properties_order

---

gallery/index.yaml

models(gallery): add dark-idol-1.2

---

gallery/index.yaml

models(gallery): add arcee-spark

---

gallery/index.yaml

models(gallery): add gemma2-9b-it and gemma2-27b-it

---

gallery/index.yaml

models(gallery): add new-dawn-llama

---

gallery/index.yaml

This PR adds https://huggingface.co/ZeusLabs/L3-Aethora-15B-V2

models(gallery): add l3-aethora-15b-v2

---

gallery/index.yaml

This PR adds the llm-compiler model family

models(gallery): add llm-compiler

---

gallery/index.yaml

This PR adds llama3-turbcat-instruct-8b

models(gallery): add llama3-turbcat-instruct-8b

---

.github/workflows/notify-models.yaml
.github/workflows/notify-releases.yaml

ci: add pipelines for discord notifications

---

gallery/index.yaml

This PR adds hercules-5.0-qwen2-7b

models(gallery): add hercules-5.0-qwen2-7b

---

gallery/index.yaml

models(gallery): add llama3-8b-darkidol-2.2-uncensored-1048k-iq-imatrix

---

gallery/index.yaml

This PR adds llama-3-llamilitary

models(gallery): add llama-3-llamilitary

---

gallery/index.yaml

This PR adds tess-v2.5-gemma-2-27b-alpha

models(gallery): add tess-v2.5-gemma-2-27b-alpha

---

gallery/index.yaml

This PR adds https://huggingface.co/crestf411/gemma2-9B-daybreak-v0.5

models(gallery): add gemma2-daybreak

---

gallery/index.yaml

This PR adds https://huggingface.co/DavidAU/L3-Stheno-Maid-Blackroot-Grand-HORROR-16B-GGUF

models(gallery): add L3-Stheno-Maid-Blackroot-Grand-HORROR-16B-GGUF

---

gallery/index.yaml

This PR adds https://huggingface.co/MaziyarPanahi/Qwen2-7B-Instruct-v0.8

models(gallery): add qwen2-7b-instruct-v0.8

---

examples/github-actions/workflow.yml

This PR adds a small example based on our notification pipelines to run LocalAI from GHA workflows

examples(gha): add example on how to run LocalAI in Github actions

---

gallery/index.yaml

models(gallery): add internlm2_5-7b-chat-1m

---

gallery/index.yaml

This PR adds gemma-2-9b-it-sppo-iter3

models(gallery): add gemma-2-9b-it-sppo-iter3

---

.github/workflows/release.yaml
Makefile
scripts/prepare-libs.sh

This PR tries to add tts support to the binary releases as well.
- This PR also adds back MacOS x86_64 binary release assets ( https://github.com/mudler/LocalAI/issues/2650 )

ci(Makefile): adds tts in binary releases

---

gallery/index.yaml

This PR adds https://huggingface.co/SicariusSicariiStuff/LLAMA-3_8B_Unaligned_Alpha

models(gallery): add llama-3_8b_unaligned_alpha

---

gallery/index.yaml

This PR adds https://huggingface.co/bartowski/L3-8B-Lunaris-v1-GGUF

models(gallery): add l3-8b-lunaris-v1

---

.github/workflows/notify-models.yaml
gallery/index.yaml

This PR adds llama-3_8b_unaligned_alpha_rp_soup-i1

models(gallery): add llama-3_8b_unaligned_alpha_rp_soup-i1

---

gallery/index.yaml

This PR adds https://huggingface.co/Nitral-AI/Hathor_Respawn-L3-8B-v0.8

models(gallery): add hathor_respawn-l3-8b-v0.8

---

gallery/index.yaml

This PR adds https://huggingface.co/Replete-AI/Llama3-8B-Instruct-Replete-Adapted

models(gallery): add llama3-8b-instruct-replete-adapted

---

core/http/endpoints/openai/files.go
core/http/endpoints/openai/list.go
core/schema/openai.go

We aren't covering still all of the endpoints yet, this PR is adding coverage for a bunch of api calls. Planning to cover all of the APIs.
Fixes #2728

docs(swagger): enhance coverage of APIs

---

.github/workflows/release.yaml

Hopefully the last piece of https://github.com/mudler/LocalAI/pull/2758 and https://github.com/mudler/LocalAI/pull/2754

ci(grpc): disable ABSEIL tests

---

.github/workflows/release.yaml
.github/workflows/test.yml
Makefile

ci(deps): add libgmock-dev

---

gallery/index.yaml

This PR adds hathor_tahsin-l3-8b-v0.85

models(gallery): add hathor_tahsin-l3-8b-v0.85

---

.github/workflows/release.yaml
.github/workflows/test.yml
Dockerfile

use a sed hack to jam a missing line in place. TODO: Find better method if this works at all.

fix abseil test issue [attempt 3]

---

.github/checksum_checker.sh

This PR fixes
```
python3: can't open file '/home/runner/_work/LocalAI/LocalAI/./check_and_update.py': [Errno 2] No such file or directory
```
https://github.com/mudler/LocalAI/actions/runs/9898409721/job/27345162206
Introduced in: https://github.com/mudler/LocalAI/pull/2566

fix(ci): fixup correct path for check_and_update.py

---

.github/check_and_update.py

@mudler - my dev machine isn't fully set up to run this end to end locally right now, but I noticed some obvious quick fixes. I don't think we can use a PR branch to run a workflow, so I've kicked off a run on my repo's branch... but it's in the queue still.
https://github.com/dave-gray101/LocalAI/actions/runs/9901413340
Side Note: Not sure what's going on with netlify here - I didn't touch the docs in this PR.

fixes to `check_and_update.py` script

---

backend/cpp/grpc/Makefile
backend/cpp/llama/Makefile

This PR fixes # N/A
More Makefile git clone cleanup.

Update remaining git clones to git fetch

---

gallery/index.yaml

This PR adds https://huggingface.co/bartowski/Replete-Coder-Instruct-8b-Merged-GGUF

models(gallery): add replete-coder-instruct-8b-merged

---

gallery/index.yaml

This PR adds arliai-llama-3-8b-formax-v1.0

models(gallery): add arliai-llama-3-8b-formax-v1.0

---

gallery/index.yaml

This PR adds smegmma-deluxe-9b-v1

models(gallery): add smegmma-deluxe-9b-v1

---

gallery/index.yaml

This PR  adds l3-ms-astoria-8b

models(gallery): add l3-ms-astoria-8b

---

gallery/index.yaml

This PR adds halomaidrp-v1.33-15b-l3-i1

models(gallery): add halomaidrp-v1.33-15b-l3-i1

---

scripts/latest_hf.py
scripts/model_gallery_info.py

This PR adds a bunch of scripts I had laying around helping in adding models to the gallery

feat(scripts): add scripts to help adding new models to the gallery

---

gallery/index.yaml

models(gallery): add llamax3

---

gallery/index.yaml

This PR adds arliai-llama-3-8b-dolfin-v0.5

models(gallery): add arliai-llama-3-8b-dolfin-v0.5

---

gallery/index.yaml

This PR adds tiger-gemma-9b-v1-i1

models(gallery): add tiger-gemma-9b-v1-i1

---

core/http/endpoints/jina/rerank.go
core/http/endpoints/localai/gallery.go
core/schema/localai.go

This keeps adding documentation to the swagger API.
There are still some pieces not covered, this adds comment for:
- Gallery endpoints 
- Jina rerankers

docs(swagger): comment LocalAI gallery endpoints and rerankers

---

docs/content/docs/faq.md

Add a note on LocalAI defaults and benchmarks in our FAQ section.
See also https://github.com/mudler/LocalAI/issues/2780

docs: add a note on benchmarks

---

backend/python/openvoice/requirements-intel.txt

Revert "chore(deps): Bump librosa from 0.9.1 to 0.10.2.post1 in /backend/python/openvoice"

---

gallery/index.yaml

This PR adds phi-3.1 which is the updated version of phi3 (Microsoft released it as an in-place upgrade)

models(gallery): add phi-3.1-mini-4k-instruct

---

gallery/index.yaml

This PR adds ezo model series (for Japanese language) for gemma and llama3

models(gallery): add ezo model series (llama3, gemma)

---

Dockerfile

Cleans up some duplicated statements in the Dockerfile

fix: cleanup indentation and remove duplicate dockerfile stanza

---

gallery/index.yaml

This PR adds l3-8b-niitama-v1-i1

models(gallery): add l3-8b-niitama-v1

---

.github/workflows/comment-pr.yaml

This PR  adds a workflow that analyzes the PRs and comments them with a small summary of the changeset (if doesn't pushes outside the ctx limits!)

ci: add workflow to comment new Opened PRs

---

backend/python/diffusers/backend.py
backend/python/diffusers/requirements.txt

fix: Lora loading

---

.github/workflows/comment-pr.yaml
.github/workflows/notify-models.yaml
.github/workflows/notify-releases.yaml
README.md

This PR links to the new GHA and uses it in the workflow to centralize configuration

ci: use github action

---

gallery/index.yaml
gallery/mathstral.yaml

models(gallery): add mathstral-7b-v0.1-imat

---

gallery/index.yaml

This PR adds MythicalMaid and EtherealMaid

models(gallery): add MythicalMaid/EtherealMaid 15b

---

gallery/index.yaml

This PR adds https://huggingface.co/flammenai/Mahou-1.3d-mistral-7B

models(gallery): add flammenai/Mahou-1.3d-mistral-7B

---

docs/content/docs/getting-started/try-it-out.md

docs: update try-it-out.md

---

core/http/endpoints/localai/backend_monitor.go
core/http/endpoints/localai/metrics.go
core/http/endpoints/openai/assistant.go
core/http/endpoints/openai/assistant_test.go
core/http/endpoints/openai/edit.go
core/http/endpoints/openai/files.go
core/http/endpoints/openai/files_test.go
core/schema/openai.go

This PR adds swagger endpoints for part of the assistant api, and for part of the localai endpoints

docs(swagger): core more localai/openai endpoints

---

core/gallery/gallery.go
core/http/endpoints/localai/gallery.go
docs/content/docs/advanced/run-other-models.md
docs/content/docs/getting-started/models.md
docs/content/docs/getting-started/quickstart.md
docs/content/docs/getting-started/try-it-out.md

This PR should finish covering LocalAI endpoints

docs: more swagger, update docs

---

core/cli/federated.go
core/p2p/federated.go
core/p2p/federated_server.go
core/p2p/node.go
core/p2p/p2p.go
core/p2p/p2p_disabled.go

This PR moves the federation logic outside of the cmdline package

refactor: move federated server logic to its own service

---

gallery/index.yaml

models(gallery): add qwen2-wukong-7b

---

gallery/index.yaml

This PR adds gemma-translation

models(gallery): add gemma-2b-translation-v0.150

---

gallery/index.yaml

models(gallery): add emo-2b

---

gallery/index.yaml

models(gallery): add celestev1

---

docs/content/docs/features/distributed_inferencing.md

This PR adds a bit more of documentation on federated mode

docs: add federation

---

backend/python/sentencetransformers/requirements-intel.txt
backend/python/transformers-musicgen/requirements-intel.txt
backend/python/transformers/requirements-intel.txt
backend/python/transformers/requirements.txt

fix: pin setuptools 69.5.1

---

core/http/views/p2p.html

This pr adds a warning if the token isn't detected

feat(p2p): warn the user to start with --p2p

---

backend/cpp/llama/grpc-server.cpp

This PR is an adaptation from the upstream changes in https://github.com/ggerganov/llama.cpp/pull/8607

fix(llama.cpp): do not set anymore lora_base

---

gallery/index.yaml

models(gallery): add llama3.1-claude

---

gallery/index.yaml

This PR adds the new darkidol model, based on llama3.1

models(gallery): add darkidol llama3.1

---

gallery/index.yaml

models(gallery): add gemmoy

---

gallery/index.yaml
gallery/llama3.1-instruct-grammar.yaml

This PR adds a variant of llama3.1 in the gallery based off #3015

models(gallery): add llama3 with enforced functioncall with grammars

---

core/gallery/gallery.go
pkg/utils/strings.go

This PR fixes deletion errors when there are duplicates files listed

fix(gallery): do not attempt to delete duplicate files

---

docs/static/install.sh

fix == to = for sh portability
See: https://github.com/mudler/LocalAI/issues/3037

fix: install.sh bash specific equality check

---

gallery/index.yaml

models(gallery): add lumimaid-v0.2-70b-i1

---

backend/python/transformers-musicgen/requirements-intel.txt

Revert "chore(deps): Bump setuptools from 69.5.1 to 72.1.0 in /backend/python/transformers-musicgen"

---

backend/python/transformers/requirements.txt

Revert "chore(deps): Bump setuptools from 69.5.1 to 72.1.0 in /backend/python/transformers"

---

backend/python/vllm/requirements-intel.txt

Revert "chore(deps): Bump setuptools from 70.3.0 to 72.1.0 in /backend/python/vllm"

---

gallery/index.yaml

models(gallery): add llama-guard-3-8b

---

Makefile

Fixes: https://github.com/mudler/LocalAI/issues/3041

fix(llama-cpp): do not compress with UPX

---

backend/python/openvoice/test.sh

This PR fixes CI tests that are currently failing due to the checkpoints that have been moved

fix(ci): update openvoice checkpoints URLs

---

core/http/endpoints/localai/welcome.go

This PR fixes https://github.com/mudler/LocalAI/issues/3011

fix(ui): do not show duplicate entries if not installed by gallery

---

core/config/guesser.go

This PR fixes gemma model guesser template, and extends for gemma 2
For template: https://ai.google.dev/gemma/docs/formatting 
> Token to indicate the beginning of dialogue turn: <start_of_turn>
> Token to indicate the end of dialogue turn: <end_of_turn>
For repeat penalty:
> In llama.cpp, and other related tools such as Ollama and LM Studio, please make sure that you have these flags set correctly, especially repeat-penalty. Georgi Gerganov (llama.cpp's author) shared his experience in https://huggingface.co/google/gemma-7b-it/discussions/38#65d7b14adb51f7c160769fa1.
https://huggingface.co/google/gemma-2-2b-it-GGUF

feat(guesser): add gemma2

---

Makefile
backend/cpp/llama/grpc-server.cpp

supersedes https://github.com/mudler/LocalAI/pull/3165
https://github.com/ggerganov/llama.cpp/compare/0d6fb52be0c1b7e77eb855f3adc4952771c8ce4c..0a4ce786814b123096d18aadca89cd352b9e590b

chore: :arrow_up: Update ggerganov/llama.cpp

---

Makefile
backend/cpp/llama/grpc-server.cpp

supersedes https://github.com/mudler/LocalAI/pull/3187
Changes: https://github.com/ggerganov/llama.cpp/compare/0a4ce786814b123096d18aadca89cd352b9e590b..1e6f6554aa11fa10160a5fda689e736c3c34169f

chore: :arrow_up: Update ggerganov/llama.cpp to `1e6f6554aa11fa10160a5fda689e736c3c34169f`

---

backend/python/vall-e-x/requirements-hipblas.txt

Seems we need to pin torch for torchaudio

fix(vall-e-x): pin hipblas deps

---

backend/python/diffusers/backend.py
backend/python/diffusers/requirements-cpu.txt
backend/python/diffusers/requirements-cublas11.txt
backend/python/diffusers/requirements-cublas12.txt
backend/python/diffusers/requirements-hipblas.txt
backend/python/diffusers/requirements-intel.txt

This adds support for FLUX models. For instance:
https://huggingface.co/black-forest-labs/FLUX.1-dev

feat(diffusers): support flux models

---

gallery/flux.yaml
gallery/index.yaml

This PR adds flux-dev and flux-schnell to the gallery

models(gallery): add flux.1-dev and flux.1-schnell

---

core/http/elements/gallery.go

This PR makes the images in the model gallery lazy-loaded.
Part of #2156

feat(gallery): lazy load images

---

gallery/hermes-2-pro-mistral.yaml
gallery/index.yaml

models(gallery): add hermes-3

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose-devcontainer.yml

improve devcontainer:
- `-r` fix
- checkout within volume to see if that's more performant.

fix: devcontainer part 1

---

core/http/views/explorer.html
core/p2p/federated_server.go

This adds an informative box to display the command to run to connect to the cluster

chore(explorer): add join instructions

---

core/cli/run.go
core/config/application_config.go
core/http/routes/localai.go
core/p2p/federated.go
core/p2p/federated_server.go
core/p2p/p2p.go

This PR is particularly useful for e.g. instances that are shared via p2p and that are not meant to be modified during runtime (e.g. by installing new models)

chore: allow to disable gallery endpoints, improve p2p connection handling

---

.devcontainer/devcontainer.json

tiny fix of copy path within devcontainer

fix: devcontainer pt 2

---

backend/python/parler-tts/requirements-after.txt
backend/python/parler-tts/requirements.txt

fix(parler-tts): bump and require after build type deps

---

core/http/static/p2panimation.js

Make the animation more interactive!

chore(ux): allow to create and drag dots in the animation

---

.devcontainer-scripts/utils.sh
.devcontainer/customization/README.md

* While updating my customization file to be more robust, decided to add utils.sh, which will simplify onboarding.
* prelim docs in README.md - once devcontainer is fully robust, we can roll out a new page to localai.io

feat: devcontainer part 4

---

docs/content/docs/features/distributed_inferencing.md

This PR updates the p2p docs with the available environment variables

chore(docs): update p2p env var documentation

---

core/cli/run.go
core/p2p/p2p.go
core/p2p/p2p_disabled.go

This PR allows to tweak p2p intervals during token generation

feat(p2p): allow to set intervals

---

core/http/endpoints/openai/chat.go

This was noticed by models returning content besides function calls. Sadly we can't test that easily in the CI so it got unnoticed.

fix(chat): re-generated uuid, created, and text on each request

---

backend/python/autogptq/requirements.txt
backend/python/bark/requirements.txt
backend/python/common/template/requirements.txt
backend/python/coqui/requirements.txt
backend/python/diffusers/requirements.txt
backend/python/exllama/requirements.txt
backend/python/exllama2/requirements.txt
backend/python/mamba/requirements.txt
backend/python/openvoice/requirements-intel.txt
backend/python/openvoice/requirements.txt
backend/python/parler-tts/requirements.txt
backend/python/rerankers/requirements.txt
backend/python/sentencetransformers/requirements.txt
backend/python/transformers-musicgen/requirements.txt
backend/python/transformers/requirements.txt
backend/python/vall-e-x/requirements.txt
backend/python/vllm/requirements.txt

This PR fixes
```
{"level":"debug","time":"2024-08-22T23:33:30Z","message":"GRPC Service state dir: /tmp/go-processmanager3713335805"}
{"level":"debug","time":"2024-08-22T23:33:30Z","message":"GRPC Service Started"}
{"level":"debug","time":"2024-08-22T23:33:30Z","message":"GRPC(all-MiniLM-L6-v2-127.0.0.1:43645): stdout Initializing libbackend for http"}
{"level":"debug","time":"2024-08-22T23:33:30Z","message":"GRPC(all-MiniLM-L6-v2-127.0.0.1:43645): stdout virtualenv activated"}
{"level":"debug","time":"2024-08-22T23:33:30Z","message":"GRPC(all-MiniLM-L6-v2-127.0.0.1:43645): stdout activated virtualenv has been ensured"}
{"level":"debug","time":"2024-08-22T23:33:30Z","message":"GRPC(all-MiniLM-L6-v2-127.0.0.1:43645): stderr Traceback (most recent call last):"} …
```

fix(deps): bump grpcio

---

gallery/hermes-vllm.yaml
gallery/index.yaml
gallery/vllm.yaml

This PR adds Q8 and Q5 for popular models, and sets a reasonable `max_tokens` for defaults vllm models

chore(model-gallery): add more quants for popular models

---

core/cli/worker/worker_p2p.go

This is a fix to allow to pass-by llama.cpp arguments. See also https://github.com/mudler/LocalAI/issues/3364

fix(p2p): correctly allow to pass extra args to llama.cpp

---

Dockerfile
Makefile

chore(cuda): reduce binary size

---

core/backend/tts.go

Otherwise we panic when a res is nil

fix(tts): check error before inspecting result

---

gallery/index.yaml

Revert "models(gallery): add phi-3.5-vision"

---

backend/python/autogptq/requirements.txt
backend/python/bark/requirements.txt
backend/python/common/template/requirements.txt
backend/python/coqui/requirements.txt
backend/python/diffusers/requirements.txt
backend/python/exllama/requirements.txt
backend/python/exllama2/requirements.txt
backend/python/mamba/requirements.txt
backend/python/openvoice/requirements-intel.txt
backend/python/openvoice/requirements.txt
backend/python/parler-tts/requirements.txt
backend/python/rerankers/requirements.txt
backend/python/sentencetransformers/requirements.txt
backend/python/transformers-musicgen/requirements.txt
backend/python/transformers/requirements.txt
backend/python/vall-e-x/requirements.txt
backend/python/vllm/requirements.txt
core/cli/worker/worker.go
core/cli/worker/worker_llamacpp.go
core/cli/worker/worker_p2p.go
docs/content/docs/features/distributed_inferencing.md

This PR makes sure that the user can specify additional worker rpc options in the same way between p2p and non-p2p cases

chore(cli): be consistent between workers and expose ExtraLLamaCPPArgs to both

---

backend/python/diffusers/test.py

chore(tests): replace runaway models for tests

---

gallery/index.yaml

Added Piper Italian voice bundled from https://huggingface.co/rhasspy/piper-voices
The actual file is a tar.gz from a my own github repo where I uploaded it.

feat: Added Piper voice it-paola-medium

---

.github/workflows/release.yaml
.github/workflows/test.yml
Makefile

This PR supersedes https://github.com/mudler/LocalAI/pull/3423
See also https://open-box.readthedocs.io/en/latest/installation/openmp_macos.html

chore(deps): update whisper.cpp

---

aio/intel/image-gen.yaml
backend/python/diffusers/backend.py

This PR purge a few remaining runway model references. These were removed, so they have been swapped out with [Lykon/dreamshaper-8](https://huggingface.co/Lykon/dreamshaper-8) which is the temporary consensus replacement.

fix: purge a few remaining runway model references

---

.github/workflows/secscan.yaml

downgrade to latest known version of the gosec action
See also: https://github.com/securego/gosec/issues/1220

chore(gosec): fix CI

---

Makefile
backend/cpp/llama/grpc-server.cpp

chore(deps): update llama.cpp to 6262d13e0b2da91f230129a93a996609a2fa2f2

---

.github/workflows/secscan.yaml

Revert "chore(deps): Bump securego/gosec from 2.21.0 to 2.21.2"

---

gallery/index.yaml

models(gallery): add qwen2.5-14b-instruct

---

gallery/index.yaml

models(gallery): add qwen2.5-math-7b-instruct

---

gallery/index.yaml

models(gallery): add qwen2.5-14b_uncencored

---

gallery/index.yaml

models(gallery): add qwen2.5-coder-7b-instruct

---

gallery/index.yaml

models(gallery): add qwen2.5-math-72b-instruct

---

gallery/index.yaml

models(gallery): add qwen2.5-0.5b-instruct, qwen2.5-1.5b-instruct

---

gallery/index.yaml

models(gallery): add qwen2.5 32B, 72B, 32B Instruct

---

gallery/index.yaml

models(gallery): add llama3.1-8b-shiningvaliant2

---

docs/content/docs/getting-started/container-images.md

This adds links to the vulkan images

chore(docs): add Vulkan images links

---

gallery/index.yaml

Fix NeuralDaredevil URL

---

backend/python/coqui/requirements.txt

This PR fixes: https://github.com/mudler/LocalAI/issues/2513

feat(coqui): switch to maintained community fork

---

.github/check_and_update.py

This PR fixes 
```
Checking model qwen2.5-14b-instruct, file Qwen2.5-14B-Instruct-Q4_K_M.gguf. URI = huggingface://bartowski/Qwen2.5-14B-Instruct-GGUF/Qwen2.5-14B-Instruct-Q4_K_M.gguf, Checksum = e47ad95dad6ff848b431053b375adb5d39321290ea2c638682577dafca87c008
Traceback (most recent call last):
File "/home/runner/_work/LocalAI/LocalAI/./.github/check_and_update.py", line 44, in <module>
hazard = manual_safety_check_hf(repo_id_or_url)
File "/home/runner/_work/LocalAI/LocalAI/./.github/check_and_update.py", line 32, in manual_safety_check_hf
if scan['hasUnsafeFile']:
KeyError: 'hasUnsafeFile'
Error calculating checksum for Qwen2.5-14B-Instruct-Q4_K_M.gguf. Skipping...
```
@dave-gray101 seems this was broken since a bit :smiling_face_with_tear: …

fix(ci): fixup checksum scanning pipeline

---

gallery/index.yaml

models(gallery): add nightygurps-14b-v1.1

---

core/http/endpoints/localai/system.go
core/schema/localai.go
pkg/model/initializers.go
pkg/model/loader.go
pkg/model/loader_test.go
pkg/model/model.go

This PR adds the list of all the loaded models returned in the `/system` REST api call.

feat(api): list loaded models in `/system`

---

backend/python/autogptq/requirements.txt
backend/python/bark/requirements.txt
backend/python/common/template/requirements.txt
backend/python/coqui/requirements.txt
backend/python/diffusers/requirements.txt
backend/python/exllama2/requirements.txt
backend/python/mamba/requirements.txt
backend/python/openvoice/requirements-intel.txt
backend/python/openvoice/requirements.txt
backend/python/parler-tts/requirements.txt
backend/python/rerankers/requirements.txt
backend/python/sentencetransformers/requirements.txt
backend/python/transformers-musicgen/requirements.txt
backend/python/transformers/requirements.txt
backend/python/vall-e-x/requirements.txt
backend/python/vllm/requirements.txt

chore(deps): bump grpcio to 1.66.2

---

core/p2p/federated_server.go

This PR changes the federated server as such errors to proxy connections are streamed back via http

chore(federated): display a message when nodes are not available

---

pkg/model/loader.go

We default to a soft kill, however, we might want to force killing backends after a while to avoid hanging requests (which may hallucinate indefinetly).
This behavior can be turned on with `LOCALAI_FORCE_BACKEND_SHUTDOWN=true`

feat(shutdown): allow force shutdown of backends

---

gallery/index.yaml

This pull request adds a new model entry to the `gallery/index.yaml` file. The most important change is the addition of the "moe-girl-1ba-7bt-i1" model, which includes details such as its icon, URL, description, and file information.
* Added the "moe-girl-1ba-7bt-i1" model entry with its corresponding icon, URLs, description, and file details.

models(gallery): add moe-girl-1ba-7bt-i1

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "llama3.2-3b-enigma".
* Added a new model entry for "llama3.2-3b-enigma" with its corresponding metadata, including name, icon URL, description, parameters, and file details.

models(gallery): add llama3.2-3b-enigma

---

gallery/index.yaml

This pull request includes updates to the `gallery/index.yaml` file to add a new AI assistant model, `llama3.2-3b-esper2`, which is specialized in DevOps and cloud architecture.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR132-R145): Added a new AI assistant model `llama3.2-3b-esper2` with details including its name, icon, URLs, description, and file parameters. This model is focused on AWS, Azure, GCP, Terraform, Dockerfiles, pipelines, shell scripts, and more.

models(gallery): add llama3.2-3b-esper2

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry is for the "Llama 3.1 Swallow 70B v0.1 i1" model, which enhances Japanese language capabilities while retaining English language capabilities.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR961-R975): Added a new model entry for "Llama 3.1 Swallow 70B v0.1 i1" with detailed description, icon, URLs, and file information.

models(gallery): add llama-3.1-swallow-70b-v0.1-i1

---

gallery/index.yaml

This pull request includes an addition to the `gallery/index.yaml` file to integrate a new model configuration. The most important change is the addition of a new model entry for `qwen2.5-7b-ins-v3`.
Model configuration update:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR421-R435): Added a new model entry for `qwen2.5-7b-ins-v3`, including URLs, description, and file details.

models(gallery): add qwen2.5-7b-ins-v3

---

gallery/index.yaml

This pull request includes an addition to the `gallery/index.yaml` file, introducing a new model entry for "dans-personalityengine-v1.0.0-8b". 
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1345-R1361): Added a new model entry for "dans-personalityengine-v1.0.0-8b" with detailed descriptions, URLs, and file information.

models(gallery): add dans-personalityengine-v1.0.0-8b

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "llama-3.2-3b-agent007". The most important changes include the addition of the model's metadata, URLs, description, and file details.
* Added a new model entry for "llama-3.2-3b-agent007" with the following details:
- Name: "llama-3.2-3b-agent007"
- URLs: `https://huggingface.co/QuantFactory/Llama-3.2-3B-Agent007-GGUF`
- Description: A quantized version of EpistemeAI/Llama-3.2-3B-Agent007, trained 2x faster with Unsloth and Huggingface's TRL library, fine-tuned with Agent datasets.
- File details: 
- Filename: `Llama-3.2-3B-Agent007.Q4_K_M.gguf`
- SHA256: `7a2543a69b116f2a059e2e445e5d362bb7df4a51b97e83d8785c180
**[Signed …

models(gallery): add llama-3.2-3b-agent007

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `nihappy-l3.1-8b-v0.09` model, which is a quantized version of a role-playing model.
Updates to models:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1375-R1387): Added a new model entry for `nihappy-l3.1-8b-v0.09`, including its description, parameters, and file details.

models(gallery): add nihappy-l3.1-8b-v0.09

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry with detailed metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR159-R171): Added a new model entry for `Llama-3.2-3B-Agent007-Coder-GGUF`, including its description, URLs, parameters, and file details.

models(gallery): add llama-3.2-3b-agent007-coder

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `Gemma-2-Ataraxy-v3i-9B`.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2639-R2651): Added a new model entry for `Gemma-2-Ataraxy-v3i-9B`, including its description, URLs, parameters, and file details.

models(gallery): add gemma-2-ataraxy-v3i-9b

---

gallery/index.yaml

This pull request adds a new model entry to the `gallery/index.yaml` file, including metadata, descriptions, and file details for the LLAMA-3_8B_Unaligned_BETA model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR5178-R5197): Added a new model entry for `LLAMA-3_8B_Unaligned_BETA`, including its icon URL, name, description, parameter overrides, and file details.

models(gallery): add llama-3_8b_unaligned_beta

---

gallery/index.yaml

This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry includes details about the Llama3.1-Flammades-70B model, such as its name, icon, URLs, description, and file parameters.
* Added a new model entry for `Llama3.1-Flammades-70B` with the following details:
- Name: "llama3.1-flammades-70b"
- Icon URL: `https://huggingface.co/flammenai/Flammades-Mistral-7B/resolve/main/flammades.png?download=true`
- URLs: 
- `https://huggingface.co/flammenai/Llama3.1-Flammades-70B`
- `https://huggingface.co/mradermacher/Llama3.1-Flammades-70B-GGUF`
- Description: Finetuned on `flammenai/Date-DPO-NoAsterisks` and `jondurbin/truthy-dpo-v0.1` (F9f7389cL1412
**[Signed …

models(gallery): add llama3.1-flammades-70b

---

gallery/index.yaml

This pull request updates the `gallery/index.yaml` file to include a new model entry for `llama3.1-gutenberg-doppel-70b`. The most important change is the addition of this new model with its associated metadata and parameters.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1430-R1446): Added a new model entry for `llama3.1-gutenberg-doppel-70b` with its name, URL, icon, description, and associated files.

models(gallery): add llama3.1-gutenberg-doppel-70b

---

gallery/index.yaml

This pull request adds a new entry to the `gallery/index.yaml` file for the SuperNova-Medius model, providing detailed information about its capabilities and usage.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR475-R489): Added the SuperNova-Medius model, a 14B parameter language model developed by Arcee.ai, built on the Qwen2.5-14B-Instruct architecture. This model is designed for business use cases and is compatible with smaller hardware configurations.

models(gallery): add supernova-medius

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for Hermes-3-Llama-3.1-70B-lorablated.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1481-R1498): Added a new model entry for "hermes-3-llama-3.1-70b-lorablated" with details including name, icon, URLs, description, parameters, and files.

models(gallery): add hermes-3-llama-3.1-70b-lorablated

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for Hermes-3-Llama-3.1-8B-lorablated. The most important changes include adding metadata, URLs, a description, and file details for the new model.
* **New Model Metadata**: Added a new model entry for Hermes-3-Llama-3.1-8B-lorablated, including its name and description. (`gallery/index.yaml`)
* **URLs**: Provided the URL for the new model on Hugging Face. (`gallery/index.yaml`)
* **Description**: Included a detailed description of the model, explaining the extraction and merge process using LoRA adapter. (`gallery/index.yaml`)
* **File Details**: Added file details such as filename, sha256, and URI for the new model. (`gallery/index.yaml`)
**[Signed …

models(gallery): add hermes-3-llama-3.1-8b-lorablated

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `CursorCore-QW2.5-7B-i1`. This model is designed for AI-assisted programming and aims to replicate the core abilities of closed-source tools like Cursor.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR505-R518): Added a new model entry for `CursorCore-QW2.5-7B-i1`, including its description, URLs, parameters, and file details.

models(gallery): add cursorcore-qw2.5-7b-i1

---

gallery/index.yaml

This pull request includes the addition of a new model configuration to the `gallery/index.yaml` file. The new model, named "cursorcore-qw2.5-1.5b-lc-i1," is part of the CursorCore series designed for AI-assisted programming.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR519-R532): Added a new model configuration for "cursorcore-qw2.5-1.5b-lc-i1," including descriptions, URLs, parameters, and file details.

models(gallery): add cursorcore-qw2.5-1.5b-lc-i1

---

gallery/index.yaml

This pull request includes a significant update to the `gallery/index.yaml` file, primarily focusing on the addition of a new model entry for `CursorCore-DS-6.7B-i1`. The changes enhance the gallery by introducing a new AI-assisted programming model, providing detailed metadata, and specifying the relevant files and their sources.
* Added a new model entry for `CursorCore-DS-6.7B-i1`, including:
* A description outlining the model's purpose for AI-assisted programming and its features. (`[gallery/index.yamlR1583-R1596](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1583-R1596)`)
* URLs pointing to the model's hosting locations on Hugging Face. (`[gallery/index.yamlR1583-R1596](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de9 …

models(gallery): add cursorcore-ds-6.7b-i1

---

gallery/index.yaml

This pull request introduces a new model configuration to the `gallery/index.yaml` file. The most important change is the addition of the CursorCore-Yi-9B model, which is designed for AI-assisted programming.
Model Configuration Addition:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4408-R4420): Added configuration for the CursorCore-Yi-9B model, including its name, URLs, description, and file details.

models(gallery): add cursorcore-yi-9b

---

gallery/index.yaml

This pull request includes an addition to the `gallery/index.yaml` file, introducing a new model configuration for `EdgeRunner-Command-Nested`.
New model configuration:
* Added a new model named "EdgeRunner-Command-Nested" with detailed description, URLs, and file information. This model is designed for handling complex nested function calls and is based on Qwen2.5-7B-Instruct, enhanced with the Hermes function call template and additional training on a specialized dataset. (`gallery/index.yaml`)

models(gallery): add edgerunner-command-nested-i1

---

docs/content/docs/integrations.md

This PR adds a the link to LLPhant to the project documentation. LLPhant is a PHP library for interacting with LLMs and Vector Databases

Update integrations.md with LLPhant

---

pkg/model/initializers.go

This is in order to identify also builds which are not using alternatives based on capabilities.
For instance, there are cases when we build the backend only natively in the host.

fix(llama.cpp): consider also native builds

---

gallery/index.yaml

This pull request includes a notable addition to the `gallery/index.yaml` file, introducing a new model configuration for "Llama-3.2-3B-Reasoning-Time".
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR200-R212): Added a new entry for "Llama-3.2-3B-Reasoning-Time", a large language model designed for reasoning and time-based tasks in English. This model is based on the Llama architecture and has been quantized using the GGUF format.

models(gallery): add llama-3.2-3b-reasoning-time

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The changes primarily focus on adding metadata and details for the new model.
Metadata and model details:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2224-R2244): Added a new model entry for "ml-ms-etheris-123b" including its name, URL, icon, description, and file details.

models(gallery): add ml-ms-etheris-123b

---

gallery/index.yaml

This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, "Astral-Fusion-Neural-Happy-L3.1-8B," is designed for dynamic storytelling and immersive roleplaying.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1623-R1638): Added "Astral-Fusion-Neural-Happy-L3.1-8B" with URLs, description, parameters, and file details.

models(gallery): add astral-fusion-neural-happy-l3.1-8b

---

gallery/index.yaml

This pull request introduces a new model entry in the `gallery/index.yaml` file. The most important changes include adding details about the new model, such as its name, icon, URLs, description, and associated files.
* Added a new model entry for "tsunami-0.5x-7b-instruct-i1" with the name, icon URL, and description.
* Included URLs pointing to the model's pages on Hugging Face.
* Provided a detailed description of the model, including its full name and the dataset it was fine-tuned on.
* Added file details, including the filename, SHA256 hash, and URI for the model.

models(gallery): add tsunami-0.5x-7b-instruct-i1

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `Llama-3.1-Nemotron-70B-Instruct-HF`.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1675-R1696): Added a new model entry for `Llama-3.1-Nemotron-70B-Instruct-HF`, including its name, URLs, description, parameters, and file details.

models(gallery): add llama-3.1-nemotron-70b-instruct-hf

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `qevacot-7b-v2` model, including its metadata and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR595-R613): Added `qevacot-7b-v2` model with URLs, description, parameters, and file details.

models(gallery): add qevacot-7b-v2

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "Ethereal Rainbow v1.0."
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1716-R1734): Added "Ethereal Rainbow v1.0" model with details including name, icon, URLs, description, overrides, and associated files.

models(gallery): add l3.1-etherealrainbow-v1.0-rc1-8b

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `mn-lulanum-12b-fix-i1` model, which includes several details such as URLs, description, parameters, and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2380-R2398): Added a new model entry `mn-lulanum-12b-fix-i1` with URLs, description, parameters, and file information.

models(gallery): add mn-lulanum-12b-fix-i1

---

gallery/index.yaml

This pull request includes a change to the `gallery/index.yaml` file to add a new model entry for "tor-8b" with associated metadata.
* Added a new model entry for "tor-8b" with the following details:
* `name`: "tor-8b"
* `icon`: URL to the model's icon image
* `url`: GitHub URL for the model's configuration file
* `urls`: List of URLs where the model can be accessed
* `description`: Detailed description of the model, including its training and fine-tuning specifics
* `overrides`: Parameters specific to the model
* [`files`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2413-R2427): Filename and SHA256 hash for the model file, along with its URI
**[Signed …

models(gallery): add tor-8b

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `Baldur-8B`. The most important changes are as follows:
* Added a new model entry for `Baldur-8B` with the following details:
- `icon`: URL to the model's icon
- `name`: "baldur-8b"
- `urls`: Two URLs pointing to the model on Hugging Face
- `description`: A detailed description of the model's intent and performance
- `overrides`: Parameters specific to the model
- [`files`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1749-R1763): Filename, SHA256 checksum, and URI for the model file

models(gallery): add baldur-8b

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `meissa-qwen2.5-7b-instruct` model with relevant metadata and links.
* Added a new model entry `meissa-qwen2.5-7b-instruct` with the following details:
- Name, icon, and URLs for the model. (`[gallery/index.yamlR614-R630](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR614-R630)`)
- Description highlighting the model's fine-tuning over writing and roleplaying datasets. (`[gallery/index.yamlR614-R630](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR614-R630)`)
- Overrides section specifying model parameters. …

models(gallery): add meissa-qwen2.5-7b-instruct

---

backend/python/mamba/requirements-cpu.txt
backend/python/mamba/requirements-cublas11.txt
backend/python/mamba/requirements-cublas12.txt

causal-conv1d supports only torch 2.4.x, not torch 2.5.x

fix(mamba): pin torch version

---

backend/python/coqui/requirements.txt

This pull request includes a small change to the `backend/python/coqui/requirements.txt` file. The change adds the `packaging` library to the list of dependencies.

chore(deps): pin packaging

---

backend/python/openvoice/requirements.txt

OpenVoice requires a older version https://github.com/myshell-ai/OpenVoice/blob/f3cf835540572ade1460c8952f39d53e4f7952df/requirements.txt#L5

chore(deps): pin numpy

---

backend/python/openvoice/requirements.txt

Revert "chore(deps): Bump gradio from 3.48.0 to 5.0.0 in /backend/python/openvoice in the pip group"

---

gallery/phi-3-vision.yaml

This PR adds multimodal field to the gallery config of phi-3-vision

fix(phi3-vision): add multimodal template

---

docs/content/docs/getting-started/quickstart.md

docs: add Homebrew as an option to install on MacOS

---

.github/workflows/test.yml

fix(ci): drop grpcio-tools pin to apple CI test run

---

.github/workflows/test-extra.yml
backend/python/parler-tts/install.sh
backend/python/parler-tts/requirements-after.txt
backend/python/parler-tts/requirements.txt

fix(parler-tts): pin protobuf

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the L3.1-Moe-2x8B-v0.2 model, including its metadata and file information.
* Added new model entry for `L3.1-Moe-2x8B-v0.2` with metadata such as name, icon, URLs, description, and overrides.
* Included file information for `L3.1-Moe-2x8B-v0.2.Q4_K_M.gguf` with its `sha256` hash and URI.

models(gallery): add l3.1-moe-2x8b-v0.2

---

gallery/index.yaml

This pull request includes a significant update to the `gallery/index.yaml` file, introducing a new AI model called Llama3.1-DarkStorm-Aspire-8B. The most important changes are the addition of the model's metadata, description, and file details.
New AI model introduction:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1799-R1816): Added metadata for the new model `llama3.1-darkstorm-aspire-8b`, including its name, URLs, and a detailed description.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1799-R1816): Included file details for the model, specifying the filename, SHA256 checksum, and URI for downloading the model.
**[Signed …

models(gallery): add llama3.1-darkstorm-aspire-8b

---

core/http/views/partials/footer.html

This pull request includes a small but important change to the `core/http/views/partials/footer.html` file. The change updates the URL for the LocalAI link to point to its GitHub repository instead of its website.
* [`core/http/views/partials/footer.html`](diffhunk://#diff-62c8baf6eb9e2933af7fe680254c0c1b7889dd569d3af210526542eb3057ecf3L3-R3): Updated the LocalAI link to point to the GitHub repository.

chore: change url to github repository

---

gallery/index.yaml

This pull request includes an addition to the `gallery/index.yaml` file to include a new model entry for `llama-3.2-3b-instruct-uncensored`.
* Added `llama-3.2-3b-instruct-uncensored` with associated metadata, including name, icon, URLs, description, parameters, and file details. (`gallery/index.yaml`)

models(gallery): add llama-3.2-3b-instruct-uncensored

---

gallery/index.yaml

This pull request adds a new model entry to the `gallery/index.yaml` file. The new model is a release candidate designed for creative writing and roleplay, and it includes detailed metadata and file references.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1890-R1908): Added a new model entry for `L3.1-70Blivion-v0.1-rc1-70B-i1` with metadata, description, and file references. This model is in the release candidate stage and is intended for creative writing and roleplay.

models(gallery): add l3.1-70blivion-v0.1-rc1-70b-i1

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry provides details about the `delirium-v1` model, including its name, icon, URLs, description, and file parameters.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3302-R3318): Added a new model entry for `delirium-v1`, including its name, icon, URLs, description, and file parameters.

models(gallery): add delirium-v1

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the "L3-Nymeria-Maid-8B" model, which is a merged model combining "Sao10K/L3-8B-Stheno-v3.2" and "princeton-nlp/Llama-3-Instruct-8B-SimPO". This model includes specific configurations and descriptions.
* Added "L3-Nymeria-Maid-8B" model with the following details:
- **Name**: "l3-nymeria-maid-8b"
- **Icon**: URL to the model's icon
- **URLs**: Links to the model on Hugging Face
- **Description**: Detailed description of the model's merge process and intended use
- **Overrides**: Specific parameters for the model
- **Files**: Filename, SHA256 checksum, and URI for the model file
**[Signed …

models(gallery): add l3-nymeria-maid-8b

---

backend/python/diffusers/requirements-hipblas.txt

Revert "chore(deps): Bump torchvision from 0.18.1+rocm6.0 to 0.20.0+cu118 in /backend/python/diffusers"

---

backend/python/autogptq/requirements.txt
backend/python/bark/requirements.txt
backend/python/common/template/requirements.txt
backend/python/coqui/requirements.txt
backend/python/diffusers/requirements.txt
backend/python/exllama2/requirements.txt
backend/python/mamba/requirements.txt
backend/python/openvoice/requirements-intel.txt
backend/python/openvoice/requirements.txt
backend/python/parler-tts/requirements.txt
backend/python/rerankers/requirements.txt
backend/python/sentencetransformers/requirements.txt
backend/python/transformers-musicgen/requirements.txt
backend/python/transformers/requirements.txt
backend/python/vall-e-x/requirements.txt
backend/python/vllm/install.sh
backend/python/vllm/requirements.txt

This pull request updates the `grpcio` dependency across multiple requirement files to version 1.67.1. This change ensures consistency and compatibility across various Python projects.
Dependency Updates:
* [`backend/python/autogptq/requirements.txt`](diffhunk://#diff-326f4c9109482e17ae05b0eb5b30adbaddfa067a59199b82fc18f954ef7e4b65L3-R3): Updated `grpcio` to 1.67.1.
* [`backend/python/bark/requirements.txt`](diffhunk://#diff-a298ae0bd8fb041e45e658764d74d3a0087220ea2d9aa3a66b719e735f5ace07L2-R2): Updated `grpcio` to 1.67.1.
* [`backend/python/common/template/requirements.txt`](diffhunk://#diff-588cd64d1a39b6bfccc024d5faf067ccd3e984f3f1214273ac0b10f8ceba67deL1-R1): Updated `grpcio` to 1.67.1.
* [`backend/python/coqui/requirements.txt`](diffhunk://#diff-09dc1b8d98614c14a8329de …

chore(deps): bump grpcio to 1.67.1

---

gallery/index.yaml

This pull request includes updates to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the "spiral-da-hyah-qwen2.5-72b-i1" model with its associated metadata.
Additions to model entries:
* Added new model entry "spiral-da-hyah-qwen2.5-72b-i1" including name, icon, URLs, description, overrides, and files. (`gallery/index.yaml`)

models(gallery): add spiral-da-hyah-qwen2.5-72b-i1

---

core/http/app_test.go

chore(tests): bump timeouts

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model, `Llama3.1-BestMix-Chem-Einstein-8B`, is designed for instruction-following, chemistry-focused tasks, and long-form conversational generation.
Key changes:
* Added a new model entry `Llama3.1-BestMix-Chem-Einstein-8B` with a detailed description and associated URLs.
* Included parameters and file details for the new model.

models(gallery): add llama3.1-bestmix-chem-einstein-8b

---

gallery/index.yaml

This pull request adds a new language model entry to the `gallery/index.yaml` file. The new entry includes metadata such as the model's name, icon, description, and file details.
New language model addition:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2713-R2730): Added a new entry for the "Starcannon-Unleashed-12B-v1.0" model, including its URLs, description, and file details.

models(gallery): add starcannon-unleashed-12b-v1.0

---

docs/layouts/partials/docs/top-header.html

this PR makes the head configurable, and adds a star us button

chore(docs): add top-header partial

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `WhiteRabbitNeo-2.5-Qwen-2.5-Coder-7B`. This entry includes metadata such as the model name, icon, URLs, description, and file details.
* Added new model entry `WhiteRabbitNeo-2.5-Qwen-2.5-Coder-7B` with the following details:
* Name: "whiterabbitneo-2.5-qwen-2.5-coder-7b"
* Icon URL: `https://huggingface.co/WhiteRabbitNeo/WhiteRabbitNeo-2.5-Qwen-2.5-Coder-7B/resolve/main/whiterabbitneo-logo-defcon.png`
* URLs: 
* `https://huggingface.co/WhiteRabbitNeo/WhiteRabbitNeo-2.5-Qwen-2.5-Coder-7B`
* `https://huggingface.co/bartowski/WhiteRabbitNeo-2.5-Qwen-2.5-Coder-7B-GGUF`
* Description: WhiteRabbitNeo is a model series that can be used for
**[Signed …

models(gallery): add whiterabbitneo-2.5-qwen-2.5-coder-7b

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `llama-3.1-whiterabbitneo-2-8b` model, which includes detailed metadata and file information.
* Added `llama-3.1-whiterabbitneo-2-8b` model with associated metadata, including name, icon, URLs, description, and file details.

models(gallery): add llama-3.1-whiterabbitneo-2-8b

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file, adding new model information for `cybertron-v4-qw7b-mgs`.
* Added a new model entry `cybertron-v4-qw7b-mgs` with the following attributes:
- [`name`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR800-R816): "cybertron-v4-qw7b-mgs"
- [`icon`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR800-R816): URL to the model icon
- [`urls`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR800-R816): List of URLs pointing to the model on Hugging Face
- [`description`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR800-R816): Detailed description of the model and its approach
- …

models(gallery): add cybertron-v4-qw7b-mgs

---

gallery/index.yaml

This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, named "G2-9B-Sugarquill-v0," includes detailed information such as the icon URL, description, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3532-R3550): Added a new model entry for "G2-9B-Sugarquill-v0" with details including icon URL, description, and file specifics.

models(gallery): add g2-9b-sugarquill-v0

---

backend/backend.proto
backend/python/diffusers/backend.py
core/backend/options.go
core/config/backend_config.go

This PR adds support for multiple loras, and ties that in with the diffusers backend.

feat(diffusers): allow multiple lora adapters

---

pkg/model/loader.go

This PR hides safetensors from the model list

chore: hide raw safetensors files

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "valor-7b-v0.1". The most important changes include adding the model's metadata, description, and file details.
* Added a new model entry "valor-7b-v0.1" with metadata including icon URL, source URL, and name.
* Included a description for the new model, highlighting its purpose and dataset used for finetuning.
* Added file details for the new model, including filename, sha256 checksum, and URI.

models(gallery): add valor-7b-v0.1

---

core/p2p/p2p.go
core/p2p/p2p_common.go

This PR fixes decreases logging with p2p enabled, and ties the logging to the p2p logging level that can be set separately.

chore(p2p): enhance logging

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `Tess-R1-Limerick-Llama-3.1-70B`. The most important changes include the addition of the model's metadata, description, and file references.
* Added a new model entry for `Tess-R1-Limerick-Llama-3.1-70B` with its name, icon, and URLs.
* Included a detailed description of the model, explaining its Chain-of-Thought (CoT) reasoning capabilities and usage instructions.
* Listed the model parameters and associated files with their respective `sha256` checksums and URIs.

models(gallery): add tess-r1-limerick-llama-3.1-70b

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model, `llenn-v0.75-qwen2.5-72b-i1`, includes details such as its name, icon, URLs, description, overrides, and associated files.
Changes to the `gallery/index.yaml` file:
* Added a new model entry `llenn-v0.75-qwen2.5-72b-i1` with the following details:
* Name, icon, and URLs
* Description listing the included models
* Overrides specifying model parameters
* Associated file details including filename, sha256, and URI

models(gallery): add llenn-v0.75-qwen2.5-72b-i1

---

gallery/index.yaml

This pull request includes an addition to the `gallery/index.yaml` file, introducing a new model entry for `eva-qwen2.5-14b-v0.2`.
* Added a new model `eva-qwen2.5-14b-v0.2` with detailed description, version notes, and prompt format. The entry includes URLs for downloading the model and specifies the model parameters and file details.

models(gallery): add eva-qwen2.5-14b-v0.2

---

gallery/index.yaml

This pull request adds new entries for OpenCoder models to the `gallery/index.yaml` file. These entries include details about the models, their sources, and their descriptions.
New model entries added:
* [`opencoder-8b-base`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2-R39): Added with details including name, icon, URLs, tags, license, description, parameters, and file information.
* [`opencoder-8b-instruct`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2-R39): Added with details including name, URLs, description, parameters, and file information.

models(gallery): add opencoder-8b instruct and base

---

gallery/index.yaml

This pull request includes updates to the `gallery/index.yaml` file to add new models to the gallery. The changes primarily involve adding descriptions and metadata for two new models in the OpenCoder family.
New model additions:
* Added `opencoder-1.5b-base` model with metadata, including URLs, description, and file details.
* Added `opencoder-1.5b-instruct` model with metadata, including URLs, description, and file details.

models(gallery): add opencoder-1.5b instruct and base

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry.
Updates to `gallery/index.yaml`:
* Added a new model entry for `tissint-14b-128k-rp`, including its name, URLs, description, overrides, and file details.

models(gallery): add tissint-14b-128k-rp

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry with detailed information about the model, its description, and associated files.
* Added a new model entry `tq2.5-14b-sugarquill-v1` with its name, icon URL, description, and associated file details.

models(gallery): add tq2.5-14b-sugarquill-v1

---

gallery/index.yaml

This pull request adds new model entries to the `gallery/index.yaml` file. The changes introduce three new models, each with detailed metadata including names, icons, URLs, descriptions, parameters, and file information.
New model entries added:
* Added entry for `calme-3.3-baguette-3b` with detailed metadata including name, icon, URLs, description, parameters, and file information.
* Added entry for `calme-3.2-baguette-3b` with detailed metadata including name, icon, URLs, description, parameters, and file information.
* Added entry for `calme-3.1-baguette-3b` with detailed metadata including name, icon, URLs, description, parameters, and file information.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)* …

models(gallery): add calme-3 qwen2.5 series

---

gallery/index.yaml

This pull request updates the `gallery/index.yaml` file to add new model entries and update existing ones. The most important changes include adding new models with their respective metadata and correcting an icon URL.
* Added `calme-3.3-qwenloi-3b` with metadata, including icon URL, description, overrides, and file details.
* Added `calme-3.2-qwenloi-3b` with metadata, including icon URL, description, overrides, and file details.
* Added `calme-3.1-qwenloi-3b` with metadata, including icon URL, description, overrides, and file details.
* Corrected the icon URL for `calme-3.3-baguette-3b` by removing an unnecessary backslash.

models(gallery): add calme-3 qwenloi series

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important changes are:
* Added a new model entry for "mn-tiramisu-12b" with detailed metadata including URL, name, icon, description, and file information.

models(gallery): add mn-tiramisu-12b

---

backend/python/transformers/requirements.txt

Revert "chore(deps): Bump setuptools from 69.5.1 to 75.4.0 in /backend/python/transformers"

---

gallery/index.yaml

This pull request adds a new entry for the Qwen2.5-Coder-14B model to the `gallery/index.yaml` file. The changes include detailed information about the model, its improvements, and specific file details.
Key changes:
* Added a new model entry `qwen2.5-coder-14b` with descriptions and URLs.
* Included detailed improvements and features of the Qwen2.5-Coder series.
* Provided file details with SHA256 checksum and URI for the model file.

models(gallery): add qwen2.5-coder-14b

---

gallery/index.yaml

This pull request includes updates to the `gallery/index.yaml` file to add a new model entry for `Qwen2.5-Coder-3B-Instruct`. The most important changes are as follows:
* Added a new model entry `Qwen2.5-Coder-3B-Instruct` with detailed description and URLs. This model is part of the Qwen2.5-Coder series, which includes improvements in code generation, reasoning, and fixing, and supports long-context up to 128K tokens.
* Specified the model parameters and file details for the new model entry.

models(gallery): add qwen2.5-coder-3b-instruct

---

gallery/index.yaml

This pull request to the `gallery/index.yaml` file includes the addition of a new model configuration for `qwen2.5-coder-14b-instruct`.
Key changes:
* Added a new model configuration for `qwen2.5-coder-14b-instruct` including its name, URLs, parameters, and file details.

models(gallery): add qwen2.5-coder-14b-instruct

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "qwen2.5-coder-1.5b-instruct". 
* Added a new model entry for "qwen2.5-coder-1.5b-instruct" with associated URLs, parameters, and file details.

models(gallery): add qwen2.5-coder-1.5b-instruct

---

gallery/index.yaml

This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new model and its associated metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR89-R105): Added a new model entry `qwen2.5-coder-7b-3x-instruct-ties-v1.2-i1` with detailed metadata including URLs, description, parameters, and file details.

models(gallery): add qwen2.5-coder-7b-3x-instruct-ties-v1.2-i1

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `Qwen2.5-Coder-7B-Instruct-abliterated-i1`. This entry includes metadata such as the name, URLs, description, parameters, and files associated with the new model.
* Added a new model entry `Qwen2.5-Coder-7B-Instruct-abliterated-i1` with metadata including name, URLs, description, and parameters.
* Included file details for the new model with filename, sha256 hash, and URI.

models(gallery): add qwen2.5-coder-7b-instruct-abliterated-i1

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `Rombos-Coder-V2.5-Qwen-14b`. The most important changes are as follows:
* Added a new model entry for `Rombos-Coder-V2.5-Qwen-14b` with details such as name, icon, URLs, description, and file information.

models(gallery): add rombos-coder-v2.5-qwen-14b

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The main change is the addition of the `mistral-nemo-prism-12b` model with its associated metadata.
* Added `mistral-nemo-prism-12b` model entry with details such as URL, name, icon, description, overrides, and files.

models(gallery): add mistral-nemo-prism-12b

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new pre-trained language model. The changes are focused on enhancing the gallery with a new model and providing detailed information about it.
* Added a new model entry for "celestial-harmony-14b-v1.0-experimental-1016-i1" with relevant URLs, descriptions, and file details. This entry includes a description of the merge process and the models involved.

models(gallery): add celestial-harmony-14b-v1.0-experimental-1016-i1

---

gallery/index.yaml

This pull request includes an addition to the `gallery/index.yaml` file. The change adds a new model entry for `llama-3.1-8b-arliai-rpmax-v1.3` with multiple URLs, a detailed description, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2724-R2738): Added a new model entry for `llama-3.1-8b-arliai-rpmax-v1.3` with URLs, description, parameters, and file details.

chore(model): add llama-3.1-8b-arliai-rpmax-v1.3 to the gallery

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model is a 72b parameter model named "q2.5-ms-mistoria-72b-i1."
* Added new model `q2.5-ms-mistoria-72b-i1` with relevant metadata, including name, icon URL, description, and file details.

models(gallery): add q2.5-ms-mistoria-72b-i1

---

gallery/index.yaml

This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry with detailed metadata.
* Added a new model entry `l3.1-ms-astoria-70b-v2` with the following details:
* Icon URL: `https://cdn-uploads.huggingface.co/production/uploads/64545af5ec40bbbd01242ca6/C-ndfxAGdf21DjchZcf2p.png`
* Name: `l3.1-ms-astoria-70b-v2`
* URLs:
* `https://huggingface.co/Steelskull/L3.1-MS-Astoria-70b-v2`
* `https://huggingface.co/bartowski/L3.1-MS-Astoria-70b-v2-GGUF`
* Description: Detailed description provided, highlighting the model's goal to merge robust storytelling with intelligence using modern models and context sizes.
* Overrides and parameters specified for the model.
* Files associated with the model, including …

chore(model): add l3.1-ms-astoria-70b-v2 to the gallery

---

gallery/index.yaml

This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for `Athene-V2-Chat`. The most important changes are as follows:
* Added a new model entry named `athene-v2-chat` with detailed description and multiple URLs. This model is described as an open-weights LLM comparable to GPT-4o, excelling in chat, math, and coding, and trained through RLHF with Qwen-2.5-72B-Instruct as the base model.
* Included an override section specifying the model parameter as `Athene-V2-Chat-Q4_K_M.gguf`.
* Added file details for `Athene-V2-Chat-Q4_K_M.gguf` with its SHA256 checksum and URI.

chore(model): add athene-v2-chat to the gallery

---

backend/python/autogptq/requirements.txt
backend/python/bark/requirements.txt
backend/python/common/template/requirements.txt
backend/python/coqui/requirements.txt
backend/python/diffusers/requirements.txt
backend/python/exllama2/requirements.txt
backend/python/mamba/requirements.txt
backend/python/openvoice/requirements-intel.txt
backend/python/openvoice/requirements.txt
backend/python/parler-tts/requirements.txt
backend/python/rerankers/requirements.txt
backend/python/sentencetransformers/requirements.txt
backend/python/transformers-musicgen/requirements.txt
backend/python/transformers/requirements.txt
backend/python/vall-e-x/requirements.txt
backend/python/vllm/install.sh
backend/python/vllm/requirements.txt

This pull request includes updates to the `grpcio` dependency across multiple requirement files in the `backend/python` directory. The most important changes are the version bump of `grpcio` from `1.67.1` to `1.68.0` in various projects.
Dependency updates:
* [`backend/python/autogptq/requirements.txt`](diffhunk://#diff-326f4c9109482e17ae05b0eb5b30adbaddfa067a59199b82fc18f954ef7e4b65L3-R3): Updated `grpcio` to version `1.68.0`.
* [`backend/python/bark/requirements.txt`](diffhunk://#diff-a298ae0bd8fb041e45e658764d74d3a0087220ea2d9aa3a66b719e735f5ace07L2-R2): Updated `grpcio` to version `1.68.0`.
* [`backend/python/common/template/requirements.txt`](diffhunk://#diff-588cd64d1a39b6bfccc024d5faf067ccd3e984f3f1214273ac0b10f8ceba67deL1-R1): Updated `grpcio` to version `1.68.0`. …

chore(deps): bump grpcio to 1.68.0

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for Llama 3.2 3B Shining Valiant 2. The most important changes include adding details such as the model's name, icon, URLs, description, version, and file parameters.
* Added a new model entry for `llama3.2-3b-shiningvaliant2-i1` with the following details:
* Model name: `llama3.2-3b-shiningvaliant2-i1`
* Icon URL: `https://cdn-uploads.huggingface.co/production/uploads/63444f2687964b331809eb55/EXX7TKbB-R6arxww2mk0R.jpeg`
* URLs: `https://huggingface.co/ValiantLabs/Llama3.2-3B-ShiningValiant2` and `https://huggingface.co/mradermacher/Llama3.2-3B-ShiningValiant2-i1-GGUF`
* Description: Detailed description of the model's purpose, training data, …

chore(model): add llama3.2-3b-shiningvaliant2-i1 to the gallery

---

Makefile

chore(Makefile): default to non-native builds for llama.cpp

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The change introduces the `evathene-v1.0` model with its associated metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1452-R1470): Added the `evathene-v1.0` model with details including an icon URL, name, description, parameters, and file information.

chore(model): add evathene-v1.0 to the gallery

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `miniclaus-qw1.5b-unamgs` model, including its metadata and file details.
* Added `miniclaus-qw1.5b-unamgs` model with associated metadata such as name, icon URL, description, and file details.

chore(model): add miniclaus-qw1.5b-unamgs to the gallery

---

go.sum

This PR fixes 
```
go: github.com/valyala/fasttemplate@v1.2.2: missing go.sum entry for go.mod file; to add it:
go mod download github.com/valyala/fasttemplate
```

chore(go.mod): add valyala/fasttemplate

---

core/config/backend_config_loader.go
core/http/endpoints/openai/request.go

This PR is a small refactorization extracted from #3722 

chore(refactor): imply modelpath

---

gallery/index.yaml

This pull request adds a new voice activity detection model to the gallery index. The most important change is the inclusion of the `silero-vad` model with its associated metadata and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR9097-R9116): Added the `silero-vad` model with URLs, description, tags, backend overrides, parameters, and file details.

chore(model): add silero-vad to the gallery

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "copus-2x8b-i1". This entry includes details such as the name, icon URL, description, and file information for the new model.
Changes include:
* Added a new model entry for "copus-2x8b-i1" with the following details:
* Name: "copus-2x8b-i1"
* Icon URL: `https://huggingface.co/lodrick-the-lafted/Copus-2x8B/resolve/main/copus.png`
* Description: A brief description of the model and its performance.
* File information including filename, SHA256, and URI.

chore(model): add copus-2x8b-i1 to the gallery

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `llama-3.1-8b-instruct-ortho-v3`.
Model entry addition:
* Added a new model entry `llama-3.1-8b-instruct-ortho-v3` with associated URLs, description, parameters, and file details. This entry includes different attempts at orthogonalization/abliteration of `llama-3.1-8b-instruct` using variations of the method from "Mechanistically Eliciting Latent Behaviors in Language Models".

chore(model): add llama-3.1-8b-instruct-ortho-v3 to the gallery

---

gallery/index.yaml

This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `llama-3.1-tulu-3-8b-dpo`. The most important changes include the addition of metadata, URLs, a description, and file details for the new model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2987-R3001): Added a new model entry for `llama-3.1-tulu-3-8b-dpo` with metadata, including name, icon, URLs, description, and file details.

chore(model): add llama-3.1-tulu-3-8b-dpo to the gallery
