mudler/LocalAI

- api/api.go
This adds the following to the API:
- Allow to set `n` to return more predictions in one API call
- Exposes `batch`, `f16` and `ignore_eos` (not available in the original OpenAI API, but available in llama.cpp)
- Adds `echo` to return back the prompt in the response
- Avoid returning empty `message` when using the completion endpoint
> feat: enhance API, expose more parameters

- .gitignore
- Dockerfile
- Makefile
- README.md
- api/api.go
- docker-compose.yaml
- go.mod
- go.sum
- main.go
- pkg/model/loader.go
- prompt-templates/ggml-gpt4all-j.tmpl
- Adds GPT4ALL-J support #30 
- Some refactoring was needed to make it compatible both with llama.cpp and gpt4all
- Makefile is now used consistently during the build of the container images
- left generic targets with less-optimized flags, but works on more HW
- Many optimizations to run inference faster - building llama from Makefile wasn't optimized, now we use cmake along the way
- Note support to gpt4all for now is greedy, until we add a config endpoint or also #28 to set specific backends to use for the models
> Add support for GPT4ALL-J

- .github/workflows/image.yml
- .gitignore
- .goreleaser.yaml
- Dockerfile
- Earthfile
- Makefile
- README.md
- api/api.go
- docker-compose.yaml
- go.mod
- kubernetes/deployment.yaml
- main.go
After some thoughts, it is clear that this project must be renamed - not only due to the fact that we don't support only llama, but also because of the API-focused direction that we are taking. 
There are already several CLI that can be used, and most importantly, every model ships typically a CLI with it, and if not, the llama.cpp CLI can just be used instead. 
It also ease out of the burden of maintain more code, so we can focus on optimizations, and compatibility.
This PR:
- Drops the CLI interface
- Rename images
- Makes the first command just start the API
> Rename project to LocalAI

- examples/chatbot-ui/README.md
This PR corrects a typo in the example's README as discussed in https://github.com/go-skynet/LocalAI/issues/90
> examples: correct typo in README

- examples/README.md
was just missing in the example's index
> docs: Add langchain to the example index

- .github/workflows/image.yml
- api/openai.go
- api/prediction.go
This adds initial support for events stream from the lama.cpp backend
See #109
> feat: add stream events

- api/openai.go
OpenAI allows up to 4 stopwords to be sent in a request, not a single string. Langchain at minimum uses this, but we should support this for feature compatibility with other OpenAI users. This PR makes no attempt to enforce a limit of 4 stopwords - perhaps they have a good reason to, but we'll find out!
If you find this PR while investigating a breaking change, just send a single element array ["stopword"] instead of a single string in your request to LocalAI.
> Stop parameter of OpenAIRequest changed to String Array

- Makefile
- README.md
- api/api_test.go
- api/prediction.go
- go.mod
- go.sum
- pkg/model/loader.go
This PR adds initial support to LocalAI for https://github.com/BlinkDL/RWKV-LM with https://github.com/saharNooby/rwkv.cpp and https://github.com/donomii/go-rwkv.cpp. (acknowledgement goes to  @BlinkDL, @saharNooby and @donomii for their respective projects :heart: , and of course @ggerganov for ggml ) . RWKV's models are extremely fast on CPU!
The Makefile points to my fork just waiting for https://github.com/donomii/go-rwkv.cpp/pull/1 to be merged.
It supports fully the endpoint already exposed, and also token stream. It also updates the README with relevant projects involved.
In a glance you can drop the ggml-quantized model in the `models` folder with a tokenizer file next to it:
```
36464540 -rw-r--r--  1 mudler mudler 1.2G May  3 10:51 rwkv_small
36464543 -rw-r--r--  1 mudler mudler …
```
> feat: add rwkv support

- api/openai.go
- api/prediction.go
- pkg/model/loader.go
This fixes #180 and a nasty bug when after streams we use API calls not-streamed. seems the GC was not freeing functions so we were trying to send on a closed channel
> fix: missing returning error and free callback stream

- .gitignore
Building locally on my mac reveals a leftover whisper.cpp directory. Preventatively add .DS_Store here while I am thinking of it, just in case anyone else with a mac doesn't have that set locally.
> Tiny .gitignore suggestion

- api/openai.go
Looks like it was always reading from disk instead of reading the post data
> Upload transcription API wasn't reading the data from the post

- api/openai.go
- pkg/model/loader.go
- pkg/whisper/whisper.go
First pass at keeping whisper models in memory, saves quite a bit of load time.
> Keep whisper models in memory

- pkg/model/initializers.go
This is a regression introduced with the refactoring in https://github.com/go-skynet/LocalAI/pull/234. We were looking at the tokenizer in the wrong path.
Fixes:  https://github.com/go-skynet/LocalAI/issues/170
> fix(rwkv): load tokenizer file from model path

- Makefile
- api/config.go
- api/prediction.go
Depends on: https://github.com/go-skynet/go-llama.cpp/pull/51
Allows to build LocalAI with the `llama.cpp` backend with cublas/openblas:
To build, run:
```
make BUILD_TYPE=cublas CUDA_LIBPATH=.... build
```
```
make BUILD_TYPE=openblas build
```
To set the number of GPU layers, in the config file:
```
gpu_layers: 4
```
This also drops the "generic" build type, as I'm sunsetting it in favor of specific cmake parameters
Related to: #69
> feat: add support for cublas/openblas in the llama.cpp backend

- .dockerignore
- .gitignore
- Makefile
- README.md
- api/api.go
- api/api_test.go
- api/config.go
- api/openai.go
- api/prediction.go
- examples/chatbot-ui/README.md
- go.mod
- go.sum
- main.go
- pkg/model/initializers.go
- pkg/stablediffusion/generate.go
- pkg/stablediffusion/generate_unsupported.go
- pkg/stablediffusion/stablediffusion.go
Example with curl:
```bash
curl http://localhost:8080/v1/images/generations -H "Content-Type: application/json" -d '{
"prompt": "floating hair, portrait, ((loli)), ((one girl)), cute face, hidden hands, asymmetrical bangs, beautiful detailed eyes, eye shadow, hair ornament, ribbons, bowties, buttons, pleated skirt, (((masterpiece))), ((best quality)), colorful|((part of the head)), ((((mutated hands and fingers)))), deformed, blurry, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, poorly drawn hands, missing limb, blurry, floating limbs, disconnected limbs, malformed hands, blur, out of focus, long neck, long body, Octane renderer, lowres, bad anatomy, bad hands, text",
"size": "256x256"
}'
```
| mode=0 …
> feat: add image generation with ncnn-stablediffusion

- Dockerfile
- Dockerfile.dev
This adds openblas and opencv to the images so can be started with `GO_TAGS=stablediffusion`
> docker: add openblas and opencv to images

- examples/rwkv/.gitignore
- examples/rwkv/Dockerfile.build
Fixes the following issue:
```
❯ docker build -t rwkv-converter -f Dockerfile.build .
...
=> ERROR [5/5] RUN git clone --recurse-submodules https://github.com/saharNooby/rwkv.cpp && cd rwkv.cpp && cmake . && cmake --build . --config Release                                                                              2.2s
------                                                                                                                                                                                                                                    
> [5/5] RUN git clone --recurse-submodules https://github.com/saharNooby/rwkv.cpp && cd rwkv.cpp && cmake . && cmake --build . --config Release:                                                                                         
#0 …
```
> fix: Dockerfile.build missing cmake in rwkv example

- .github/workflows/image.yml
- .github/workflows/test.yml
- api/gallery.go
- pkg/gallery/models.go
- pkg/gallery/models_test.go
this change allow to specify from the API caller also additional files to download with the model definition as an array of `files`:
```
curl -s http://localhost:8080/models/apply -H "Content-Type: application/json" -d '{"name":"test", "url": "https://gist.githubusercontent.com/mudler/6112666e77061fe35ca3a535d25ccddc/raw/45eabb442f25db5bc991f2d2a616c15d4c26be67/gpt4all-j-localai.yaml", "files": [ { "uri": "<url>", "name": "filename" } ]}'
```
Besides, allow to override the name of the model - so can be used for instance to alias other models ( `gpt-3.5-turbo`, .. )
Also adds security checks such as any path we pass by in the model files cannot be traversed.
Related to #100
> feat: minor enhancements to /models/apply

- .vscode/launch.json
```
Starting: /go/bin/dlv dap --listen=127.0.0.1:35887 --log-dest=3 from /workspaces/LocalAI
DAP server listening at: 127.0.0.1:35887
Type 'dlv help' for list of commands.
Starting LocalAI using 4 threads, with models path: /workspaces/LocalAI/models
┌───────────────────────────────────────────────────┐ 
│                   Fiber v2.45.0                   │ 
│               http://127.0.0.1:8080               │ 
│       (bound on host 0.0.0.0 and port 8080)       │ 
│                                                   │ 
│ Handlers ............ 21  Processes ........... 1 │ 
│ Prefork ....... Disabled  PID ............. 31461 │ 
└───────────────────────────────────────────────────┘ 
```
> fix: missing model path in launch.json

- Makefile
- api/gallery.go
- api/gallery_test.go
This allows to define shorter URLs to `/models/apply`. For instance `github:go-skynet/model-gallery/gpt4all-j.yaml` will automatically resolve to: `https://raw.githubusercontent.com/go-skynet/model-gallery/main/gpt4all-j.yaml`
> feat: support shorter urls for github repositories

- api/openai.go
This PR fixes #340.
With reference to the example response from localAI from #340 (under "To Reproduce"), here's the corresponding updated response after this PR's changes:
``` http
HTTP/1.1 200 OK
Date: Sun, 21 May 2023 10:56:07 GMT
Content-Type: text/event-stream
Vary: Origin
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Transfer-Encoding: chunked
data: {"object":"chat.completion.chunk","model":"ggml-gpt4all-j","choices":[{"delta":{"role":"assistant"}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
data: {"object":"chat.completion.chunk","model":"ggml-gpt4all-j","choices":[{"delta":{"content":"1"}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
data: …
```
> fix: spec compliant instantiation and termination of streams

- api/api.go
- api/gallery.go
- api/options.go
- main.go
This allows to preload models on startup before the API is started by allowing to specify a list of models (as consumed by `models/apply` in a YAML file with `PRELOAD_MODELS_CONFIG` or a JSON string with `PRELOAD_MODELS`, useful for e.g. running in a container/pod).
I'll update docs afterwards. I'd like to consolidate examples using this method, so there are no extra action for the users to setup models.
> feat: allow to preload models before startup via env var or configs

- README.md
- examples/README.md
- examples/autoGPT/.env
- examples/autoGPT/README.md
- examples/autoGPT/docker-compose.yaml
This adds an example on how to run AutoGPT. Turns out it's only required to set a base path. As behind the scenes used the OpenAI client, is enough to set `OPENAI_API_BASE` to point to the LocalAI endpoint.
This example also makes use of `PRELOAD_MODELS` to preload models, and depends on LocalAI to be healthy - this allows to start directly when everything is correctly loaded. Will update the other examples with the same strategy in follow-ups.
Even if the example shows gpt4all I was not successful with that model. I've been using WizardLM-7b-uncensored with `f16: true` with "some" success.
> docs(examples): add AutoGPT

- .github/workflows/release.yaml
This PR fixes the build options in the CI. A small typo in the variable that set some options to build for AVX/AVX2/AVX512.
See result here: https://github.com/sebastien-prudhomme/LocalAI/actions/runs/5114923609
> ci: fix typo in variable name

- Dockerfile
- entrypoint.sh
We are not cleaning up properly, and this causes leftovers to stay around when rebuilding the first time. This ends up to link objects during startup of the container with objects compiled with a different CPU flagset, and giving out SIGILL like:
```
chatbot-ui-api-1      | SIGILL: illegal instruction
chatbot-ui-api-1      | PC=0xa17ced m=7 sigcode=2
chatbot-ui-api-1      | signal arrived during cgo execution
chatbot-ui-api-1      | instruction bytes: 0x62 0xf2 0xf5 0x8 0x3f 0xc0
0xc4 0xe1 0xf9 0x7e 0xc2 0x48 0x1 0xd0 0xf 0x92
chatbot-ui-api-1      |
chatbot-ui-api-1      | goroutine 31 [syscall]:
chatbot-ui-api-1      | runtime.cgocall(0x97f700, 0xc0002d6460)
chatbot-ui-api-1      |         /usr/local/go/src/runtime/cgocall.go:157
+0x5c fp=0xc0002d6438 sp=0xc0002d6400 pc=0x44cd3c
``` …
> fix: do not build from the same container

- .github/workflows/image.yml
Build Docker images variants. For now I propose to build also for cublas on cuda11 and cublas on cuda12.
I've switched to the docker metadata github action to compute docker tags and labels. The only difference is that tags corresponding to commit sha are prefixed by "sha-" and are on 7 characters instead of 8.
It's possible to remove the prefix if needed.
The 7 characters are the same short commit sha displayed everywhere on github.
> ci: build Docker image variants

- Makefile
> fix: Bump and fix rwkv build

- api/openai.go
This PR fixes #416 
sorry for stepping on your toes @krishnaduttPanchagnula , ([pr here](https://github.com/go-skynet/LocalAI/pull/425/files)) but I wanted to get it working for myself, so took a stab at it, then when I figured it out I supposed I should commit it back :)
> feat: add support for `Stream: true` to completionEndpoint

- examples/langchain-python/README.md
- examples/langchain-python/docker-compose.yaml
- examples/langchain-python/models
> examples: simplify langchain-python

- Makefile
- api/api_test.go
OpenLLama has been released, as such now we can just incorporate the models in our tests.
This is using the 3b variant from the model-gallery to do a small test assessment against the llama backend.
> tests: add llama tests with openllama

- api/gallery.go
- pkg/gallery/models.go
- pkg/gallery/models_test.go
This PR allows to track progress of the download with the API and from the terminal (when debug is enabled):
```bash
$ LOCALAI=http://localhost:8080                                         
$ curl $LOCALAI/models/apply -H "Content-Type: application/json" -d '{
"url": "github:go-skynet/model-gallery/rwkv-raven-1b.yaml",
"name": "rwkv"
}'
7:00PM DBG Downloading RWKV-4-Raven-1B5-v11-Eng99%2525-Other1%2525-20230425-ctx4096_Q4_0.bin: 48.4 MiB/1.1 GiB (4.41%) ETA: 1m48.55284203s
7:00PM DBG Downloading RWKV-4-Raven-1B5-v11-Eng99%2525-Other1%2525-20230425-ctx4096_Q4_0.bin: 109.3 MiB/1.1 GiB (9.96%) ETA: 1m30.525148835s
7:00PM DBG Downloading RWKV-4-Raven-1B5-v11-Eng99%2525-Other1%2525-20230425-ctx4096_Q4_0.bin: 158.7 MiB/1.1 GiB (14.46%) ETA: 1m28.87224456s
7:00PM DBG Downloading …
```
> feat: display download progress when installing models

- .gitignore
- Makefile
This ties the metal file to the build and reduces the steps the user has to take to run local-ai
> fix: copy metal file from build

- Dockerfile
- Makefile
since dependency hashes are kept in the `Makefile`, changing them will
make `docker` start from the `COPY Makefile .` line, which will then
correctly refetch sources
however, if only go source files are touched, `docker` won't throwaway
all the fetching and compiling it did previously
I've been developing in the docker containers and this massively reduces compile time
> Docker preserve sources

- api/prediction.go
This PR fixes cublas acceleration. A default of 0 would not allow to allocate ram for scratch buffers. Setting that to the same defaults of llama.cpp
Fixes #556
> fix: set default batch size

- Dockerfile
- Makefile
- api/api.go
- api/localai.go
- api/options.go
- entrypoint.sh
- go.mod
- main.go
- pkg/gallery/models.go
- pkg/model/initializers.go
- pkg/tts/generate.go
- pkg/tts/generate_unsupported.go
- pkg/tts/piper.go
- pkg/utils/path.go
This PR fixes #266 , and adds support to the amazing https://github.com/rhasspy/piper (:heart:) to generate voice from text. I've created overnight the golang binding which is available here: https://github.com/mudler/go-piper.
It adds a new `/tts` endpoint, which accepts a `model` and an `input` text.
Now you can give a voice to your LLMs!!
- Download Voices: https://github.com/rhasspy/piper/releases/tag/v0.0.2
- Extract the `.tar.tgz` files (.onnx,.json) into `models`
- 
```
curl $LOCALAI/tts -H "Content-Type: application/json" -d '{         
"model":"it-riccardo_fasol-x-low.onnx",
"input": "Ciao, sono Ettore"
}' | aplay
```
- Profit!
> feat: add tts with go-piper

- entrypoint.sh
This updates entrypoint.sh to make use of the THREADS environment variable if present to speed up compilation on startup. In my case, I have an older, slower CPU which has 24 cores, so it makes a big difference for me. If that is not set, it will use 1 thread as it does now.
> Update entrypoint.sh to use $THREADS for parallel compilation on start if present

- Dockerfile
> fix: detect TARGETARCH if not present

- entrypoint.sh
This can be particularly problematic when running on kubernetes where CPU limits can kill the pod.
@maccam912 this splits the env variable so it is not tied to the `THREADS` which is in runtime. In my k8s deployment LocalAI fails otherwise as overbooks my CPU and gets killed during start, and I'm pretty sure I won't be alone here.
> fix: split build threads from running threads

- api/openai/chat.go
Previously we were using omitempty which was then parsed by clients as "". Now we return null, which certain clients concatenates blindly.
This makes it close to OpenAI where the first message sent has an empty content, but just the role.
This PR fixes
> fix: make first stream message to send empty content

- examples/README.md
- examples/functions/.env
- examples/functions/Dockerfile
- examples/functions/README.md
- examples/functions/docker-compose.yaml
- examples/functions/functions-openai.py
- examples/functions/requirements.txt
Adds an e2e example with OpenAI functions
> example(functions): Add OpenAI functions example

- Makefile
This PR modifies the makefile so the build type is passed to cmake when building libtransformers.a.
Related to https://github.com/go-skynet/go-ggml-transformers.cpp/pull/40
> [build] pass build type to cmake on libtransformers.a build

- pkg/grammar/functions.go
- pkg/grammar/json_schema.go
This PR adds compatibility to the JSONSchema notation `$defs` and `$refs` which allow to re-use objects across a schema.
This allows projects like  https://github.com/stillmatic/gollum or https://github.com/jxnl/openai_function_call compatible.
> feat: resolve JSONSchema refs (planners)

- Makefile
After moving backends to gRPC, llama it's going to look to the metal file next to the grpc binary and not local-ai. so we can now put it in the backend assets and carry it over so no need to extra steps from the user as well
A possible fix for #755 
> fix: move metal file to grpcs assets

- entrypoint.sh
This should help to show the CPU capabilities
regarding AVX, AVX2 and AVX512.
Debugging probems with precompiled containers and the matching models could be hard.
If the container is used without REBUILD=true , new users get some errors and are lost.
This hint shows the found CPU flags if someone opens an PR.
With this change the output during startup could look like:
```
@@@@@
Skipping rebuild
@@@@@
If you are experiencing issues with the pre-compiled builds, try setting REBUILD=true
If you are still experiencing issues with the build, try setting CMAKE_ARGS and disable the instructions set as needed:
CMAKE_ARGS="-DLLAMA_F16C=OFF -DLLAMA_AVX512=OFF -DLLAMA_AVX2=OFF -DLLAMA_FMA=OFF"
see the documentation at: https://localai.io/basics/build/index.html
Note: See also …
```
> Added CPU information to entrypoint.sh

- api/backend/llm.go
- api/openai/api.go
- api/openai/chat.go
- api/openai/completion.go
- api/openai/edit.go
- api/openai/embeddings.go
- api/openai/image.go
- api/openai/inference.go
- api/openai/request.go
- api/openai/transcription.go
- pkg/model/initializers.go
- pkg/model/loader.go
I added `Context` and `Cancel` fields to `OpenAIRequest`, and then ensured that the new per-request context was wired up to the grpc client.
Now if I ctrl+c my curl request while its streaming, the LocalAI server will show:
```
7:15PM DBG Sending chunk: {"object":"chat.completion.chunk","model":"llama2","choices":[{"index":0,"delta":{"content":" a"}
}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
7:15PM DBG Sending chunk failed: connection closed
Error rpc error: code = Canceled desc = context canceled
```
The next request after a cancellation is acting weird and produces some garbage tokens.
```
7:21PM DBG Sending chunk: {"object":"chat.completion.chunk","model":"llama2","choices":[{"index":0,"delta":{"role":"assistant","conte …
```
> feat: cancel stream generation if client disappears

- api/openai/request.go
An oversight that caused to not respect functions to be called as enforced by the caller.
> fix: select function calls if 'name' is set in the request

- .github/workflows/test.yml
- Dockerfile
- api/api_test.go
- pkg/grpc/llm/llama/llama.go
> fix: symlink libphonemize in the container

- pkg/utils/path.go
- pkg/utils/uri.go
Model Gallery downloads are broken. Small tweak prevents VerifyPath from going into an endless loop on my system.
This PR fixes https://github.com/go-skynet/model-gallery/issues/16
> Fix: Model Gallery Downloads

- api/api_test.go
- api/openai/image.go
- pkg/gallery/models_test.go
https://pkg.go.dev/io/ioutil
my IDE tooling claims loudly that ioutil is depreciated, might as well just clean up the remaining uses now and switch to `io` and `os` since we already use those regularly.
Probably not a huge deal, but reduced warning pressure is reason enough for me to suggest this.
> refactor: Remove remaining uses of depreciated package `io/ioutil`

- .gitattributes
This change forces `git clone` to keep the LF line endings on .sh files
This PR fixes https://www.reddit.com/r/AutoGPT/comments/1438fb6/localai_v1180_release/ 
where cloning the repository onto a windows machine changes the line-endings of .sh files to CRLF, breaking them.
> Create .gitattributes to force git clone to keep the LF line endings on .sh files

- api/localai/gallery.go
- pkg/gallery/gallery.go
This fixes specifying models to be preloaded via file. Supposedly we should have been reading YAMLs, but by refactoring and re-using functions we ended up expecting those files as json.
Does also a small refactoring around the gallery so now with the galleries loaded in the .env:
`GALLERIES=[{"name":"model-gallery", "url":"github:go-skynet/model-gallery/index.yaml"}, {"url": "github:go-skynet/model-gallery/huggingface.yaml","name":"huggingface"}]`
we can directly specify models by using the huggingface repository name (`owner/repository/file`), and similarly now we can just curl the chat endpoint with the model name of the huggingrepository, that should trigger automatically the download.
> fix(gallery): preload from file should by in YAML format

- Makefile
Reverts go-skynet/LocalAI#824. seems to have broken CUDA support. (See #840 #844)
> Revert ":arrow_up: Update go-skynet/go-llama.cpp"

- api/openai/chat.go
- api/openai/completion.go
- api/openai/edit.go
- pkg/model/loader.go
Model configuration already allowed for the concept of a per-configuration "default system prompt", but it only functioned for the `chat-message` endpoint. This PR adds two related template variables for `*.tmpl` authors to use, specifically for the "simpler" `chat` / `edit` / `completion` templates.
- `SystemPrompt`: string - is configured as `system_prompt` in the model yaml configuration file. Intended to serve as a default system prompt for this model configuration, especially if nothing else is specified (such as a `messages` array without a leading system element, or a completion request where there's no real place for it) 
- `SupressSystemPrompt`: bool - is a template utility and only can ever be true in the `chat` endpoint currently. If a message with `role == …
> feat: "simple" chat/edit/completion template system prompt from config

- api/openai/chat.go
- pkg/utils/json.go
This is a guard from the model returning newlines which are not allowed in JSON - as such we escape them with `\\n`
Since https://github.com/go-skynet/LocalAI/pull/862 now strings contains newlines, and as such JSON can output multi-line text as well now.
> fix: do not break on newlines on function returns

- Dockerfile
Otherwise somehow it fails loading exllama with:
```
No module named 'exllama.generator'; 'exllama' is not a package
```
> fix: workaround exllama import error

- Dockerfile
Better than no defaults.
This makes sure the container images have at least a basic default if nothing is set.
> feat: pre-configure LocalAI galleries

- Makefile
this allow to override default backends included in the local-ai binary during build by specifying the targets with `GRPC_BACKENDS`. 
For instance, to build only with llama.cpp:
```
make GRPC_BACKENDS=backend-assets/grpc/llama build
```
> feat(Makefile): allow to restrict backend builds

- api/backend/embeddings.go
- api/backend/image.go
- api/backend/llm.go
- api/backend/transcript.go
- api/config/config.go
- pkg/model/initializers.go
- pkg/model/options.go
On slow HW (RPI, etc.) gRPC backends might take more time to get up. this PR extends the default time (20 attempts, 2 seconds in between) and adds a config file for the model as `grpc.attempts` and `grpc.attempts_sleep_time`
> feat: make initializer accept gRPC delay times

- extra/grpc/diffusers/backend_diffusers.py
- extra/requirements.txt
Use compel to merge token weights. Allow to disable with `COMPEL=0`
> feat(diffusers): overcome prompt limit

- api/backend/embeddings.go
- api/backend/image.go
- api/backend/llm.go
- api/backend/options.go
- api/backend/transcript.go
- api/backend/tts.go
- api/options/options.go
- extra/grpc/autogptq/autogptq.py
- extra/grpc/bark/ttsbark.py
- extra/grpc/diffusers/backend_diffusers.py
- extra/grpc/exllama/exllama.py
- extra/grpc/huggingface/huggingface.py
- go.mod
- go.sum
- main.go
- pkg/grpc/client.go
- pkg/model/initializers.go
- pkg/model/loader.go
- pkg/model/options.go
- pkg/model/process.go
This PR fixes #909 by adding a simple mechanisms to manage single devices. It adds a `single-active-backend` (`SINGLE_ACTIVE_BACKEND`) CLI flag: when enabled LocalAI will make sure to use only one backend - and automatically stop the ones in use only if idleing if there is a new request (otherwise it will wait). This allows for instance, to generate an image with one GPU, and then start chatting right after with an LLM using the same GPU. This is fundamental when having two consecutive requests to different backends targeting the same GPU or LocalAI will just crash as for now. 
In scenarios with multiple-GPUs, for Llama, it is possible to specify already a CUDA device - this allows fine-grained control over the devices being used, however multi-GPU management is out of …
> feat: add --single-active-backend to allow only one backend active at the time

- api/backend/llm.go
- api/config/config.go
This PR makes `usage` turned off by default and make it opt-in. Let's promote it to default when it had sufficient rounds of testing.
> fix: disable usage by default (still experimental)

- Makefile
- cmd/grpc/llama-stable/main.go
- pkg/backend/llm/llama-stable/llama.go
- pkg/model/initializers.go
In preparation for https://github.com/ggerganov/llama.cpp/pull/2398.
This changeset adds a new backend "llama-stable" to have a second version of llama pinned to well-known-to-work commits.
This version will keep compat with `ggml` meanwhile we will consume `gguf` file format as well.
> feat: add llama-stable backend

- .github/workflows/test.yml
Small infra PR to introduce the setup-go action. Very similar to what was done in https://github.com/go-skynet/go-llama.cpp/pull/177, but slightly modified to fit the different pipeline
Currently tests against 1.20.x and stable (1.21.0 at time of writing).
> infra: add setup-go@4, test against 1.20.x (go.mod) and stable (1.21)

- api/api.go
- api/localai/backend_monitor.go
- pkg/model/loader.go
This PR adds a new endpoint to the backend monitor section `/backend/shutdown` which terminates the grpc process for the related model.
> feat: backend monitor shutdown endpoint, process based

- api/backend/image.go
- extra/grpc/diffusers/backend_diffusers.py
This PR fixes #914 
Now diffusers respects the `lora_adapter` configuration parameter.
> feat(diffusers): Add lora

- extra/grpc/diffusers/backend_diffusers.py
Enable setting the seed for the stable diffusion pipeline. This is done through an additional `seed` parameter in the request, such as:
```bash
curl http://localhost:8080/v1/images/generations \
-H "Content-Type: application/json" \
-d '{"model": "stablediffusion", "prompt": "prompt", "n": 1, "step": 51, "size": "512x512", "seed": 3}'
```
When the `seed` parameter is not sent, `request.seed` defaults to `0`, making it difficult to detect an actual seed of `0`. Is there a way to change the default to `-1` for instance ?
>  Allow to manually set the seed for the SD pipeline

- examples/query_data/query.py
- examples/query_data/store.py
Simple fix, percentage value is expected to be float in range 0..1
> [query_data example] max_chunk_overlap in PromptHelper must be in 0..1 range

- examples/continue/README.md
OpenAIServerInfo no longer exists, and api_base has been moved up. Changes were made here https://github.com/continuedev/continue/commit/8967e2d53f4f6ff744c408ae1042caffb25627f9#diff-98e147eaa7c9936befdddabb16c72447fbf8ad2df6b680c5176c24813169858e
> Update README to reflect changes in Continue's config file

- examples/chatbot-ui-manual/README.md
- examples/chatbot-ui/README.md
This PR cleans up the `chatbot-ui`/`-manual` examples:
- Fixes `Dockerfile` vs `docker-compose` confusion
- Makes it clear where to view the web UI in `## Run` sections
> Cleaned up chatbot-ui READMEs

- Makefile
- go.mod
- go.sum
This PR fixes lack of HIPBLAS support in LocalAI.
This PR builds on https://github.com/go-skynet/go-llama.cpp/pull/235 to enable ROCm/HIPBLAS support for gguf models running under llama.cpp backend (not the stable ggml one). It can be enabled by using BUILD_TYPE=hipblas. This was tested on a gfx1100 card, but should work for gfx900,gfx1030 and other cards. Card support can be set with AMDGPU_TARGETS environment variable.
> feat(llama.cpp): enable ROCm/HIPBLAS support

- api/openai/chat.go
- api/openai/completion.go
- api/openai/edit.go
- api/openai/embeddings.go
- api/openai/image.go
Adding the extra ID and Created fields to any request to the OpenAI Compatible API to improve the compatibility.
This PR fixes #1103
> fix(openai): Populate ID and Created fields in OpenAI compatible responses

- Dockerfile
- Makefile
- extra/grpc/exllama/Makefile
- extra/grpc/exllama/README.md
- extra/grpc/exllama/exllama.yml
- extra/grpc/exllama/run.sh
This PR is related to #1117 
This PR follow the install process from https://github.com/jllllll/exllama#this-is-a-python-module-version-of-exllama
All the requirements were installed successfully. Also include (`grpcio` and `protobuf`).
* `torch==2.1.0`
* `safetensors==0.3.2`
* `sentencepiece==0.1.99`
* `ninja==1.11.1`
The `exllama` package was failed to install due to `CUDA_HOME environment variable is not set.` I do not have it in my environment(whatever the software or the hardware). So, I believe  I need some help in here.
```
(exllama) @Aisuko ➜ /workspaces/LocalAI (feat/exllama) $ python -m pip install git+https://github.com/jllllll/exllama
Collecting git+https://github.com/jllllll/exllama
Cloning https://github.com/jllllll/exllama to …
```
> feat(conda):Add seperate conda env for exllama

- backend/cpp/llama/CMakeLists.txt
- pkg/gallery/gallery.go
- detect OSX and use the directories associated with homebrew-installed libraries
- Tiny logging change makes it easier to detect Protobuf issues, was helpful while creating this so I'm keeping it in place
> Fix backend/cpp/llama CMakeList.txt on OSX 

- Dockerfile
This change facilitates users working behind corporate firewalls or proxies. By allowing the integration of custom CA certificates, users can handle SSL connections that are intercepted by company infrastructure.
The idea is that users would copy their CA certificates to `custom-ca-certs`, and the Dockerfile would take care of adding them to the image so that the user doesn't get SSL certificate problems when `curl` commands run.
I decided to open this PR because of the problem I mentioned on discussion #876 
> feat(certificates): add support for custom CA certificates

- examples/llamaindex/README.md
- examples/llamaindex/main.py
Documentation update for llama index use case https://github.com/run-llama/llama_index/issues/7907
Should be noted that they just changed it again https://github.com/run-llama/llama_index/pull/8241 so this will be updated soon
> llama index example

- examples/chainlit/Dockerfile
- examples/chainlit/README.md
- examples/chainlit/config.yaml
- examples/chainlit/main.py
- examples/chainlit/requirements.txt
chainlit example using localai
> chianlit example

- .github/workflows/test.yml
- Dockerfile
- Makefile
- entrypoint.sh
This PR fixes go-piper compilation
It is linked to https://github.com/mudler/go-piper/pull/1
Tested on a complete rebuild with GO_TAGS="tts" and the example reported in the official docs
All the *.so
and required backend assets (espeak-ng-data) will live under go-piper/piper/build/pi 
> deps(go-piper): update to 2023.11.6-3

- api/openai/chat.go
- api/openai/completion.go
- api/openai/image.go
- api/schema/openai.go
Otherwise we fail with:
```
failed to generate answer: error, status code: 500, message: failed reading parameters from request:failed parsing request body: json: cannot unmarshal object into Go struct field OpenAIRequest.response_format of type string
```
> fix: respect OpenAI spec for response format

- api/localai/backend_monitor.go
- pkg/grpc/client.go
- pkg/model/initializers.go
- pkg/model/loader.go
- pkg/model/process.go
Return a GRPC which handles a lock in case it is not meant to be parallel.
> feat: queue up requests if not running parallel requests

- api/config/config.go
This PR allows to use both `.yml` and `.yaml` extensions for YAML configuration files as it is usually expected.
May be not the most efficient way of doing it but I am not a Go specialist.
Also I could not do the `make build`, `make run` or `make test` as it was failing.
> fix(api/config): allow YAML config with .yml

- backend/python/exllama/exllama.py
This PR fixes ExLlama backend having fixed 2048 size cache. This results in the following error when 2048 context is exceeded: `stderr RuntimeError: start (2009) + length (44) exceeds dimension size (2048)`
This PR also passes through Rope scaling config to the ExLlama backend.
These attributes are set by default [here](https://github.com/turboderp/exllama/blob/master/model.py#L39), and not loaded from the model config json. Therefore, we need to set it from LocalAI's end. It would also be nice to add warnings for all backends of unimplemented config flags that the user defined in the yaml.
> fix: ExLlama Backend Context Size & Rope Scaling

- backend/python/bark/ttsbark.py
- backend/python/sentencetransformers/sentencetransformers.py
- backend/python/transformers/transformers.py
This PR fixes no specific issue, I just found the bug and fixed it right away.
The changed comments prevent direct execution of the backend Python scripts unless the platform is configured in some way to always execute .py files with Python. For platforms that rely on the shebang (#!) to tell them how to run the script, these comments led to an "exec format error" message because the shebang has to be on the very first line to be properly read by exec(see `man 2 execve`).
This should be a straightforward merge.
I also adjusted the comments themselves a bit.
Changelist:
- Move header comments below shebang line where necessary (only in backends/python/)
- Make header comment for barktts.py a tad more specific
- Fix header comment in transformers.py referring to the wrong …
> fix: move python header comments below shebang in some backends

- docs/content/features/embeddings.md
The documentation website was out of date with regards to the path of the backend to run huggingface models. Since it moved to `backend/python/sentencetransformers`, I updated the documentation accordingly so that people running LocalAI outside of Docker can continue to do so.
I also changed the naming in the example YAML file to refer to the `sentencetransformers` backend instead of the `huggingface-embeddings` backend. The docker version of LocalAI knows both as an alias for the same backend, so this should not break anything there.
P.S.: Perhaps the docs should be updated to give an example on how to use the `transformers` backend as well? As I don't know what it is used for nor how one might use it, I wasn't able to include it in this PR.
The …
> docs: Update Features->Embeddings page to reflect backend restructuring

- Dockerfile
- Makefile
This PR fixes `REBUILD=true` in the container which currently is broken.
It was caused by not handling llama.cpp source code and the grpc dependencies not installed in the final container.
This PR handles now explicitly adds in the Makefile an entry to clone the source code during the preparation of the sources and it copies the grpc built artifacts over the running container and installing them.
> fix: handle grpc and llama-cpp with REBUILD=true

- .env
- api/api.go
- api/localai/backend_monitor.go
- api/options/options.go
- main.go
- pkg/grpc/client.go
- pkg/model/initializers.go
- pkg/model/loader.go
- pkg/model/process.go
- pkg/model/watchdog.go
This PR fixes #1339 and fixes #1202
The WatchDog implementation (disabled by default) is designed to monitor and manage multiple backends. It keeps track of the last active times and idle times of each backend, and can stop them if a backend has been busy or idle for too long.
Key components of the WatchDog struct include:
- `timetable`: A map that stores the last active time of each backend.
- `idleTime`: A map that stores the last idle time of each backend.
- `timeout` and `idletimeout`: Duration values that represent the maximum allowed busy and idle times for a backend, respectively.
To turn on the watchdog, configure the following environment variables:
```
###
#
#
#
```
With the CLI: `--enable-watchdog-idle`, `--enable-watchdog-busy`, `--watchdog-busy-timeout`, …
> feat: initial watchdog implementation

- Makefile
> fix: go-piper add libucd at linking time

- README.md
- docs/content/getting_started/_index.en.md
This adds a new section in the README for projects tied to LocalAI directly (such as CLI, WebUI, model galleries, etc) curated by the community. It also adds instructions side-by-side in the quickstart to run with docker and not only with docker-compose.
> docs: Add docker instructions, add community projects section in README

- backend/python/autogptq/Makefile
- backend/python/bark/Makefile
- backend/python/diffusers/Makefile
- backend/python/exllama/Makefile
- backend/python/petals/Makefile
- backend/python/sentencetransformers/Makefile
- backend/python/transformers/Makefile
- backend/python/vall-e-x/Makefile
- backend/python/vllm/Makefile
- docs/content/features/embeddings.md
In #1279, the `requirements.txt` file got dropped from the `extra/` directory during the move to a `backend/` directory. As the docs still refer to that file (and it's useful to have a central list of the necessary pip packages), I re-added it with the same content under `backend/python`. 
I also updated the Features->Embeddings docs page to use the new path in the `pip install` command.
> fix/docs: Python backend dependencies

- Makefile
It turns out I had _not_ in fact, made Metal the default on OSX for LocalAI to match llama.cpp (where it matters most) - and because of that, I have not been testing with `BUILD_TYPE=metal` for a while... and metal builds were broken due to the backend refactoring.
This PR addresses this issue by: 
- Fixing the `ggml-metal.metal` path
- Centralizing osx-specific logic
- Just making `BUILD_TYPE=metal` the default if `BUILD_TYPE` isn't specified at all and we're on mac so this doesn't happen again
As a sidenote, `GO_TAGS=stablediffusion` on osx is also not currently using brew opencv - that will be corrected in a followup PR as I want to get this one merged first.
> fix: OSX Build Fix Part 1: Metal

- Makefile
This PR updates whisper_cpp to release 1.5 and adds GPU Support
i build and tested ROCM/HIPBLAS GPU support for whisper.
i did not test any other combination.
This is a draft. Please ignore if not fitting.
> update whisper_cpp with CUBLAS, HIPBLAS, METAL, OPENBLAS, CLBLAST support

- Dockerfile
- backend/python/vall-e-x/Makefile
- backend/python/vall-e-x/install.sh
- backend/python/vall-e-x/run.sh
- docs/content/advanced/_index.en.md
This PR fixes #1370 and fixes #1174 
**Tests** 
I've tested this locally as by the docs
> fix(vall-e-x): correctly install reqs in environment

- docs/content/advanced/_index.en.md
- entrypoint.sh
This is an idea I had while discussing https://github.com/mudler/LocalAI/issues/1403#issuecomment-1847238670. Introduces an `EXTRA_BACKENDS` environment variable at entrypoint level, such as during the boot if it is set will prepare the environment specified. This allows to use -core images and additionally just prepare the single backend that might be needed on start.
Far from perfect, but I think it covers the issue for now where in some corner cases is acceptable to have delays in starts when are controlled via healthchecks and readiness probes.
> feat(entrypoint): optionally prepare extra endpoints

- docs/content/getting_started/_index.en.md
- docs/content/howtos/_index.md
- docs/content/howtos/easy-model.md
- docs/content/howtos/easy-setup-docker-cpu.md
- docs/content/howtos/easy-setup-docker-gpu.md
- Removed ``docker-compose`` for windows, as it now follows the ``docker compose`` like linux
- Updated the how to set up a model to use ``dolphin-2.2.1-mistral-7B`` not ``luna-ai``
- Updated the how to set up a model to use a chat template model
- Updated Getting Started page to remove docker-compose windows warning
- Updated the ``index`` file for how to folder to add SD requests
This PR fixes 1416 (at least for Mac Users that must use q4_0 models)
> How To Updates / Model Used Switched / Removed "docker-compose" (RIP)

- .github/workflows/test-extra.yml
- backend/python/sentencetransformers/test_sentencetransformers.py
- backend/python/transformers-musicgen/run.sh
- backend/python/transformers-musicgen/test.sh
- backend/python/transformers-musicgen/test_transformers.py
I'm trying to add python backends tests to the CI so we can merge with more confidence and test extras changes without breakage (see #1408 for context)
> fix(transformers*): add sentence-transformers and transformers-musicgen tests, fix musicgen wrapper

- api/backend/image.go
- api/config/config.go
- api/openai/image.go
- backend/python/diffusers/backend_diffusers.py
- docs/content/features/image-generation.md
- docs/content/howtos/easy-setup-sd.md
- docs/content/model-compatibility/diffusers.md
This PR fixes #1348 
In terms of video generation is not elegant - it for now relies on the image generation endpoint and indeed urls are png's (even if outputs are mp4 files). This needs to be fixed, but going to leave out for next round of polishment. For now should be good to wire up the pipelines to have a starting point. It does not support upscaling of txt2img (yet?)
> feat(img2vid,txt2vid): Initial support for img2vid,txt2vid

- docs/content/model-compatibility/_index.en.md
- docs/content/model-compatibility/llama-cpp.md
- pkg/model/initializers.go
This creates an alias for `llama` to point to `llama-cpp` and `go-llama` for the golang backend
> feat(alias): alias llama to llama-cpp, update docs

- api/api.go
- api/api_test.go
- api/config/config.go
- api/openai/chat.go
- api/openai/completion.go
- api/openai/edit.go
- pkg/gallery/models.go
- pkg/model/loader.go
- pkg/utils/uri.go
This PR makes possible to allow inline templates and, to specify urls in models. as such now the yaml file can be a single, portable config file representing the model. 
An example of a model YAML file now could be:
```yaml
name: mixtral
parameters:
model: https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF/resolve/main/mixtral-8x7b-v0.1.Q2_K.gguf
template:
completion: |
Complete the following: {{.Input}}
```
TODO: tests, examples and docs updates
Partly related to #1373
> feat: inline templates and accept URLs in models

- .github/workflows/test-extra.yml
- backend/python/common-env/transformers/transformers-nvidia.yml
- backend/python/common-env/transformers/transformers.yml
- backend/python/vall-e-x/Makefile
- backend/python/vall-e-x/install.sh
- backend/python/vall-e-x/run.sh
- backend/python/vall-e-x/test.sh
Trying to shrink image sizes again. This makes vall-e-x share the same environment with transformer-based backends
> env(conda): use transformers for vall-e-x

- backend/python/diffusers/backend_diffusers.py
I use following config for stablediffusion
```yaml
name: stablediffusion 
parameters:
model: stabilityai/sdxl-turbo 
backend: diffusers
step: 1
cuda: false
f16: false
diffusers:
scheduler_type: euler_a
cfg_scale: 1
```
When i used the image generation endpoint, i saw
`stderr Keyword arguments {'guidance_scale': 1.0} are not expected by StableDiffusionXLPipeline and will be ignored.`
According to the example provided by https://github.com/huggingface/diffusers/blob/90b9479903dcf3b053dc2461d4d6266eed0c27ea/docs/source/en/using-diffusers/sdxl.md?plain=1#L135
`guidance_scale` should not in `xxxxxpipeline.from_pretrained` or `xxxxxpipeline.from_single_file` parameters.
This PR fixes the problem mentioned above.
<details>
<summary>result:</summary>
before:
after:
</details> …
> fix: guidance_scale not work in sd

- backend/cpp/llama/CMakeLists.txt
During my setup of Localai, I ran into problems related to the llama CMakeLists.txt not having a reference to the Homebrew install location for Intel Macs. This pr fixes the problem, while maintaining the Homebrew install location for arm64 Macs.
See [https://www.reddit.com/r/MacOS/comments/jw9guu/why_did_homebrew_move_from_usrlocalto_opthomebrew/](https://www.reddit.com/r/MacOS/comments/jw9guu/why_did_homebrew_move_from_usrlocalto_opthomebrew/) for more info.
> Fix: Set proper Homebrew install location for x86 Macs

- api/config/config.go
- pkg/utils/uri.go
This PR fixes an issue that would not allow to download models if specified as URLs.
It also slightly refactors thing out
> fix(download): correctly check for not found error

- api/api.go
- api/config/config.go
- api/localai/gallery.go
Previously if applying models from the gallery API, we didn't actually allowed remote URLs as models as nothing was actually downloading the models referenced in the configuration file. Now we call Preload after we have all the models loaded in memory.
> feat(preload): prepare models in galleries

- api/api.go
- api/config/config.go
- api/options/options.go
- docs/content/advanced/_index.en.md
- docs/content/build/_index.en.md
- main.go
- pkg/model/initializers.go
- pkg/utils/logging.go
- pkg/utils/uri.go
This PR allows to start local-ai with a list of model config files URLs or our short-handed format (e.g. `huggingface://`. `github://`). It works by passing the urls as arguments or environment variable, for example:
```
local-ai github://owner/repo/file.yaml@branch
MODELS="github://owner/repo/file.yaml@branch,github://owner/repo/file.yaml@branch" local-ai
local-ai --models github://owner/repo/file.yaml@branch --models github://owner/repo/file.yaml@branch
```
For example, to start localai with phi-2, now it's possible for instance:
```bash
./local-ai https://gist.githubusercontent.com/mudler/ad601a0488b497b69ec549150d9edd18/raw/a8a8869ef1bb7e3830bf5c0bae29a0cce991ff8d/phi-2.yaml
```
The file should be a valid YAML configuration file. Note this works well with the last …
> feat: share models by url

- api/config/config.go
This PR allows to specify additional files in the YAML config file to download automatically during preparation.
This is meant to be used in tandem with #1452 and #1522 .
The list of files can be specified in `download_files`, similarly to the galleries
> feat(prepare): allow to specify additional files to download

- api/backend/llm.go
- api/config/config.go
- examples/configurations/phi-2.yaml
This PR adds a `trimsuffix` option to cut portions of results out (useful for `phi-2` for instance that always returns a newline).
> feat: add trimsuffix

- backend/python/exllama/run.sh
- backend/python/exllama2/run.sh
- backend/python/vall-e-x/run.sh
Certain backends as vall-e-x are not meant to be used as a library, so we want to start the process in the same folder where the backend and all the assets are fixes #1394
This sadly wasn't caught by our tests that are running in the same folder the backend. applying the same to exllama as that similarly is not really a library
> fix(entrypoint): cd to backend dir before start

- backend/python/diffusers/diffusers.yml
> fix(diffusers): add omegaconf dependency

- .github/workflows/image-pr.yml
- .github/workflows/release.yaml
- .github/workflows/test.yml
- api/api.go
- api/api_test.go
- api/config/config.go
- docs/content/advanced/_index.en.md
- docs/content/build/_index.en.md
- docs/content/features/GPU-acceleration.md
- docs/content/getting_started/_index.en.md
- docs/content/model-compatibility/diffusers.md
- embedded/embedded.go
- embedded/model_library.yaml
- embedded/models/llava.yaml
- embedded/models/mistral-openorca.yaml
- pkg/assets/list.go
- pkg/downloader/progress.go
- pkg/downloader/uri.go
- pkg/downloader/uri_test.go
- pkg/gallery/gallery.go
- pkg/gallery/models.go
- pkg/startup/model_preload.go
- pkg/startup/model_preload_test.go
- pkg/startup/startup_suite_test.go
- pkg/utils/hash.go
This adds docs around the setups by sharing URL and shorthands in the code (hardcoded for now) plus adds embedded model configs directly from the code. ~~It also re-adds back #1522 that was missed in #1506~~
In the `embedded/models/` are defined all the yaml config files that can be run via arg command line directly by calling `local-ai <model-file>`. For instance, running `local-ai llava` now automatically sets up llava from the `embedded/models/llava.yaml` file, likewise, specifying a mapping in the `embedded/model_library.yaml` file will map a short-hand model to a full URL as already supported by #1522  
Refactors the downloader code into its own package, and creates a new `embedded` package that allows to embed model YAML configuration file directly from the source. I've added llava …
> feat: embedded model configurations, add popular model examples, refactoring

- backend/python/autogptq/Makefile
- backend/python/autogptq/run.sh
- backend/python/common-env/transformers/transformers-nvidia.yml
- backend/python/common-env/transformers/transformers.yml
> deps(conda): use transformers environment with autogptq

- Makefile
This PR adds a bit of compatibility for windows (#1569). go mod doesn't like the returned path of pwd in the replace directive by injecting double absolute paths resulting in not finding the correct folder.
```
go mod edit -replace github.com/M0Rf30/go-tiny-dream=/c/Users/Dionysius/Projects/github.com/mudler/LocalAI/sources/go-tiny-dream
go mod download
go: github.com/M0Rf30/go-tiny-dream@v0.0.0-20231128165230-772a9c0d9aaf (replaced by /c/Users/Dionysius/Projects/github.com/mudler/LocalAI/sources/go-tiny-dream): reading c\Users\Dionysius\Projects\github.com\mudler\LocalAI\sources\go-tiny-dream\go.mod: open C:\Users\Dionysius\Projects\github.com\mudler\LocalAI\c\Users\Dionysius\Projects\github.com\mudler\LocalAI\sources\go-tiny-dream\go.mod: The system cannot find the path …
```
> minor: replace shell pwd in Makefile with CURDIR for better windows compatibility

- Makefile
This PR fixes #1602.
It adds `BUILD_API_ONLY=true` as makefile options to skip building embedded backends.
TODO: docs
> Makefile: allow to build without GRPC_BACKENDS

- docs/content/docs/getting-started/manual.md
- docs/content/docs/getting-started/quickstart.md
Fixes https://github.com/mudler/LocalAI/issues/1314
- Links multiple images
- Makes sure searches for "Docker Hub" will find results
> Expanded and interlinked Docker documentation

- examples/llamaindex/README.md
- examples/llamaindex/main.py
This PR:
- Modernizes LocalAI demo to present-day LlamaIndex
- More explicitly states requirements in `README.md`
> Modernized LlamaIndex integration

- backend/python/transformers/transformers_server.py
- embedded/models/dolphin-2.5-mixtral-8x7b.yaml
- embedded/models/llava.yaml
- embedded/models/mistral-openorca.yaml
- embedded/models/mixtral-instruct.yaml
- embedded/models/tinyllama-chat.yaml
- examples/configurations/phi-2.yaml
Related to https://github.com/mudler/LocalAI/issues/1126. Up to now this backend was only supporting embeddings.
this PR adds text generation support also with transformers AutoModel/AutoTokenizer.
> feat(transformers): support also text generation

- api/api.go
Especially useful when running inside a container.
Part of #1373 
> fix(paths): automatically create paths

- docs/content/docs/advanced/fine-tuning.md
- examples/e2e-fine-tuning/README.md
- examples/e2e-fine-tuning/notebook.ipynb
This PR fixes broken links `github/` -> `github.com/`
> fix (docs): fixed broken links `github/` -> `github.com/`

- .github/workflows/test-extra.yml
- Dockerfile
I've got my A770 finally, so I'm trying to debug the container image. Seems we are missing something still as I cannot list the GPUs from the container (but I can from the host)
> fix(Dockerfile): sycl dependencies

- .github/workflows/release.yaml
This PR fixes #1413 
test in my fork: https://github.com/sozercan/LocalAI/actions/runs/7882993336  (other builds are commented out)
> ci: add cuda builds to release

- backend/cpp/llama/grpc-server.cpp
Infinite context loop might as well trigger an infinite loop of context shifting if the model hallucinates and does not stop answering. This has the unpleasant effect that the prediction never terminates, which is the case especially on small models which tends to hallucinate. The behavior is observable when the assigned slot exceed the context size, which triggers context shifting, and can be reproduced by specifying a really small context size window.
Workarounds https://github.com/mudler/LocalAI/issues/1333 by removing context-shifting until it is fixed upstream.
See also upstream issue: https://github.com/ggerganov/llama.cpp/issues/3969
> fix(llama.cpp): disable infinite context shifting

- Makefile
- backend/python/diffusers/Makefile
- backend/python/diffusers/install.sh
- backend/python/exllama2/install.sh
- backend/python/mamba/install.sh
- backend/python/vall-e-x/install.sh
exllama recently bumped pytorch which breaks the transformer environment. Until we pin the exllama deps into conda, pin exllamav2.
This PR fixes #1707 and fixes #1710
> fix(python): pin exllama2

- api/localai/localai.go
fixes #1707
Edited within GH, not tested
> fix(tts): fix regression when supplying backend from requests

- api/api.go
- api/openai/chat.go
- api/openai/request.go
- api/schema/openai.go
- pkg/grammar/functions.go
- pkg/model/loader.go
Part of https://github.com/mudler/LocalAI/issues/1712
still missing stream support
> feat(tools): support Tool calls in the API

- api/config/config.go
- api/openai/chat.go
- pkg/grammar/json_schema.go
- pkg/grammar/json_schema_test.go
This PR fixes https://github.com/mudler/LocalAI/issues/1275 and provides a drop-in support for https://platform.openai.com/docs/guides/function-calling/parallel-function-calling
This feature is gated by a config option that needs to be explicitly enabled in the model YAML configuration file as it is still experimental:
```yaml
function:
parallel_calls: true
```
This PR didn't went through testing (yet)
> feat(tools): Parallel function calling

- backend/python/vllm/backend_vllm.py
This PR fixes #1748
Current vLLM implementation uses the LLMEngine, which was designed for offline batch inference, which results in the streaming mode outputing all blobs at once at the end of the inference.
This PR reworks the gRPC server to use asyncio and gRPC.aio, in combination with vLLM's AsyncLLMEngine to bring true stream mode.
This PR also passes more parameters to vLLM during inference (presence_penalty, frequency_penalty, stop, ignore_eos, seed, ...).
I ran extensive tests to ensure nothing breaks.
> fix: vllm - use AsyncLLMEngine to allow true streaming mode

- .github/workflows/image.yml
Split jobs by self-hosted and free public runner provided by Github
> ci: reduce stress on self-hosted runners

- backend/go/transcribe/transcript.go
This PR provide a fix for the command injection in transcript endpoint which has been stated in this [issue](https://github.com/mudler/LocalAI/issues/1777) ( @m0kr4n3 and I  worked together on this vulnerability ).
In the fix, I changed the `sh` function to `runCommand`, and instead of using `/bin/sh` as the program to execute, I directly put the command name  (in this case, ffmpeg) and the rest as arguments. This way, the arguments will only be considered as options, and special characters such as `$, ;, ||` won't have any effect.
@mudler 
Twitter Accounts: @ouxs11, @m0kr4n3
> Fix Command Injection Vulnerability

- api/openai/assistant.go
- core/http/api.go
This PR implements one of the apis described in: #1273
Still a WIP, and needs some tests.
> feat(assistant): Initial implementation of assistants api

- backend/python/autogptq/autogptq.py
- backend/python/transformers/transformers_server.py
Discussion in our help channel pointed me at the `trust_remote_code` parameter used in Transformers backends.
Currently, this is enabled on default... while convenient, I do not feel that it is wise to expose our users to pickle supply chain attack s, especially since many of them are trying out AI generation for the first time and may not fully understand the risks this option exposes them to.
Down the line, it will make sense to detect the error raised by these backends when they encounter a model that simply doesn't work without custom code so that we can give a clear error message to the user explaining both the solution and the risks involved, but I wanted to get a "quick fix" out stopping the problem while we investigate that.
Luckily, vLLM was already doing the right thing - so we …
> feat(autogpt/transformers): consume `trust_remote_code`

- docs/content/docs/advanced/advanced-usage.md
- embedded/models/codellama-7b-gguf.yaml
- embedded/models/dolphin-2.5-mixtral-8x7b.yaml
- embedded/models/llava.yaml
- embedded/models/mistral-openorca.yaml
- embedded/models/mixtral-instruct.yaml
- examples/configurations/phi-2.yaml
The default sampler on some models don't return enough candidates which leads to a false sense of randomness. Tracing back the code it looks that with the temperature sampler there might not be enough candidates to pick from, and since the seed and "randomness" take effect while picking a good candidate this yields to the same results over and over.
Fixes https://github.com/mudler/LocalAI/issues/1723 by updating the examples and documentation to use mirostat instead.
The documentation was also wrong: there was a level of indentation that was breaking the configuration read.
Tested locally:
```
mudler@zz0t ~/_git/LocalAI mirostat_default*
base ❯ curl http://10.8.0.5:32457/v1/chat/completions -H "Content-Type: application/json" -d '{ …
```
> fix(doc/examples): set defaults to mirostat

- backend/cpp/llama/Makefile
This PR fixes #1826
The Makefile uses a BUILD_TYPE of clblas to signify an OpenCL build but the Makefile for the llama backend errantly had "clblast" (with a t), causing the llama builds to not actually build with OpenCL support.
> fix: the correct BUILD_TYPE for OpenCL is clblas (with no t)

- .dockerignore
- Dockerfile
This PR fixes #1829
This fixes the errors during a `make BUILD_TYPE=clblas docker` run.  This combined with the other fix in #1828 has allowed me to have a functional OpenCL docker image with the following command:
`make BASE_IMAGE=rocm/dev-ubuntu-22.04:6.0-complete BUILD_TYPE=clblas GO_TAGS="tts" docker`
> fix: missing OpenCL libraries from docker containers during clblas docker build

- Makefile
- backend/cpp/llama/Makefile
This PR fixes an issue with upstream llama.cpp not building on osx.
This was originally inlined with the update PR, but the bot force pushed over me... so this seems better.
> fix: OSX Build Files for llama.cpp

- core/backend/embeddings.go
Certain engines requires to know during model loading if the embedding feature has to be enabled, however, it is impractical to have to set it to ALL the backends that supports embeddings.
There are transformers and sentencentransformers that seamelessly handle both cases, without having this settings to be explicitly enabled.
The case sussist only for ggml-based models that needs to enable featuresets during model loading (and thus settings `embedding` is required), however most of the other engines does not require this.
This change disables the check done at code side, making easier to use embeddings by not having to specify explicitly `embeddings: true`.
Part of: https://github.com/mudler/LocalAI/issues/1373
> feat(embeddings): do not require to be configured

- core/http/endpoints/openai/request.go
- core/schema/openai.go
- core/schema/prediction.go
- request debugging: disable marshalling of context fields
- merging FrequencyPenalty request param with config
- This PR fixes #1051 
- Progress in #1373 
> fixes #1051: handle openai presence and request penalty parameters

- .dockerignore
- .github/workflows/image-pr.yml
- .github/workflows/image.yml
- .github/workflows/image_build.yml
- Dockerfile
- Makefile
- backend/cpp/grpc/Makefile
- backend/cpp/llama/Makefile
Fix a lot of missing dependency items in the Makefile to allow for parallel builds to succeed
There is also a little bit of general cleanup in the Makfile, most things fall into one of a few categories of changes:
- All of the sources/ targets are now grouped together at the top and placed in alphabetical order
- All of the backend/ and backend-artifact/ targets are now grouped together and placed in alphabetical order
- The deprecated backend-assets/grpc/llama backend was removed, it has been replaced by llama-cpp for quite a while
- Added support for a MAKEFLAGS arg/env to the Dockerfile which can be used to cause the `make` steps in the Docker build to run in parallel by passing something like `--build-arg MAKEFLAGS="-j10"` into the docker build …
> fix(make): allow to parallelize jobs

- Makefile
This PR fixes #1733 
See also: https://gitlab.kitware.com/cmake/cmake/-/issues/25536 - looks a cmake issue (?)
upstream: https://github.com/ggerganov/whisper.cpp/issues/1553
> deps(whisper.cpp): update, fix cublas build

- core/config/backend_config.go
Otherwise we panic if we run with debug=false
> fix(config): default to debug=false if not set

- core/config/application_config.go
- core/config/backend_config.go
- core/startup/startup.go
This bug had the unpleasant effect that it ignored defaults passed by the CLI. For instance threads could be changed only via model config file.
> fix(config): pass by config options, respect defaults

- .github/workflows/image.yml
- .github/workflows/image_build.yml
> ci(aio): add latest tag images

- aio/entrypoint.sh
This change makes the assumption that "Microsoft Corporation Device 008e" is an NVIDIA CUDA device. If this is not the case, please update the hardware detection script here.
This PR fixes #1890
> NVIDIA GPU detection support for WSL2 environments

- aio/entrypoint.sh
More robust single NVIDIA GPU memory detection, following the improved NVIDIA WSL2 detection patch yesterday #1891.
Tested and working on WSL2, Linux.
This PR fixes #1893
> Fix NVIDIA VRAM detection on WSL2 environments

- README.md
- aio/gpu-8g/image-gen.yaml
- docs/content/docs/getting-started/quickstart.md
- docs/content/docs/getting-started/run-other-models.md
- docs/content/docs/overview.md
- docs/content/docs/reference/aio-images.md
- docs/content/docs/reference/container-images.md
- tests/e2e-aio/e2e_suite_test.go
- tests/e2e-aio/e2e_test.go
image generation for the GPU aio profile was not working correctly - seems pickle refuses to load models if not ending with `.safetensors`.
> fix(aio): make image-gen for GPU functional, update docs

- backend/python/autogptq/autogptq.py
- backend/python/autogptq/autogptq.yml
- backend/python/common-env/transformers/transformers-nvidia.yml
- backend/python/common-env/transformers/transformers-rocm.yml
- backend/python/common-env/transformers/transformers.yml
Due to prompt template incompatible with current prompt processing flow, I removed support for `internlm/internlm-xcomposer2-vl-7b-4bit` in this PR. I may add the support in a separate PR.
This PR fixes #1812, and enhanced AutoGPTQ to support `Qwen/Qwen-VL-Chat-Int4` ~~and `internlm/internlm-xcomposer2-vl-7b-4bit`~~ models. 
~~The AutoGPTQ version is updated to `v0.7.1`, and enables  `use_marlin` flag for `internlm/internlm-xcomposer2-vl-7b-4bit` by default. Please make sure you have the correct model in place. Ref: https://github.com/IST-DASLab/marlin~~
> Enhance autogptq backend to support VL models

- backend/python/common-env/transformers/transformers-nvidia.yml
- backend/python/common-env/transformers/transformers.yml
This PR downgrades torch - auto-gptq does not need new torch and not all the libs we use in the transformer environment are ready for the bump.
follow up of #1860 
> fix: downgrade torch

- core/config/application_config.go
- core/http/api.go
- core/http/views/404.html
- core/http/views/index.html
- core/http/views/partials/footer.html
- core/http/views/partials/head.html
- core/http/views/partials/navbar.html
- go.mod
- go.sum
- main.go
This PR fixes #1907 
For now it adds a very simple page that redirects to the docs and show the models configured, it is mapped to `/`.
> feat(welcome): add simple welcome page

- .github/workflows/image-pr.yml
- .github/workflows/image.yml
- .github/workflows/release.yaml
- .github/workflows/test-extra.yml
- .github/workflows/test.yml
- Makefile
This will group the log output of the make commands in the image builds by make target.  This will make it easier to understand the log files if/when a build failure occurs.
There are now quotes around the GO_TAGS build arg under `make docker` to fix things like `GO_TAGS="tts stablediffusion" make docker` failing.
The typical location for opencv headers is now included by default to allow stablediffusion builds.
The one downside to this is that the builds won't output any logs for a make target until that make target is complete.  So the logs will come in batches.  This still seems preferable to the logs being all intermixed and difficult to parse if there is a build failure though.
The only other thing of real note is the addition of the opencv …
> fix(build): better CI logging and correct some build failure modes in Makefile

- .github/workflows/image-pr.yml
- .github/workflows/image.yml
- .github/workflows/image_build.yml
- .github/workflows/release.yaml
- .github/workflows/test-extra.yml
- .github/workflows/test.yml
- Dockerfile
- Makefile
Adjust the number of parallel make jobs throughout the workflows to attempt to shorten build times even further
for the ubuntu and macos action runners, the --jobs parameter was informed based on the data from (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
I am unsure what the CPU capacity of the arc runner set is, so I left it at --jobs 3, which is what it was already running with.
> feat(build): adjust number of parallel make jobs

- core/http/api.go
- swagger/docs.go
- swagger/swagger.json
- swagger/swagger.yaml
In this way the requests are redirected to the host used by the client to perform the request.
> fix(swagger): do not specify a host

- aio/cpu/text-to-text.yaml
- core/http/endpoints/openai/chat.go
- core/http/endpoints/openai/completion.go
- embedded/models/phi-2-orange.yaml
- tests/e2e-aio/e2e_test.go
Somehow we did regressed and we were not respecting anymore the grammar input.
Adds an AIO test to cover the use-case
> fix(grammar): respect JSONmode and grammar from user input

- aio/entrypoint.sh
- entrypoint.sh
The Docker entrypoint scripts should use exec so that the process they call gets PID 1.  This will ensure that when docker/kubernetes/etc sends a signal to the container, it is received by local-ai.  This fixes localai pods/containers taking a long time to exit when you request the pod to stop.
> fix: use exec in entrypoint scripts to fix signal handling

- .github/labeler.yml
- .github/workflows/labeler.yml
- .github/workflows/secscan.yaml
- core/backend/options.go
- core/config/backend_config.go
- docs/content/docs/features/text-generation.md
- tests/e2e-aio/e2e_suite_test.go
Also update ci with new workflows and allow the aio tests to run with an api key
> fix(seed): generate random seed per-request if -1 is set

- .vscode/extensions.json
- core/config/application_config.go
- core/http/endpoints/openai/chat.go
- core/http/endpoints/openai/files_test.go
- core/services/backend_monitor.go
- core/startup/config_file_watcher.go
- core/startup/startup.go
- main.go
- pkg/gallery/models.go
- pkg/model/initializers.go
- pkg/model/watchdog.go
- pkg/startup/model_preload.go
- pkg/utils/config.go
Zerolog is capable of proper structured logging.  This is the first pass to leverage that functionality.  I am starting with the error logs and plan to work through the system in passes one log level at a time.
> feat: first pass at improving logging

- .github/workflows/release.yaml
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
> ci: try to build on macos14

- backend/cpp/grpc/Makefile
We shouldn't override the --jobs parameter to make for recursive make calls
This is likely left over from before LocalAI was able to use multiple build threads due to dependency ordering issues.  Now that we have that resolved, we should build GRPC using the same concurrency parameters as the rest of the build.
> fix: respect concurrency from parent build parameters when building GRPC

- core/cli/run.go
#1974 broke debug logging, this fixes it
--debug would have still worked fine, it was --log-level=debug that didn't work
> fix: previous CLI rework broke debug logging

- core/clients/store.go
This adds a basic store client for Go
#1900 
this is just a preliminar implementation to have a corresponding client in golang of the server-side functionality
> feat(store): add Golang client

- Makefile
This cleans up some of the source checkouts so that the folder in sources/ matches the name of the repository.
sources/go-rwkv > sources/go-rwkv.cpp
sources/go-bert > sources/go-bert-cpp
sources/go-llama-ggml > sources/go-llama.cpp
I also moved one go mod replace that was in a backend-assets target to be inside the replace target instead
> fix: adjust some sources names to match the naming of their repositories

- core/config/backend_config.go
- core/http/endpoints/openai/chat.go
- core/http/endpoints/openai/completion.go
- core/http/endpoints/openai/request.go
- core/schema/openai.go
- pkg/functions/functions.go
- pkg/functions/functions_suite_test.go
- pkg/functions/functions_test.go
- pkg/functions/grammar_json_schema.go
- pkg/functions/grammar_json_schema_test.go
- pkg/functions/parse.go
- pkg/functions/parse_test.go
- pkg/model/loader.go
This PR is related to #1717. It started by adding tests, but supporting no grammar required just a small addition so it is included with this refactoring round. 
It allows to define in the model config two new fields:
```yaml
function:
no_grammar: true
response_regex: "..."
```
The response regex have to be a regex with named parameters to allow to scan the function name and the arguments. For instance, consider:
```
(?P<function>\w+)\s*\((?P<arguments>.*)\)
```
will catch
```
function_name({ "foo": "bar"})
```
as a result from the LLM. This can be improved later on, but it puts the basics for extending this part without the use of JSON grammars.
it moves some code around, but now this portion is entirely covered by tests
**[Signed …
> feat(functions): support models with no grammar, add tests

- .github/workflows/generate_grpc_cache.yaml
This should fix the issue that the grpc cache generation job was being killed if something was merged to master mid-run.
> fix: move the GRPC cache generation workflow into it's own concurrency group

- core/cli/cli.go
- core/cli/run.go
- core/config/application_config.go
- core/http/api.go
- core/http/api_test.go
- core/startup/startup.go
- go.mod
- go.sum
- main.go
This updates the Fiber configuration so that it will use zerolog for it's logging like the rest of the project
It also adds support for a new, yet to be used, trace level. The trace level can be used as a "dumping ground" of sorts for any logging data that might be useful if you are trying to troubleshoot something, but that wouldn't be useful for normal Debug levels.
> feat: fiber logs with zerlog and add trace level

- core/config/backend_config.go
Likely a leftover, that had the unpleasant effect of cutting the prompts results always to 2048 if no max_tokens is specified
Related https://github.com/mudler/LocalAI/issues/2054#issuecomment-2067609255
> fix(llama.cpp): set -1 as default for max tokens

- Makefile
- core/http/api.go
- core/http/endpoints/localai/welcome.go
- core/http/render.go
- core/http/routes/elevenlabs.go
- core/http/routes/localai.go
- core/http/routes/openai.go
- core/http/routes/welcome.go
A small PR to split routes registration. There is no change in the logic, just moving things to avoid merge conflicts in that area later on.
> refactor(routes): split routes registration

- core/config/backend_config.go
likely caused by #2087. The old binding does not recognize -1, and tries to allocate a slice of length of -1.
llama.cpp instead is already configured to set infinite tokens if a value of 0 of max_tokens is specified.
> fix(llama.cpp-ggml): fixup `max_tokens` for old backend

- .github/workflows/test.yml
connect-timeout-seconds works best with `detached: true`
This PR should fix slow running test failures that I noticed
> fix: action-tmate detached

- README.md
- core/config/backend_config.go
- core/http/app.go
- core/http/elements/gallery.go
- core/http/endpoints/localai/welcome.go
- core/http/routes/localai.go
- core/http/routes/ui.go
- core/http/routes/welcome.go
- core/http/views/models.html
- core/http/views/partials/head.html
- core/http/views/partials/navbar.html
- docs/content/docs/overview.md
- go.mod
- go.sum
- main.go
- pkg/downloader/progress.go
- pkg/downloader/uri.go
- pkg/gallery/models.go
- pkg/gallery/op.go
- pkg/startup/model_preload.go
there are few things still to fix:
> feat: Galleries UI

- .github/workflows/test-extra.yml
- Dockerfile
- Makefile
- aio/cpu/rerank.yaml
- aio/entrypoint.sh
- aio/gpu-8g/rerank.yaml
- aio/intel/rerank.yaml
- backend/backend.proto
- backend/python/common-env/transformers/transformers-nvidia.yml
- backend/python/common-env/transformers/transformers-rocm.yml
- backend/python/common-env/transformers/transformers.yml
- backend/python/rerankers/Makefile
- backend/python/rerankers/README.md
- backend/python/rerankers/reranker.py
- backend/python/rerankers/run.sh
- backend/python/rerankers/test.sh
- backend/python/rerankers/test_reranker.py
- core/backend/rerank.go
- core/http/app.go
- core/http/endpoints/jina/rerank.go
- core/http/routes/jina.go
- core/schema/jina.go
- pkg/grpc/backend.go
- pkg/grpc/client.go
- pkg/grpc/embed.go
This PR fixes #2018 . It was quite easy out to assemble as `rerankers` have a very good support for models out there.
It adds support for rerankers API, specifically implements the jina reranker APIs documented here: https://jina.ai/reranker/#apiform, behind the hoods, uses https://github.com/AnswerDotAI/rerankers for calculations.
You can test this by using container images with python (this does **NOT** work with `core` images) and a model config file like this:
```yaml
name: jina-reranker-v1-base-en
backend: rerankers
parameters:
model: cross-encoder
usage: |
You can test this model with curl like this:
curl http://localhost:8080/v1/rerank \
-H "Content-Type: application/json" \
-d '{
"model": "jina-reranker-v1-base-en",
"query": "Organic …
```
> feat(rerankers): Add new backend, support jina rerankers API

- core/backend/options.go
- core/backend/tts.go
- core/http/app.go
- core/http/app_test.go
- core/http/endpoints/openai/assistant_test.go
- core/http/endpoints/openai/files_test.go
- core/startup/startup.go
- pkg/assets/extract.go
- pkg/downloader/uri.go
- pkg/gallery/models.go
- pkg/gallery/models_test.go
- pkg/model/process.go
- pkg/templates/cache_test.go
- pkg/utils/config.go
- tests/integration/stores_test.go
quiet more security scanner issues: pass one of chmod restriction to remove group and other permissions
This PR should remove a number of noisy scanner issues like https://github.com/mudler/LocalAI/security/code-scanning/28
@cryptk if you have a minute, please check that the permissions I've picked here will work in all docker scenarios you're aware of. As far as I know, we shouldn't be depending on group or other permissions in any environment, but after the windows + docker mount file event issue... I want to make sure that nothing funky is going on there.
> fix: reduce chmod permissions for created files and directories

- backend/go/transcribe/transcript.go
runCommand ==> ffmpegCommand. No functional changes, but makes it clear to the security scanner and future developers that this function cannot run arbitrary commands by changing the arguments very slightly.
https://github.com/mudler/LocalAI/security/code-scanning/6
This really is a false positive, but this change is slightly worth it for readability
> fix: security scanner dislikes `runCommand` function arguments

- .github/workflows/image-pr.yml
- .github/workflows/image.yml
- Makefile
- backend/python/common-env/transformers/transformers.yml
- backend/python/transformers/transformers_server.py
Bump to the latest release: [openvino 2024.1.0](https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino/2024-1.html)
Selected from release notes:
- Mixtral and URLNet models optimized for performance improvements on Intel® Xeon® processors.
- The preview NPU plugin for Intel® Core™ Ultra processors is now available in the OpenVINO open-source GitHub repository, in addition to the main OpenVINO package on PyPI.
- Significant memory reduction for select smaller GenAI models on Intel® Core™ Ultra processors with integrated GPU.
- (CPU) LLM compilation time and memory footprint have been improved through additional optimizations with compressed embeddings.
- (CPU) Performance of MoE (e.g. Mixtral), Gemma, and GPT-J has been improved further.
- (GPU) …
> Bump oneapi-basekit, optimum and openvino

- core/config/backend_config.go
- core/http/elements/gallery.go
- core/http/routes/ui.go
- pkg/xsync/map.go
- pkg/xsync/map_test.go
- pkg/xsync/sync_suite_test.go
Previously, if you started installation of a model by clicking on the install button and you hit refresh or change page the progressbar  and the job status would be lost - this change make sure we keep showing the progressbar as long as the job is still running.
> feat(gallery): display job status also during navigation

- .github/workflows/generate_grpc_cache.yaml
- .github/workflows/image_build.yml
- Dockerfile
Cleans up the Dockerfile to make it a bit easier to see what's going on and also makes a few adjustments to reduce the size of the final image a little.  In my local testing, the uncompressed image is about 2.5GB smaller and the compressed image in a registry is about 0.5GB smaller
The changes fall into a few categories:
- newline and indentation adjustments to make the Dockerfile easier to read and maintain
- ensure that all apt-get stanzas completely cleanup after themselves
- do not install recommended packages, only actual dependencies
- have GRPC install into a prefix in the same container that builds it, which allows us to copy in the resulting build artifacts rather than the entire GRPC source tree in subsequent containers
- This alone …
> feat: cleanup Dockerfile and make final image a little smaller

- docs/content/docs/features/model-gallery.md
The readme points to a file that hasn't been updated in months so when there are announcements about new models, user's won't get them pointing to the old file. Point to this file that is the one you've been updating in the docs: https://github.com/mudler/LocalAI/blob/master/gallery/index.yaml
I'm giving up setting these values in the compose.yaml, and will just use the .env file to get galleries but I don't know how to update your documentation with the issue that I get when I try to run what I think is the fixed change
environment:
- DEBUG=true
- GALLERIES=[{"name":"localai", "url":"github:mudler/gallery/index.yaml"}]
```
curl http://localhost:8080/models/available 
{"error":{"code":500,"message":"yaml: unmarshal errors:\n  line 1: …
```
> draft:Update model-gallery.md with correct gallery file

- Makefile
While working on some other PRs, I noticed the following in the build output from the whisper backend:
!!!!
WHISPER_CUBLAS is deprecated and will be removed in the future. Use WHISPER_CUDA instead.
!!!!
This PR changes over to the WHISPER_CUDA env var instead.
> fix: swap to WHISPER_CUDA per deprecation message from whisper.cpp

- .github/workflows/image_build.yml
- Dockerfile
As we are performing the `make install` in the grpc cache now, the only thing we actually need from that cache are the build artifacts, not the source, or the intermediate artifacts.
This PR updates the cache target so that it will clone, configure, build and install all in one step, and then remove the entire source tree, so that the only data left in the image layer are the final build artifacts that we need.
Looking at some current builds, pulling down that last layer, with ~2.5GB of data, only takes ~20 seconds on the github hosted runners to download and extract the GRPC cache, but they have a very fast connection to the GHA cache.  The self-hosted runners however have threads tied up for at least 4 minutes (and in some cases over 5 minutes) pulling down the cache, so …
> feat: only keep the build artifacts from the grpc build

- core/config/backend_config.go
- core/http/elements/gallery.go
- core/http/endpoints/localai/gallery.go
- core/http/routes/localai.go
- core/http/routes/ui.go
- core/services/gallery.go
- pkg/gallery/gallery.go
- pkg/gallery/gallery_suite_test.go
- pkg/gallery/models.go
- pkg/gallery/models_test.go
- pkg/gallery/op.go
- pkg/model/loader.go
> feat(gallery): support model deletion

- docs/content/docs/getting-started/build.md
The numbering [here ](https://localai.io/basics/build/#troublshooting-mac) was reset half way, so `1->2->code section->1->2`. 
I think it's likely due to the way HTML/CSS treats nested code sections, the numbering seems to got reset when there is a code section `<div>` in between. 
The [README](https://github.com/mudler/LocalAI/blob/master/docs/content/docs/getting-started/build.md) is fine, it properly displays 1, 2, 3, 4.
We could think of a better way dealing with this type of question in the future, but sounds like an over-engineering to me. This PR will remove the numbers.
> [Documentations] Removed invalid numberings from `troubleshooting mac`

- gallery/chatml.yaml
- gallery/index.yaml
This PR adds https://huggingface.co/MaziyarPanahi/Llama-3-8B-Instruct-DPO-v0.3-32k-GGUF
> models(gallery): add llama3-32k

- Makefile
Found another spot where we weren't passing through the GNUMake jobserver for parallel builds
> fix: ensure GNUMake jobserver is passed through to whisper.cpp build

- backend/python/transformers/transformers_server.py
This PR fixes implement OpenVINO acceleration for embeddings in transformer backend.
Like for Text Generation the GPU is automatically used if present.
Acceleration is enabled with new argument for `type: OVModelForFeatureExtraction`
example:
```
name: transformer-embedding
backend: transformers
embeddings: true
parameters:
model: intfloat/multilingual-e5-base
type: OVModelForFeatureExtraction
```
> feat: OpenVINO acceleration for embeddings in transformer backend

- .github/workflows/generate_grpc_cache.yaml
- .github/workflows/image_build.yml
- .github/workflows/release.yaml
- .github/workflows/test-extra.yml
- .github/workflows/test.yml
- backend/python/autogptq/autogptq.yml
- backend/python/common-env/transformers/transformers-nvidia.yml
- backend/python/common-env/transformers/transformers-rocm.yml
- backend/python/common-env/transformers/transformers.yml
- backend/python/diffusers/diffusers-rocm.yml
- backend/python/diffusers/diffusers.yml
- backend/python/diffusers/install.sh
- backend/python/exllama/exllama.yml
- backend/python/exllama2/exllama2.yml
- backend/python/parler-tts/parler-nvidia.yml
- backend/python/parler-tts/parler.yml
- backend/python/vall-e-x/ttsvalle.yml
grpcio and grpcio-tools 1.63 was just released and it started causing the extra backend tests to fail as some the protobuf files were being built with 1.63 and the conda envs were running 1.59.  This PR brings all GRPC usage to the same version.
Homebrew only has 1.54.3 or 1.62 of GRPC available currently, so everything has been aligned on the newly released 1.63 (which is compatible with 1.62 available on brew/metal).
> fix: bring everything onto the same GRPC version to fix tests

- gallery/index.yaml
This PR adds https://huggingface.co/MaziyarPanahi/guillaumetell-7b-GGUF
Thanks to @MaziyarPanahi for providing the great models! :muscle:
> models(gallery): add guillaumetell

- .github/workflows/image-pr.yml
- .github/workflows/image.yml
- Dockerfile
This is an attempt to not only update ROCM to 6.1, which according to the release notes should be compatible with every card that 6.0 is compatible with, but also to move away from the very very large -complete images and instead use the smaller rocm "base" images, while only pulling in the few individual things that we need from the -complete image.
This should save a couple of GB on the resulting images, as well as considerably speed up builds as we won't need to download an ~4.2GB image, but instead an ~970MB image.
I did some local testing, and I was able to build images, but I don't have a ROCM compatible GPU to do any in-depth testing/validation with.
Below is the complete list of packages that are installed in the -complete image that are not …
> feat: update ROCM and use smaller image

- docs/content/docs/features/text-generation.md
Added documentation for all the parameters and features available in transformer backend.
> docs: updated Transformer parameters description

- Makefile
- backend/cpp/llama/Makefile
- backend/cpp/llama/prepare.sh
- backend/go/llm/langchain/langchain.go
- core/http/app_test.go
- pkg/langchain/huggingface.go
- pkg/model/initializers.go
We can simply try to autoload the backends extracted in the asset dir, instead of hardcoding those in the binary.  Besides simplifying maintenance as we don't need to keep the index up-to-date, it also simplifies building as we have to just drop the backends in the folder which is then embedded in the binary during build time. 
This will allow ALSO to build variants of the same backend (for e.g. with different instructions sets)  without having to specify an hardcoded name, easing out to have a single binary for all the variants.
In this PR I've also added two build variants for llama.cpp: `noavx` which disables only AVX, and `fallback` which disables specific instruction sets. 
Partly related to #1888 
Potentially fixes many other issues which root cause is an old CPU without support for …
> feat(llama.cpp): do not specify backends to autoload and add llama.cpp variants

- gallery/index.yaml
This PR fixes a changed checksum for a model in the gallery. currently you will get a error like this if you try to install a model:
Installing
ErrorSHA mismatch for file "/models/Hermes-2-Pro-Llama-3-8B-Q5_K_M.gguf" ( calculated: 107f3f55e26b8cc144eadd83e5f8a60cfd61839c56088fa3ae2d5679abf45f29 != metadata: 2be39d775b2a64aa5bbdc1f96fa1703ec54b5fa8982c1732b7ae9d2b57c6bb43 )
> fix(gallery): hermes-2-pro-llama3 models checksum changed

- core/startup/startup.go
- go.mod
- go.sum
- pkg/model/initializers.go
- pkg/xsysinfo/cpu.go
- pkg/xsysinfo/gpu.go
This PR adds debug information about the system when `--debug` is enabled, allowing to have a slightly more information about the system, which can be especially useful when sharing logs.
Besides, it is an exercise to start laying down the functionalities we need in order to load the correct backends variants given the CPU/GPU capacity. We could for instance also have gpu variants pre-compiled for amd and gpu in the same binary (partly related to #1888)
> feat(startup): show CPU/GPU information with --debug

- .github/workflows/release.yaml
- Makefile
Now that we have llama.cpp variants directly in a single binary as separate backends #2232, there is no need to have separate versions in the releases anymore
Related to #1888
> feat(single-build): generate single binaries for releases

- core/config/backend_config_loader.go
- core/http/elements/gallery.go
- core/http/endpoints/localai/gallery.go
- core/http/endpoints/localai/welcome.go
- core/http/routes/ui.go
- core/http/views/index.html
- core/http/views/models.html
- core/services/gallery.go
- pkg/gallery/gallery.go
- pkg/gallery/models.go
- pkg/gallery/op.go
- pkg/gallery/request.go
This PR introduces the following enhancements to the WebUI:
- Deleting a model now asks for confirmation
- Installed models can be deleted from the model list view, and show the model icon 
- Changes the welcome screen as such gives the user indications in case there are no models installed.
- Adds filters for searching models in the gallery, and generates all the existing tags as clickable items
- Makes the tag buttons in the model card clickable to filter out other models with the same tag
Also - if the user clicks on Chat/Generate images/TTS and no model is installed is redirected automatically at the index (showing the message that no models are present).
This PR is related to #2156
> feat(webui): ux improvements

- gallery/index.yaml
This PR adds https://huggingface.co/failspy/Llama-3-8B-Instruct-abliterated-GGUF
> models(gallery): add Llama-3-8B-Instruct-abliterated

- core/http/endpoints/openai/chat.go
- core/schema/openai.go
- pkg/functions/functions.go
- pkg/functions/functions_test.go
- pkg/functions/grammar_json_schema.go
- pkg/functions/grammar_json_schema_test.go
- pkg/functions/parse.go
When enabling grammar with functions, it might be useful to allow more flexibility to support models that are fine-tuned against returning function calls of the form of { "name": "function_name", "arguments" {...} } rather then { "function": "function_name", "arguments": {..} }.
This might call out to a more generic approach later on, but for the moment being we can easily support both as we have just to specific different types.
If needed we can expand on this later on
> feat(grammar): support models with specific construct

- backend/python/autogptq/install.sh
- backend/python/autogptq/requirements-intel.txt
- backend/python/bark/install.sh
- backend/python/bark/requirements-intel.txt
- backend/python/common/template/install.sh
- backend/python/common/template/requirements-intel.txt
- backend/python/coqui/install.sh
- backend/python/coqui/requirements-intel.txt
- backend/python/diffusers/install.sh
- backend/python/parler-tts/install.sh
- backend/python/parler-tts/requirements-intel.txt
- backend/python/petals/install.sh
- backend/python/petals/requirements-intel.txt
- backend/python/rerankers/install.sh
- backend/python/rerankers/requirements-intel.txt
- backend/python/sentencetransformers/install.sh
- backend/python/sentencetransformers/requirements-intel.txt
- backend/python/transformers-musicgen/install.sh
- backend/python/transformers-musicgen/requirements-intel.txt
- backend/python/transformers/install.sh
- backend/python/transformers/requirements-intel.txt
- backend/python/vall-e-x/install.sh
- backend/python/vall-e-x/requirements-intel.txt
- backend/python/vllm/install.sh
- backend/python/vllm/requirements-intel.txt
This PR fixes #2289 
Uses the new libbackend to handle some required flags to workaround bad behavior by the intel pip index. ;)
> fix: add missing openvino/optimum/etc libraries for Intel, fixes #2289

- core/http/routes/ui.go
- core/http/views/models.html
> feat(ui): display number of available models for installation

- backend/python/transformers/requirements-intel.txt
Adding setuptools for OpenVINO transformer backend
This PR fixes #2289 with setuptools install in venv.
Only transformer backend `requirements-intel.txt` has been changed: do you think that all must be updated?
> add setuptools for openvino

- gallery/index.yaml
This PR adds https://huggingface.co/BAAI/Bunny-Llama-3-8B-V-gguf
> models(gallery): add Bunny-llama

- backend/backend.proto
- backend/cpp/llama/grpc-server.cpp
- core/backend/options.go
- core/config/backend_config.go
https://github.com/ggerganov/llama.cpp/pull/5021
> feat(llama.cpp): add `flash_attention` and `no_kv_offloading`

- pkg/functions/parse.go
- pkg/functions/parse_test.go
This allows to forward directly what the LLM returns in JSON without specifying any regex or by disabling entirely grammar. It is of course, at this point all to the LLM to return the correct JSON that we can use in the response.
> feat(functions): support models with no grammar and no regex

- core/http/endpoints/openai/chat.go
- pkg/functions/parse.go
- pkg/functions/parse_test.go
This PR allow to set JSON matcher in the response coming from the LLM, for example:
```yaml
function:
no_grammar: true
json_regex_match: "(?s)<tool_call>(.*?)</tool_call>"
```
Should be able to parse responses from hermes pro without JSON grammars
> feat(functions): allow to set JSON matcher

- .env
- .github/workflows/release.yaml
- Dockerfile
- Makefile
- backend/cpp/llama/grpc-server.cpp
- core/cli/cli.go
- core/cli/llamacppworker.go
- core/config/backend_config.go
- core/http/endpoints/openai/chat.go
- pkg/assets/extract.go
- pkg/model/initializers.go
This PR fixes #2322 and is based off https://github.com/ggerganov/llama.cpp/pull/6829.
This works by setting the `LLAMACPP_GRPC_SERVERS` environment variable - automatically then the llama.cpp backend is mapped to the `grpc` one and being selected instead of the other variants.
You can start `local-ai` as always with `local-ai run`, however, you can now start workers to offload the computation with:
```
local-ai llamacpp-worker <listening_address> <listening_port>
```
or either by following the llama.cpp README and building a rpc-server (https://github.com/ggerganov/llama.cpp/blob/master/examples/rpc/README.md)
When starting LocalAI, now you can set a list of servers by specifying the addresses with `LLAMACPP_GRPC_SERVERS`:
```bash …
```
> feat(llama.cpp): add distributed llama.cpp inferencing

- core/http/endpoints/openai/chat.go
- pkg/functions/grammar_json_schema.go
- pkg/functions/grammar_json_schema_test.go
- pkg/functions/parse.go
This PR provides new options to control how functions are extracted from the LLM, and also provides more control on how JSON grammars can be used (also in conjunction).
New YAML settings introduced:
- `grammar_message`: when enabled, the generated grammar can also decide to push strings and not only JSON objects. This allows the LLM to pick to either respond freely or using JSON constrained by BNF rules (which are generated on the fly by the parser).
- `grammar_prefix`: Allows to prefix a string to the JSON grammar definition.
- `replace_results`: Is a map that allows to replace strings in the LLM result.
As an example, consider the following settings for Hermes-2-Pro-Mistral, which allow extracting **both** JSON results coming from the model, and the ones coming from the grammar:
```yaml …
```
> feat(functions): mixed JSON BNF grammars

- gallery/index.yaml
This must be a mistake because the config tries to use a model file that is different from the one actually being downloaded. I assumed the downloaded file is what should be used so I corrected the specified model file to that
> fix(gallery) Correct llama3-8b-instruct model file

- backend/python/autogptq/requirements-intel.txt
- backend/python/bark/requirements-intel.txt
- backend/python/coqui/requirements-intel.txt
- backend/python/diffusers/requirements-intel.txt
- backend/python/parler-tts/requirements-intel.txt
- backend/python/petals/requirements-intel.txt
- backend/python/rerankers/requirements-intel.txt
- backend/python/sentencetransformers/requirements-intel.txt
- backend/python/transformers-musicgen/requirements-intel.txt
- backend/python/vall-e-x/requirements-intel.txt
- backend/python/vllm/requirements-intel.txt
This fixes part of #2332 .  We also had a previous issue where intel backends required setuptools to be added with the transformers backend.  Adding it to all backends that run on intel builds just to be safe.
> fix: add setuptools to all requirements-intel.txt files for python backends

- pkg/functions/parse.go
- pkg/functions/parse_test.go
This PR simplifies the parsing part, making sure that there is no duplication of code and:
- we treat similarly grammars and no grammars outputs from the LLM: now regex matching has effect also on output returned by grammars and options can be mixed freely
- read a list of tools or a single tool regardless if it was enabled or not via configuration - if the LLM returns a list we map to a list, otherwise to a list with a single element
- simplify overall code
> feat(functions): simplify parsing, read functions as list

- pkg/functions/parse.go
- pkg/functions/parse_test.go
This PR fixes #2340
It allows using true regexs in the regex replacement. Current implementation of strings.repalceall treats any regex statement as a plain string. 
None
> feat(functions): Enable true regex replacement for the regexReplacement option

- gallery/index.yaml
This PR adds https://huggingface.co/qnguyen3/Master-Yi-9B
> models(gallery): add master-yi

- pkg/functions/parse.go
- pkg/functions/parse_test.go
This PR lets use JSONRegexMatch regardless before processing further, allowing it to use both in grammar and no-grammar environment - this is especially useful if used in conjunction with `grammar_message`.
This PR also changes `json_regex_match` to be a list instead of a string. First match wins.
Example
```yaml
context_size: 4096
f16: true
mmap: true
name: hermes-2-pro-llama-3-8b
parameters:
model: Hermes-2-Pro-Llama-3-8B-Q4_K_M.gguf
stopwords:
- <|im_end|>
- </tool_call>
function:
disable_no_action: true
grammar_message: true
grammar_prefix: '<tool_call>\n'
return_name_in_function_response: true
json_regex_match: 
- "(?s)<tool_call>(.*?)</tool_call>"
- "(?s)<tool_call>(.*?)"
replace_results: 
"(?s)^[^{\[]*": ""
"(?s)[^}\]]*$": ""
"'([^']*?)'": "_DQUOTE_${1}_DQUOTE_" …
```
> feat(functions): allow to use JSONRegexMatch unconditionally

- gallery/index.yaml
- gallery/mudler.yaml
This PR adds https://huggingface.co/mudler/LocalAI-Llama3-8b-Function-Call-v0.2-GGUF.
It is my first fine-tune trying to match more closely LocalAI features and leverage grammar completely. Once the LLM enters in tools mode, it will keep reply with JSON for consistency.
> models(gallery): add LocalAI-Llama3-8b-Function-Call-v0.2-GGUF

- pkg/functions/parse.go
- pkg/functions/parse_test.go
No need to use yaml.Mapslice, just have a list of key/values
Tested with:
```yaml
context_size: 4096
f16: true
mmap: true
name: hermes-2-theta-llama-3-8b
parameters:
model: Hermes-2-Pro-Llama-3-Instruct-Merged-DPO-Q4_K_M.gguf
stopwords:
- <|im_end|>
- </tool_call>
function:
disable_no_action: true
grammar_message: true
grammar_prefix: '<tool_call>\n'
return_name_in_function_response: true
json_regex_match: 
- "(?s)<tool_call>(.*?)</tool_call>"
- "(?s)<tool_call>(.*?)"
replace_results: 
- key: '(?s)^[^{\[]*'
value: ""
- key: '(?s)[^}\]]*$'
value: ""
- key: "'([^']*?)'"
value: "_DQUOTE_${1}_DQUOTE_"
- key: '\\"'
value: "__TEMP_QUOTE__"
- key: "\'"
value: "'"
- key: "_DQUOTE_"
value: '"'
- key: "__TEMP_QUOTE__"
value: '"'
template:
chat: |
{{.Input -}}
<|im_start|>assistant
chat_message: | …
```
> feat(functions): don't use yaml.MapSlice

- .github/workflows/generate_grpc_cache.yaml
- .github/workflows/image_build.yml
- .github/workflows/release.yaml
- .github/workflows/test-extra.yml
- .github/workflows/test.yml
- backend/python/autogptq/requirements.txt
- backend/python/bark/requirements.txt
- backend/python/common/template/requirements.txt
- backend/python/coqui/requirements.txt
- backend/python/diffusers/requirements.txt
- backend/python/exllama/requirements.txt
- backend/python/exllama2/requirements.txt
- backend/python/mamba/requirements.txt
- backend/python/openvoice/requirements-intel.txt
- backend/python/openvoice/requirements.txt
- backend/python/parler-tts/requirements.txt
- backend/python/rerankers/requirements.txt
- backend/python/sentencetransformers/requirements.txt
- backend/python/transformers-musicgen/requirements.txt
- backend/python/transformers/requirements.txt
- backend/python/vall-e-x/requirements.txt
- backend/python/vllm/requirements.txt
- core/config/backend_config.go
- core/config/backend_config_loader.go
- core/config/backend_config_test.go
- core/config/config_suite_test.go
- core/config/config_test.go
- pkg/model/process.go
also some minor enhancements I had around in my branch. I've re-enabled a test-suite that was accidentally disabled.
> dependencies(grpcio): bump to fix CI issues

- aio/cpu/text-to-text.yaml
- aio/gpu-8g/text-to-text.yaml
- aio/intel/text-to-text.yaml
- core/http/endpoints/openai/chat.go
- gallery/hermes-2-pro-mistral.yaml
- pkg/functions/grammar_json_schema.go
- pkg/functions/grammar_json_schema_test.go
- pkg/functions/options.go
- pkg/functions/parse.go
- pkg/functions/parse_test.go
Extend even more the functionalities and when mixed mode is enabled, tolerate also both strings and JSON in the result - in this case we make sure that the JSON can be correctly parsed. Before we were forcing OR strings output only, OR JSON. In this change we make sure that we can also return strings mixed with JSON among the same results, allowing to be more "relaxed" and enforce only in that case that the JSON doesn't break and is always parseable.
This also updates the examples and the gallery model to configure the grammar.
The changeset also breaks current function/grammar configuration as it reserves now a stanza in the YAML config, and renames some fields (notably now there is a `mixed_mode` option).
For example:
```yaml
function:
grammar:
mixed_mode: true
```
**Notes for …
> feat(functions): relax mixedgrammars

- Dockerfile
cleanups the docker file GO_TAGS definition that was moved during refactors
> ci: correctly build p2p in GO_TAGS

- .github/checksum_checker.sh
- gallery/index.yaml
This PR simplifies the checker so it does not need to download the whole file ( it is kept as a failback if getting back from HF fails ).
Thanks @Nold360 for the pointers
> ci(checksum_checker): do get sha from hf API when available

- Makefile
- backend/cpp/llama/grpc-server.cpp
small API change from upstream in https://github.com/ggerganov/llama.cpp/pull/7462
> deps(llama.cpp): update and adapt API changes

- .github/workflows/release.yaml
Looks like `stablediffusion` binary in the release is not built right, adding `GO_TAG` that fixes this
> fix: stablediffusion binary

- README.md
Add https://github.com/valentinfrlch/ha-gpt4vision to Home Assistant Integration section.
gpt4vision uses LocalAI's API to send images along with a prompt and return the models output so it can be used in Home Assistant Automations.
> Add Home Assistant Integration

- gallery/index.yaml
> models(gallery): add aya-35b

- core/startup/config_file_watcher.go
Watchers shouldn't be fatal - we handle the error already, so we should just return here. See also: https://github.com/mudler/LocalAI/discussions/2407
> fix(watcher): do not emit fatal errors

- gallery/index.yaml
This PR adds https://huggingface.co/flammenai/Mahou-1.2-llama3-8B-GGUF
> models(gallery): add Mahou

- backend/python/autogptq/requirements-hipblas.txt
- backend/python/bark/requirements-hipblas.txt
- backend/python/common/template/requirements-hipblas.txt
- backend/python/coqui/requirements-hipblas.txt
- backend/python/diffusers/requirements-hipblas.txt
- backend/python/openvoice/requirements-hipblas.txt
- backend/python/parler-tts/requirements-hipblas.txt
- backend/python/petals/requirements-hipblas.txt
- backend/python/rerankers/requirements-hipblas.txt
- backend/python/sentencetransformers/requirements-hipblas.txt
- backend/python/transformers-musicgen/requirements-hipblas.txt
- backend/python/transformers/requirements-hipblas.txt
- backend/python/vall-e-x/requirements-hipblas.txt
- backend/python/vllm/requirements-hipblas.txt
Attempting to fix issues with pytorch and hipblas builds in #1592.  PyTorch was being installed from pypi, which is only correct for cuda11 builds, for rocm/hipblas builds we need to install pytorch from a different index similar to intel
> fix: install pytorch from proper index for hipblas builds

- .github/workflows/image_build.yml
This allow the PRs to push test images to ttl.sh, so we can use the CI to build test images when opening up PRs, helpful for testing
> ci: push test images when building PRs

- Dockerfile
This surely saves a bunch of space - we don't need python in the core images.
> feat(images): do not install python deps in the core image

- core/http/endpoints/openai/chat.go
- pkg/functions/parse.go
- pkg/functions/parse_test.go
This PR allows (when grammars is in mix mode or disabled) to extract multiple functions calls from the LLM output, and also to extract the text content in case, for instance, the model expects some reasoning text and wants to stream out as part of the OpenAI request content.
for matching regex no change is required, for instance:
```yaml
function:
json_regex_match: 
- (?s)<tool_call>(.*?)</tool_call>
```
will also now match:
```
Some text before the JSON
<tool_call>{"function": "add", "arguments": {"x": 5, "y": 3}}</tool_call>
<tool_call>{"function": "subtract", "arguments": {"x": 10, "y": 7}}</tool_call>
Some text after the JSON
```
And parse correctly two tool calls.
A list of regexes can be specified which will extract a text out from the reply to serve it back as part …
> feat(functions): allow parallel calls with mixed/no grammars

- gallery/chatml.yaml
- gallery/index.yaml
This PR adds https://huggingface.co/fblgit/UNA-ThePitbull-21.4B-v2
> models(gallery): add una-thepitbull

- core/http/endpoints/openai/chat.go
- pkg/functions/grammar_json_schema.go
- pkg/functions/options.go
- pkg/functions/parse.go
Allow now any non-character, both as suffix and prefix when mixed grammars are enabled
Testing with
```yaml
context_size: 8192
f16: true
mmap: true
name: hermes-2-theta-llama-3-8b
parameters:
model: huggingface://NousResearch/Hermes-2-Theta-Llama-3-8B-GGUF/Hermes-2-Pro-Llama-3-Instruct-Merged-DPO-Q4_K_M.gguf
stopwords:
- <|im_end|>
function:
disable_no_action: true
return_name_in_function_response: true
grammar:
#disable: true
mixed_mode: true
parallel_calls: true
expect_strings_after_json: true
json_regex_match: 
- "(?s)<tool_call>(.*?)</tool_call>"
- "(?s)<tool_call>(.*)"
capture_llm_results: 
- (?s)<scratchpad>(.*?)</scratchpad>
replace_llm_results:
- key: (?s)<scratchpad>(.*?)</scratchpad>
value: ""
template:
chat: |
{{.Input -}}
<|im_start|>assistant
chat_message: | …
```
> feat(functions): better free string matching, allow to expect strings after JSON

- Makefile
- docs/content/docs/advanced/advanced-usage.md
This PR re-adds the llama-cpp target so it can built natively. This is useful for instance when compiling LocalAI manually from sources for a native host.
> build(Makefile): add back single target to build native llama-cpp

- gallery/index.yaml
This PR adds llama3 11b https://huggingface.co/Replete-AI/Llama-3-11.5B-V2
> models(gallery): add llama3-11b

- Makefile
- backend/backend.proto
- backend/python/coqui/backend.py
- core/backend/tts.go
- core/cli/tts.go
- core/config/backend_config.go
- core/http/endpoints/elevenlabs/tts.go
- core/http/endpoints/localai/tts.go
- core/schema/localai.go
- docs/content/docs/features/text-to-audio.md
Continuation of PR #2086
Improvements to the Coqui TTS API/backend.
- ~[ ] TTS Info endpoint: List available models, speakers and languages~ (will start new PR for this one)
The original PR got closed when I force deleted by error the branch while merging
> TTS  API improvements

- gallery/gemma.yaml
- gallery/index.yaml
> models(gallery): add gemma-2b

- backend/python/transformers/backend.py
- Temperature = 0 correctly handled as greedy search
- Handles custom words as stop words
- Implement KV cache
- Phi 3 no more requires `trust_remote_code: true` flag
Most of these features are thanks to transformers >4.41 
> feat(transformers): various enhancements to the transformers backend

- core/cli/run.go
- core/config/application_config.go
- pkg/xsysinfo/cpu.go
This sets by default the number of threads to the number of Physical cores. Logical cores doesn't work well as it creates overhead that impact in the generation speed noticeably.
> feat(default): use number of physical cores as default

- .github/workflows/release.yaml
- Makefile
- pkg/model/initializers.go
This PR tries to build into the single binary also hipblas support
Partly related to #1592
> feat(amdgpu): try to build in single binary

- gallery/index.yaml
This PR  adds bartowski/dolphin-2.9.2-Phi-3-Medium-GGUF
> models(gallery): add dolphin-2.9.2-Phi-3-Medium

- .github/workflows/release.yaml
- Makefile
- pkg/model/initializers.go
This PR, similarly to #2485, bundles the sycl binaries as well so the single binary can now select the specific variant if the GPU is amd, intel, or Nvidia
> build(intel): bundle intel variants in single-binary

- .github/workflows/release.yaml
Now that we build both intel and hipblas the size of the container image grew quite a lot that doesn't fit anymore free hosted runners
> ci: run release build on self-hosted runners

- .github/workflows/release.yaml
`build-linux` CI step is now repaired, but quite slow.
---
experiment 1: set -j4 to see if things go faster, while we wait for a proper fix from mudler
> experiment: `-j4` for `build-linux:`

- core/http/endpoints/openai/chat.go
Blocking the loop here leaves the channel unconsumed, finally ending by blocking the backend as keeping sending on a channel that is not consumed by a worker anymore.
We just need to cancel the context here, which is then released by the backend which finally closes the channel.
This buggy behavior can be reproduced by:
- Start a request with `stream: true`
- CTRL+C the request while the result is being streamed to the client
- The server now will be stuck as the channel isn't consumed anymore, as it is not buffered, go will make the producer sit there waiting for a consumer
- Try again to issue another request - now the backend is blocked for good.
> fix(stream): do not break channel consumption

- docs/static/install.sh
This PR adds an oneliner install bash script. It partially is inspired from the ollama one for the setup of cuda and systemd - it misses still openrc support (it is detected). It supports installing and starting docker images too based on the environment and, installs where required the nvidia cuda toolkit, the drivers, and docker.
Settings:
```
DOCKER_INSTALL = true # Defaults to auto-detect if docker is installed
USE_AIO = true # Defaults to false
CORE_IMAGES = true # Defaults to false
PORT = 8080 # Defaults to 8080
API_KEY = xxxx # Defaults to none
THREADS = 20 # Defaults to auto-detected number of logical cores
VERSION = v2.16.0 # Defaults to latest version
MODELS_PATH = /foo/bar # Defaults to /models for containers, or /usr/share/localai/models otherwise
```
Usage: …
> feat(install): add install.sh for quick installs

- core/cli/transcript.go
- core/config/application_config.go
- core/config/backend_config.go
- core/config/backend_config_loader.go
- core/config/config_test.go
- core/config/guesser.go
- core/http/endpoints/openai/request.go
- core/startup/startup.go
- go.mod
- go.sum
This PR adds a simple logic to start identifying GGUF files and applying well known templates if not defined by config.
The changes hooks directly when generating default configurations for the model, and scan the files when information is not provided.
It also adds llama3 to start with. Other templates will likely follow.
> feat(llama.cpp): guess model defaults from file

- core/http/routes/ui.go
- core/http/static/talk.js
- core/http/views/partials/navbar.html
- core/http/views/talk.html
Adds a simple mask form to talk to an LLM. At the moment is very barebones, but allows to exercise TTS, Whisper and LLMs easily from the web interface. It does not detect speech or silence - just offers a push to talk button. Of course, if anyone want to experiment on making it more smarter is welcome - but for sake of keeping things simple, this looks like a good starting point.
Until the testing image is up, you can test with:
```
docker run -ti -v $PWD/models:/build/models -p 8090:8080 ttl.sh/localai-ci-pr-2520:sha-4005761-ffmpeg-core --debug
```
and install the models with the gallery
> feat(ui): add page to talk with voice, transcription, and tts

- .github/workflows/release.yaml
- Makefile
- pkg/assets/extract.go
This PR tries to add a job to build on aarch64 by cross-compiling.
In the current state, it only builds the llama.cpp backend (non-cuda).
I've  tried compiling other backends and cuda but didn't had success yet.I'm leaving the CI configured for installing CUDA on the host, however that needs another iteration to figure out what's still wrong with it.
As a note, I've also added in the startup logics to allow to ship libraries as part of the backend assets and load those during start, under the `lib` directory, for instance, sibiling of the current directory we use to extract the grpc backends. 
In my tests with the binary it needed other libraries as well (which aren't part of this PR) in order to start llama.cpp correctly. This is not addressed in this PR, but I will …
> feat(arm64): enable single-binary builds

- core/cli/cli.go
- core/cli/util.go
- main.go
- pkg/templates/cache.go
This PR adds a simple util command to help into getting more informations from GGUF files. This is mostly helpful while adding new families for the built-in template system.
```
local-ai util gguf-info <gguf_file>
```
> feat(util): add util command to print GGUF informations

- Dockerfile
* Update Go inside Dockerfile to 1.22.4 (security fixes to the go command and crypto/x509, html/template, net/http, net/http/cookiejar, net/mail, net/netip and archive/zip)
* Update protoc-gen-go to 1.34.1 and protoc-gen-go-grpc to 1.4.0 (fixes CVE-2024-24786)
* Update CUDA to 11.8
* Update grpc to 1.64.2 (fixes CVE-2023-44487)
* Update protoc to 27.1
> chore(deps): Update Dockerfile

- .github/ci/modelslist.go
- .gitignore
- Makefile
- core/cli/models.go
- docs/content/docs/gallery.md
- pkg/gallery/gallery.go
- pkg/gallery/request.go
This PR introduces two changes:
1. Lets the CI build a static html page which contains the models available. It is just a quick way to show off available models, with no frills directly hooked to `model.localai.io` and `models.localai.io`. It calls for enhancements, but for a first stab I was mostly interested in the conversion/hooking the dns mostly. Planning to follow-up for graphical changes.
2. It adapts the CLI such now `local-ai models install <model_name>` allows to install models directly from the configured gallery.
Changes to the docs needs some changes to happen in netlify, so this can be tested only on master
> feat(gallery):  show available models in website, allow `local-ai models install` to install from galleries

- core/backend/llm.go
- core/cli/models.go
- core/services/gallery.go
- core/startup/startup.go
- pkg/gallery/gallery.go
- pkg/startup/model_preload.go
- pkg/startup/model_preload_test.go
This PR uniforms installation from gallery, now `local-ai run <gallery-name>` will automatically install and make sure the model from the gallery is available on start, so it is extended to cover also gallery installations.
Before this, `local-ai run` was be able to install only YAML config files.
> feat(gallery): uniform download from CLI

- Makefile
This PR enable `STATIC=true` when building the golang binary. As now it doesn't depend on CGO libs directly (only the gRPC backend) the main API binary can be compiled statically now.
> fix(Makefile): enable STATIC on dist

- core/cli/run.go
- core/config/application_config.go
- core/startup/startup.go
- pkg/assets/extract.go
- pkg/library/dynaload.go
This PR allows to load dinamically libs from a specific path (defaults to `/usr/share/local-ai/libs`) for single-binary installs. For instance, this can be used to drop Nvidia or AMD libraries which are too big to being bundled in the single-binary file.
> feat(libpath): refactor and expose functions for external library paths

- gallery/index.yaml
This PR fixes adds https://huggingface.co/bartowski/gemma-1.1-7b-it-GGUF
> models(gallery): add gemma-1.1-7b-it

- backend/python/diffusers/backend.py
- backend/python/diffusers/requirements.txt
- gallery/index.yaml
- gallery/stablediffusion3.yaml
This PR adds SD-3 support.
Tested with:
```yaml
backend: diffusers
diffusers:
cuda: true
enable_parameters: negative_prompt,num_inference_steps
pipeline_type: StableDiffusion3Pipeline
f16: false
name: sd3
parameters:
model: v2ray/stable-diffusion-3-medium-diffusers
step: 25
```
curl call:
```
http://localhost:9091/v1/images/generations -H "Content-Type: application/json" -d '{
"prompt": "A cute baby sea otter", "model": "sd3"
}'
```
Result:
> feat(sd-3): add stablediffusion 3 support

- .github/workflows/release.yaml
- Makefile
- core/cli/models.go
- pkg/library/dynaload.go
- pkg/model/initializers.go
- pkg/model/process.go
This PR fixes single binary execution on linux systems by adding the `ld.so` file to the libraries.
**Context** As we bundle libs when running in single-binary mode and we use `LD_LIBRARY_PATH` to point to the .so files, we need also to run them with the associated `ld.so` file to avoid hitting stack smash.
**Note** This affects ONLY Linux builds (both arm64 and amd64)
> fix(single-binary): bundle ld.so

- .github/workflows/image-pr.yml
- .github/workflows/image.yml
- .github/workflows/image_build.yml
- .github/workflows/release.yaml
- Dockerfile
- Makefile
* Upgrade to CUDA 12.5
* Add Docker tag suffix `-cuda11`
> feat: Upgrade to CUDA 12.5

- gallery/index.yaml
This PR adds https://huggingface.co/Lewdiculous/LLaMa-3-CursedStock-v1.8-8B-GGUF-IQ-Imatrix-Request
> models(gallery): add llama-3-cursedstock-v1.8-8b-iq-imatrix

- gallery/index.yaml
This PR adds https://huggingface.co/LWDCLS/llama3-8B-DarkIdol-1.1-GGUF-IQ-Imatrix-Request
> models(gallery): add llama3-8b-darkidol-1.1-iq-imatrix

- gallery/hermes-2-pro-mistral.yaml
- gallery/index.yaml
This PR adds https://huggingface.co/NousResearch/Hermes-2-Theta-Llama-3-70B-GGUF to the gallery, and sets model default to disable mixed_grammar, however, it's left as a comment if the user wants to override model settings
> models(gallery): add hermes-2-theta-llama-3-70b

- docs/static/install.sh
This PR fixes `install.sh` as such now the systemd service is correctly installed and started
> fix(install.sh): correctly handle systemd service installation

- core/cli/worker/worker_llamacpp.go
- core/cli/worker/worker_p2p.go
- pkg/library/dynaload.go
This PR fixes #2609 
We didn't covered starting workers with the shared libs shipped within the binary. Now the main should start the bins as the other gRPC backends
> fix(worker): use dynaload for single binaries

- docs/content/docs/advanced/advanced-usage.md
- docs/content/docs/advanced/installer.md
- docs/content/docs/advanced/run-other-models.md
- docs/content/docs/getting-started/container-images.md
- docs/content/docs/getting-started/customize-model.md
- docs/content/docs/getting-started/manual.md
- docs/content/docs/getting-started/quickstart.md
- docs/content/docs/getting-started/try-it-out.md
- docs/content/docs/overview.md
- docs/content/docs/reference/binaries.md
- examples/kubernetes/deployment-nvidia.yaml
This PR tries to put on par docs, and break down the quickstart into sections
> docs: update to include installer and update advanced YAML options

- .github/workflows/image-pr.yml
- .github/workflows/image.yml
As now we have a new sponsor (Prem) and access to more resources :partying_face: , I've just finished setting up the cluster and x2 the current number of nodes! I think we can handle more than what's currently set - however - I'll be on the safe side now and see how the loads spreads across the cluster and see if we can bump this further more later on.
> ci: bump parallel jobs

- .github/workflows/image-pr.yml
- .github/workflows/image.yml
- Dockerfile
- Makefile
This PR adds support for vulkan in llama.cpp  ( see also #1592 ) and adds vulkan images
> feat(vulkan): add vulkan support to the llama.cpp backend

- core/cli/transcript.go
This PR removes the duplicate alias from the CLI command (was introduced by mistake in #2649 )
> fix(cli): remove duplicate alias

- core/http/routes/ui.go
- core/http/views/chat.html
- core/http/views/talk.html
**TLDR**
This PR is part of #2156 . It is a small change to allow to chat with any model present in the model folder (not only these with a YAML file).
As now we have capabilities to identify automatically gguf files ( https://github.com/mudler/LocalAI/pull/2536 ), we can now show in the select box in the chat all the models - even these which are single files in the `models` folder without an associated YAML file. 
The system will automatically identify the gguf model and apply a default template if required, as such there is no need to create a YAML file anymore to let the model pop-up in the chat selection.
> feat(ui): allow to select between all the available models in the chat

- Makefile
- backend/cpp/llama/Makefile
This PR tries to speedup llama.cpp builds by building only the needed targets (and not all of them).
> feat(build): only build llama.cpp relevant targets

- .github/workflows/test.yml
- Makefile
- backend/cpp/llama/Makefile
- docs/content/docs/advanced/fine-tuning.md
- docs/content/docs/faq.md
- docs/content/docs/getting-started/build.md
- entrypoint.sh
- examples/e2e-fine-tuning/README.md
- examples/e2e-fine-tuning/notebook.ipynb
This PR updates llama.cpp and adapts the build variables (see https://github.com/ggerganov/llama.cpp/pull/8006)
Supersedes https://github.com/mudler/LocalAI/pull/2652
> deps(llama.cpp): bump to latest, update build variables

- core/http/views/talk.html
This fixes a breakage in rendering the template. Now the models passed by to the renderer have the ID field rather then Name
> fix(talk): identify the model by ID instead of name

- Dockerfile
- pkg/model/initializers.go
we were not checking if the binary exists before picking these up from
the asset dir.
> fix(initializer): do select backends that exist

- backend/cpp/llama/Makefile
Builds not using the requested number of threads when building llama.cpp
> fix: make sure the GNUMake jobserver is passed to cmake for the llama.cpp build

- gallery/index.yaml
> models(gallery): add arcee-agent

- Makefile
- Update include path to add ggml
- Update linker options to add gml and libgomp
https://github.com/ggerganov/whisper.cpp/pull/2256
> deps(whisper.cpp): update to latest commit

- backend/python/common/libbackend.sh
Instead of spawning new processes when starting a new python backend, use exec to replace the shell process with the python process.
When using the transformers and derived custom backends I noticed the following behaviour when running localai with the flag `--single-active-backend`.
1. When calling a model, the specified transformers based backend was started.
2. When calling a model for a different model, the run.sh shell process was killed and the new backend started
3. The transformers python process stayed active (and did not receive a kill signal)
With the change the run.sh process is replaced with the python backend process, leading to that process being killed correctly and freeing its resources.
**[Signed …
> Using exec when starting a backend instead of spawning a new process

- Makefile
I'm trying to create a homebrew package for mac, but unfortunately gpt4all does not build. My only solution was to remove it from the list of all backends, but I don't want the brew package to have to be updated with newer backends in the future, but instead that it always filters the gpt4all until the issue is resolved.
https://github.com/Homebrew/homebrew-core/pull/172734
> Allows to remove a backend from the list

- .github/workflows/release.yaml
This PR fixes:
```
Run git clone --recurse-submodules -b v1.64.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc && \
Cloning into 'grpc'...
Note: switching to 'b8a04acbbf18fd1c805e5d53d62ed9fa4721a4d1'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:
git switch -c <new-branch-name>
Or undo this operation with:
git switch -
Turn off this advice by setting config variable advice.detachedHead to false
Submodule 'third_party/abseil-cpp' …
```
> ci(arm64): fix gRPC build by adding googletest to CMakefile

- core/p2p/p2p.go
- docs/content/docs/features/distributed_inferencing.md
This allows LocalAI to be less noisy avoiding to connect outside. Needed if e.g. there is no plan into using p2p across separate networks.
There is room for optimization here - options needs to be passed by and I don't like hooking into env vars directly, but I want to have quick route to it now, we can optimize later.
> feat(p2p): allow to disable DHT and use only LAN

- .github/workflows/release.yaml
- Makefile
This PR fixes the recurring build issues on ARM that have been happening lately by skipping Abseil's internal tests while building gRPC. We do not modify the library in any way, and many projects use this - I cannot see any reason why these tests need to be ran on every single invocation of our CI pipeline. 
Additionally, gRPC is tested, and exercises the relevant parts of Abseil that way!
The method I am using is documented here: https://github.com/abseil/abseil-cpp/blob/master/CMake/README.md
> fix: arm builds via disabling abseil tests

- core/application.go
- core/http/ctx/fiber.go
- core/http/endpoints/elevenlabs/tts.go
- core/http/endpoints/jina/rerank.go
- core/http/endpoints/localai/tts.go
- core/http/endpoints/localai/welcome.go
- core/http/endpoints/openai/assistant.go
- core/http/endpoints/openai/chat.go
- core/http/endpoints/openai/completion.go
- core/http/endpoints/openai/edit.go
- core/http/endpoints/openai/embeddings.go
- core/http/endpoints/openai/image.go
- core/http/endpoints/openai/list.go
- core/http/endpoints/openai/request.go
- core/http/endpoints/openai/transcription.go
- core/http/routes/openai.go
- core/http/routes/ui.go
- core/http/views/chat.html
- core/http/views/talk.html
- core/services/list_models.go
- core/startup/startup.go
- pkg/model/loader.go
This changeset does two things:
- Removes the dependency of listing models from the OpenAI schema.
- Tries to reduce confusion between ListModels() in model loader and in the service - now there is only one ListModels which is in services and does not depend anymore on the OpenAI schema
- The OpenAI-schema functions were moved nearby the OpenAI specific endpoints that needs the schema
- Drops the ListModel Service structure as there was no real need for it.
- Skip directories from listing models
- Skip `README` and `MODEL_CARD` files
- There were some parts of the code that erroneously were looking at ListModels from the model loader, that had the unpleasant effect to not list all the detected models. The function has been also renamed to avoid confusion in the future.
> feat(model-list): be consistent, skip known files from listing

- .github/checksum_checker.sh
This PR fixes 
```
Run export HF_HOME=/hf_cache
.github/checksum_checker.sh: line 20: syntax error in conditional expression: unexpected token `;'
.github/checksum_checker.sh: line 20: syntax error near `;'
.github/checksum_checker.sh: line 20: `    if [[ result -eq 5]]; then'
```
Introduced in: https://github.com/mudler/LocalAI/pull/2566
> fix(ci): small fixups to checksum_checker.sh

- docs/content/docs/advanced/installer.md
- docs/static/install.sh
This allows to support federation by exposing:
- FEDERATED: true/false to share the instance
- FEDERATED_SERVER: true/false to start the federated load balancer (it forwards requests to the federation)
It also updates documentation
> feat(install.sh): support federated install

- gallery/index.yaml
This PR adds llama-3-patronus-lynx-70b-instruct
> models(gallery): add llama-3-patronus-lynx-70b-instruct

- Makefile
- backend/cpp/grpc/Makefile
- backend/cpp/llama/Makefile
adds --single-branch to `git submodule update` commands for speed - no need to pull all the "dead" branches down
> build: speedup `git submodule update` with `--single-branch`

- backend/python/openvoice/requirements-intel.txt
Reverts mudler/LocalAI#2796
```
#54 107.6  + wrapt==1.16.0
#54 107.6   × No solution found when resolving dependencies:
#54 107.6   ╰─▶ Because only melotts==0.1.2 is available and melotts==0.1.2 depends
#54 107.6       on inflect==7.0.0, we can conclude that all versions of melotts depend
#54 107.6       on inflect==7.0.0.
#54 107.6       And because you require inflect==7.3.1 and melotts, we can conclude that
#54 107.6       the requirements are unsatisfiable.
#54 107.6 make: *** [Makefile:5: install] Error 1
```
> Revert "chore(deps): Bump inflect from 7.0.0 to 7.3.1 in /backend/python/openvoice"

- backend/python/openvoice/requirements-intel.txt
> Revert "chore(deps): Bump numpy from 1.26.4 to 2.0.0 in /backend/python/openvoice"

- Makefile
- core/http/endpoints/localai/p2p.go
- core/http/routes/localai.go
- core/schema/localai.go
This PR adds swagger docs for p2p endpoints (and refactors the endpoint moving them into `core/endpoints`.
> docs(swagger): cover p2p endpoints

- Makefile
- backend/cpp/llama/grpc-server.cpp
- core/backend/options.go
- core/config/backend_config.go
- docs/content/docs/advanced/advanced-usage.md
This PR makes the llama.cpp-grpc backend in pair with the go-llama, as such also now the embeddings endpoint is supported.
Note: this doesn't enable embeddings by default yet, as it breaks our test suites - models needs to have `embeddings: true` enabled in the YAML config file.
```bash
$ local-ai run qwen2-7b-instruct
$ curl http://localhost:8080/embeddings -X POST -H "Content-Type: application/json" -d '{
"input": "Your text string goes here",
"model": "qwen2-7b-instruct"
}' | jq "."
```
> feat(llama.cpp): support embeddings endpoints

- backend/python/autogptq/requirements.txt
- backend/python/bark/requirements.txt
- backend/python/common/template/requirements.txt
- backend/python/coqui/requirements.txt
- backend/python/diffusers/requirements.txt
- backend/python/exllama/requirements.txt
- backend/python/exllama2/requirements.txt
- backend/python/mamba/requirements.txt
- backend/python/openvoice/requirements.txt
- backend/python/parler-tts/requirements.txt
- backend/python/rerankers/requirements.txt
- backend/python/sentencetransformers/requirements.txt
- backend/python/transformers-musicgen/requirements.txt
- backend/python/transformers/requirements.txt
- backend/python/vall-e-x/requirements.txt
- backend/python/vllm/requirements.txt
Update grpcio python package to 1.65.0 to match the version used everywhere else
> fix: update grpcio version to match version used in builds

- core/cli/federated.go
- core/cli/run.go
- core/p2p/p2p.go
- core/p2p/p2p_disabled.go
Fixes:
```
panic: invalid argument to IntN
goroutine 401 [running]:
math/rand/v2.(*Rand).IntN(...)
/home/mudler/_git/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/math/rand/v2/rand.go:190
math/rand/v2.IntN(...)
/home/mudler/_git/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/math/rand/v2/rand.go:307
github.com/mudler/LocalAI/core/cli.Proxy.func2()
/home/mudler/_git/LocalAI/core/cli/federated.go:104 +0x76e
created by github.com/mudler/LocalAI/core/cli.Proxy in goroutine 1
/home/mudler/_git/LocalAI/core/cli/federated.go:91 +0x3c5
```
When no nodes are found and something is trying to hit the federated endpoint (and no tunnels are ready yet).
> fix: short-circuit when nodes aren't detected

- core/http/endpoints/openai/chat.go
- core/schema/openai.go
- docs/content/docs/advanced/advanced-usage.md
- pkg/functions/functions.go
- pkg/functions/functions_test.go
- pkg/functions/grammar_json_schema.go
- pkg/functions/grammar_json_schema_test.go
- pkg/functions/parse.go
- pkg/functions/parse_test.go
This PR makes the JSON parsing a little bit stronger against invalid output from the LLM when parsing tools, such as:
```
{"key1": "value1"} invalid {"key2": "value2"}
```
Besides, it allows also now to generate dynamically grammars, independently of the keys part of the expected JSON result, for instance now in the YAML configuration file we can specify different set of keys with `function_name_key` and `function_arguments_key` to override the default key values (`name` and `arguments`).
`return_name_in_function_response` has been deprecated and now is default. To restore the old behavior, set in the YAML config file the following:
```yaml
function:
function_name_key: "functions"
```
> feat(functions): parse broken JSON when we parse the raw results, use dynamic rules for grammar keys

- core/cli/federated.go
- core/p2p/federated.go
- core/p2p/federated_server.go
This PR adds the `--load-balanced` option to `local-ai federated`.
It features a very basic mechanism that keeps track of the requests between the nodes so to dispatch the load fairly in the cluster.
> feat(federation): add load balanced option

- gallery/index.yaml
> models(gallery): add einstein-v4-7b

- Makefile
This PR adds `p2p` support to arm64 cross-arch binary builds
> ci(Makefile): enable p2p on cross-arm64 builds

- gallery/index.yaml
> models(gallery): add tulu 8b and 70b

- .github/workflows/release.yaml
- .github/workflows/test.yml
- Dockerfile
- Makefile
This PR tries to reduce the binary size by using `upx` and `-s -w ` in the golang binaries that we build during the process
> ci(Makefile): reduce binary size by compressing

- gallery/index.yaml
This PR  adds llama3.1 70b and 8b. looks like 405b is still being uploaded in HF (but available in ollama already)
> models(gallery): add llama3.1 70b and 8b

- gallery/index.yaml
- gallery/llama3.1-instruct.yaml
This PR adds function call capabilities to llama3.1 models by following  https://github.com/meta-llama/llama-agentic-system/blob/ced0661761fc6529b23ac44ba1f19968ac5ad376/llama_agentic_system/system_prompt.py#L64
The function are returned in this syntax, for instance to call `get_weather`:
```
<function=get_current_weather>{{"location": "Boston, MA", "unit": "celsius"}}</function>
```
> chore: add function calling template for llama 3.1 models

- core/http/elements/gallery.go
- core/http/routes/ui.go
This PR makes sure that errors aren't sicky in the UI
> fix(gallery): do clear out errors once displayed

- gallery/index.yaml
This PR adds l3.1-8b-celeste-v1.5
> models(gallery): add l3.1-8b-celeste-v1.5

- core/cli/models.go
- core/cli/util.go
- core/config/backend_config.go
- core/config/backend_config_loader.go
- core/dependencies_manager/manager.go
- core/gallery/gallery.go
- core/gallery/models.go
- core/http/app_test.go
- embedded/embedded.go
- pkg/downloader/huggingface.go
- pkg/downloader/uri.go
- pkg/downloader/uri_test.go
- pkg/startup/model_preload.go
This PR puts some order in the downloader such as functions are re-used across several places.
This fixes an issue with having uri's inside the model YAML file, it would resolve to MD5 rather then using the filename.
It also fixes https://github.com/mudler/LocalAI/issues/3114
> fix: be consistent in downloading files, check for scanner errors

- core/http/endpoints/openai/chat.go
- core/schema/openai.go
- pkg/functions/functions.go
This PR adds support for `strict` in the fields of the tools and support for response type to `json_schema`. Behind the hood, it hooks on the grammar support and forces the engine to generate BNF formula so the LLM stays strict on the JSON output.
Note:
- specifying `strict: true` to any of the tool from the API call, will enable grammar even if disabled by config
- if format_type is `json_schema`, the schema will be parsed and BNF grammars generated automatically from the schema.
Reference: https://openai.com/index/introducing-structured-outputs-in-the-api/
> feat(openai): add `json_schema` format type and strict mode

- core/cli/federated.go
- core/cli/run.go
- core/cli/worker/worker_p2p.go
- core/config/application_config.go
- core/http/endpoints/localai/p2p.go
- core/http/routes/localai.go
- core/http/routes/ui.go
- core/p2p/federated.go
Allow to specify a network ID via CLI which allows to run multiple clusters, logically separated within the same network (by using the same shared token).
Note: This segregation is not "secure" by any means, anyone having the network token can see the services available in all the network, however, this provides a way to separate the inference endpoints.
This allows for instance to have a node which is both federated and having attached a set of llama.cpp workers. Just specify `LOCALAI_P2P_NETWORK_ID` to an uuid that is the same for across the instances. The `LOCALAI_P2P_NETWORK_ID` can be set arbitrarly by the user.
> feat(p2p): allow to run multiple clusters in the same p2p network

- Makefile
When compiling the single-binary on Apple, we enforce BUILD_TYPE=metal, however, we want still to have the fallback vanilla such as if llama.cpp fails to load metal (e.g. if Acceleration framework is missing, or MacOS version is too old) we can still run by offloading to the CPU. The default backend is still using metal as usual.
> fix(apple): disable BUILD_TYPE metal on fallback

- backend/python/diffusers/requirements-hipblas.txt
Hopefully the last piece (see https://github.com/mudler/LocalAI/issues/1592#issuecomment-2275890287 )
> fix(diffusers): use nightly rocm for hipblas builds

- .github/workflows/deploy-explorer.yaml
- Makefile
- core/cli/cli.go
- core/cli/explorer.go
- core/cli/run.go
- core/cli/worker/worker_p2p.go
- core/explorer/database.go
- core/explorer/database_test.go
- core/explorer/discovery.go
- core/explorer/explorer_suite_test.go
- core/http/endpoints/explorer/dashboard.go
- core/http/endpoints/localai/p2p.go
- core/http/explorer.go
- core/http/routes/explorer.go
- core/http/routes/ui.go
- core/http/views/explorer.html
- core/http/views/partials/navbar_explorer.html
- core/p2p/node.go
- core/p2p/p2p.go
This PR fixes https://github.com/mudler/LocalAI/issues/3113
It adds another arguments to the CLI that allows to spawn-up an http server that can monitor networks and determine how many clusters and workers there are in each one.
The instance is deployed at https://explorer.localai.io
> feat(p2p): add network explorer and community pools

- core/cli/explorer.go
- core/explorer/discovery.go
The explorer currently removes entries that fails to connect or have offline workers. However, if connection fails for other reasons entries are deleted instantly and lost from the explorer view.
This changeset give chances to network in case of connection failures.
If a Network can't be reached, it will be recorded and kept attempting - when it hits the error threshold the entry is definitely removed
> feat(explorer): relax token deletion with error threshold

- core/explorer/discovery.go
When a connection is established and we have detected some workers, we want to reset the failure counter for the entry, if it has any
> fix(explorer): reset counter when network is active

- core/cli/explorer.go
- core/explorer/database.go
- core/explorer/discovery.go
- core/http/endpoints/explorer/dashboard.go
- core/http/explorer.go
- core/http/routes/explorer.go
- core/p2p/p2p.go
- go.mod
- go.sum
This PR allows to run the discovery as a separate process, and moves the informations cumulated of the network to the database.
The problem I have is that by going over the networks over and over, closing the nodes leaks data, and as such the node might exhaust RAM. Since discovery is something that have to happen periodically, it's good to move it to its own process that is short-lived.
> feat(explorer): make possible to run sync in a separate process

- core/cli/federated.go
- core/p2p/federated.go
- core/p2p/federated_server.go
- core/p2p/p2p.go
This PR is multi-fold:
- fixes loadbalanced option for federated: offline nodes where still kept into consideration. 
- It also refactors some of the code and adds an options to the CLI that allows to specify a worker target
- allow to specify a worker target
- Sets load balanced by default
- Fixes small nuances with load balanced that made it unstable (now it's thread safe)
> feat(federated): allow to pickup a specific worker, improve loadbalancing

- core/http/views/explorer.html
TODO next: add instructions on how to use a network or create one.
> feat(explorer): visual improvements

- Makefile
- backend/cpp/llama/grpc-server.cpp
This PR supersedes https://github.com/mudler/LocalAI/pull/3251.
Upstream renamed `llama_should_add_bos_token` to `llama_add_bos_token`
> chore(deps): bump llama.cpp, rename `llama_add_bos_token`

- core/cli/run.go
- core/p2p/federated_server.go
- core/p2p/p2p.go
- core/p2p/p2p_disabled.go
This PR reduces the strain on the federated instance: there is no need to allocate the tunnels when starting the federated server
> fix(p2p): allocate tunnels only when needed

- core/http/routes/ui.go
This PR tries to be consistent in the UI and disables the gallery endpoints also in the UI if `DisableGalleryEndpoint` is set
> fix(gallery): be consistent and disable UI routes as well

- core/http/static/p2panimation.js
- core/http/views/explorer.html
- core/http/views/p2p.html
- core/http/views/partials/head.html
- embedded/webui_static.yaml
> chore(ux): add animated header with anime.js in p2p sections

- core/http/views/p2p.html
- core/http/views/partials/head.html
- core/p2p/p2p.go
This makes the click on the textbox to copy the content over to the clipboard directly
> chore(p2p): make commands easier to copy-paste

- Dockerfile
This PR fixes 
```
#52 112.4 Traceback (most recent call last):
#52 112.4   File "/root/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/z7opmFvAdzkqfYFex8UU_/llvmlite-0.34.0.tar.gz/ffi/build.py", line 105, in main_posix
#52 112.4     out = subprocess.check_output([llvm_config, '--version'])
#52 112.4   File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
#52 112.4     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#52 112.4   File "/usr/lib/python3.10/subprocess.py", line 503, in run
#52 112.4     with Popen(*popenargs, **kwargs) as process:
#52 112.4   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
#52 112.4     self._execute_child(args, executable, preexec_fn, close_fds,
#52 112.4   File …
```
> fix: add llvm to extra images

- core/p2p/federated.go
- core/p2p/federated_server.go
- core/p2p/node.go
- core/p2p/p2p.go
This PR changes the underlying p2p code of the federated server to not allocate local services anymore, but directly dials now libp2p behind the hood. This makes more simplified the process and requires less hops to dispatch the requests. This sadly can't be extended to the llama.cpp workers.
It refactors out some code in `p2p` to re-use as much code as possible rather introducing duplicates.
> feat(federation): do not allocate local services for load balancing

- core/cli/run.go
- core/cli/worker/worker_p2p.go
- core/p2p/federated_server.go
- core/p2p/p2p.go
- core/p2p/p2p_disabled.go
This avoids having two nodes running in the some host when we have federated mode enabled.
> fix(p2p): re-use p2p host when running federated mode

- Dockerfile
- backend/python/parler-tts/requirements.txt
This PR tries to fix the CI issues we are having with llvm+parler-tts.
It seems parler-tts started to fail now because llvmlite can't be installed - and apparently needs llvm 14
> fix(ci): pin to llvmlite 0.43

- core/cli/run.go
- core/cli/worker/worker_p2p.go
- core/p2p/p2p.go
This PR avoids the servicediscovery to start the node, instead it should be started before passing the node to it (service discovery should only register handlers)
> fix(p2p): avoid starting the node twice

- .devcontainer-scripts/utils.sh
fix `./.devcontainer-scripts/utils.sh` - use HOME variable, permissions and logging during the ssh copy step.
> fix: devcontainer `utils.sh` ssh copy improvements

- gallery/index.yaml
> models(gallery): add phi-3.5-vision

- pkg/model/loader.go
- pkg/model/loader_test.go
- pkg/model/model.go
This PR tries to increase coverage of the model loader. I'm having some issues when single active backend is active and I'm trying to debug it without success so far - so I'm adding tests and exercising the code step-by-step at this point.
> chore(model-loader): increase test coverage of model loader

- Makefile
- backend/cpp/llama/grpc-server.cpp
> chore(deps): update llama.cpp

- backend/python/vllm/backend.py
- backend/python/vllm/test.py
> feat(vllm): add support for embeddings

- core/http/app_test.go
- core/http/endpoints/localai/system.go
- core/http/routes/localai.go
- core/schema/localai.go
- pkg/model/initializers.go
For now, it lists the available backends, but can be expanded later on to include more system informations (such as GPU devices detected, RAM, threads configured, and so on so forth).
It is accessible at `/system`
> feat: add endpoint to list system informations

- core/backend/backend_suite_test.go
- core/backend/llm.go
- core/backend/llm_test.go
- core/config/backend_config.go
- core/http/endpoints/openai/chat.go
This changset adds `extract_regex` to the LLM config. It is a list of regexes that can match output and will be used to re extract text from the LLM output. This is particularly useful for LLMs which outputs final results into tags.
> feat: extract output with regexes from LLMs

- pkg/model/loader.go
Rather than always retry every two seconds, back off the shutdown attempt rate?
This PR fixes #3543 
Suggesting this as a PR-to-PR since it may or may not be necessary. I don't think we need to go all the way to exponential backoff for this situation.
> fix: multiplicative backoff for shutdown

- core/cli/run.go
- core/config/application_config.go
- core/http/app.go
- core/http/middleware/auth.go
- core/http/routes/elevenlabs.go
- core/http/routes/jina.go
- core/http/routes/localai.go
- core/http/routes/openai.go
- core/http/routes/ui.go
- go.mod
- go.sum
This PR supersedes #2894 - while it only tackles the Auth portion, I'll be handling metrics differently and at a later date.
As mentioned in that older PR, the new auth code was submitted to fiber and upstreamed, but until fiber v3 stabilizes, that code was backported to https://github.com/dave-gray101/v2keyauth.
> feat: auth v2 - supersedes #2894

- pkg/model/loader.go
- pkg/model/process.go
This PR tries to fix edge cases where we attempt to shutdown the model via Shutdown while the model is running and busy. It checks if the model is busy and waits before actually killing it.
> fix(shutdown): do not shutdown immediately busy backends

- backend/python/sentencetransformers/backend.py
- backend/python/sentencetransformers/requirements.txt
Allow setting trust_remote_code for SentenceTransformers backend for loading models such as nvidia/NV-Embed-v2 as described in issue: #3544
This PR fixes #3544
Added datasets and einops to requirements because nvidia/NV-Embed-v2 asked for it on loading.
> feat: allow setting trust_remote_code for sentencetransformers backend

- backend/python/transformers/requirements.txt
Reverts mudler/LocalAI#3579
https://github.com/mudler/LocalAI/issues/2406
> Revert "chore(deps): Bump setuptools from 69.5.1 to 75.1.0 in /backend/python/transformers"

- gallery/index.yaml
extremely minor fix: add a space to index.yaml for the scanner
This should prevent it from showing up on entirely unrelated PRs.
> fix: `gallery/index.yaml` comment spacing

- core/http/routes/localai.go
- pkg/model/filters.go
- pkg/model/initializers.go
- pkg/model/loader.go
- pkg/model/process.go
- Handle locking in Shutdown and CheckModelIsLoaded in a more go-idiomatic way
- Drop duplicated code and re-organize shutdown code
> chore(refactor): drop duplicated shutdown logics

- aio/cpu/vision.yaml
- aio/gpu-8g/vision.yaml
- aio/intel/vision.yaml
- tests/e2e-aio/e2e_test.go
> chore(aio): rename gpt-4-vision-preview to gpt-4o

- backend/backend.proto
- core/backend/llm.go
- core/http/endpoints/openai/chat.go
- core/http/endpoints/openai/inference.go
- core/http/endpoints/openai/request.go
- core/schema/openai.go
- pkg/utils/base64.go
- pkg/utils/base64_test.go
This prepares the API to receive videos as well for video understanding.
It works similarly to images, where the request should be in the form:
```
{
"type": "video_url",
"video_url": { "url": "url or base64 data" }
}
```
This does not add a backend for video understanding, but enables the API to pass by the data to the backends - the ones that can read video are now enabled to receive videos.
Related to #2318  #1640  #3439
> feat(api): allow to pass videos to backends

- backend/backend.proto
- core/backend/llm.go
- core/http/endpoints/openai/chat.go
- core/http/endpoints/openai/inference.go
- core/http/endpoints/openai/request.go
- core/schema/openai.go
This prepares the API to receive audios as well for audio understanding.
It works similarly to images, where the request should be in the form:
```
{
"type": "audio_url",
"audio_url": { "url": "url or base64 data" }
}
```
This does not add a backend for audio understanding, but enables the API to pass by the data to the backends - the ones that can read audio are now enabled to receive audios.
Related to #3602
> feat(api): allow to pass audios to backends

- gallery/index.yaml
> models(gallery): add llama-3.1-supernova-lite

- gallery/index.yaml
> models(gallery): add buddy2

- gallery/index.yaml
> models(gallery): add llama-3.1-8b-arliai-rpmax-v1.1

- backend/python/parler-tts/install.sh
This PR fixes  building issues with intel sycl images:
```
#62 103.4  + werkzeug==3.0.4
#62 103.4   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#62 103.4                                  Dload  Upload   Total   Spent    Left  Speed
#62 103.4 
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4015  100  4015    0     0  18525      0 --:--:-- --:--:-- --:--:-- 18587
#62 103.4   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#62 103.4                                  Dload  Upload   Total   Spent    Left  Speed
#62 103.4 
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: __ocl_svml_h8.so
#62 103.4   % Total    % Received …
```
> fix(parler-tts): fix install with sycl

- core/backend/embeddings.go
- core/backend/image.go
- core/backend/llm.go
- core/backend/options.go
- core/backend/rerank.go
- core/backend/soundgeneration.go
- core/backend/tts.go
- core/cli/run.go
- core/config/application_config.go
- core/startup/startup.go
This PR adds a flag to auto load models into memory on startup
Converted `startup.go` from CRLF to LF, which is why the entire file looks changed
> feat: auto load into memory on startup

- Dockerfile
Like with CUDA builds, we don't need all the variants when we are compiling against the accelerated variants - in this way we save space and we avoid to exceed embedFS golang size limits.
logs:
```
#55 14460.3  2362 |     grpc::Status Predict(ServerContext* context, const backend::PredictOptions* request, backend::Reply* reply) {
#55 14460.3       |                  ^
#55 14460.3 /build/backend/cpp/llama-grpc/llama.cpp/build/examples/grpc-server/backend.grpc.pb.h:444:28: note: overridden virtual function is here
#55 14460.3   444 |     virtual ::grpc::Status Predict(::grpc::ServerContext* context, const ::backend::PredictOptions* request, ::backend::Reply* response);
#55 14460.3       |                            ^
#55 14460.3 …
```
> fix(hipblas): do not push all variants to hipblas builds

- core/http/app.go
- core/http/routes/health.go
- core/http/routes/localai.go
This PR fixes #3655
Introduced in https://github.com/mudler/LocalAI/pull/3476
> fix(health): do not require auth for /healthz and /readyz

- .github/workflows/test.yml
- Makefile
- pkg/model/initializers.go
- pkg/model/loader.go
- pkg/model/loader_test.go
- pkg/model/model.go
- pkg/model/process.go
This avoids to have to handle in two parts the data relative to the same model. It makes it easier to track and use mutex with.
This also fixes races conditions while accessing to the model.
> chore(refactor): track grpcProcess in the model structure

- backend/backend.proto
- backend/cpp/llama/grpc-server.cpp
- core/backend/token_metrics.go
- core/http/endpoints/localai/get_token_metrics.go
- core/schema/localai.go
- pkg/grpc/backend.go
- pkg/grpc/client.go
- pkg/grpc/embed.go
This PR creates a GRPC method to expose some of the Token Metrics
**TODO**
Add tests
> feat: Add Get Token Metrics to GRPC server

- core/backend/embeddings.go
- core/backend/image.go
- core/backend/llm.go
- core/backend/options.go
- core/backend/rerank.go
- core/backend/soundgeneration.go
- core/backend/token_metrics.go
- core/backend/transcript.go
- core/backend/tts.go
- core/cli/soundgeneration.go
- core/http/endpoints/elevenlabs/soundgeneration.go
- core/http/endpoints/jina/rerank.go
- core/http/endpoints/localai/get_token_metrics.go
- core/startup/startup.go
- pkg/model/initializers.go
- pkg/model/loader.go
- pkg/model/loader_test.go
- pkg/model/options.go
- pkg/model/process.go
- tests/e2e-aio/e2e_test.go
This PR changes how we track models that are being loaded. Instead of refering to the model's file and path, we are going to track now the  model ID. The model ID is also the name of each model that can be specified with a `name` - in this way we keep a 1:1 mapping and we fallback into using the model file name if a model name is not provided.
This allows for instance now to have the same backing model to be loaded with different parameters, and helps also into understanding which models are loaded as it now references what is returned when we list available models or models loaded in `/system`.
This pull request includes significant changes to the model loading and backend configuration processes in the codebase. The changes primarily focus on improving the flexibility …
> feat: track internally started models by ID

- core/backend/tokenize.go
- core/http/endpoints/localai/tokenize.go
- core/http/routes/localai.go
- core/schema/tokenize.go
This PR is a step towards #1649 
> feat: tokenization endpoint

- core/backend/tokenize.go
This PR fixes 
```
CGO_LDFLAGS="" go build -ldflags "-s -w -X "github.com/mudler/LocalAI/internal.Version=v2.21.1-41-g5488fc3b" -X "github.com/mudler/LocalAI/internal.Commit=5488fc3bc14598ffb36a2d98f0b66705b45ebe0c"" -tags "p2p" -o local-ai ./              
core/backend/tokenize.go:14:14: undefined: GRPCModelOpts
core/backend/tokenize.go:19:10: undefined: modelOpts                                                                   
core/backend/tokenize.go:21:9: undefined: model.WithThreads 
```
This is a follow-up on https://github.com/mudler/LocalAI/pull/3693 as https://github.com/mudler/LocalAI/pull/3710 was depending on it
> chore: simplify model loading

- core/http/ctx/fiber.go
This PR changes model detection such as it is now considered also in the query (e.g. `?model=xx`) of the URL
Context: extracted from #3714
> chore: get model also from query

- pkg/model/initializers.go
- pkg/model/loader.go
- pkg/model/process.go
This PR fixes a current existing issue when starting new processes. If the backend fails, for instance by loading the model and the model was not explicitly configured with a `backend`, LocalAI would loop over the backends - however if it fails it won't reap the process, and calling `deleteProcess` is a no-op as the model isn't registered yet.
> fix(initializer): correctly reap dangling processes

- CONTRIBUTING.md
Updated some formatting in the doc.
> chore(docs): update CONTRIBUTING.md

- core/config/backend_config.go
- core/http/endpoints/openai/request.go
- pkg/model/initializers.go
- pkg/templates/multimodal.go
- pkg/templates/multimodal_test.go
This PR allows to customize the placeholders for the images that are sent back to the model. 
For context, some models/libraries have different way to express images, videos or audio placeholders. For example, llama.cpp backend expects images within an `[img-ID]` tag, but other backends/models (e.g. vLLM) use a different notation ( `<|image_|>`). This changeset allow to specify the notation in the template config section of the YAML file:
For example, to override defaults, now it is possible to set in the model configuration the following:
```yaml
template:
video: "<|video_{{.ID}}|> {{.Text}}"
image: "<|image_{{.ID}}|> {{.Text}}"
audio: "<|audio_{{.ID}}|> {{.Text}}"
```
This PR is related to #3670 #3602 #2318 
**[Signed …
> feat(multimodal): allow to template placeholders

- backend/python/vllm/backend.py
- backend/python/vllm/install.sh
- backend/python/vllm/requirements-cublas11.txt
- backend/python/vllm/requirements-cublas12.txt
- backend/python/vllm/requirements-hipblas.txt
- backend/python/vllm/requirements-intel.txt
Depends on https://github.com/mudler/LocalAI/pull/3728
Closes: https://github.com/mudler/LocalAI/issues/2318
Closes: https://github.com/mudler/LocalAI/issues/3670
Also covers https://github.com/mudler/LocalAI/issues/3669 as should enable also Vision with Llama3.2 models 
not tested yet on a GPU - just made sure it does not break generation by running vLLM in CPU-mode.
> feat(vllm): add support for image-to-text and video-to-text

- pkg/grpc/base/base.go
If the LLM does not implement any logic for PredictStream, we close the channel immediately to not leave the process hanging.
Supersedes https://github.com/mudler/LocalAI/pull/3732
> fix(base-grpc): close channel in base grpc server

- Dockerfile
- backend/python/coqui/test.py
This PR fixes CI issues currently when installing the vLLM backend. It seems they bumped cmake required version
> fix(vllm): bump cmake - vllm requires it

- backend/python/openvoice/test.py
- backend/python/vllm/install.sh
This pull request includes changes to the setup and installation scripts of vLLM to skip building from source when using CPU. Besides, extends the openvoice test timeout to avoid test flakiness.
Changes to test setup:
* Increased the sleep time in the `setUp` method of `backend/python/openvoice/test.py` from 10 to 30 seconds to ensure the gRPC service is fully started before tests run. (`backend/python/openvoice/test.py`)
Changes to installation script:
* Commented out the block of code in `backend/python/vllm/install.sh` that installs VLLM via source with CPU support. This change makes the installation of this large dependency optional and notes that the current speed of inference is not usable for production use-cases. (`backend/python/vllm/install.sh`)
**Notes for …
> chore(vllm): do not install from source

- Dockerfile
This pull request includes changes to the `Dockerfile` to add flexibility in how CMake is installed. The most important changes include the addition of a new argument to control whether CMake is installed from source and the modification of the installation process to respect this new argument.
* Added `ARG CMAKE_FROM_SOURCE=false` to control whether CMake is installed from source or via `apt-get`. (`Dockerfile` [[1]](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R13) [[2]](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R205)
* Modified the CMake installation process to conditionally install from source if `CMAKE_FROM_SOURCE` is set to `true`. (`Dockerfile` …
> chore(Dockerfile): default to cmake from package manager

- Makefile
- core/http/app_test.go
consistently use TEST_FLAKES and reduce flakiness of rwkv tests by being case insensitive
This pull request includes changes to the `Makefile` and `core/http/app_test.go` to improve the flexibility of test configurations and enhance test reliability. The most important changes involve parameterizing the flake attempts in the `Makefile` and normalizing string comparisons in the test file.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L473-R504): Updated various test commands to replace hardcoded flake attempt values with the `$(TEST_FLAKES)` variable to allow configurable flake attempts.
* [`core/http/app_test.go`](diffhunk://#diff-5545d0f6c0cfda8f48632c066b1630a86c820bb9fc43f4b2fd4fcfbf78972a79R15): Added the `strings` …
> chore(tests): improve rwkv tests and consume TEST_FLAKES

- gallery/index.yaml
This pull request adds new entries to the `gallery/index.yaml` file, introducing the Katanemo Arch-Function collection of large language models (LLMs). These models are designed for function calling tasks, achieving state-of-the-art performance.
New LLM entries:
* Added `arch-function-1.5b` model, including its description, tags, and file details. (`gallery/index.yaml` [gallery/index.yamlR356-R408](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR356-R408))
* Added `arch-function-7b` model, inheriting properties from `arch-function-1.5b` and specifying its own file details. (`gallery/index.yaml` [gallery/index.yamlR356-R408](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR356-R408))
* Added …
> models(gallery): add archfunctions models

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `Rombos-LLM-V2.5.1-Qwen-3b` model with its associated metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR399-R420): Added a new model entry for `Rombos-LLM-V2.5.1-Qwen-3b`, including its name, icon URL, description, parameters, and file details.
> models(gallery): add rombos-llm-v2.5.1-qwen-3b

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "Fireball-Meta-Llama-3.2-8B-Instruct-agent-003-128k-code-DPO".
Changes to model entries:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR172-R184): Added a new model entry for "Fireball-Meta-Llama-3.2-8B-Instruct-agent-003-128k-code-DPO" with detailed description, URLs, parameters, and file information.
> models(gallery): add fireball-meta-llama-3.2-8b-instruct-agent-003-128k-code-dpo

- core/http/endpoints/localai/welcome.go
- core/services/list_models.go
This PR fixes #3790 - simplifies welcome.go by using LOOSE_ONLY, repairs it in listmodelservice
quick PR, seems to work in my simple mac testing.
> fix: listmodelservice / welcome endpoint use LOOSE_ONLY

- Makefile
- backend/cpp/llama/grpc-server.cpp
This adapts also to upstream changes
Supersedes https://github.com/mudler/LocalAI/pull/3792
> chore(deps): bump llama-cpp to 96776405a17034dcfd53d3ddf5d142d34bdbb657

- .github/ci/modelslist.go
- core/http/elements/gallery.go
- core/http/endpoints/openai/assistant.go
- core/http/endpoints/openai/files.go
- core/http/middleware/auth.go
- core/http/routes/ui.go
LocalAI already makes use of bluemonday for html sanitization. This PR implements that safety step in more places. Please let me know if any have been missed.
~~The fix to .github/ci/modelslist.go needs to be tested via this PR, but the other sanitizations seem to work according to my local testing.~~ CI Step Passed 🍾
> fix: roll out bluemonday Sanitize more widely

- .github/dependabot.yml
dependabot is frequently / always stuck on `github.com/mudler/LocalAI/pkg/grpc/proto` lately.
Adding a configuration flag to ignore this package, as its generated on build anyway.
> chore: dependabot ignore generated grpc go package

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `Llama-3.1-8B-ArliAI-Formax-v1.0-iq-arm-imatrix`.
* Added a new model `Llama-3.1-8B-ArliAI-Formax-v1.0-iq-arm-imatrix` with detailed metadata including name, URL, icon, description, overrides, and associated files. (`gallery/index.yaml`)
> models(gallery): add llama-3.1-8b-arliai-formax-v1.0-iq-arm-imatrix

- gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The entry includes details about the model, its description, and the associated files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR490-R504): Added a new model entry for `eva-qwen2.5-14b-v0.1-i1`, including its description, parameters, and file details.
> models(gallery): add eva-qwen2.5-14b-v0.1-i1

- gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, `llama-3.2-chibi-3b`, is designed for efficient and accurate processing of the Japanese language. 
* Added a new model entry `llama-3.2-chibi-3b` with relevant metadata, including name, icon, URLs, description, and file details. This model is optimized for environments with constrained resources, such as mobile devices and edge computing scenarios.
> models(gallery): add llama-3.2-chibi-3b

- gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, specifically adding a new model configuration for `Doctoraifinetune-3.1-8b-i1`, which is fine-tuned for medical applications.
New model configuration:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1600-R1622): Added a new model `Doctoraifinetune-3.1-8b-i1` with details about its URLs, description, key features, dataset, and file overrides. This model is fine-tuned for the medical field, focusing on disease diagnosis, symptom analysis, and treatment recommendations.
> models(gallery): add doctoraifinetune-3.1-8b-i1

- gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file to include the Mahou model. The most important change is the addition of the Mahou model's metadata, including its name, URL, icon, description, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1639-R1654): Added metadata for the Mahou model (`mahou-1.5-llama3.1-70b-i1`), including its name, URL, icon, description, and file details.
> models(gallery): add mahou-1.5-llama3.1-70b-i1

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `phi-3.5-mini-titanfusion-0.2` model, including its details and associated files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR6098-R6118): Added a new model entry `phi-3.5-mini-titanfusion-0.2` with its name, URLs, description, overrides, and associated files.
> models(gallery): add phi-3.5-mini-titanfusion-0.2

- gallery/index.yaml
- gallery/vicuna-chat.yaml
This pull request includes updates to the `gallery/index.yaml` and `gallery/vicuna-chat.yaml` files to add a new model and improve configuration settings. The most important changes include adding the Apollo2-9B model to the gallery and introducing stopwords to the Vicuna chat configuration.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3026-R3039): Added the Apollo2-9B model with detailed metadata and file information.
* [`gallery/vicuna-chat.yaml`](diffhunk://#diff-e7421926a9034a4e3e90ad9166807818e55cd294108f2c2b2f5f515bc1e571b9R17-R20): Introduced stopwords to the configuration to improve text processing.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate- …
> models(gallery): add apollo2-9b

- gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file. The change introduces a new large language model (LLM) specialized in the cryptocurrency domain, named Theia-Llama-3.1-8B-v1. 
* Added a new entry for `Theia-Llama-3.1-8B-v1`, an open-source LLM fine-tuned from the Llama-3.1-8B base model. This model is specialized in crypto-related tasks and includes details such as description, recommended parameters, and file information.
> models(gallery): add theia-llama-3.1-8b-v1

- backend/python/vllm/backend.py
Images otherwise aren't passed by correctly and cannot be processed for multimodal
Part of  #3670 
> fix(vllm): images and videos are base64 by default

- core/backend/llm.go
When offloading template construction to the backend, we want to keep text around in case of multimodal requests.
This pull request to `core/backend/llm.go` includes changes to support multimodal content in the `ModelInference` function by handling `[]interface{}` types and converting them to strings. 
Part of https://github.com/mudler/LocalAI/issues/3670
> feat(templates): extract text from multimodal requests

- pkg/templates/multimodal.go
This PR adds sprig to the multimodal templates. This allows to use sprig functions when configuring the multimodal templates, which can be needed in case of backends that expects the ID of images to start with 1 instead of 0 (and we can customize that in the template by ++-ing the IDs with sprig functions, rather then hardcoding it).
Part of https://github.com/mudler/LocalAI/issues/3670
> feat(templates): add sprig to multimodal templates

- backend/python/openvoice/requirements.txt
Openvoice seems to depend on older versions of networkx. This pins down the dependency in the `requirements.txt`
> chore(deps): pin networkx

- Makefile
- backend/cpp/llama/grpc-server.cpp
This PR supersedes https://github.com/mudler/LocalAI/pull/3883
> chore(deps): bump llama-cpp to cda0e4b648dde8fac162b3430b14a99597d3d74f

- backend/python/vllm/backend.py
This pull request to `backend/python/vllm/backend.py` includes changes to improve the handling of multi-modal data and error management in the `load_image` method.
Improvements to multi-modal data handling:
* `async def _predict(self, request, context, streaming=False)`: Refactored the handling of `multi_modal_data` to use a dictionary that is conditionally populated with `image` and `video` data, simplifying the code and making it more readable.
Error management improvements:
* `def load_image(self, image_path: str)`: Modified the method to return `None` instead of calling `load_video` when an error occurs, ensuring that the method's behavior is more predictable and consistent.
This fixes a bug where if a model didn't support both video and image …
> fix(vllm): do not set videos if we don't have any

- gallery/index.yaml
- gallery/phi-3-vision.yaml
This pull request adds new configurations and descriptions for the Phi-3 model family in the gallery. The most important changes include adding new entries for the Phi-3.5-vision model and creating a configuration file for the phi3-vision model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR6228-R6240): Added new entries for `phi-3-vision:vllm` and `phi-3.5-vision:vllm`, including detailed descriptions and URLs.
* [`gallery/phi-3-vision.yaml`](diffhunk://#diff-cdefdc30ccecd507e98155b4cd0a1cb2b35cae9a12367d74b76e0d640cf3239aR1-R21): Created a new configuration file for the `phi3-vision` model, specifying parameters such as `backend`, `model`, and templates for chat and completion messages. …
> models(gallery): add phi-3 vision

- core/config/backend_config.go
- core/http/endpoints/openai/request.go
- pkg/templates/multimodal.go
- pkg/templates/multimodal_test.go
This pull request includes significant changes to the way multimodal content (images, audio, and video) is handled and templated in the backend configuration and request processing. The most important changes include consolidating individual media fields into a single `Multimodal` field, updating the request configuration to handle multiple media types more efficiently, and enhancing the templating logic to support multimodal content.
As opposed to https://github.com/mudler/LocalAI/pull/3728 - this PR focuses on replacing the following YAML configuration:
```yaml
template:
video: "<|video_{{.ID}}|> {{.Text}}"
image: "<|image_{{.ID}}|> {{.Text}}"
audio: "<|audio_{{.ID}}|> {{.Text}}"
```
With a simple:
```yaml
template:
multimodal:  "{{ range .Audio …
```
> feat(templates): use a single template for multimodals messages

- go.mod
- go.sum
update go-piper to the latest to pick up https://github.com/mudler/go-piper/pull/8
> chore: update go-piper to latest

- core/cli/run.go
- core/config/application_config.go
- core/http/app.go
- core/http/routes/localai.go
Seem the "/metrics" endpoint that is source of confusion as people tends to believe we collect telemetry data just because we import "opentelemetry", however it is still a good idea to allow to disable even local metrics if not really required.
See also: https://github.com/mudler/LocalAI/issues/3942
> feat: allow to disable '/metrics' endpoints for local stats

- backend/python/vllm/backend.py
- core/backend/options.go
- core/config/backend_config.go
This pull request introduces a new `LoadFormat` parameter across various parts of the codebase to enhance model loading flexibility. The changes include updates to the backend configuration, the gRPC model options, and the model loading function.
It allows to specify a vLLM load format type ( for example, to specify bnb: https://docs.vllm.ai/en/v0.6.0/quantization/bnb.html )
> feat(vllm): expose 'load_format'

- backend/python/parler-tts/install.sh
- backend/python/parler-tts/requirements-after.txt
This PR fixes #3941 
Seems https://github.com/descriptinc/audiotools/pull/111 was merged, so this pins the deps to latest and drops the hacky workaround
> fix(parler-tts): use latest audiotools

- backend/python/parler-tts/Makefile
- backend/python/parler-tts/install.sh
- backend/python/parler-tts/protogen.sh
- backend/python/parler-tts/requirements-after.txt
- backend/python/parler-tts/requirements.txt
Seems we require a specific version to build the backend files. This changes pins grpcio in the venv and uses protoc from the venv instead from the host.
> fix(parler-tts): pin grpcio-tools

- gallery/index.yaml
This PR fixes the gallery entry for parler-tts.
> fix(gallery): overrides for parler-tts in the gallery

- backend/python/common/template/Makefile
- backend/python/common/template/protogen.sh
- backend/python/common/template/requirements.txt
Backends can as well depends on grpcio and require different versions from the ones that are installed in the system.
This extends the approach in #3960 to be the examples of creating backends in python.
> chore(python): update backend sample to consume grpcio from venv

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "llama-3.2-sun-2.5b-chat." The most important changes include the addition of the model's metadata, description, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR213-R244): Added a new model entry for "llama-3.2-sun-2.5b-chat" with metadata including name, icon, URLs, description, key features, use case, and file details.
> models(gallery): add llama-3.2-sun-2.5b-chat

- gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new model called "darkest-muse-v1". The change provides detailed information about the model, including its description, sources, and specific parameters.
* **Model Information**:
- Added a new entry for the model "darkest-muse-v1" with a unique icon and URLs for accessing the model on Hugging Face. (`gallery/index.yaml` [gallery/index.yamlR3185-R3207](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3185-R3207))
* **Description**:
- Included a comprehensive description of the model, highlighting its creative writing capabilities, the balance between its source models, and its unique style. (`gallery/index.yaml` …
> models(gallery): add darkest-muse-v1

- gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The entry includes details about the model, such as its name, description, URLs, and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR663-R688): Added a new model named "thebeagle-v2beta-32b-mgs" with detailed description, URLs, and file information.
> models(gallery): add thebeagle-v2beta-32b-mgs

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `llama-3.1-hawkish-8b` model, which has been finetuned on financial topics and shows significant improvements in benchmarks.
* Added a new model entry for `llama-3.1-hawkish-8b` with the following details:
* **Icon**: URL to the model's icon image.
* **Name**: "llama-3.1-hawkish-8b".
* **URLs**: Links to the model on Hugging Face.
* **Description**: Detailed description of the model's finetuning process and performance improvements, particularly in Math and Economics.
* **Overrides**: Specific parameters for the model.
* **Files**: Information about the model file, including `filename`, `sha256`, and `uri`. …
> models(gallery): add llama-3.1-hawkish-8b

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new writing model named "Quill-v1" to the gallery. The most important changes are listed below:
* Added a new model entry for "Quill-v1" with relevant metadata, including name, icon, URLs, description, and file details. (`gallery/index.yaml`)
> models(gallery): add quill-v1

- gallery/index.yaml
This pull request adds a new model to the `gallery/index.yaml` file. The most important changes include the addition of the `magnum-v4-9b` model with associated metadata and files.
* Added new model `magnum-v4-9b` with URL, name, icon, and description.
* Included file details for `magnum-v4-9b` with `filename`, `sha256`, and `uri`.
> models(gallery): add magnum-v4-9b

- gallery/granite.yaml
- gallery/index.yaml
This pull request introduces a new configuration for the Granite language model and updates the gallery index to include this new model. The most important changes include the addition of a new YAML configuration file for the Granite model and updates to the gallery index to reference the new model.
New Granite model configuration:
* [`gallery/granite.yaml`](diffhunk://#diff-de9b798c4ce5755b59c6519bea114fd97bab1fcd491c449890193bb0c622c372R1-R40): Added a new YAML configuration file for the Granite language model, including settings for mmap, templates for chat messages, functions, and completions, context size, and stopwords.
Gallery index update:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2-R27): Updated the …
> models(gallery): add granite-3.0-1b-a400m-instruct

- gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new model with detailed metadata and resources.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR28-R46): Added a new model entry for "moe-girl-800ma-3bt" including its name, icon, URL, description, parameter overrides, and associated files.
> models(gallery): add moe-girl-800ma-3bt

- backend/backend.proto
- backend/python/diffusers/backend.py
- pkg/model/initializers.go
Instead of trying to derive it from the model file. In backends that specify HF url this results in a fragile logic.
This pull request introduces a new `ModelPath` field to the `ModelOptions` message in `backend/backend.proto` and updates the relevant code to utilize this new field. The changes ensure that the `ModelPath` is used consistently across different parts of the codebase.
* [`backend/backend.proto`](diffhunk://#diff-b81549028379a9592a48240219d0d0e070f7b47e2351dbd9e9f5ce4dd632ca6cR236-R237): Added `ModelPath` field to the `ModelOptions` message.
* [`backend/python/diffusers/backend.py`](diffhunk://#diff-526f896cc791ae2971e143a1e3cbc048f074491e8721f23a95606c5c9da86144L304-R308): Updated `LoadModel` method to use `ModelPath` for constructing the `LoraAdapter` path instead of …
> fix(grpc): pass by modelpath

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry. The most important changes include the addition of the SmolLM2-1.7B-Instruct model with its metadata, description, and file details.
Updates to language models:
* Added a new entry for the `SmolLM2-1.7B-Instruct` model, including its name, icon, URLs, description, and file details.
> models(gallery): add smollm2-1.7b-instruct

- docs/content/docs/features/text-to-audio.md
This PR update the documentation regarding `response_format` in the tts endpoint.
Includes a warning regarding this feature not working without ffmpeg.
> docs: Update documentation for text-to-audio feature regarding response_format

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry with detailed information and parameters.
* Added a new model entry for `g2-9b-aletheia-v1` with a description, icon, URLs, and file details.
> models(gallery): add g2-9b-aletheia-v1

- backend/python/diffusers/backend.py
- core/http/endpoints/openai/image.go
This PR fixes inconsistencies when passing by a width and a height length, during image generation
> fix(diffusers): correctly parse height and width request without parametrization

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `Q25-1.5B-VeoLu`. The most important changes are the addition of the model's metadata, including its name, icon, URLs, description, and file details.
* Added a new model entry `Q25-1.5B-VeoLu` with the following details:
- Name: "Q25-1.5B-VeoLu"
- Icon URL: `https://huggingface.co/Alfitaria/Q25-1.5B-VeoLu/resolve/main/veolu.png`
- URLs: `https://huggingface.co/Alfitaria/Q25-1.5B-VeoLu`, `https://huggingface.co/bartowski/Q25-1.5B-VeoLu-GGUF`
- Description: Detailed description of the model's inspiration, components, and capabilities.
- Overrides: Model parameters set to `Q25-1.5B-VeoLu-Q4_K_M.gguf`
- Files: Filename and SHA256 hash for the model file …
> models(gallery): add q25-1.5b-veolu

- Dockerfile
This PR fixes this error that is happening since today in our image builds:
```
0.089 Initializing libbackend for coqui
0.089 make: Leaving directory '/build/backend/python/coqui'
0.089 ./../common/libbackend.sh: line 91: uv: command not found
0.089 make: *** [Makefile:3: coqui] Error 127
```
Seems uv install changed default paths or something around that (didn't deep dive). It sounds anyway safe to install the package at system-level because it has no users and uv is supposed to be usable by all users in the system.
> fix(container-images): install uv as system package

- core/backend/embeddings.go
- core/backend/image.go
- core/backend/llm.go
- core/backend/options.go
- core/backend/rerank.go
- core/backend/soundgeneration.go
- core/backend/stores.go
- core/backend/token_metrics.go
- core/backend/tokenize.go
- core/backend/transcript.go
- core/backend/tts.go
- core/startup/startup.go
- pkg/model/initializers.go
- tests/integration/stores_test.go
This PR contains some refactors extracted from #3722 .
It simplifies loading as it now expose a single method to load a model.
`BackendLoader` is now moved to an internal function ( `backendLoader`), `GreedyLoader` is now just `Loader`, which will automatically go in greedy mode if no backend is explicitly set in the configuration.
This has the added benefit that now not only the code is more consistent, but every caller have the chance to hit back the cache if a model was already loaded.
> chore(refactor): drop unnecessary code in loader

- pkg/concurrency/jobresult_test.go
> chore: update jobresult_test.go

- gallery/index.yaml
This pull request makes significant updates to the `gallery/index.yaml` file, primarily focusing on the addition and reorganization of Qwen2.5-Coder models. The changes include adding new entries for various Qwen2.5-Coder models and removing some existing entries.
* Added new entries for `qwen2.5-coder-14b`, `qwen2.5-coder-3b-instruct`, and `qwen2.5-coder-32b-instruct` models. These entries include details such as name, URLs, description, parameters, and file information.
* Removed existing entries for `qwen2.5-coder-14b` and `qwen2.5-coder-3b-instruct` models. These entries included similar details that have now been updated and re-added with new information.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origi …
> models(gallery): add qwen2.5-coder-32b-instruct

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for Qwen2.5-Coder-7B-Instruct. The most important change is the addition of the new model details, including its name, URLs, parameters, and file information.
* Added new model `qwen2.5-coder-7b-instruct` with the following details:
* Name: "qwen2.5-coder-7b-instruct"
* URLs: 
* https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct
* https://huggingface.co/bartowski/Qwen2.5-Coder-7B-Instruct-GGUF
* Parameters:
* Model: Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf
* Files:
* Filename: Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf
* SHA256: 1664fccab734674a50763490a8c6931b70e3f2f8ec10031b54806d30e5f956b6
* URI: huggingface://bartowski/Qwen2.5-Coder-7B-Instruct-GGUF/Qwen2.5-C …
> models(gallery): add qwen2.5-coder-7b-instruct

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "Rombos-Coder-V2.5-Qwen-7b". The most important changes include the addition of metadata and file information for the new model.
* Added a new model entry for "Rombos-Coder-V2.5-Qwen-7b" with metadata including name, icon, URLs, and description.
* Included file information for the new model, specifying the filename, sha256 checksum, and URI.
> models(gallery): add rombos-coder-v2.5-qwen-7b

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `Rombos-Coder-V2.5-Qwen-32b`. The most important changes include adding the model's metadata, URLs, description, and file details.
* Added a new model `rombos-coder-v2.5-qwen-32b` with the following details:
- Name, icon, and description of the model.
- URLs linking to the model on Hugging Face and documentation.
- File details including filename, SHA256 hash, and URI.
> models(gallery): add rombos-coder-v2.5-qwen-32b

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry. The most important change is the addition of the EVA-Qwen2.5-72B-v0.1-i1 model.
Model updates:
* Added a new model entry for `eva-qwen2.5-72b-v0.1-i1` with details including URLs, description, version notes, and file information.
> models(gallery): add eva-qwen2.5-72b-v0.1-i1

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file. The update adds a new entry for the "Tess-3-Llama-3.1-70B" model with relevant details.
* Added new model entry "Tess-3-Llama-3.1-70B" with name, icon, URLs, description, parameters, and file details (`gallery/index.yaml`).
> models(gallery): add tess-3-llama-3.1-70b

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "Llama 3.1 8b Enigma." The changes involve adding metadata, URLs, a description, and file details for the new model.
* Added a new model entry for "Llama 3.1 8b Enigma" with metadata, including name, icon, URLs, description, and file details.
> models(gallery): add llama3.1-8b-enigma

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "llama3.1-8b-cobalt".
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2675-R2693): Added a new entry for "llama3.1-8b-cobalt" with detailed information including URLs, description, version, parameters, and file details.
> chore(model): add llama3.1-8b-cobalt to the gallery

- gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, Llama3.2-3B-Enigma, is a high-quality code-instruct model built on Llama 3.2 3b, suitable for both code-instruct and general chat applications.
Key changes:
* Added a new model entry for Llama3.2-3B-Enigma, including its name, icon, URLs, description, overrides, and file details.
> chore(model): add llama3.2-3b-enigma to the gallery

- .gitattributes
This pull request includes a small change to the `.gitattributes` file. The change marks all `.hpp` files in the `backend/cpp/llama` directory as vendored files.
* [`.gitattributes`](diffhunk://#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eR2): Added a rule to mark `backend/cpp/llama/*.hpp` files as linguist-vendored.
> chore(linguist): add *.hpp files to linguist-vendored

- core/http/endpoints/localai/system.go
- core/schema/localai.go
- pkg/model/loader.go
This pull request includes several changes to improve the handling and representation of system information models. This is mainly done to the fact that we don't want to marshal the `model.Model` struct that has a Mutex, which makes swagger choke during generation of the documentation.
We create here a `schema.Model` which is used to return the results instead of consuming directly `model.Model`
Bumped into this as part of #3722 
> chore(api): return values from schema

- gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, named "l3.1-8b-slush-i1", is a two-stage model designed to enhance creativity and roleplaying capabilities.
The most important changes include:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2739-R2755): Added a new model entry "l3.1-8b-slush-i1" with associated metadata, including name, icon, URLs, description, overrides, and file details.
> chore(model): add l3.1-8b-slush-i1 to the gallery

- Makefile
- backend/cpp/llama/Makefile
> chore(deps): bump llama-cpp to ae8de6d50a09d49545e0afab2e50cc4acfb280e2

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important changes include the addition of a new model with its associated metadata and file details.
* Added a new model entry named "magnum-v2-4b-i1" with a description, icon, and URLs pointing to its locations on Hugging Face.
* Included file details for the new model, specifying the filename, SHA-256 checksum, and URI.
> chore(model): add magnum-v2-4b-i1 to the gallery

- Makefile
Seems the hipblas binary still have AVX and other CPU flags that might be problematic on old HW. As hipblas is reserved in cases of running inference on GPU, CPU optimizations aren't needed and actually just causes sigsev when running binaries.
See: https://github.com/mudler/LocalAI/issues/3367#issuecomment-2480400573
> fix(hipblas): disable avx flags when accellerated bins are used

- gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for `qwen2.5-7b-nerd-uncensored-v1.7`. The most important changes include adding the model's metadata, description, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1407-R1429): Added a new model entry for `qwen2.5-7b-nerd-uncensored-v1.7`, including its name, URLs, description, and file details.
> chore(model): add qwen2.5-7b-nerd-uncensored-v1.7 to the gallery

- .github/workflows/generate_intel_image.yaml
- Makefile
This PR bumps sycl. It is an attempt to fix the CI issues:
```
2024-11-19T09:13:54.2414646Z #56 97.42 /build/backend/cpp/llama-avx2/llama.cpp/ggml/src/ggml-sycl/dpct/helper.hpp:1240:55: warning: cast from 'const void *' to 'unsigned char *' drops const qualifier [-Wcast-qual]
2024-11-19T09:13:54.2417134Z #56 97.42  1240 |                 auto it = m_map.upper_bound((byte_t *)ptr);
2024-11-19T09:13:54.2418252Z #56 97.42       |                                                       ^
2024-11-19T09:13:54.2420526Z #56 97.42 /build/backend/cpp/llama-avx2/llama.cpp/ggml/src/ggml-sycl/dpct/helper.hpp:1837:16: error: no member named 'dp4a' in namespace 'syclcompat'; did you mean simply 'dp4a'?
2024-11-19T09:13:54.2422486Z #56 97.42  1837 |         return syclcompat::dp4a(a, b, c); …
```
> chore(deps): bump sycl intel image

- core/http/app_test.go
- core/http/middleware/auth.go
- core/http/routes/ui.go
- core/http/views/login.html
This PR fixes #2227 (tracked in #2156)
I've added a simple (we can't use fancy template resources without auth) html login page for token input, which pushes xhr request to the new /login handler, which is sets a 24hr valid cookie for a token.
The v2keyauth is now looking for token field in cookies too.
> feat: add WebUI API token authorization

- go.sum
This PR fixes 
```
go: github.com/urfave/cli/v2@v2.27.4: missing go.sum entry for go.mod file; to add it:
go mod download github.com/urfave/cli/v2
```
> fix(go.mod): add urfave/cli v2

- core/p2p/p2p.go
Previously in case of not specifying a value it would pass a slice of 1 empty element
This pull request includes changes to improve the configuration handling in the `newNodeOpts` function within the `core/p2p/p2p.go` file. The most important change is the modification of how the environment variables for `LOCALAI_P2P_LISTEN_MADDRS` and `LOCALAI_P2P_BOOTSTRAP_PEERS_MADDRS` are processed.
Improvements to configuration handling:
* [`core/p2p/p2p.go`](diffhunk://#diff-ba0b4d3c3fac0a53f790ed836fcd161d545c15e486a8e8eb5c70c9bc6071f5b7L389-R402): Modified the `newNodeOpts` function to handle empty environment variable values more gracefully by checking if the environment variables are non-empty before splitting them into slices.
**[Signed …
> fix(p2p): parse maddr correctly

- core/cli/worker/worker_p2p.go
Previously we were sensible when args aren't defined and we would clash parsing extra args.
This PR fixes #4214
This pull request includes an important change to the `Run` function in the `worker_p2p.go` file. The change ensures that the `extraArgs` variable is properly initialized and adds a debug log statement to provide better visibility into the arguments being used when starting the `llama-cpp-rpc-server`.
Initialization and logging improvements:
* [`core/cli/worker/worker_p2p.go`](diffhunk://#diff-9cb2fc9984e91747a6e95a6a4d4ac04b42f2992fccb6a7038dcb87fce745a69dL79-R86): Modified the initialization of the `extraArgs` variable to avoid splitting an empty string and added a debug log statement to log the arguments and their count when starting the …
> fix(p2p): parse correctly ExtraLLamaCPPArgs

- docs/content/docs/integrations.md
Showcase the integration of LocalAI and Microsoft Word.
Thank you for this great repo. I have recently integrated LocalAI with Microsoft Word through a local Word Add-in ([GPTLocalhost](https://gptlocalhost.com/demo#LocalAI)). Would it be possible to list this integration in the repo, providing users with another way to utilize LocalAI? Appreciate your consideration.
> chore(docs): integrating LocalAI with Microsoft Word

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for LLaMA-Mesh. The most important change involves the addition of the LLaMA-Mesh model with its associated metadata and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2943-R2957): Added a new entry for the LLaMA-Mesh model, including its name, URLs, description, overrides, and file details.
> models(gallery): add llama-mesh

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `llama-doctor-3.2-3b-instruct`. The most important changes include adding the model's name, URLs, description, overrides, and file details.
* Added a new model entry for `llama-doctor-3.2-3b-instruct` with its name, URLs, and description.
* Included overrides for the model parameters specifying `Llama-Doctor-3.2-3B-Instruct-Q4_K_M.gguf`.
* Added file details for `Llama-Doctor-3.2-3B-Instruct-Q4_K_M.gguf` including filename, sha256, and URI.
> chore(model): add llama-doctor-3.2-3b-instruct to the gallery

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "marco-o1". The most important changes include adding the model's metadata, description, and file information.
* Added model name "marco-o1" with an icon URL and description. The description highlights the model's focus on both standard disciplines and open-ended resolutions.
* Included URLs for accessing the "marco-o1" model on Hugging Face.
* Added file information for "Marco-o1.Q4_K_M.gguf" including its filename, SHA256 hash, and URI on Hugging Face.
> chore(model): add marco-o1 to the gallery

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file. The change adds a new model entry for `OneLLM-Doey-V1-Llama-3.2-3B`, which is a fine-tuned version of LLaMA 3.2-3B optimized for conversational AI and question answering tasks.
Key changes:
* Added a new model entry for `OneLLM-Doey-V1-Llama-3.2-3B`, including its URLs, description, and file details.
> chore(model): add onellm-doey-v1-llama-3.2-3b to the gallery

- gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file by adding a new model entry for `Llama-Sentient-3.2-3B-Instruct`. 
Key changes:
* Added a new model entry `Llama-Sentient-3.2-3B-Instruct` with detailed metadata including name, URLs, description, overrides, and file details.
> chore(model): add llama-sentient-3.2-3b-instruct to the gallery

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model is named "qwen2.5-3b-smart-i1" and includes relevant metadata such as URLs, description, parameters, and file details.
* Added a new model entry "qwen2.5-3b-smart-i1" with URLs, description, parameters, and file details.
> chore(model): add qwen2.5-3b-smart-i1 to the gallery

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for the Qwen2.5-Coder-32B-Instruct-Uncensored model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR173-R186): Added a new model entry for `qwen2.5-coder-32b-instruct-uncensored-i1`, including its name, URLs, description, parameters, and file details.
> chore(model): add qwen2.5-coder-32b-instruct-uncensored-i1 to the gallery

- gallery/index.yaml
- gallery/rwkv.yaml
This pull request includes the addition of a new model configuration and its corresponding YAML file to the gallery. The most important changes are summarized below:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2-R24): Added a new model entry for `rwkv-6-world-7b`, including its URL, license, tags, description, and file details.
New configuration file:
* [`gallery/rwkv.yaml`](diffhunk://#diff-ebfe4ef6b3c40343b4994962503c1e156b3b4fe1a001707a76b69fbfd9fec721R1-R25): Created a new configuration file for the `rwkv` model, specifying parameters such as `top_k`, `temperature`, `max_tokens`, and `top_p`, as well as roles, stopwords, and templates for chat and completion. …
> chore(model): add rwkv-6-world-7b to the gallery

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry is for the "eva-qwen2.5-72b-v0.2" model, which is a fine-tuned version of Qwen2.5-72B specialized in RP/storywriting.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1617-R1633): Added a new model entry "eva-qwen2.5-72b-v0.2" with details including URLs, description, version notes, and file information.
> chore(model): add eva-qwen2.5-72b-v0.2 to the gallery

- Makefile
- backend/cpp/llama/Makefile
This PR fixes https://github.com/mudler/LocalAI/issues/4274
> fix(llama.cpp): embed metal file into result binary for darwin

- gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, introducing a new experimental research model called "QwQ-32B-Preview". The most important changes are summarized below:
* Added a new model entry for "QwQ-32B-Preview" with detailed description, URLs, and file information. The model is focused on advancing AI reasoning capabilities and comes with several limitations such as language mixing, recursive reasoning loops, safety considerations, and performance limitations in certain areas.
> chore(model gallery): add qwq-32b-preview

- core/backend/llm.go
- core/http/endpoints/openai/chat.go
- pkg/grpc/backend.go
- pkg/grpc/client.go
- pkg/grpc/embed.go
This PR fixes __didn't find such issue__
i found out that usage body part is always zeroed when localai is used through webui, e.g. the output is streamed   
the issue is grpc server is supposed to return a stream of Reply structures, but for **some** reason they was used to retrieve just message bytes every chunk and nothing more     
But, the logic for holding mysterious empty usage data for every chunk is present (even it have sent only at the last closing chunk, that's why i was forced to do a hack with empty choices to retrieve just usage data through the tokenCallback)   
i don't really know about testing the tools part (and what the hell it is, lol), but since it uses usage data returned from ComputeChoices function - i have verified that it indeed returns non-empty …
> feat: include tokens usage for streamed output

- gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file. The change introduces a new model entry called "q2.5-32b-slush-i1" with detailed metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1678-R1693): Added a new model entry "q2.5-32b-slush-i1" with URLs, description, overrides, and file details.
> chore(model gallery): add q2.5-32b-slush-i1

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model series called Skywork o1 Open, developed by the Skywork team at Kunlun Inc. The most important changes include adding model details, descriptions, and associated files.
* Added a new model entry for `skywork-o1-open-llama-3.1-8b` with an icon, name, URLs, and a detailed description of the Skywork o1 Open model series.
* Included specific model parameters and file details for `Skywork-o1-Open-Llama-3.1-8B.Q4_K_M.gguf`.
> chore(model gallery): add skywork-o1-open-llama-3.1-8b

- backend/python/autogptq/requirements.txt
- backend/python/bark/requirements.txt
- backend/python/common/template/requirements.txt
- backend/python/coqui/requirements.txt
- backend/python/diffusers/requirements.txt
- backend/python/exllama2/requirements.txt
- backend/python/mamba/requirements.txt
- backend/python/openvoice/requirements-intel.txt
- backend/python/openvoice/requirements.txt
- backend/python/parler-tts/requirements.txt
- backend/python/rerankers/requirements.txt
- backend/python/sentencetransformers/requirements.txt
- backend/python/transformers-musicgen/requirements.txt
- backend/python/transformers/requirements.txt
- backend/python/vall-e-x/requirements.txt
- backend/python/vllm/install.sh
- backend/python/vllm/requirements.txt
This pull request includes updates to the `grpcio` dependency across multiple requirement files in the project. The `grpcio` version has been updated from `1.68.0` to `1.68.1` to ensure consistency and compatibility across different modules.
Dependency updates:
* [`backend/python/autogptq/requirements.txt`](diffhunk://#diff-326f4c9109482e17ae05b0eb5b30adbaddfa067a59199b82fc18f954ef7e4b65L3-R3): Updated `grpcio` from `1.68.0` to `1.68.1`.
* [`backend/python/bark/requirements.txt`](diffhunk://#diff-a298ae0bd8fb041e45e658764d74d3a0087220ea2d9aa3a66b719e735f5ace07L2-R2): Updated `grpcio` from `1.68.0` to `1.68.1`.
* [`backend/python/common/template/requirements.txt`](diffhunk://#diff-588cd64d1a39b6bfccc024d5faf067ccd3e984f3f1214273ac0b10f8ceba67deL1-R1): Updated `grpcio` from …
> chore(deps): bump grpcio to 1.68.1

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new advanced language model called "Qwen2.5-7B-HomerCreative-Mix". The most important changes include the addition of the model's metadata, description, and file details.
* Added a new model entry for "Qwen2.5-7B-HomerCreative-Mix" with a detailed description of its merged components and capabilities.
* Included URLs for accessing the model on Hugging Face.
* Provided a list of merged models and their specific contributions to the overall capabilities of "Qwen2.5-7B-HomerCreative-Mix".
* Added file details including the filename, sha256 checksum, and URI for the model.
**[Signed …
> chore(model gallery): add qwen2.5-7b-homercreative-mix

- gallery/index.yaml
This pull request adds a new Bulgarian language model to the `gallery/index.yaml` file. The model, named BgGPT-Gemma-2-2.6B-IT-v1.0, is based on Google's Gemma models and has been pre-trained and fine-tuned for Bulgarian language and cultural capabilities.
Key changes:
* Added a new entry for the BgGPT-Gemma-2-2.6B-IT-v1.0 model, including its name, icon, URLs, description, parameters, and associated file details.
> chore(model gallery): add bggpt-gemma-2-2.6b-it-v1.0

- gallery/flux-ggml.yaml
- gallery/index.yaml
This pull request introduces a new configuration for the `flux-ggml` model and updates the `gallery` index to include the new model. The most important changes include the addition of the `flux-ggml` configuration file and updates to the `gallery/index.yaml` to reference and describe the new model.
* [`gallery/flux-ggml.yaml`](diffhunk://#diff-f30a0f561b2f0a0e2f85d1e82e83e62cbfaa01b039b1e068e2b75f06ff98676aR1-R11): Added a new configuration file for the `flux-ggml` model, specifying backend and options.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR8909-R8945): Added a new entry for the `flux.1-dev-ggml` model, including license, description, tags, and file references.
**[Signed …
> chore(model gallery): add flux.1-dev-ggml

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "bark-cpp-small". The most important changes are as follows:
* Added a new model entry named "bark-cpp-small" with relevant metadata, including URLs, license information, description, tags, backend, parameters, and file details.
> chore(model gallery): add bark-cpp-small

- core/backend/llm.go
- core/http/endpoints/openai/chat.go
- pkg/grpc/backend.go
- pkg/grpc/client.go
- pkg/grpc/embed.go
Reverts mudler/LocalAI#4282
See: https://github.com/mudler/LocalAI/issues/4334
> Revert "feat: include tokens usage for streamed output"

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model, Virtuoso-Small, is designed to bring cutting-edge generative AI capabilities in a compact and efficient form.
* Added a new model entry for Virtuoso-Small, including its name, icon, URLs, description, overrides, and associated file details.
> chore(model gallery): add virtuoso-small

- gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file. The change introduces a new model entry with detailed metadata and file information.
* Added a new model named "impish_mind_8b" with associated metadata including name, icon, URLs, description, and file details. This model is designed to excel at general assistant tasks and includes unique datasets.
> chore(model gallery): add impish_mind_8b

- gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file. The change introduces a new language model entry, `INTELLECT-1-Instruct`, with relevant metadata and configuration details.
Addition of new language model:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2-R26): Added a new entry for `INTELLECT-1-Instruct`, including its name, URL, icon, tags, license, description, and file details.
> chore(model gallery): add intellect-1-instruct

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `Sailor2-20B-Chat`. The change introduces a detailed description of the model, its parameters, and associated metadata.
* Addition of a new model entry for `Sailor2-20B-Chat` with a detailed description highlighting its purpose and supported languages.
* Inclusion of the model's icon URL and a link to the model on Hugging Face.
* Specification of the model's parameters and the associated file details, including filename, sha256 checksum, and URI.
> chore(model gallery): add sailor2-20b-chat

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `deepthought-8b-llama-v0.01-alpha`.
* Added a new model entry for `deepthought-8b-llama-v0.01-alpha`, including its description, URLs, parameters, and file details.
> chore(model gallery): add deepthought-8b-llama-v0.01-alpha

- gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file. The changes involve adding a new model entry for `Evathene-v1.3`.
* Added a new model entry for `Evathene-v1.3` with an icon, name, description, and URLs.
* Included file details such as filename, sha256, and URI for the new model.
> chore(model gallery): add evathene-v1.3

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry. The new entry is for the "Hermes-3-Llama-3.2-3B" model, which is a recent addition to the Hermes series of LLMs by Nous Research.
Key changes:
* Added a new entry for the "Hermes-3-Llama-3.2-3B" model, including its name, icon, URLs, description, and file details.
> chore(model gallery): add hermes-3-llama-3.2-3b

- Makefile
- backend/cpp/llama/grpc-server.cpp
Supersedes https://github.com/mudler/LocalAI/pull/4377
> feat(llama.cpp): bump and adapt to upstream changes

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model to the gallery. The new model, FuseChat-3.0, has been integrated with detailed information about its sources, training process, and performance improvements.
Key changes:
* Added a new model entry for "fusechat-gemma-2-9b-instruct" with a detailed description of the model's creation, sources, and performance.
* Included URLs for accessing the model on Huggingface.
* Provided an icon URL for the new model entry.
* Added file details for the model, including the filename, sha256 checksum, and URI.
> chore(model gallery): add fusechat-gemma-2-9b-instruct

- gallery/index.yaml
This pull request introduces a new model entry to the `gallery/index.yaml` file. The change adds details for the `FuseChat-Llama-3.1-8B-Instruct` model, including its description, icon, URLs, and associated parameters.
* Added `FuseChat-Llama-3.1-8B-Instruct` model entry with detailed description, icon, URLs, and parameters.
> chore(model gallery): add fusechat-llama-3.1-8b-instruct

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The changes introduce the Neumind-Math-7B-Instruct model, which is designed for mathematical reasoning and problem-solving.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2036-R2049): Added the Neumind-Math-7B-Instruct model, including its name, URLs, description, parameters, and file details.
> chore(model gallery): add neumind-math-7b-instruct

- backend/python/autogptq/requirements-intel.txt
- backend/python/bark/requirements-intel.txt
- backend/python/common/libbackend.sh
- backend/python/coqui/requirements-intel.txt
- backend/python/diffusers/requirements-intel.txt
- backend/python/openvoice/requirements.txt
- backend/python/parler-tts/requirements-intel.txt
- backend/python/parler-tts/requirements.txt
- backend/python/rerankers/requirements-intel.txt
- backend/python/sentencetransformers/requirements-intel.txt
- backend/python/transformers-musicgen/requirements-intel.txt
- backend/python/transformers/requirements.txt
- backend/python/vall-e-x/requirements-intel.txt
- backend/python/vall-e-x/requirements.txt
- backend/python/vllm/requirements-intel.txt
Bumps setuptools as currently CI fails with:
```
Resolved 123 packages in 1.75s
× Failed to download and build `numpy==1.22.0`
╰─▶ Build backend failed to determine requirements with `build_wheel()`
(exit status: 1)
[stderr]
Traceback (most recent call last):
File "<string>", line 8, in <module>
File
"/home/runner/.cache/uv/builds-v0/.tmp6DE6nf/lib/python3.12/site-packages/setuptools/__init__.py",
line 10, in <module>
import distutils.core
ModuleNotFoundError: No module named 'distutils'
hint: `distutils` was removed from the standard library in Python 3.12.
Consider adding a constraint (like `numpy >1.22.0`) to avoid building a
version of `numpy` that depends on `distutils`.
make: *** [Makefile:5: install] Error 1
```
**[Signed …
> fix(python): remove pin to setuptools, pin python version

- core/http/app_test.go
This PR tries to stabilize tests that currently are failing on master:
```
API test Model gallery [It] installs and is capable to run tts [tts]
/home/runner/work/LocalAI/LocalAI/core/http/app_test.go:681
[FAILED] Expected
<string>: audio/vnd.wave
to equal
<string>: audio/x-wav
In [It] at: /home/runner/work/LocalAI/LocalAI/core/http/app_test.go:707 @ 12/16/24 15:19:51.986
```
> chore(tests): stabilize tts test

- gallery/index.yaml
This pull request adds a new entry for the Llama-OpenReviewer-8B model in the `gallery/index.yaml` file. The most important changes include the addition of the model's metadata, URLs, description, and file details.
* Added a new model entry `llama-openreviewer-8b` with metadata including name, URLs, description, and file details.
> chore(model gallery): add llama-openreviewer-8b

- backend/python/autogptq/requirements-intel.txt
- backend/python/bark/requirements-intel.txt
- backend/python/common/template/requirements-intel.txt
- backend/python/coqui/requirements-intel.txt
- backend/python/diffusers/requirements-intel.txt
- backend/python/openvoice/requirements-intel.txt
- backend/python/parler-tts/requirements-intel.txt
- backend/python/rerankers/requirements-intel.txt
- backend/python/sentencetransformers/requirements-intel.txt
- backend/python/transformers-musicgen/requirements-intel.txt
- backend/python/transformers/requirements-intel.txt
- backend/python/vall-e-x/requirements-intel.txt
- backend/python/vllm/requirements-intel.txt
This PR pins torch* and intel-extensions versions in the python backends. New pytorch release is still rolling and not compatible yet with all backends.
> fix(intel): pin torch and intel-extensions

- backend/python/openvoice/requirements-cpu.txt
- backend/python/openvoice/requirements-cublas11.txt
- backend/python/openvoice/requirements-cublas12.txt
- backend/python/openvoice/requirements-hipblas.txt
- backend/python/openvoice/requirements-intel.txt
- backend/python/openvoice/requirements.txt
This PR tries to fix CI issues that are currently hammering the CI due to the new pytorch release (2.5.1). Seems we didn't had many pins around and the new pytorch version isn't available everywhere yet 
> fix(deps): pin openvoice pytorch/torchaudio

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry to the gallery. The new entry is for the TQ2.5-14B-Aletheia-v1 model, which is a hybrid model designed for both role-playing (RP) and storywriting.
Key changes:
* Added a new model entry named `tq2.5-14b-aletheia-v1` with an associated icon and description. The description highlights the model's capabilities and the collaborative effort involved in its creation.
* Included URLs pointing to the model's locations on Hugging Face.
* Added specific parameters and file details for the new model, including the filename and SHA-256 hash for verification.
> chore(model gallery): add tq2.5-14b-aletheia-v1

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of a new model called "anubis-70b-v1" with its details and parameters.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR129-R143): Added a new model entry "anubis-70b-v1" with its name, icon, URLs, description, overrides, and file details.
> chore(model gallery): add anubis-70b-v1

- Dockerfile
This PR introduces a `SKIP_DRIVERS` variable during container image build which allows to skip the drivers installations. This is useful e.g. when the drivers are already part of the image, for instance to build an image for the Nvidia AGX Orin:
```
docker build --build-arg SKIP_DRIVERS=true --build-arg BUILD_TYPE=cublas --build-arg BASE_IMAGE=nvcr.io/nvidia/l4t-jetpack:r36.4.0 --build-arg IMAGE_TYPE=core -t localai-orin .
```
> feat(Dockerfile): allow to skip driver installation

- gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model configuration for the Falcon3 series. The most important changes include adding the new model's details, descriptions, and file references.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR66-R80): Added a new model `falcon3-3b-instruct-abliterated` with its corresponding URLs, description, and file references. This model is an uncensored version created with abliteration.
> chore(model gallery): add falcon3-3b-instruct-abliterated

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model, Control-Nanuq-8B, is a fine-tuned version of LLaMA 3.1 8B Supernova with specific characteristics and enhancements.
Key changes:
* Added a new model entry named "control-nanuq-8b" with relevant metadata, including an icon URL, description, and download URLs.
* Included the model's parameters and associated file details, such as filename, SHA256 hash, and URI for downloading the model.
> chore(model gallery): add control-nanuq-8b

- gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for `SmallThinker-3B-Preview`. The changes introduce details about the model's use cases, parameters, and file information.
* Added a new model entry `SmallThinker-3B-Preview` with descriptions, use cases, and URLs for download.
> chore(model gallery): add smallthinker-3b-preview

- gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new pre-trained language model named "mn-12b-mag-mell-r1-iq-arm-imatrix". The changes include detailed metadata and descriptions for the new model.
* Added a new model entry "mn-12b-mag-mell-r1-iq-arm-imatrix" with detailed metadata including name, URL, icon, and multiple source URLs.
* Provided a comprehensive description of the model's creation process, intended use cases, and the specific models included in the merge.
* Included the filenames, SHA256 checksums, and URIs for the model files.
> chore(model gallery): add mn-12b-mag-mell-r1-iq-arm-imatrix

- gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file to include a new model entry. The new model is `codepy-deepthink-3b`, which is designed for text generation tasks requiring deep reasoning and logical structuring.
Key changes:
* Added a new model entry `codepy-deepthink-3b` with URLs for downloading the model from Hugging Face.
* Included a detailed description of the `codepy-deepthink-3b` model, highlighting its capabilities in education, programming, and creative writing.
* Specified the model parameters and file details, including the filename, SHA256 checksum, and URI for `codepy-deepthink-3b`.
> chore(model gallery): add codepy-deepthink-3b

- gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry is for the "llama3.1-8b-prm-deepseek-data" model, which includes details about the model's training process, parameters, and file information.
Key changes:
* Added a new model entry for "llama3.1-8b-prm-deepseek-data" with URLs, description, and training details.
* Included parameters and file information for the new model.
> chore(model gallery): add llama3.1-8b-prm-deepseek-data

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the Qwentile 2.5 32B Instruct model with detailed information and references.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2390-R2414): Added a new model entry for "qwentile2.5-32b-instruct" with its name, icon, URLs, description, overrides, and associated files.
> chore(model gallery): add qwentile2.5-32b-instruct

- backend/python/autogptq/requirements.txt
- backend/python/bark/requirements.txt
- backend/python/common/template/requirements.txt
- backend/python/coqui/requirements.txt
- backend/python/diffusers/requirements.txt
- backend/python/exllama2/requirements.txt
- backend/python/mamba/requirements.txt
- backend/python/openvoice/requirements-intel.txt
- backend/python/openvoice/requirements.txt
- backend/python/parler-tts/requirements.txt
- backend/python/rerankers/requirements.txt
- backend/python/sentencetransformers/requirements.txt
- backend/python/transformers-musicgen/requirements.txt
- backend/python/transformers/requirements.txt
- backend/python/vall-e-x/requirements.txt
- backend/python/vllm/requirements.txt
This pull request updates the `grpcio` dependency across multiple requirement files in the backend Python projects. The version of `grpcio` has been updated from 1.68.1 to 1.69.0 to ensure consistency and compatibility across different modules.
Dependency updates:
* Updated `grpcio` from 1.68.1 to 1.69.0 in `backend/python/autogptq/requirements.txt`
* Updated `grpcio` from 1.68.1 to 1.69.0 in `backend/python/bark/requirements.txt`
* Updated `grpcio` from 1.68.1 to 1.69.0 in `backend/python/common/template/requirements.txt`
* Updated `grpcio` from 1.68.1 to 1.69.0 in `backend/python/coqui/requirements.txt`
* Updated `grpcio` from 1.68.1 to 1.69.0 in `backend/python/diffusers/requirements.txt`
* Updated `grpcio` from 1.68.1 to 1.69.0 in …
> chore(deps): bump grpcio to 1.69.0

- gallery/index.yaml
This pull request includes the addition of a new model entry to the `gallery/index.yaml` file. The most important change is the inclusion of the `Triangulum-10B` model with detailed metadata and training approach information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR9312-R9334): Added `Triangulum-10B` model entry, including name, icon, URLs, description, key features, training approach, parameter overrides, and file details.
> chore(model gallery): add triangulum-10b

- docs/content/docs/reference/compatibility-table.md
This pull request includes updates to the compatibility table documentation to correct inaccuracies and clarify model support details.
Documentation updates:
* [`docs/content/docs/reference/compatibility-table.md`](diffhunk://#diff-d380bb3d017b23a4326d7c7d3c6947b6092d61fd9e28c3db39986da9722c5266L19-R20): Removed inaccurate notes about the `llama.cpp` and `transformers` models, and updated the footnotes to accurately reflect support details. [[1]](diffhunk://#diff-d380bb3d017b23a4326d7c7d3c6947b6092d61fd9e28c3db39986da9722c5266L19-R20) [[2]](diffhunk://#diff-d380bb3d017b23a4326d7c7d3c6947b6092d61fd9e28c3db39986da9722c5266L40-R47)
> docs: update compatibility-table.md

- gallery/index.yaml
- gallery/phi-4-chat.yaml
This pull request includes the addition of a new model entry, `phi-4`, to the gallery and the creation of a configuration file for `phi-4-chat`. The most important changes are listed below:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2-R25): Added a new model entry for `phi-4`, including its URL, name, license, tags, description, and file details.
* [`gallery/phi-4-chat.yaml`](diffhunk://#diff-16e15b9b7626620146c23274c91f8efedd980891684ab67548181f0e54575c4eR1-R20): Created a new configuration file for `phi-4-chat` with settings for memory mapping, templates for chat messages, context size, and stopwords.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of …
> chore(model gallery): add phi-4

- pkg/downloader/uri.go
- pkg/downloader/uri_test.go
This PR adds support for resuming partial downloads.
**Notes for Reviewers** 
A few questions:  
1. Should we check if the server supports Range Header(used here for partial downloads), most modern web servers do.   
2. I wanted to have a discussion when a model in gallery has multiple files. 
> feat(dowloader): resume partial downloads

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model checkpoint entry for `MiniThinky-v2-1B-Llama-3.2`. 
Key changes:
* Added a new model checkpoint entry for `MiniThinky-v2-1B-Llama-3.2`, including its name, URLs, description, parameters, and file details.
> chore(model gallery): add minithinky-v2-1b-llama-3.2

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry is for the HuatuoGPT-o1-7B-v0.1 model, which is a medical LLM designed for advanced medical reasoning.
Key changes:
* Added a new model entry for `HuatuoGPT-o1-7B-v0.1` with detailed information including URLs, description, parameters, and file details.
> chore(model gallery): add huatuogpt-o1-7b-v0.1

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "phi-3.5-moe-instruct". The most important changes are:
* Added a new model entry for "phi-3.5-moe-instruct" with its corresponding URLs, description, and file details. This model is a lightweight, state-of-the-art open model built upon datasets used for Phi-3, supporting multilingual and 128K context length. It incorporates supervised fine-tuning, proximal policy optimization, and direct preference optimization to ensure precise instruction adherence and robust safety measures.
> chore(model gallery): add phi-3.5-moe-instruct

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "NightWing3-10B-v0.1". The most important change is the addition of this new model with its associated metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR135-R150): Added a new model entry for "NightWing3-10B-v0.1" with details including name, URL, icon, description, parameters, and file information.
> chore(model gallery): add nightwing3-10b-v0.1

- Makefile
- backend/go/image/stablediffusion-ggml/Makefile
- backend/go/image/stablediffusion-ggml/gosd.go
This PR refactors build process for stablediffusion-ggml and respects build_type to enable cuda acceleration 
> feat(stablediffusion-ggml): respect build type

- backend/go/image/stablediffusion-ggml/Makefile
This PR disables sycl build type in the stablediffusion-ggml backend. Seems it fails compiling for now, leaving for investigation on a second time.
> chore(stablediffusion-ggml): disable sycl optimizations

- gallery/index.yaml
- gallery/phi-4-chat-fcall.yaml
This pull request includes updates to the `gallery/index.yaml` and `gallery/phi-4-chat-fcall.yaml` files to add a new model and enhance the configuration for function calls. The most important changes are:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR26-R41): Added a new model entry for "LocalAI-functioncall-phi-4-v0.3" with relevant details such as URL, name, icon, description, and file information.
* [`gallery/phi-4-chat-fcall.yaml`](diffhunk://#diff-3ba5b558791ea02b7fbabf6f01a22686228a64221ade27027ddeb43b0eb7779cR6-R15): Enhanced the configuration by adding support for function calls with JSON regex matching, capturing, and replacing LLM results, and specifying grammar properties order.
**Notes for …
> chore(model gallery): add LocalAI-functioncall-phi-4-v0.3

- gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, specifically the inclusion of a new entry for the DRT-o1-14B model. The most important changes are as follows:
* Added new model entry `drt-o1-14b` with associated URLs, description, and parameters. This model is part of the DRT-o1 series aimed at optimizing deep reasoning translation via long chain-of-thought.
* Included detailed description of the DRT-o1 project, highlighting the use of a multi-agent framework and the training of various DRT-o1 models using different backbones.
* Added file information for `DRT-o1-14B-Q4_K_M.gguf` with its corresponding SHA256 checksum and URI.
> chore(model gallery): add drt-o1-14b

- Makefile
- backend/cpp/llama/grpc-server.cpp
Update to '3edfa7d3753c29e44b964c0ff424d2ea8d5fdee6' and adapt to upstream changes
Supersedes https://github.com/mudler/LocalAI/pull/4626
> chore(llama.cpp): update dependency

- docs/content/docs/getting-started/container-images.md
This PR fix missing container images tag for sycl images.
Doing:
```
podman pull localai/localai:v2.25.0-sycl-f16
podman pull localai/localai:v2.25.0-sycl-f32
```
returns errors on images unavailability
> fix(docs): add missing `-core` suffix to sycl images

- gallery/index.yaml
This PR adds MiniCPM-o-2.6-7.6b model and set a MiniCPM icon for all MiniCPM models in the gallery
> chore(model gallery): add MiniCPM-V-2.6-8b-q4_K_M

- gallery/index.yaml
This PR fixes wrong architecture for MiniCPM-V 2.6.
Now it work flawlessly. Both with image and text.
> fix(model gallery): minicpm-v-2.6 is based on qwen2

- gallery/index.yaml
This PR adds some little Deepseek-R1 distill models to the gallery
Not fully working yet.
For Qwen this commit https://github.com/ggerganov/llama.cpp/commit/ec7f3ac9ab33e46b136eb5ab6a76c4d81f57c7f1
shoudl be added
For LLama some prompt tweaking seems to be needed
> chore(model gallery): add Deepseek-R1-Distill models

- Dockerfile
- Makefile
- backend/python/faster-whisper/Makefile
- backend/python/faster-whisper/backend.py
- backend/python/faster-whisper/install.sh
- backend/python/faster-whisper/protogen.sh
- backend/python/faster-whisper/requirements-cpu.txt
- backend/python/faster-whisper/requirements-cublas11.txt
- backend/python/faster-whisper/requirements-cublas12.txt
- backend/python/faster-whisper/requirements-hipblas.txt
- backend/python/faster-whisper/requirements-intel.txt
- backend/python/faster-whisper/requirements.txt
- backend/python/faster-whisper/run.sh
- backend/python/faster-whisper/test.sh
This PR adds the faster-whisper backend
> feat(faster-whisper): add backend

- pkg/model/initializers.go
This pull request includes changes to the `pkg/model/initializers.go` file to simplify the detection and handling of `llama.cpp` backend variants. The most important changes include the introduction of a new variable to store the variants and the refactoring of the backend detection logic.
Improvements to backend detection:
* [`pkg/model/initializers.go`](diffhunk://#diff-a26dd3419ca8caa91cc7f44ce53e3b843c9b09ee3f180a584423dd3b1beccda7R69-R79): Added a new variable `llamaCPPVariants` to store `llama.cpp` backend variants.
* [`pkg/model/initializers.go`](diffhunk://#diff-a26dd3419ca8caa91cc7f44ce53e3b843c9b09ee3f180a584423dd3b1beccda7L110-L143): Refactored the backend detection logic to use the new `llamaCPPVariants` variable, simplifying the code and reducing redundancy. …
> chore(refactor): group cpu cap detection

- pkg/downloader/uri.go
This pull request includes updates to the `pkg/downloader/uri.go` file to support additional Hugging Face URL prefixes. 
Now: `hf.co/`, and `hf://` are accepted URIs prefix as well.
The changes include adding new constants for the prefixes, updating the URL detection logic, and modifying the URL resolution function to handle the new prefixes.
Support for additional Hugging Face URL prefixes:
* [`pkg/downloader/uri.go`](diffhunk://#diff-7b30200b6c2051abb6708097d9568ffe3ea941aee870ad872205a84ed35cd2feR25-R26): Added new constants `HuggingFacePrefix1` and `HuggingFacePrefix2` for additional Hugging Face URL formats.
* [`pkg/downloader/uri.go`](diffhunk://#diff-7b30200b6c2051abb6708097d9568ffe3ea941aee870ad872205a84ed35cd2feR132-R133): Updated the `LooksLikeURL` function to …
> chore(downloader): support hf.co and hf:// URIs

- gallery/index.yaml
This PR adds some missing icons for popular models as stated in the PR title
> chore(model gallery): add flux.1, stablediffusion and whisper icons

- gallery/deepseek-r1.yaml
- gallery/index.yaml
This PR fixes deepseek-r1 prompt. `</think>` splitting is missing, I already tried with cutstrings parameter but seems that regex doesn't work.
This is the entire jinja template
```jinja
```
> chore(model gallery): update deepseek-r1 prompt template

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `deepseek-r1-qwen-2.5-32b-ablated`. The most important changes include adding the model's metadata, description, and file information.
* Added new model `deepseek-r1-qwen-2.5-32b-ablated` with associated metadata including name, icon, URLs, and description.
* Included file details for the new model, specifying filename, sha256, and URI.
> chore(model gallery): add deepseek-r1-qwen-2.5-32b-ablated

- pkg/functions/parse.go
This PR fixes #4671
I've added a function to parse function call arguments using named regex into valid json, in case the model is trained on non json argument / function calling.
Example model configuration can be found [here](https://github.com/mKenfenheuer/localai-gallery/blob/main/llama-3.2-3b.yaml)
> feat: function argument parsing using named regex

- pkg/functions/parse.go
This PR refactors the function argument parsing as discussed in #4700.
> refactor: function argument parsing using named regex

- docs/content/docs/advanced/advanced-usage.md
This PR updates the docs in advanced-usage.md to reflect changes in #4700
> docs: update advanced-usage.md to reflect changes in #4700

- backend/backend.proto
- backend/cpp/llama/grpc-server.cpp
- core/backend/options.go
- pkg/functions/parse.go
Thanks to the great upstream work in llama.cpp ( https://github.com/ggerganov/llama.cpp/pull/9639 thanks :heart_hands:  @ochafik ! ) it is now possible to enable grammars with a set of trigger words. This allows to force a special schema in answers only if a trigger word is detected as part of the text of the LLM. This, for example, allows to models that uses tags before returning the json (e.g. `[TOOL_CALL]`, `<tool_call>`, ... ) to identify the function call and enable the grammar - which allows the model to output text replies or JSON.
This PR enables this feature in LocalAI, and it can be enabled in the model configuration file:
```yaml
function:
grammar:
triggers:
- word: "foo"
at_start: true
```
**[Signed …
> feat(llama.cpp): Add support to grammar triggers

- backend/cpp/llama/grpc-server.cpp
- core/backend/tokenize.go
- core/http/endpoints/localai/tokenize.go
> feat: tokenization with llama.cpp

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new entry for the `rubenroy_gilgamesh-72b` model. The most important changes include the addition of the model's metadata, description, and associated files.
* Added a new model entry `rubenroy_gilgamesh-72b` with relevant metadata such as name, icon, and URLs.
* Included a detailed description of the `rubenroy_gilgamesh-72b` model, highlighting the specialized datasets used for its training.
* Added overrides for the model parameters and the associated file details, including filename, SHA256 checksum, and URI.
> chore(model gallery): add rubenroy_gilgamesh-72b

- core/gallery/models_test.go
- core/gallery/request.go
- core/gallery/request_test.go
- core/http/app_test.go
- core/http/endpoints/localai/gallery.go
When hitting /models/available we are intersted in the model description, name and small metadatas. Configuration and overrides are part of internals which are required only for installation.
This also solves a current bug when hitting /models/available fails if one of the gallery items have overrides with parameters defined, e.g.:
```
curl localhost:8080/models/available     
{"error":{"code":500,"message":"json: unsupported type: map[interface {}]interface {}","type":""}}
```
> fix(gallery): do not return overrides and additional config

- core/http/endpoints/openai/chat.go
We were not returning a stop reason when no tool was actually called (even if specified).
Fixes: https://github.com/mudler/LocalAI/issues/4716
> fix(openai): consistently return stop reason

- .github/workflows/generate_grpc_cache.yaml
- .github/workflows/image_build.yml
- Dockerfile
This PR bumps grpcio caches to 1.70
grpc caches seems to fail building now: https://github.com/mudler/LocalAI/actions/runs/13240324429/job/36954074194
> chore(grpcio): bump to 1.70

- gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new entry for the `sicariussicariistuff_phi-lthy4` model. The most important changes include adding the model's metadata, description, and file details.
* Added a new entry for the `sicariussicariistuff_phi-lthy4` model, including its name, URL, icon, and multiple URLs for additional resources.
* Included a detailed description highlighting the model's capabilities in roleplay and creative writing, its compact size, and its smart assistant features.
* Specified override parameters and file details, including the filename, SHA256 hash, and URI for the model file.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certifica …
> chore(model gallery): add sicariussicariistuff_phi-lthy4

- gallery/deephermes.yaml
- gallery/index.yaml
This PR adds the latest deephermes!
> chore(model gallery): add nousresearch_deephermes-3-llama-3-8b-preview

- backend/cpp/llama/grpc-server.cpp
This pull request includes changes to the `backend/cpp/llama/grpc-server.cpp` file to handle context capacity and prevent redundant checks. The most important changes include adding a check for context capacity and improving logging when context is exhausted.
Context capacity handling:
* Added a check to set `truncated` and `stopped_limit` flags and log a message when the context capacity is reached. (`backend/cpp/llama/grpc-server.cpp`)
Redundant check removal:
* Removed redundant checks and improved logging when context is exhausted by releasing the slot and logging an error message. (`backend/cpp/llama/grpc-server.cpp`)
> fix(llama.cpp): improve context shift handling

- pkg/model/initializers.go
fix init order, so avx512 gets tried before avx2
This PR fixes #4836 
trivial fix for PR, please pull
> fix: change initialization order of llama-cpp-avx512 to go before avx2 variant

- core/http/views/chat.html
- core/http/views/index.html
This slightly improves the index providing buttons to go chat to the model
> feat: improve ui models list in the index

- core/config/backend_config.go
- core/http/views/index.html
A small quality improvement for the WebUI. 
Models capabilities are automatically infered when the model configuration is being loaded and the UI now can display buttons depending on the model capabilities:
Browsing to the gallery isn't anymore the default action - a separate icon next to the model is displayed. Clicking on "Chat" will open up the chat window with the model selected.
Part of #2156 
> feat(ui): detect model usage and display link

- backend/backend.proto
- backend/python/vllm/backend.py
- core/backend/options.go
- core/config/backend_config.go
- gallery/vllm.yaml
This allows for additional configuration of the vLLM backend, specifically the following options
- --disable-log-requests
- This allows disable request logging for your deployment 
- --dtype
- This allows configuring the datatype that vLLM will use. When using awq, bfloat16 is not supported, this you need to adjust 
- --limit-mm-per-prompt
- This allows you to up the limit on attached media per request per modality. The default is 1 image/video/audio entry per request, even though many models support more 
_see: https://docs.vllm.ai/en/latest/serving/engine_args.html_
`limit_mm_per_prompt` is a nested object with config for image, video, and audio modality types. See below (and in commit) for example on bumping the default limit (1)
The resulting vllm-based config file …
> feat(vllm): Additional vLLM config options (Disable logging, dtype, and Per-Prompt media limits)

- core/http/routes/ui.go
- core/http/views/chat.html
- core/http/views/index.html
This PR restricts the choice of models to chat with in the chat view. Now in the drop-down menu will be present only models that are detected supporting text generation.
Part of #2156 
> feat(ui): show only text models in the chat interface

- core/http/routes/ui.go
- core/http/views/chat.html
- core/http/views/text2image.html
- core/http/views/tts.html
Follow up of https://github.com/mudler/LocalAI/pull/4869, using the same approach we filter now also models in the tts and the image selection.
Part of #2156 
> feat(ui): do also filter tts and image models

- core/gallery/gallery.go
- core/gallery/request.go
- core/http/routes/ui.go
- core/http/views/models.html
This PR is a simple implementation of pagination for the webui. As the models are growing the page now is slow to load. 
There are many low-hanging fruit from this PR - this is just a simple start. 
Notably to do still:
- Do calculation of pages in the client side
- use htmx to not refresh page when navigating
- adding a page list selector, (First/last, and few pages to click)
- Extend this also to the search (now not paginated)
#2156 
> feat(ui): paginate model gallery

- core/gallery/gallery.go
- core/http/routes/ui.go
- core/http/static/chat.js
- core/http/views/chat.html
- core/http/views/models.html
This PR improves the chat interface on several fronts, with tiny changes here and there to improve daily quality of life:
- It now displays informations about the model
- It moves the action buttons on the left in a leftbar
- It improves the UX in the chat (message scrolling is now fixed)
- Visually changes to improve UX generally (icon model)
- Fixes pagination buttons showing during search (search is not paginated yet)
- Adds a copy icon to click to copy the output of the assistant
#2156 
> feat(ui): improve chat interface

- core/http/views/chat.html
This pull request includes changes to the `core/http/views/chat.html` file to improve the handling of gallery configurations in the chat interface. The most important changes focus on adding conditional checks for the presence of gallery configurations before attempting to display gallery icons.
Improvements to gallery configuration handling:
* [`core/http/views/chat.html`](diffhunk://#diff-65bba31d9ea4fd7a1ce1bfb2ee069e72bb00ea15d66032ee3c319dddfa3cfb22R232-R235): Added a conditional check for the presence of `$galleryConfig` before attempting to display the gallery icon in the chat header.
* [`core/http/views/chat.html`](diffhunk://#diff-65bba31d9ea4fd7a1ce1bfb2ee069e72bb00ea15d66032ee3c319dddfa3cfb22R267-R269): Added a conditional check for the presence of …
> fix(ui): not all models comes from gallery

- core/http/elements/buttons.go
- core/http/elements/gallery.go
- core/http/static/chat.js
- core/http/static/general.css
- core/http/views/chat.html
- core/http/views/index.html
- core/http/views/models.html
- core/http/views/text2image.html
- mobile-friendly index
- adjust color palette
- improve search experience
#2156 
> feat(ui): improvements to index and models page

- core/backend/llm.go
- core/config/backend_config.go
This PR adds a new config option (`reply_prefix`) in order to add a prefix to each LLM reply
> feat: allow to specify a reply prefix

- core/http/static/chat.js
- core/http/static/image.js
- core/http/static/talk.js
- core/http/static/tts.js
- core/http/views/chat.html
- core/http/views/models.html
- core/http/views/talk.html
- core/http/views/text2image.html
- core/http/views/tts.html
This pull request removes the requirement for an API key across multiple files in the project. The changes include the removal of functions related to API key handling, updates to function calls, and adjustments to the UI to reflect these changes.
* [`core/http/static/chat.js`](diffhunk://#diff-85612be3564b6aaf404c4e771b0ea5787afbebc4d94a8ca84deee54c1dfd1f00L45-L50): Removed the `submitKey` function and all references to the API key in various functions, including `submitPrompt`, `promptGPT`, and event listeners. [[1]](diffhunk://#diff-85612be3564b6aaf404c4e771b0ea5787afbebc4d94a8ca84deee54c1dfd1f00L45-L50) [[2]](diffhunk://#diff-85612be3564b6aaf404c4e771b0ea5787afbebc4d94a8ca84deee54c1dfd1f00L65-R61) …
> feat(ui): remove api key handling and small ui adjustments

- Makefile
- backend/backend.proto
- backend/cpp/llama/grpc-server.cpp
- core/backend/options.go
- pkg/functions/parse.go
> chore(deps): update llama.cpp and sync with upstream changes

- gallery/index.yaml
This pull request adds new models to the `gallery/index.yaml` file. The most important changes include the addition of two new embedding models from the Granite Embeddings suite.
* Added `granite-embedding-107m-multilingual` model, which is a 107M parameter dense biencoder embedding model that generates high-quality text embeddings. This model produces embedding vectors of size 384 and is trained using a combination of open source relevance-pair datasets and IBM collected/generated datasets.
* Added `granite-embedding-125m-english` model, which is a 125M parameter dense biencoder embedding model that generates high-quality text embeddings. This model also produces embedding vectors of size 384 and is trained using similar datasets and …
> chore(model gallery): add granite embeddings models

- backend/python/diffusers/requirements-intel.txt
> Revert "chore(deps): Bump intel-extension-for-pytorch from 2.3.110+xpu to 2.6.10+xpu in /backend/python/diffusers"

- gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, introducing a new model entry for "Deductive Reasoning Qwen 32B". The most important change is the addition of this new model with its associated metadata and file information.
* Added a new model entry for "openpipe_deductive-reasoning-qwen-32b" with URLs, description, parameters, and file details.
> chore(model gallery): add openpipe_deductive-reasoning-qwen-32b

- aio/cpu/embeddings.yaml
- aio/cpu/text-to-text.yaml
- aio/cpu/vision.yaml
- aio/gpu-8g/embeddings.yaml
- aio/gpu-8g/text-to-text.yaml
- aio/gpu-8g/vision.yaml
- aio/intel/embeddings.yaml
- aio/intel/text-to-text.yaml
- aio/intel/vision.yaml
This PR updates the default models pulled by the AIO images.
cpu:
- text-to-text: llama3.1
- embeddings: granite-embeddings
- vision: ~moondream2~ minicpm. See: https://github.com/ggml-org/llama.cpp/pull/12322#issuecomment-2717483759
gpu/intel:
- text-to-text: localai-functioncall-qwen2.5-7b-v0.5
- embeddings: granite-embeddings
- vision: minicpm
> feat(aio): update AIO image defaults

- backend/cpp/llama/grpc-server.cpp
Until a better solution is found upstream, be conservative and default to GPU.
https://github.com/ggml-org/llama.cpp/pull/12322
https://github.com/ggml-org/llama.cpp/pull/12322#issuecomment-2720970695
This PR slows things on GPU (clip on gpu makes it to run much faster!), however it breaks non-GPU usage.
> fix(clip): do not imply GPU offload by default

- Dockerfile
devcontainer clean builds had issue with git-lfs not being present within the image.
Since the package isn't that large (~11 megs) -- see: https://packages.ubuntu.com/search?keywords=git-lfs I think it makes the most sense to put it in every image - that way we don't need to hunt this issue down again in the future.
> fix: ensure git-lfs is present

- core/cli/run.go
- core/config/backend_config.go
- core/config/gguf.go
- core/config/guesser.go
This PR adds detection of context size for gguf files. It also drop defaults via cmd line to 512 (increase to 1024)
> feat(gguf): guess default context size from file

- backend/cpp/llama/grpc-server.cpp
This PR adds sighandling to the llama.cpp backend to terminate gracefully on sigterms
> fix(llama.cpp): properly handle sigterm

- main.go
This pull request includes a small change to the `main.go` file. The change removes the `remoteLibraryURL` variable from the `kong.Vars` map. 
* [`main.go`](diffhunk://#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261L78): Removed the `remoteLibraryURL` variable from the `kong.Vars` map.
> chore: drop remoteLibraryURL from kong vars

- core/application/application.go
- core/application/startup.go
- core/backend/embeddings.go
- core/backend/image.go
- core/backend/llm.go
- core/backend/options.go
- core/backend/rerank.go
- core/backend/soundgeneration.go
- core/backend/token_metrics.go
- core/backend/tokenize.go
- core/backend/transcript.go
- core/backend/tts.go
- core/backend/vad.go
- core/cli/soundgeneration.go
- core/cli/transcript.go
- core/cli/tts.go
- core/http/endpoints/localai/stores.go
- core/http/endpoints/openai/assistant_test.go
- core/http/routes/localai.go
- pkg/model/initializers.go
- pkg/model/loader.go
- pkg/model/loader_options.go
- pkg/model/loader_test.go
- tests/integration/stores_test.go
This PR tries to increase stability when using single active backend option
> feat(loader): enhance single active backend by treating as singleton

- core/http/elements/gallery.go
This pull request includes changes to the `modelModal` function in the `core/http/elements/gallery.go` file to enhance the modal's appearance and functionality. The most important changes include adjustments to the modal's layout, styling, and behavior. It fixes a small issue where if you close the modal, you can't anymore scroll the view.
Changes to modal layout and styling:
* Updated the modal container class to include a background overlay and ensure the modal takes up the full height of the viewport. (`core/http/elements/gallery.go`, [core/http/elements/gallery.goL125-R133](diffhunk://#diff-8a3536c90bd0029f02fd916e18743f96e871cf999f68dbad35d3829f6534a3c8L125-R133))
* Modified the inner container class to set a fixed height and center the modal vertically. …
> fix(webui): improve model display, do not block view

- Makefile
- backend/cpp/llama/Makefile
This PR supercedes https://github.com/mudler/LocalAI/pull/5136
> chore(deps): bump llama.cpp to `4ccea213bc629c4eef7b520f7f6c59ce9bbdaca0`

- backend/go/image/stablediffusion-ggml/Makefile
Signed-off-by: Richard Palethorpe <io@richiejp.com>
THIS TIME!
> fix(stablediffusion): Avoid overwriting SYCL specific flags from outer make call

- core/config/backend_config.go
This PR fixes model chooser in TTS web page. Now is possible to select and successfully use bark-cpp-small
After the fix:
Before this fix bark-cpp-small is not listed in the dropdown menu and can't be used.
Tested on latest 2.28.0
> fix: bark-cpp: assign FLAG_TTS to bark-cpp backend

- .github/workflows/image.yml
This pull request updates the `.github/workflows/image.yml` file to include new `latest-image` tags for various GPU configurations. These changes ensure that the workflow explicitly specifies the appropriate latest image for each build type.
* Added `latest-image: 'latest-gpu-hipblas-core'` for the `hipblas` build type.
* Added `latest-image: 'latest-gpu-intel-f16-core'` for the `sycl_f32` build type.
* Added `latest-image: 'latest-gpu-intel-f32-core'` for an additional Intel GPU configuration.
* Added `latest-image: 'latest-gpu-nvidia-cuda-12-core'` for the `cublas` build type.
* Added `latest-image: 'latest-gpu-vulkan-core'` for the `vulkan` build type.
> chore(ci): add latest images for core

- core/http/static/talk.js
This PR fixes failing LLM request in Talk Interface.
Since de81b42 the Content-Type header has not been sent for the text generation request in the Talk Interface.
> fix(talk): Talk interface sends content-type headers to chatgpt

- docs/static/install.sh
This PR fixes #2865 
You can now pass `--uninstall` to the script to remove LocalAI entirely.
> feat(install.sh): allow to uninstall with --uninstall

- gallery/index.yaml
This pull request adds a new entry in the `gallery/index.yaml` file for a code reasoning language model, `Pictor-1338-QwenP-1.5B`. The entry includes metadata, descriptions, and file details for the model.
* **Model Metadata**: Added `Pictor-1338-QwenP-1.5B` with an icon, multiple URLs, and a detailed description highlighting its features, such as code reasoning, multi-language support, and debugging capabilities.
* **Overrides and Files**: Defined the model's parameters and associated file information, including the filename, SHA-256 checksum, and URI for downloading the model.
> chore(model gallery): add pictor-1338-qwenp-1.5b

- backend/cpp/llama/grpc-server.cpp
- backend/python/autogptq/backend.py
- backend/python/bark/backend.py
- backend/python/coqui/backend.py
- backend/python/diffusers/backend.py
- backend/python/exllama2/backend.py
- backend/python/faster-whisper/backend.py
- backend/python/kokoro/backend.py
- backend/python/rerankers/backend.py
- backend/python/transformers/backend.py
- backend/python/vllm/backend.py
- pkg/grpc/client.go
- pkg/grpc/server.go
This pull request introduces changes to ensure consistent gRPC message size limits across various backends and client implementations. The updates set maximum message sizes to 50MB for sending, receiving, and overall message length. These changes improve the handling of large payloads and prevent errors caused by exceeding default gRPC limits.
* **C++ Backend (`grpc-server.cpp`)**: Added `SetMaxMessageSize`, `SetMaxSendMessageSize`, and `SetMaxReceiveMessageSize` to set the maximum gRPC message size to 50MB.
* **Python Backends**:
- Updated `serve` functions in multiple files (e.g., `autogptq`, `bark`, `coqui`, `diffusers`, `exllama2`, `faster-whisper`, `kokoro`, `rerankers`, `transformers`, `vllm`) to include gRPC options for `max_message_length`, …
> chore: bump grpc limits to 50MB

- docs/static/install.sh
Description
This PR improves the installation script by addressing compatibility and clarity issues:
1. Renamed VERSION to LOCALAI_VERSION to prevent conflicts with system variables.
2. Enhanced NVIDIA and CUDA repository setup for DNF5 compatibility.
3. Revised Fedora version handling for CUDA installations.
4. Standardized the use of LOCALAI_VERSION for Docker image tags.
5. Improved logging for repository and binary downloads.
6. Added a temporary bypass for nvidia-smi installation on Fedora Cloud Edition.
Compatibility with Fedora 41 and later (handling of newer dnf5 instead of dnf4)
Unclear errors when launching the installation script on a headless Fedora setup.
Notes for Reviewers
This is a WIP that atleast dosn't fail with an unclear error anymore on a Fedora Cloud …
> fix: installation script compatibility with fedora 41 and later, fedora headless unclear errors

- backend/python/bark/requirements.txt
- backend/python/common/template/requirements.txt
- backend/python/coqui/requirements.txt
- backend/python/diffusers/requirements.txt
- backend/python/exllama2/requirements.txt
- backend/python/faster-whisper/requirements.txt
- backend/python/kokoro/requirements.txt
- backend/python/rerankers/requirements.txt
- backend/python/transformers/requirements.txt
- backend/python/vllm/requirements.txt
This pull request updates the `grpcio` library from version `1.71.0` to `1.72.0` across multiple Python backend requirement files to ensure consistency and take advantage of the latest fixes and improvements.
Dependency updates:
* Updated `grpcio` to version `1.72.0` in the following requirement files:
- `backend/python/bark/requirements.txt`
- `backend/python/common/template/requirements.txt`
- `backend/python/coqui/requirements.txt`
- `backend/python/diffusers/requirements.txt`
- `backend/python/exllama2/requirements.txt`
- `backend/python/faster-whisper/requirements.txt`
- `backend/python/kokoro/requirements.txt`
- `backend/python/rerankers/requirements.txt`
- `backend/python/transformers/requirements.txt`
- `backend/python/vllm/requirements.txt` …
> chore(deps): bump grpcio to 1.72.0

- core/config/guesser.go
- pkg/model/initializers.go
- pkg/xsysinfo/gpu.go
This PR fixes https://github.com/mudler/LocalAI/issues/4815
We try to guess if we have GPUs and we set `options` gpu if not already configured. guessing of defaults can be always disabled with `LOCALAI_DISABLE_GUESSING=true`
> feat(llama.cpp/clip): inject gpu options if we detect GPUs

- docs/content/docs/features/GPU-acceleration.md
This PR adds documentation for work already done in #1647
I did not actually get cuda + Docker working, so the note in the doc is a best guess for how to pass the nvidia GPU to the container.
> docs(Vulkan): Add GPU docker documentation for Vulkan

- docs/content/docs/features/GPU-acceleration.md
Add documentation note for how to fix SELinux policies to allow passing nvidia GPU to docker
Also updates the cuda image pointer since the `latest` tag is no longer supported per the nvidia/cuda description.
Sneaks in some whitespace cleanup. I can remove that commit if not desired. 
> fix(CUDA):Add note for how to run CUDA with SELinux

- gallery/index.yaml
This pull request adds a new entry for the Qwen3-14B model to the `gallery/index.yaml` file, providing detailed metadata and descriptions for the model.
* Added a new entry for the Qwen3-14B model, including its name, URLs, description, and key features such as reasoning capabilities, multilingual support, and agent capabilities. The description highlights its ability to switch between thinking and non-thinking modes, superior human preference alignment, and strong performance in multilingual tasks.
* Included specific technical details for Qwen3-14B, such as the number of parameters (14.8B total, 13.2B non-embedding), number of layers (40), attention heads, and context length (32,768 natively, extendable to 131,072 with YaRN).
* Added file metadata for Qwen3-14B, …
> chore(model gallery): add qwen3-14b

- backend/python/diffusers/backend.py
this PR fixes a shortcoming with #5243 where we inject the gpu option by default if we detect gpus. Diffusers was taking for granted that options are of key/value, but that is not always the case.
> fix(diffusers): consider options only in form of key/value

- gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, introducing the "Fast-Math-Qwen3-14B" model with detailed metadata and performance improvements.
* A new model, "Fast-Math-Qwen3-14B," has been added to the gallery. This model is an efficiency-optimized version of Qwen3-14B, offering approximately 65% faster inference on average with minimal performance loss.
* Metadata includes:
- URLs for accessing the model on Hugging Face.
- A detailed description of the model's development, performance enhancements, and technical specifics.
- File information with a SHA-256 checksum and URI for downloading the model.
> chore(model gallery): add fast-math-qwen3-14b

- .env
- Makefile
- backend/cpp/llama/Makefile
- backend/cpp/llama/grpc-server.cpp
- backend/cpp/llama/patches/01-llava.patch
- backend/cpp/llama/prepare.sh
- backend/cpp/llama/utils.hpp
> chore(deps): bump llama.cpp to '1d36b3670b285e69e58b9d687c770a2a0a192194

- core/backend/options.go
- core/config/backend_config.go
This PR is a follow-up of https://github.com/mudler/LocalAI/pull/5299
> chore(defaults): enlarge defaults, drop gpu layers which is infered

- core/config/gguf.go
- pkg/xsysinfo/gpu.go
This pull request includes changes to improve error handling and ensure robustness in VRAM estimation logic. The updates focus on adding checks for nil values and refining conditions to handle edge cases.
* [`core/config/gguf.go`](diffhunk://#diff-bdc83435b880ad06671e5db75945668b47a68de007cac1238fd69ec7ad26a5c3L173-R173): Updated the `guessGGUFFromFile` function to only estimate VRAM usage if the available VRAM is greater than zero, preventing unnecessary operations when VRAM is unavailable.
* [`pkg/xsysinfo/gpu.go`](diffhunk://#diff-38514486650e23ed983a536f6ec9220e87671665dc9061c762bcef65fc7b8defR27-R32): Enhanced the `TotalAvailableVRAM` function by adding checks to ensure that `gpu`, `gpu.Node`, and `gpu.Node.Memory` are not nil before accessing their properties, …
> fix(gpu): do not assume gpu being returned has node and mem

- Dockerfile
We don't need to build these optimized versions as not available on arm64
> fix(arm64): do not build instructions which are not available

- .github/workflows/bump_deps.yaml
- Makefile
- backend/go/transcribe/whisper/whisper.go
This PR fixes https://github.com/mudler/LocalAI/issues/5315 and supercedes https://github.com/mudler/LocalAI/pull/4785.
It brings whisper.cpp up-to-date and adapts to the new build changes
> chore(deps): bump whisper.cpp

- .github/workflows/image-pr.yml
- Makefile
This is a follow up of https://github.com/mudler/LocalAI/issues/5315 and https://github.com/mudler/LocalAI/pull/5338 , by enabling acceleration support for sycl and hipblas we found out later on builds in master that things were not working right, this is because only master runs builds with sycl and hipblas (to avoid to consume too many CI resources).
This PR also re-enables hipblas, vulkan and sycl testing in PRs so we can catch that early on.
whisper acceleration is supported on (with this PR):
- vulkan
- cuda
- Metal
Not yet:
- sycl
- hipblas
> feat(whisper.cpp): gpu support

- README.md
- docs/content/docs/advanced/installer.md
- docs/content/docs/getting-started/container-images.md
- docs/static/install.sh
This PR updates docs around the latest image changes.
This pull request introduces significant updates to the documentation and installation script for LocalAI, with a focus on supporting additional GPU configurations, simplifying image selection, and improving usability. The changes include new Docker image tags for various GPU types, updates to environment variables, and enhancements to the installation script to handle these new options.
* Expanded Docker image options to include support for Vulkan, Intel, AMD, and NVIDIA GPUs with both core and "extras" variants (e.g., `latest-gpu-vulkan`, `latest-gpu-intel-f16-extras`). Added AIO (all-in-one) images for pre-downloaded models. (`README.md`, `docs/content/docs/getting-started/container-images.md`) …
> chore(docs/install.sh): image changes

- pkg/xsysinfo/gpu.go
This pull request introduces a caching mechanism to the `GPUs` function in the `pkg/xsysinfo/gpu.go` file to improve performance by ensuring GPU information is only fetched once. The most important changes are as follows:
* Introduced a `sync.Once` variable (`gpuCacheOnce`) to ensure the GPU information is fetched only once, even in concurrent scenarios.
* Added a `gpuCache` variable to store the cached GPU information and a `gpuCacheErr` variable to store any errors encountered during the fetch.
* Modified the `GPUs` function to use the `sync.Once` mechanism to populate the cache on the first call and return the cached data or error on subsequent calls.
> chore: memoize detected GPUs

- core/http/endpoints/localai/gallery.go
- core/http/routes/ui.go
- core/http/views/error.html
This PR allows to visualize errors and surface them when needed from the UI
> feat(ui): add error page to display errors

- docs/content/docs/advanced/fine-tuning.md
…irrors how modern version of llama.cpp operate
This PR fixes #5418 
There's one small issue in the last steps.  It depends on what you're building to how the Merged model will appear.  I used the version name for the 32B model I was working with (Qwen 2.5 32B).
**X/Twitter handle:** @thedarktrumpet
> updating the documentation on fine tuning and advanced guide. 

- backend/backend.proto
- backend/cpp/llama/grpc-server.cpp
- backend/go/llm/llama/llama.go
- core/backend/options.go
- core/config/backend_config.go
This PR supersedes #4958 
Not tested yet, but compiles succesfully
> feat(llama.cpp): add reranking

- backend/cpp/llama/grpc-server.cpp
- core/http/middleware/request.go
- pkg/templates/multimodal.go
- pkg/templates/multimodal_test.go
Thanks to @ngxson (thanks! :heart:  ) in https://github.com/ggml-org/llama.cpp/pull/13714 llama.cpp now supports audio input. This PR is to extend audio input support also to the llama.cpp backend in LocalAI.
> feat(llama.cpp): add support for audio input

- gallery/index.yaml
This PR adds qwen 2.5 omni, with both image and audio input support. 
Audio example:
```
curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{               
"model": "qwen-omni",                                                                                                                                                                                           
"messages": [{"role": "user", "content": [{"type":"text", "text": "What is this audio?"}, {"type": "audio_url", "audio_url": {"url": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Alcal%C3%A1_de_Henares
_%28RPS_13-04-2024%29_canto_de_ruise%C3%B1or_%28Luscinia_megarhynchos%29_en_el_Soto_del_Henares.wav" }}], "temperature": 0.9}]}' …
```
> chore(model gallery): add qwen2.5-omni-7b

- core/http/static/chat.js
- core/http/views/chat.html
- go.mod
- go.sum
- pkg/utils/base64.go
> feat(ui): add audio upload button in chat view

- core/backend/llm.go
- core/http/static/chat.js
- core/http/views/chat.html
This PR fixes https://github.com/mudler/LocalAI/issues/4761
Part of #2156 
Depends on https://github.com/mudler/LocalAI/pull/5539
> feat(ui): display thinking tags appropriately

- .github/workflows/release.yaml
- Dockerfile
> fix(ci): try to add different mirrors to avoid 403 issues

- gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The addition includes detailed information about the model, its purpose, and usage parameters.
* Added a new model entry for `e-n-v-y_legion-v2.1-llama-70b-elarablated-v0.8-hf`. This model was fine-tuned using a process called "Elarablation" to reduce repetitiveness and improve creative writing output. The entry includes metadata such as URLs, a detailed description, tested settings, and associated file information.
> chore(model gallery): add e-n-v-y_legion-v2.1-llama-70b-elarablated-v0.8-hf

- .github/workflows/test.yml
- Dockerfile
- backend/python/bark/requirements.txt
- backend/python/chatterbox/requirements.txt
- backend/python/common/template/requirements.txt
- backend/python/coqui/requirements.txt
- backend/python/diffusers/requirements.txt
- backend/python/exllama2/requirements.txt
- backend/python/faster-whisper/requirements.txt
- backend/python/kokoro/requirements.txt
- backend/python/rerankers/requirements.txt
- backend/python/transformers/requirements.txt
- backend/python/vllm/requirements.txt
This PR pins grpcio both in Dockerfiles, tests and in the backends
> fix(deps): pin grpcio

- pkg/functions/parse.go
Description:  
This pull request updates comments and documentation in the `pkg/functions/parse.go` file to improve clarity and readability. Specifically, it:
- Refines the explanation for the `MixedMode` and `NoMixedFreeString` configuration options, making the descriptions more precise and easier to understand.
- Fixes minor wording issues (e.g., "constraining" and "necessarily").
- Updates the comment for the `ParseJSON` function to clarify that it is a slightly reworked version for improved readability and error handling.
No functional code changes are introduced; this PR is focused solely on documentation and comment improvements.
> Improve Comments and Documentation for MixedMode and ParseJSON Functions

- pkg/grpc/base/base.go
- pkg/model/initializers.go
Description:  
This pull request corrects minor spelling mistakes in the codebase:
- Fixed the typo "statisfy" to "satisfy" in a comment within pkg/grpc/base/base.go.
- Corrected "refering" to "referring" in an error message in pkg/model/initializers.go.
These changes improve code readability and maintain professionalism in comments and error outputs. No functional code was altered.
> Fix Typos in Comments and Error Messages

- core/p2p/p2p.go
- docs/content/docs/features/GPU-acceleration.md
Description:  
This pull request addresses several minor issues in the codebase and documentation:
- Corrects English typos such as "informations" to "information" and "additonal" to "additional".
- Improves clarity in documentation by fixing annotation spelling and formatting.
- Updates comments and documentation for better readability and accuracy.
> Fix Typos and Improve Documentation Clarity

- backend/python/kokoro/istftnet.py
- docs/content/docs/features/GPU-acceleration.md
This pull request corrects several typographical errors in both the Python backend and documentation files. Specifically, it fixes the spelling of "integer" in a code comment within backend/python/kokoro/istftnet.py, and corrects "gauranteed" to "guaranteed" and "milage" to "mileage" in docs/content/docs/features/GPU-acceleration.md. These changes improve the clarity and professionalism of the codebase and documentation.
> Fix Typos in Documentation and Python Comments

- core/gallery/backends.go
- pkg/downloader/uri.go
- pkg/oci/image.go
- pkg/oci/image_test.go
This PR adds reporting of downloading status when downloading OCI images
> feat(backend gallery): display download progress

- docs/content/docs/features/GPU-acceleration.md
- docs/content/docs/features/image-generation.md
**Description:**
```markdown
This PR addresses minor typographical errors in the documentation.
- Corrected "availible" to "available" in `docs/content/docs/features/gpu-acceleration.md`.
- Corrected "suppoorted" to "supported" in `docs/content/docs/features/image-generation.md`.
```
> Docs: Fix typos

- core/gallery/backend_types.go
- core/gallery/backends.go
- core/gallery/backends_test.go
- core/http/app.go
- core/services/backends.go
- core/services/gallery.go
- core/system/capabilities.go
- pkg/startup/backend_preload.go
So we can have meta packages such as "vllm" that automatically installs the corresponding package depending on the GPU that is being currently detected in the system.
> feat(backend gallery): add meta packages

- .github/workflows/image-pr.yml
- .github/workflows/image.yml
- .github/workflows/image_build.yml
- docs/content/docs/features/GPU-acceleration.md
- docs/content/docs/getting-started/container-images.md
- docs/content/docs/whats-new.md
- docs/static/install.sh
Also uniform tagging names, instead of having `cublas-cuda` images and `sycl`, now all images defaults with its corresponding latest tag:
- `gpu-nvidia-cuda11` and `gpu-nvidia-cuda12` instead of `cublas-cuda11` and `cublas-cuda12`
- `gpu-intel-f16` and `gpu-intel-f32` instead of `sycl-f16` and `sycl-f32`
Should fix #5720
> chore(ci): :warning: fix latest tag by using docker meta action

- Dockerfile
- aio/entrypoint.sh
- docs/content/docs/features/GPU-acceleration.md
- docs/content/docs/getting-started/container-images.md
- docs/content/docs/reference/nvidia-l4t.md
- docs/static/install.sh
- entrypoint.sh
Do not copy sources anymore, and reduce packages of the base images by not using builder images.
If needed to rebuild, just build the container image from scratch by following the docs. We will slowly try to migrate all backends to the gallery to keep the core small.
:warning:  This PR is a breaking change, it also sets the base folders to /models and /backends instead of /build/models and /build/backends.
> feat: :warning:  reduce images size and stop bundling sources

- gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, introducing the Gemma 3n family of models. These models are lightweight, multimodal, and optimized for low-resource devices, with open weights and efficient parameter activation technology.
* **New model entry (`gemma-3n-e2b-it`)**: Added a description, URLs, and file details for the Gemma 3n models, which are designed for efficient execution on low-resource devices and support multimodal input (text, image, video, and audio). These models leverage selective parameter activation to reduce resource requirements while maintaining high performance.
> chore(model gallery): add gemma-3n-e2b-it

- .github/workflows/backend.yml
- .github/workflows/backend_build.yml
> fix(ci): better handling of latest images for backends

- core/gallery/backend_types.go
This PR fixes a corner case when defining galleries with YAML anchors. Meta packages ideally should be first, and using these as anchors will result in all subsequent to be considered metas (even if having URIs).
> fix(backends gallery): meta packages do not have URIs

- backend/backend.proto
- backend/cpp/llama/grpc-server.cpp
- core/backend/options.go
- core/config/backend_config.go
> feat(llama.cpp): allow to set kv-overrides

- Makefile
Signed-off-by: Richard Palethorpe <io@richiejp.com>
This enables Whisper's SYCL support
The linker flags added for the benefit of CGO could be overkill, but it is a real pain finding the exact minimum set of flags. For some reason it is quite different from stablediffusion even though the both use the GGML SYCL support.
> feat(whisper): Enable SYCL

- core/cli/backends.go
- core/gallery/backends.go
- pkg/downloader/uri.go
- pkg/startup/backend_preload.go
This PR allows to install backends locally, for instance:
```
docker build --build-arg BACKEND=llama-cpp -t llama-cpp-backend -f backend/Dockerfile.llama-cpp .
docker save llama-cpp-backend -o llama-backend.tar
local-ai backends install "ocifile://$PWD/llama-backend.tar"
```
It also now avoid duplication of commands when installing things locally or not, it will work the same across the codebase (hence why more removals).
This is needed in order to go ahead with https://github.com/mudler/LocalAI/pull/5790 - we need to build some backends on-the-fly to run CI tests.
> feat(cli): allow to install backends from OCI tar files

- core/cli/util.go
- pkg/oci/tarball.go
This PR introduces a new command, `local-ai util create-oci-image` , in the CLI to allow to create OCI images directly from source files or directory. this can be really handy to create backends for platforms that do not support docker natively such as macOS on arm64. This is required for https://github.com/mudler/LocalAI/pull/5790 in order to package the backend as OCI images (but the CI can't run docker on the first place).
How to use:
```
local-ai util create-oci-image --help
Usage: local-ai util create-image <input> ... [flags]
Create an OCI image from a file or a directory
Arguments:
<input> ...    Input file or directory to create an OCI image from
Flags:
-h, --help                      Show context-sensitive help.
--log-level=LOG-LEVEL       Set the level of logs to …
```
> feat(cli): add command to create custom OCI images from directories

- core/http/endpoints/openai/realtime.go
Adds speech started an stopped events which are useful visually indicating that speech has been detected or that it has stopped and transcription will be starting.
> feat(realtime): Add speech started and stopped events

- .github/workflows/backend.yml
- backend/index.yaml
CI currently fails building flash-attn for cuda 11 and vllm.This PR is about dropping vllm for cuda11. We can try later to re-add it if there is a way to make it work again.
> chore: drop vllm for cuda 11

- .github/workflows/image.yml
- Dockerfile
- Makefile
It seems like I got distracted and did not actually commit these changes to the last intel PR.
This changes the build type from sycl to intel for the core. The backends are unaffected.
> chore(build): Rename sycl to intel

- .github/workflows/backend.yml
- backend/python/diffusers/requirements-cpu.txt
- backend/python/diffusers/requirements-cublas11.txt
- backend/python/diffusers/requirements-cublas12.txt
- backend/python/diffusers/requirements-hipblas.txt
- backend/python/diffusers/requirements-intel.txt
This PR bumps torch and diffusers to latest, so that should bring support for Qwen Image.
> chore(deps): bump torch and diffusers

- gallery/harmony.yaml
This PR tweaks the harmony prompt such as respect the reasoning effort coming from the API (introduced in #5981) and the system prompt from the metadata (`system_prompt` field).
> fix(harmony): improve template by adding reasoning effort and system_prompt

- backend/cpp/llama-cpp/Makefile
- backend/cpp/llama-cpp/grpc-server.cpp
This PR supersedes https://github.com/mudler/LocalAI/pull/6061
> chore(deps): bump llama.cpp to 'df36bce667bf14f8e538645547754386f9516326

- core/http/static/general.css
This PR fixes the `li` font color used in Chat prompts. The previous text color was barely readable as it was too close to the background color.
> Tune the "dark gray" font color in the webui to make it more readable

- backend/python/diffusers/requirements-cpu.txt
- backend/python/diffusers/requirements-cublas11.txt
- backend/python/diffusers/requirements-cublas12.txt
- backend/python/diffusers/requirements-l4t.txt
Qwen-image-edit was released, and currently fails in LocalAI with:
```
8:03AM ERR Server error error="failed to load model with internal loader: could not load model (no success): Unexpected err=ImportError('\\nAutoVideoProcessor requires the Torchvision library but it was not found in your environment. Check out the instructions on the\\ninstallation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.\\nPlease note that you may need to restart your runtime after installation.\\n'), type(err)=<class 'ImportError'>" ip=172.20.0.2 latency=2m13.109201857s method=POST status=500 url=/v1/images/generations
```
This PR adds torchvision as it is required for Qwen-image-edit.
**[Signed …
> feat(diffusers): add torchvision to support qwen-image-edit

- .github/workflows/backend_build_darwin.yml
- Makefile
- backend/index.yaml
- backend/python/diffusers/requirements-mps.txt
- backend/python/diffusers/run.sh
This PR adds diffusers for MacOS with mps
> feat(diffusers): add MPS version

- gallery/index.yaml
This pull request adds new model definitions for the InternVL3.5 multimodal family to the `gallery/index.yaml` file. The changes introduce support for different quantization levels of the InternVL3.5-30B-A3B model, including associated metadata, download URLs, and file references.
**Model additions and configuration:**
* Added a new entry (`internvl35`) for the `opengvlab_internvl3_5-30b-a3b` model, including metadata such as description, tags, license, and links to Hugging Face resources.
* Defined model-specific overrides for parameters and projection files, specifying the default quantization (`Q4_K_M`) and associated file hashes and URIs.
**Support for multiple quantization levels:**
* Introduced a merged variant for the `opengvlab_internvl3_5-30b-a3b-q8_0` model, …
> chore(model gallery): add opengvlab_internvl3_5-30b-a3b

- core/http/endpoints/localai/edit_model.go
- core/http/routes/localai.go
- core/http/views/index.html
New Feature
* Adds a dedicated ReloadModelsEndpoint at /models/reload
* Add UI element on welcome page to call the reload endpoin
> feat: Add a model refresh button to manually refresh on-disk yaml

- backend/python/common/libbackend.sh
This PR starts the portable python environment if we find out that the binary in the backend exist
> fix: select portable environment if detected

- core/http/endpoints/openai/chat.go
- core/http/endpoints/openai/completion.go
Otherwise these are silently absorbed in the background
> chore: stream errors while streaming SSE

- backend/go/stablediffusion-ggml/.gitignore
- backend/go/stablediffusion-ggml/Makefile
- backend/go/stablediffusion-ggml/gosd.cpp
- **:arrow_up: Update leejet/stable-diffusion.cpp**
- **fix(stablediffusion-ggml): Use new sample_params_t**
Fix for PR #6208 because I can't seem to push directly to that PR.
> chore: ⬆️ Update leejet/stable-diffusion.cpp to d7f430cd693f2e12ecbaa0ce881746cf305c3b1f

- Makefile
- backend/cpp/llama-cpp/grpc-server.cpp
- core/http/app_test.go
- core/http/http_suite_test.go
- tests/e2e-aio/e2e_test.go
~~This PR is to add a test to validate #6257 specifically for the llama.cpp backend. We have this test for sentencetransformers just a couple of lines below, but somehow seems we missed applying it to llama.cpp~~
Seems the bug is confirmed. It looks like we did had a regression while we migrated to the new mtmd/context server. We were incorrectly returning always a static embedding vector in the embedding calls with the llama.cpp backend.
Fixes #6257 
> fix(llama-cpp): correctly calculate embeddings

- backend/go/stablediffusion-ggml/Makefile
- backend/go/stablediffusion-ggml/gosd.cpp
- backend/go/stablediffusion-ggml/gosd.go
- backend/go/stablediffusion-ggml/gosd.h
- backend/go/stablediffusion-ggml/main.go
- **:arrow_up: Update leejet/stable-diffusion.cpp**
- **fix(stablediffusion-ggml): Move parameters and start refactor of passing params**
Supersedes: #6264
Also I started refactoring how params are passed because we are running out of arguments when calling C functions and populating C structs from Go is a pain unless they are carefully constructed to have an obvious memory layout.
So this adds some setters for VAE params which presently can't be configured. The setters are called from Go on the various param structs. This adds a lot of boiler plate, but I don't see a nice alternative.
> chore: ⬆️ Update leejet/stable-diffusion.cpp to 0ebe6fe118f125665939b27c89f34ed38716bff8

- backend/python/diffusers/backend.py
There was apparently an oversight, this fixes the float/int detection
Fixes: https://github.com/mudler/LocalAI/issues/6312
> fix(diffusers): fix float detection

- .github/workflows/image-pr.yml
Removed configuration for cublas and arm64 platform to streamline CI builds.
> CI: disable build-testing on PRs against arm64

- backend/cpp/llama-cpp/grpc-server.cpp
I discovered a bug with how llamacpp's grcp backend is implemented in LocalAI.  Basically the batch parameter is exposed in the LocalAI model yaml file but this only changes the n_batch parameter in llama.cpp.  When trying to run a reranking model in llama.cpp, it sometimes complains that the prompt input is larger than the maximum physical batch size.  The default is 512 tokens and set by n_ubatch, not by n_batch.  I fixed it by making the batch value from the model yaml file change both the n_batch and n_ubatch parameters in llamacpp.  
> fix: reranking models limited to 512 tokens in llama.cpp backend

- backend/cpp/llama-cpp/CMakeLists.txt
- backend/cpp/llama-cpp/Makefile
This PR supersedes #6345 
See https://github.com/ggml-org/llama.cpp/issues/16285 for the upstream issue (it seems that it was not added to upstream cmake targets too?)
> chore(deps): bump llama.cpp to '72b24d96c6888c609d562779a23787304ae4609c'

- core/config/model_config.go
- core/http/endpoints/openai/mcp.go
- docs/content/docs/features/mcp.md
This pull request introduces a new `agent` configuration section for the Model Context Protocol (MCP) feature, allowing fine-grained control over agent behavior and tool execution. It adds support for advanced reasoning, re-evaluation, and customizable limits on execution attempts and iterations. The changes span configuration structures, endpoint logic, and documentation.
The most important changes are:
**Agent configuration support:**
* Added an `AgentConfig` struct to `ModelConfig`, with fields for `max_attempts`, `max_iterations`, `enable_reasoning`, and `enable_re_evaluation` to control agent behavior and reasoning capabilities.
* Updated the MCP completion endpoint to use the new `agent` config values for tool execution, reasoning, and re-evaluation, falling back to …
> feat: add agent options to model config

- core/http/routes/openai.go
This PR makes sure we support routes with and without `/v1` prefix.
> feat(api): support both /v1 and not on openai routes
