gallery/index.yaml
This pull request adds a new language model entry to the `gallery/index.yaml` file. The new model, named "L3.1-Aspire-Heart-Matrix-8B," is an experimental language model created by merging three high-quality 8B parameter models using the Model Stock Merge method.
* Added a new model entry named "L3.1-Aspire-Heart-Matrix-8B" with a detailed description.
* Included URLs for the new model hosted on Hugging Face.
* Specified the parameters and files associated with the new model.
=> chore(model): add l3.1-aspire-heart-matrix-8b to the gallery

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model, named "dark-chivalry_v1.0-i1", includes metadata such as its name, icon, URLs, description, and file details.
* Added a new model entry "dark-chivalry_v1.0-i1" with associated metadata, including name, icon, URLs, description, and file details.
=> chore(model): add dark-chivalry_v1.0-i1 to the gallery

gallery/index.yaml
This pull request includes a new model entry in the `gallery/index.yaml` file. The change adds a merged model named "tulu-3.1-8b-supernova-i1" with its associated URLs, description, parameters, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3074-R3090): Added a new model "tulu-3.1-8b-supernova-i1" with URLs, description of included models, parameters, and file details.
=> chore(model): add tulu-3.1-8b-supernova-i1 to the gallery

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `SteyrCannon-0.2-Qwen2.5-72b`. The most important changes include the addition of the new model's metadata, URLs, description, and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1543-R1559): Added a new model entry for `SteyrCannon-0.2-Qwen2.5-72b` with its metadata, description, URLs, and file information.
=> chore(model): add steyrcannon-0.2-qwen2.5-72b to the gallery

Makefile, backend/cpp/llama/grpc-server.cpp
=> chore(deps): bump llama.cpp to `47f931c8f9a26c072d71224bc8013cc66ea9e445`

scripts/model_gallery_info.py
This pull request includes an important change to the `scripts/model_gallery_info.py` file to improve error handling when summarizing the README file.
Error handling improvement:
* [`scripts/model_gallery_info.py`](diffhunk://#diff-15eba38ea822869bbf05c6f29c475fd50d0e043282680ecc687be674d7b4bb34R106-R109): Added a try-except block around the `summarize` function call to catch and print any exceptions that occur, ensuring the script continues to run even if summarizing the README fails.
=> chore(scripts): handle summarization errors

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, introducing a new model entry with detailed metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1598-R1616): Added a new model named "q2.5-ms-mistoria-72b-v2" with associated metadata such as icon, URLs, description, and file details.
=> chore(model): add q2.5-ms-mistoria-72b-v2 model config

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for the `llama-3.1-tulu-3-70b-dpo`. The most important changes include the addition of the model's metadata, description, and file details.
* Added a new model entry `llama-3.1-tulu-3-70b-dpo` with metadata including name, icon, URLs, and description.
* Included file details and parameters for the new model, specifying the filename, sha256 hash, and URI.
=> chore(model): add llama-3.1-tulu-3-70b-dpo model config

gallery/rwkv.yaml, tests/models_fixtures/rwkv.yaml
This pull request includes changes to the stopwords configuration in two YAML files to improve the handling of certain tokens in the chat templates. The most important changes include the addition of the '<s>' token to the stopwords list in both `gallery/rwkv.yaml` and `tests/models_fixtures/rwkv.yaml`.
Changes to stopwords configuration:
* [`gallery/rwkv.yaml`](diffhunk://#diff-ebfe4ef6b3c40343b4994962503c1e156b3b4fe1a001707a76b69fbfd9fec721R19): Added '<s>' to the stopwords list to ensure it is properly filtered out in the chat template.
* [`tests/models_fixtures/rwkv.yaml`](diffhunk://#diff-3b987280e765ec4420fe9c2454e57c906fc477a2acee8b0476e27cdc4d317d81R17): Added '<s>' to the stopwords list to maintain consistency in test fixtures.
**[Signed …
=> fix(rwkv model): add stoptoken

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for `llama-smoltalk-3.2-1b-instruct`. The most important changes include the addition of the model's metadata, description, key features, intended applications, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR707-R731): Added a new model entry for `llama-smoltalk-3.2-1b-instruct` with detailed metadata, including its name, URLs, description, key features, intended applications, and file details.
=> chore(model gallery): add llama-smoltalk-3.2-1b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the new model "freyja-v4.95-maldv-7b-non-fiction-i1" with its relevant details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR7459-R7479): Added a new model "freyja-v4.95-maldv-7b-non-fiction-i1" with URLs, description, parameters, and file information.
=> chore(model gallery): add freyja-v4.95-maldv-7b-non-fiction-i1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "volare-i1". The most important change is the addition of the new model details, including its description, parameters, and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4853-R4869): Added a new model entry for "volare-i1", including its name, URLs, description, parameters, and file information.
=> chore(model gallery): add volare-i1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important changes include adding details for the new model "teleut-7b".
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1713-R1727): Added a new model entry "teleut-7b" with its name, icon, URLs, description, parameters, and file details.
=> chore(model gallery): add teleut-7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "cybercore-qwen-2.1-7b". The changes include the model's name, URLs, description, parameters, and associated files.
* Added a new model entry for "cybercore-qwen-2.1-7b" with details such as name, URLs, description, parameters, and associated files.
=> chore(model gallery): add cybercore-qwen-2.1-7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "Chatty-Harry_V3.0". The most important change is the addition of detailed information about the new model, including its name, icon, URLs, description, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4175-R4191): Added a new model entry for "Chatty-Harry_V3.0" with details such as name, icon, URLs, description, and file information.
=> chore(model gallery): add chatty-harry_v3.0

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, named "HomerCreativeAnvita-Mix-Qw7B," includes detailed information such as its icon, URLs, description, merge method, and files.
Key changes:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1770-R1793): Added a new model entry "HomerCreativeAnvita-Mix-Qw7B" with its associated metadata, including icon URL, description, and file details.
=> chore(model gallery): add homercreativeanvita-mix-qw7b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file with the addition of a new model entry. The most important changes are:
* Added a new model entry named `rp-naughty-v1.0c-8b` with a detailed description and list of included models.
* Provided URLs and file details for the new model, including `filename`, `sha256`, and `uri` attributes.
=> chore(model gallery): add rp-naughty-v1.0c-8b

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new model named "loki-v2.6-8b-1024k" along with its associated metadata and descriptions of merged models.
* Added a new model entry `loki-v2.6-8b-1024k` with an icon URL, description, and a list of merged models.
* Included the model's parameters and file details, such as filename, sha256 checksum, and URI.
=> chore(model gallery): add loki-v2.6-8b-1024k

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new language model entry. The most important change is the addition of the "Math IIO 7B Instruct" model, which is designed for mathematical reasoning and instruction-based tasks.
New language model addition:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1794-R1817): Added the "Math IIO 7B Instruct" model entry with its description, key features, parameters, and file details.
=> chore(model gallery): add math-iio-7b-instruct

docs/content/docs/getting-started/kubernetes.md
Links to deplyment*.yaml was changed
This PR fixes incorrect links.
=> Updated links of yamls

docs/content/docs/reference/compatibility-table.md
This pull request includes updates to the `docs/content/docs/reference/compatibility-table.md` file to expand the compatibility table with additional backends and models, and to improve clarity regarding compatible models and associated repositories.
Updates to compatibility table:
* Clarified that the table lists all backends, compatible models families, and associated repositories.
* Updated the list of compatible models for `llama.cpp` and added an entry for `llama.cpp's ggml model` to ensure backward compatibility with the old format.
* Added new entries for `mamba`, `openvoice`, `parler-tts`, `rerankers`, `bark-cpp`, `stablediffusion-cpp`, and `silero-vad` to the compatibility table.
**[Signed …
=> chore(docs): update available backends

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for Llama 3.3. The most important change is the addition of the Llama 3.3 model with its respective metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2-R24): Added a new entry for the Llama 3.3 model, including its URL, icon, license, description, tags, name, URLs, overrides, and files.
=> chore(model gallery): add llama-3.3-70b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important changes include the addition of a new model named "mn-chunky-lotus-12b" with associated metadata and a description.
* Added a new model entry for "mn-chunky-lotus-12b" with the following details:
* URL: "github:mudler/LocalAI/gallery/chatml.yaml@master"
* Name: "mn-chunky-lotus-12b"
* Icon: A link to the model's image on Hugging Face
* URLs: A list of URLs including the model's Hugging Face page
* Description: Detailed description of the model's performance, characteristics, and the included language models in the merge
* Overrides: Parameters specifying the model file
* Files: Filename, sha256, and URI for the model file
**[Signed …
=> chore(model gallery): add mn-chunky-lotus-12b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model is specialized for biomedical applications and includes detailed metadata.
Key changes:
* Added a new model entry for `bio-medical-llama-3-8b` with metadata including name, icon, URLs, description, and file details.
=> chore(model gallery): add bio-medical-llama-3-8b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry. The most important change is the addition of the Qwen2.5-7B-HomerAnvita-NerdMix model with its associated metadata and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1855-R1868): Added the Qwen2.5-7B-HomerAnvita-NerdMix model, including its name, URLs, description, parameters, and file details.
=> chore(model gallery): add qwen2.5-7b-homeranvita-nerdmix

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model, `tulu-3.1-8b-supernova-smart`, is a merged model with specific parameters and file details.
Key change:
* Added a new model entry `tulu-3.1-8b-supernova-smart` with details including name, URLs, description, parameters, and file information.
=> chore(model gallery): add tulu-3.1-8b-supernova-smart

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file. The change introduces a new entry for the Qwen 2.5 model with specific details and parameters.
Key changes:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1869-R1883): Added a new entry for `qwen2.5-math-14b-instruct` with URLs, description, parameters, and file details.
=> chore(model gallery): add qwen2.5-math-14b-instruct

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file. The change introduces a new AI model called B-NIMITA, designed for role-playing scenarios with emotional depth and rich storytelling.
* Added a new AI model entry for B-NIMITA-L3-8B-v0.02, including its description, URLs, and file details.
=> chore(model gallery): add b-nimita-l3-8b-v0.02

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry for "Sailor2-1B-Chat". The most important changes include adding metadata, description, and file details for the new model.
Addition of new language model:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1909-R1924): Added a new entry for "Sailor2-1B-Chat" with metadata including name, icon, URLs, description, and file details.
=> chore(model gallery): add sailor2-1b-chat

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `Sailor2-8B-Chat`. This new entry provides detailed information about the model, including its description, parameters, and associated files.
Key changes:
* Added a new model entry for `Sailor2-8B-Chat` with a detailed description, icon, and URLs.
* Included parameters and file details for the `Sailor2-8B-Chat-Q4_K_M.gguf` model.
=> chore(model gallery): add sailor2-8b-chat

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry and its associated metadata.
* Added a new model `L3.3-70B-Euryale-v2.3` with its metadata, including name, icon URL, description, parameters, and file details.
=> chore(model gallery): add l3.3-70b-euryale-v2.3

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The change introduces a new model called "l3.3-ms-evayale-70b" with specific details and parameters.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR65-R79): Added a new model entry "l3.3-ms-evayale-70b" with its name, icon, URLs, description, and file details.
=> chore(model gallery): add l3.3-ms-evayale-70b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, FuseChat-3.0, is designed to enhance performance by integrating the strengths of multiple source LLMs into more compact target LLMs. The changes include the model's name, icon, URLs, description, and associated files.
Key changes:
* Added a new model entry `fusechat-qwen-2.5-7b-instruct` to the `gallery/index.yaml` file, including details such as name, icon, URLs, description, and associated files.
=> chore(model gallery): add fusechat-qwen-2.5-7b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The update introduces the Chronos Gold 12B 1.0 model with detailed metadata and description.
* Added Chronos Gold 12B 1.0 model entry with metadata including URL, name, icon, description, and file parameters.
=> chore(model gallery): add chronos-gold-12b-1.0

gallery/index.yaml
DBG YAML errors: line 2025: cannot unmarshal !!str `-https:...` into []string
This PR fixes #4383
=> fix: correct gallery/index.yaml

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `FuseChat-Llama-3.2-3B-Instruct`. The most important changes include adding detailed information about the new model, its sources, and its performance improvements.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR810-R823): Added a new model entry for `FuseChat-Llama-3.2-3B-Instruct`, including its name, URLs, description, parameters, and file details.
=> chore(model gallery): add fusechat-llama-3.2-3b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new multilingual model to the gallery.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2116-R2129): Added the `qwen2-7b-multilingual-rp` model, including its description, URLs, and file details.
=> chore(model gallery): add qwen2-7b-multilingual-rp

Makefile, backend/cpp/llama/grpc-server.cpp
This PR bumps llama.cpp and drops penalize_nl (was removed upstream)
=> chore(llama.cpp): bump, drop penalize_nl

gallery/index.yaml
This pull request includes the addition of a new language model entry to the `gallery/index.yaml` file. The new model, named "QwQ-LCoT-7B-Instruct", is designed for advanced reasoning and instruction-following tasks.
* Added the "QwQ-LCoT-7B-Instruct" model entry, which leverages the Qwen2.5-7B base model and is fine-tuned on the amphora/QwQ-LongCoT-130K dataset. This model focuses on chain-of-thought (CoT) reasoning.
=> chore(model gallery): add qwq-lcot-7b-instruct

gallery/falcon3.yaml, gallery/index.yaml
This pull request introduces a new configuration for the Falcon3 model in the gallery. The changes include adding a new YAML configuration file for Falcon3 and updating the gallery index to reference this new model.
Key changes:
* [`gallery/falcon3.yaml`](diffhunk://#diff-edc28877ec557552ee52b99cd6c78961d0c05a6ded0e7bf678a5e0cfb1ce485bR1-R40): Added a new configuration file for the Falcon3 model, including chat message templates, function calling instructions, and other model parameters.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2-R26): Updated the gallery index to include the Falcon3-1B-Instruct model, along with its metadata, description, and file references.
**[Signed …
=> chore(model gallery): add falcon3-1b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model configuration for Falcon3-3B-Instruct.
New model configuration:
* Added a new entry for `falcon3-3b-instruct` with associated URLs, parameters, and file details.
=> chore(model gallery): add falcon3-3b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "Qwen2-VL-72B-Instruct." The changes include the model's name, URLs, description, and associated parameters and files.
* Added a new model entry for "Qwen2-VL-72B-Instruct" with detailed description, URLs, and parameters.
=> chore(model gallery): add qwen2-vl-72b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry. The new model, `Llama-Song-Stream-3B-Instruct`, is a fine-tuned language model specializing in generating music-related text.
Details of the new model addition:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR872-R885): Added a new entry for `Llama-Song-Stream-3B-Instruct`, including its description, URLs, parameters, and file details.
=> chore(model gallery): add llama-song-stream-3b-instruct

gallery/index.yaml
This pull request introduces a new model configuration to the `gallery/index.yaml` file. The most important change is the addition of the `llama-chat-summary-3.2-3b` model, which is designed for generating context-aware summaries of long conversational or text-based inputs.
* Added `llama-chat-summary-3.2-3b` model configuration, including its name, URLs, description, parameters, and associated files.
=> chore(model gallery): add llama-chat-summary-3.2-3b

backend/python/openvoice/requirements-cpu.txt, backend/python/openvoice/requirements-cublas11.txt, backend/python/openvoice/requirements-cublas12.txt, backend/python/openvoice/requirements-intel.txt
=> fix(openvoice): do not pin numpy

backend/python/openvoice/requirements-cpu.txt, backend/python/openvoice/requirements-cublas11.txt, backend/python/openvoice/requirements-cublas12.txt, backend/python/openvoice/requirements-hipblas.txt, backend/python/openvoice/requirements-intel.txt, backend/python/openvoice/requirements.txt
=> fix(openvoice): pin numpy before installing torch

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, focusing on adding a new model entry. The most important changes include the addition of a new model with its associated metadata and files.
* Added a new model entry named "tq2.5-14b-neon-v1" with an icon, URLs, and a detailed description.
* Included the model parameter override for "TQ2.5-14B-Neon-v1-Q4_K_M.gguf".
* Listed the associated file with its filename, SHA256 checksum, and URI.
=> chore(model gallery): add tq2.5-14b-neon-v1

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, which adds a new model entry for "orca_mini_v8_1_70b". Below is a summary of the most important changes:
New Model Addition:
* Added a new model entry for "orca_mini_v8_1_70b" with associated metadata, including name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add orca_mini_v8_1_70b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "llama-3.3-70b-instruct-ablated". The most important changes are:
* Added a new model entry under the name "llama-3.3-70b-instruct-ablated" with an associated icon, URLs, description, and file details.
=> chore(model gallery): add llama-3.3-70b-instruct-ablated

.github/workflows/image.yml, .github/workflows/image_build.yml
This PR adds Nvidia arm64 images with l4t (for instance to use with Nvidia AGX Orin, etc).
Depends on https://github.com/mudler/LocalAI/pull/4447
=> chore(nvidia-l4t): add l4t arm64 images

.github/workflows/image.yml
Until I find a native arm64 runner this is too slow to run on virtualized - let's just disable it for now
=> chore(ci): comment arm64 job until we find a native CI runner

docs/content/docs/reference/nvidia-l4t.md
This pull request includes changes to add documentation for running LocalAI on Nvidia ARM64 devices. The most important changes are the addition of prerequisites, build instructions, and usage instructions for the LocalAI container.
Documentation updates:
* [`docs/content/docs/reference/nvidia-l4t.md`](diffhunk://#diff-7af7d2412590b673e4357abf8587cac7194f850867e4390d4e6dde0b622959f5R1-R35): Added a new section titled "Running on Nvidia ARM64" with prerequisites, build instructions, and usage instructions for running LocalAI on Nvidia ARM64 devices such as the Jetson Nano, Jetson Xavier NX, and Jetson AGX Xavier.
=> chore(docs): add nvidia l4t instructions

gallery/index.yaml
This pull request includes a new model entry to the `gallery/index.yaml` file. The most important change is the addition of the L3.3-MS-Evalebis-70b model, which includes several attributes such as name, icon, URLs, description, overrides, and files.
* Added L3.3-MS-Evalebis-70b model with attributes including name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add l3.3-ms-evalebis-70b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `tqwendo-36b`. This update includes several details about the model, such as its name, icon, URLs, description, and file information.
* Added a new model entry for `tqwendo-36b` with the following details:
- Name: `tqwendo-36b`
- Icon URL: `https://cdn-uploads.huggingface.co/production/uploads/6379683a81c1783a4a2ddba8/DI7Yw8Fs8eukluzKTHjEH.png`
- URLs: 
- `https://huggingface.co/nisten/tqwendo-36b`
- `https://huggingface.co/bartowski/tqwendo-36b-GGUF`
- Description: Includes information on using a draft model for speculative decoding and chain of thought reasoning.
- Overrides: Specifies parameters and files for the model, including the filename …
=> chore(model gallery): add tqwendo-36b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important changes include adding details for the `rombos-llm-70b-llama-3.3` model, including its name, icon, URLs, description, and associated files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR201-R218): Added a new model entry for `rombos-llm-70b-llama-3.3` with relevant details such as name, icon, URLs, description, parameters, and associated files.
=> chore(model gallery): add rombos-llm-70b-llama-3.3

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "FastLlama-3.2-1B-Instruct". The new entry includes details such as the model name, icon URL, description, and file information.
Key changes:
* Added a new model entry for "FastLlama-3.2-1B-Instruct" with the following details:
- Name: "fastllama-3.2-1b-instruct"
- Icon URL: `https://huggingface.co/suayptalha/FastLlama-3.2-1B-Instruct/resolve/main/FastLlama.png`
- Description: FastLlama is a highly optimized version of the Llama-3.2-1B-Instruct model, designed for superior performance in constrained environments. It has been fine-tuned using the MetaMathQA-50k section of the HuggingFaceTB/smoltalk dataset to enhance its mathematical reasoning and problem-solving abilities.
- …
=> chore(model gallery): add fastllama-3.2-1b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model, `dans-personalityengine-v1.1.0-12b`, is intended to enhance the capabilities of the gallery.
Addition of a new model entry:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR5071-R5085): Added `dans-personalityengine-v1.1.0-12b` to the gallery with details including name, URL, description, and file parameters.
=> chore(model gallery): add dans-personalityengine-v1.1.0-12b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `llama-3.1-8b-open-sft`.
* Added a new entry for the `llama-3.1-8b-open-sft` model, including its description, URLs, parameters, and associated file details.
=> chore(model gallery): add llama-3.1-8b-open-sft

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, introducing a new experimental research model named QVQ-72B-Preview.
Key changes:
* Added a new entry for the QVQ-72B-Preview model, including its name, URLs, description, and associated files.
=> chore(model gallery): add qvq-72b-preview

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `teleut-7b-rp` model with its associated metadata, including name, icon, URLs, description, overrides, and files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2385-R2400): Added a new model entry for `teleut-7b-rp`, including its name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add teleut-7b-rp

gallery/index.yaml
This pull request includes a new entry to the `gallery/index.yaml` file, adding a new model configuration.
* Added a new model entry named "falcon3-1b-instruct-abliterated" with corresponding URLs, description, and file details. This model is an uncensored version of Falcon3-1B-Instruct created using abliteration to remove refusals.
=> chore(model gallery): add falcon3-1b-instruct-abliterated

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `falcon3-10b-instruct-abliterated` model with its associated details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR81-R95): Added a new model entry for `falcon3-10b-instruct-abliterated` including its name, URLs, description, parameters, and file details.
=> chore(model gallery): add falcon3-10b-instruct-abliterated

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for Falcon3-7B-Instruct-abliterated. The main changes involve adding the model's metadata and file details.
* Added a new model entry for `falcon3-7b-instruct-abliterated`, including its name, URLs, description, and overrides.
* Included file details for `Falcon3-7B-Instruct-abliterated-Q4_K_M.gguf`, specifying its filename, SHA256 checksum, and URI.
=> chore(model gallery): add falcon3-7b-instruct-abliterated

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry. The most important change is the addition of the `miscii-14b-1028` model, which is designed for chat and conversational AI tasks.
* Added a new language model entry for `miscii-14b-1028`, including its name, icon, URLs, description, overrides, and associated file details.
=> chore(model gallery): add miscii-14b-1028

gallery/index.yaml
This pull request includes a new model entry in the `gallery/index.yaml` file. The new entry adds a merged model with associated metadata and file information.
Changes to the `gallery/index.yaml` file:
* Added a new model entry for `miscii-14b-1225`, including its name, icon URL, description, and associated files.
=> chore(model gallery): add miscii-14b-1225

gallery/index.yaml
This pull request includes a new entry to the `gallery/index.yaml` file, adding a new model to the gallery.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2493-R2508): Added a new model entry for "qwen2.5-32b-rp-ink" with relevant metadata, including name, icon, URLs, description, and file details.
=> chore(model gallery): add qwen2.5-32b-rp-ink

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, introducing a new medical language model entry. The most important change is the addition of the `HuatuoGPT-o1-8B` model, which is designed for advanced medical reasoning.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4368-R4382): Added `HuatuoGPT-o1-8B`, a medical language model with detailed descriptions, URLs for more information, and specific parameters and files.
=> chore(model gallery): add huatuogpt-o1-8b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry and its associated details.
* Added a new model entry named "q2.5-veltha-14b-0.5" with URLs, description, parameters, and file details.
=> chore(model gallery): add q2.5-veltha-14b-0.5

gallery/index.yaml
…rm-imatrix
This pull request includes a change to the `gallery/index.yaml` file to add a new model entry. The new entry includes details such as the model's name, icon, description, and file information.
* Added a new model entry for "captain-eris-diogenes_twilight-v0.420-12b-arm-imatrix" with associated URLs and description.
=> chore(model gallery): add captain-eris-diogenes_twilight-v0.420-12b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model is named "violet_twilight-v0.2" and includes several details such as URL, icon, description, parameters, and file information.
Changes in `gallery/index.yaml`:
* Added a new model entry for "violet_twilight-v0.2" with associated metadata including URL, icon, description, and file details.
=> chore(model gallery): add violet_twilight-v0.2

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new model named `qwenwify2.5-32b-v4.5` with detailed metadata and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2543-R2562): Added a new model entry `qwenwify2.5-32b-v4.5` with its URLs, description, parameters, and associated file information.
=> chore(model gallery): add qwenwify2.5-32b-v4.5

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry includes detailed information about the model `sainemo-remix`.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR5388-R5405): Added the `sainemo-remix` model with its name, icon URL, description of included models, parameters, and file details.
=> chore(model gallery): add sainemo-remix

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The change introduces a new model with detailed information about its sources and parameters.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4417-R4435): Added a new model named "l3.1-purosani-2-8b" with URLs, description, overrides, and file details.
=> chore(model gallery): add l3.1-purosani-2-8b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `Nera_Noctis-12B` model to the gallery.
* Added a new model entry for `Nera_Noctis-12B` with relevant metadata including name, URLs, icon, description, and file details.
=> chore(model gallery): add nera_noctis-12b

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, specifically introducing a new entry for the DRT-o1-7B model. The changes add detailed information about the model, including its name, URLs, description, and associated files.
Key changes:
* Added a new entry for the DRT-o1-7B model, including its name, URLs, and a comprehensive description of the model's purpose and training methodology.
* Included the `overrides` section specifying the model parameters for DRT-o1-7B.
* Added the `files` section with details about the filename, SHA-256 hash, and URI for the DRT-o1-7B model file.
=> chore(model gallery): add drt-o1-7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new experimental model entry. The most important change is the addition of a new model designed to improve the controllability and consistency of current roleplaying models.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2599-R2625): Added a new model entry named "experimental-lwd-mirau-rp-14b-iq-imatrix" with detailed description, icon, URLs, and file information.
=> chore(model gallery): add experimental-lwd-mirau-rp-14b-iq-imatrix

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `llama-deepsync-3b`. The changes include specifying the model's name, URLs, description, parameters, and associated files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1058-R1071): Added a new model entry for `llama-deepsync-3b`, including its name, URLs, description, parameters, and associated files.
=> chore(model gallery): add llama-deepsync-3b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model is named "32b-qwen2.5-kunou-v1" and includes relevant metadata such as its icon, URLs, description, and file details.
The most important change is:
* Added a new model entry "32b-qwen2.5-kunou-v1" with associated metadata including icon URL, description, and file details.
=> chore(model gallery): add 32b-qwen2.5-kunou-v1

gallery/index.yaml
=> chore(model gallery): add dolphin3.0-llama3.2-3b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for Dolphin 3.0. The most important changes include adding the model's metadata, description, and file details.
* Added the Dolphin 3.0 model to the `gallery/index.yaml` file with the following details:
* Name: "dolphin3.0-qwen2.5-0.5b"
* Icon URL: https://cdn-uploads.huggingface.co/production/uploads/63111b2d88942700629f5771/cNCs1TBD3FelWCJGkZ3cd.png
* URLs: 
* https://huggingface.co/cognitivecomputations/Dolphin3.0-Qwen2.5-0.5B
* https://huggingface.co/bartowski/Dolphin3.0-Qwen2.5-0.5B-GGUF
* Description: Detailed description emphasizing the model's general-purpose capabilities and user control features.
* Overrides: Model parameters set to …
=> chore(model gallery): add dolphin3.0-qwen2.5-0.5b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model, Dolphin 3.0-Qwen2.5-3b, to the gallery. The most important changes include adding metadata, description, and file details for the new model.
* Added metadata for Dolphin 3.0-Qwen2.5-3b, including name, icon, and URLs.
* Included a detailed description of the Dolphin 3.0 model, highlighting its general-purpose capabilities and advantages over other models.
* Added file details and overrides for the Dolphin 3.0-Qwen2.5-3b model, including parameters and SHA256 checksum.
=> chore(model gallery): add dolphin3.0-qwen2.5-3b

.github/labeler.yml
This PR makes sure to auto-label PRs touching go.mod/go.sum files
=> chore: update labeler.yml to include go files

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new model entry with detailed metadata.
* Added a new model named "14b-qwen2.5-freya-x1" with associated metadata including icon URL, description, and file details. The description provides insights into the training methods and steps used for the model.
=> chore(model gallery): add 14b-qwen2.5-freya-x1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new language model entry. The most important changes are:
New language model entry:
* Added a new language model named "chuluun-qwen2.5-72b-v0.01" with associated metadata, including an icon URL, description, and file details.
=> chore(model gallery): add chuluun-qwen2.5-72b-v0.01

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "QwQ-32B-Preview-IdeaWhiz-v1".
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2955-R2969): Added a new model entry "QwQ-32B-Preview-IdeaWhiz-v1" with details including name, icon, URLs, description, overrides, and files. This model is fine-tuned for scientific creativity and step-by-step reasoning using the LiveIdeaBench dataset.
=> chore(model gallery): add qwq-32b-preview-ideawhiz-v1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important changes include adding details for the new model, including its name, icon, URLs, description, overrides, and associated files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2970-R2984): Added the `rombos-qwen2.5-writer-32b` model with details such as name, icon, URLs, description, overrides, and associated files.
=> chore(model gallery): add rombos-qwen2.5-writer-32b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `Sky-T1-32B-Preview`.
* Added a new model entry for `Sky-T1-32B-Preview`, including its name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add sky-t1-32b-preview

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "Negative_LLAMA_70B". The new entry provides detailed information about the model, including its name, icon, URLs, description, parameters, and file details.
Key changes:
* Added a new model entry named "Negative_LLAMA_70B" with specific attributes and descriptions to the `gallery/index.yaml` file.
=> chore(model gallery): add negative_llama_70b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `finemath-llama-3b`. The new entry provides detailed information about the model, its training dataset, performance, and associated files.
Key changes:
* Added a new model entry for `finemath-llama-3b` with the following details:
- Icon URL
- Name and URLs for the model
- Description of the model, including training dataset and performance metrics
- Overrides for model parameters
- File details, including filename, SHA-256 checksum, and URI
=> chore(model gallery): add finemath-llama-3b

gallery/index.yaml, gallery/phi-4-chat-fcall.yaml
This pull request includes new additions to the model configurations and enhancements to the gallery index. The most important changes are the addition of a new model entry in the `gallery/index.yaml` and the creation of a new configuration file for the `phi-4-chat` model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR26-R41): Added a new model entry for `LocalAI-functioncall-phi-4-v0.1`, including details such as URL, name, icon, description, and file parameters.
* [`gallery/phi-4-chat-fcall.yaml`](diffhunk://#diff-3ba5b558791ea02b7fbabf6f01a22686228a64221ade27027ddeb43b0eb7779cR1-R27): Created a new configuration file for the `phi-4-chat` model, detailing the model's name, configuration settings, and templates …
=> chore(model gallery): add LocalAI-functioncall-phi-4-v0.1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model version and its associated metadata. The most important changes include adding details for the new `LocalAI-functioncall-phi-4-v0.2` model.
* Added a new model entry for `LocalAI-functioncall-phi-4-v0.2` with a description highlighting its conversational capabilities and function call execution. The model is based on phi-4 and includes CoT (o1) capabilities from the marco-o1 dataset.
* Included URLs for accessing the new model on Hugging Face.
* Specified the parameters and files associated with the new model version.
=> chore(model gallery): add LocalAI-functioncall-phi-4-v0.2

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `qwen2.5-72b-rp-ink`.
* Added `qwen2.5-72b-rp-ink` model to the gallery with relevant metadata, including name, icon, URLs, description, and file details.
=> chore(model gallery): add qwen2.5-72b-rp-ink

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, introducing a new model named "steiner-32b-preview" with detailed descriptions and associated metadata.
* Introduced a new model entry named "steiner-32b-preview" with URLs for downloading the model files from Hugging Face.
* Provided a comprehensive description of the "steiner-32b-preview" model, explaining its purpose, inspiration, and the reasoning behind open-sourcing it.
* Added metadata for the model, including parameters and file details, such as filename, sha256 checksum, and URI for the model file.
=> chore(model gallery): add steiner-32b-preview

backend/python/diffusers/backend.py
This PR  adds support for the Sana pipeline type ( https://github.com/NVlabs/Sana ) 
=> feat(diffusers): add support for Sana pipelines

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file. The change introduces a new model entry for "Qwerus-7B" with its relevant details.
* Added "Qwerus-7B" model with descriptions, URLs, and file details, including parameters and SHA256 checksum.
=> chore(model gallery): add qwerus-7b

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file. The change introduces a new model entry with detailed metadata and descriptions.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR404-R420): Added a new model entry named "l3.3-ms-nevoria-70b" with associated metadata including icon URL, description, and file details. The description explains the unique approach taken in creating the model by leveraging a "weight twisting" effect.
=> chore(model gallery): add l3.3-ms-nevoria-70b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry.
* Added a new model entry for "uwu-7b-instruct" with details including URLs, description, parameters, and file information.
=> chore(model gallery): add uwu-7b-instruct

gallery/index.yaml
This pull request makes updates to the `gallery/index.yaml` file, including the removal of an entry and the addition of a new model with detailed metadata.
Changes in `gallery/index.yaml`:
* Removed the entry for `drt-o1-14b`.
* Added a new model entry for `vikhr-qwen-2.5-1.5b-instruct`, including its name, URLs, description, parameters, and file details.
=> chore(model gallery): add vikhr-qwen-2.5-1.5b-instruct

Dockerfile, Makefile, backend/python/kokoro/Makefile, backend/python/kokoro/backend.py, backend/python/kokoro/install.sh, backend/python/kokoro/istftnet.py, backend/python/kokoro/kokoro.py, backend/python/kokoro/models.py, backend/python/kokoro/plbert.py, backend/python/kokoro/protogen.sh, backend/python/kokoro/requirements-cpu.txt, backend/python/kokoro/requirements-cublas11.txt, backend/python/kokoro/requirements-cublas12.txt, backend/python/kokoro/requirements-hipblas.txt, backend/python/kokoro/requirements-intel.txt, backend/python/kokoro/requirements.txt, backend/python/kokoro/run.sh, backend/python/kokoro/test.sh, pkg/model/loader.go
This PR adds the kokoro backend (https://huggingface.co/hexgrad/Kokoro-82M)
=> feat(tts): Add Kokoro backend

pkg/model/initializers.go
This PR adds an alias for `transformers-musicgen` to be redirected to `transformers` automatically
=> chore: alias transformers-musicgen to transformers

backend/python/transformers/backend.py, backend/python/transformers/requirements-cpu.txt, backend/python/transformers/requirements-cublas11.txt, backend/python/transformers/requirements-cublas12.txt, backend/python/transformers/requirements-hipblas.txt, backend/python/transformers/requirements-intel.txt, backend/python/transformers/requirements.txt
This PR adds the OuteTTS model supports to the `transformers` backend. Since `OuteTTS` supports transformers it made just much sense to add support directly into it. 
=> feat(transformers): add support to OuteTTS

core/cli/run.go, core/http/endpoints/openai/chat.go, core/http/endpoints/openai/completion.go, core/http/endpoints/openai/edit.go, docs/content/docs/advanced/advanced-usage.md
This PR adds missing docs about machine tag and extra usage config options
=> Extra-Usage and Machine-Tag docs

gallery/index.yaml
This PR adds InternLM3-8b-Q4_K_M  to model gallery.
=> chore(model gallery): add InternLM3-8b-Q4_K_M 

gallery/index.yaml
This PR remove some dead urls and add some organizations icons.
It sports icons for 
- Microsoft Phi models
- Google Gemma models
- Arcee models
- KatanemoLabs models
- OpenBMB models
- IBM-granite models
- OpenCoder models
- Meta updated icon
- QwenLM models
- RWKV models
plus some fixes for dead links (i.e ibb domain)
=> chore(model gallery): update icons and add missing ones

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry to the gallery. The new entry includes details such as the model name, icon, URLs, description, and file information.
* Added a new model entry named `l3.3-prikol-70b-v0.2` with an associated icon and URLs for accessing the model on Hugging Face.
* Included a detailed description of the model, explaining the merge process and the expected improvements over the previous revision.
* Specified the prompt format and provided an override for the model parameters.
* Added file information for the new model, including the filename, SHA-256 hash, and URI.
=> chore(model gallery): add l3.3-prikol-70b-v0.2

gallery/index.yaml
This PR consists of another bunch of dead links removal and some updated icons;
- missing logo for LLAVA
- updated icon for deepseek-ai models
=> chore(model gallery): remove dead icons and update LLAVA and DeepSeek ones

gallery/index.yaml, gallery/sd-ggml.yaml
This PR adds stablediffusion 3.5 with ggml. I want to drop the old sd implementation, however, that looks much more smaller compared to this one so might not fit CI.
=> chore(model gallery): add sd-3.5-large-ggml

gallery/index.yaml
This PR adds stablediffusion 1.5 and 3.5 with the ggml backend into the gallery
=> chore(model gallery): add sd-1.5-ggml and sd-3.5-medium-ggml

Dockerfile, Makefile, pkg/model/initializers.go
This PR fixes #4662 
Based on #4674 
=> chore: detect and enable avx512 builds

gallery/index.yaml
This PR adds OpenBMB MiniCPM-o-2.6 model support
Needs https://github.com/ggerganov/llama.cpp/commit/3e3357fd77bcf5bd8cfcc53ca53d4a5532e67e1b
=> chore(model gallery): add MiniCPM-o-2.6-7.6b

gallery/index.yaml
This PR reorganizes deepseek-r1 models, de-duplicates some entries and add other model sizes
=> chore(model gallery): add DeepSeek R1 14b, 32b and 70b

backend/python/autogptq/requirements.txt, backend/python/bark/requirements.txt, backend/python/common/template/requirements.txt, backend/python/coqui/requirements.txt, backend/python/diffusers/requirements.txt, backend/python/exllama2/requirements.txt, backend/python/faster-whisper/requirements.txt, backend/python/kokoro/requirements.txt, backend/python/rerankers/requirements.txt, backend/python/transformers/requirements.txt, backend/python/vllm/requirements.txt
This PR bumps grpcio from 1.69 to 1.70
=> chore(deps): bump grpcio to 1.70.0

gallery/index.yaml
This PR adds https://huggingface.co/sometimesanotion/Lamarck-14B-v0.7
=> chore(model gallery): add lamarck-14b-v0.7

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The entry is for the `l3.3-nevoria-r1-70b` model, which builds upon the original Nevoria foundation and incorporates the Deepseek-R1 reasoning architecture to enhance dialogue interaction and scene comprehension.
* Addition of a new model entry `l3.3-nevoria-r1-70b` with detailed description and characteristics.
* Inclusion of multiple URLs for the model's location on Hugging Face.
* Specification of the model's parameters and associated files, including the filename and SHA256 checksum.
=> chore(model gallery): add l3.3-nevoria-r1-70b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The main changes involve adding metadata and details for the new model "dumpling-qwen2.5-32b".
Additions to model entries:
* Added a new model entry for "dumpling-qwen2.5-32b" with its name, icon URL, description, and associated files.
=> chore(model gallery): add dumpling-qwen2.5-32b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `Confucius-o1-14B`. This model is based on the Qwen2.5-14B-Instruct model and has been developed by the NetEase Youdao Team.
* Added a new model entry for `Confucius-o1-14B`, including its description, URLs, and file details.
=> chore(model gallery): add confucius-o1-14b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry is for the `FuseO1-DeepSeekR1-Qwen2.5-Coder-32B-Preview-v0.1` model, which aims to enhance System-II reasoning capabilities through model fusion techniques.
* Added a new model entry `FuseO1-DeepSeekR1-Qwen2.5-Coder-32B-Preview-v0.1` with detailed description and multiple URLs for access. This model integrates multiple open-source o1-like LLMs to enhance reasoning abilities in mathematics, coding, and science domains.
=> chore(model gallery): add fuseo1-deepseekr1-qwen2.5-coder-32b-preview-v0.1

gallery/index.yaml
This pull request includes an important addition to the `gallery/index.yaml` file, which enhances the model listing with a new entry for the `FuseO1-DeepSeekR1-Qwen2.5-Instruct-32B-Preview` model. This new entry includes detailed information about the model, such as its name, URLs, description, and file parameters.
Additions to the model listing:
* Added a new model entry `FuseO1-DeepSeekR1-Qwen2.5-Instruct-32B-Preview` with the following details:
- Name: `fuseo1-deepseekr1-qwen2.5-instruct-32b-preview`
- URLs: 
- https://huggingface.co/FuseAI/FuseO1-DeepSeekR1-Qwen2.5-Instruct-32B-Preview
- https://huggingface.co/bartowski/FuseO1-DeepSeekR1-Qwen2.5-Instruct-32B-Preview-GGUF
- Description: Detailed explanation of the model's purpose and fusion techniques used to enhance …
=> chore(model gallery): add fuseo1-deepseekr1-qwen2.5-instruct-32b-preview

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file. The update introduces a new model, `fuseo1-deepseekr1-qwq-32b-preview`, and provides detailed information about its purpose, description, and associated files.
Key changes:
* Added a new model entry `fuseo1-deepseekr1-qwq-32b-preview` with associated URLs and a detailed description.
* Included a list of parameters and files specific to the new model, including the filename, SHA256 hash, and URI for the GGUF file.
=> chore(model gallery): add fuseo1-deepseekr1-qwq-32b-preview

gallery/index.yaml, gallery/llama3.2-quantized.yaml
This PR adds specific llama3.2 model templates based on the prompts from the llama3.2 model card [here](https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_2/)
This will affect **34**  llama3.2 models in the gallery in total, all of which previously were based on the llama3.1-instruct model config and templates.
=> chore(model gallery): add specific message templates for llama3.2 based models

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new language model entry. The most important change is the addition of the `virtuoso-lite` model, which is based on the Llama-3 architecture and designed for efficiency and performance.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR201-R214): Added a new entry for the `virtuoso-lite` model, including its description, URLs, parameters, and file details.
=> chore(model gallery): add virtuoso-lite

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for "Selene-1-Mini-Llama-3.1-8B". The changes provide detailed information about the new model, including its description, performance benchmarks, and file details.
* Added a new model entry for "Selene-1-Mini-Llama-3.1-8B" with detailed metadata including name, icon, URLs, description, performance benchmarks, and file details.
=> chore(model gallery): add selene-1-mini-llama-3.1-8b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `openthinker-7b`. The most important change is the addition of the new model with its corresponding metadata and configuration.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3458-R3476): Added a new model entry for `openthinker-7b`, including its name, icon, URLs, description, overrides, and file details.
=> chore(model gallery): add openthinker-7b

core/config/backend_config_test.go, core/http/app_test.go, docs/content/docs/features/model-gallery.md
This pull request includes a small but important update to the `core/config/backend_config_test.go` file. The change updates the URL used to download a configuration file to a specific version.
* Updated the URL in `parameters:` to download the configuration file from `v2.25.0` instead of `master` in `core/config/backend_config_test.go`.
=> fix(tests): pin to branch for config used in tests

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry describes the Mistral Small 3 model with 24 billion parameters, which sets a new benchmark in the "small" Large Language Models category.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR6616-R6632): Added a new model entry for "mistral-small-24b-instruct-2501", including its URLs, description, parameters, and file details.
=> chore(model gallery): add mistral-small-24b-instruct-2501

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "tinyswallow-1.5b-instruct". The most important changes are:
* Added a new model entry for "tinyswallow-1.5b-instruct" with relevant details including URLs, description, parameters, and file information.
=> chore(model gallery): add tinyswallow-1.5b-instruct

gallery/index.yaml
This pull request includes a new entry for the TAID-LLM-1.5B model in the `gallery/index.yaml` file. The new entry includes details such as the model name, icon, URLs, description, and file information.
Changes in `gallery/index.yaml`:
* Added a new model entry for "taid-llm-1.5b" with the following details:
- Name: "taid-llm-1.5b"
- Icon URL: https://sakana.ai/assets/taid-jp/cover_large.jpeg
- URLs: 
- https://huggingface.co/SakanaAI/TAID-LLM-1.5B
- https://huggingface.co/bartowski/TAID-LLM-1.5B-GGUF
- Description: TAID-LLM-1.5B is an English language model created through TAID (Temporally Adaptive Interpolated Distillation), using Qwen2-72B-Instruct as the teacher model and Qwen2-1.5B-Instruct as the student model.
- Overrides:
- Parameters: model: …
=> chore(model gallery): add taid-llm-1.5b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model configuration for `FuseO1-DeekSeekR1-QwQ-SkyT1-32B-Preview`.
* Added a new model configuration for `FuseO1-DeekSeekR1-QwQ-SkyT1-32B-Preview`, including its name, URLs, description, parameters, and associated files.
=> chore(model gallery): add fuseo1-deekseekr1-qwq-skyt1-32b-preview

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new AI model entry. The most important changes include the addition of the `Damascus-R1` model with detailed descriptions of its architecture, philosophy, and technical specifications.
New AI model entry:
* Added `Damascus-R1` model entry with the name "steelskull_l3.3-damascus-r1", including an icon URL, multiple URLs for more information, and a comprehensive description of its architecture and core philosophy.
* Detailed the technical architecture of `Damascus-R1`, highlighting its use of the SCE merge method and integration of components from various high-performance models for enhanced capabilities.
* Described the core philosophy of `Damascus-R1`, emphasizing its balance …
=> chore(model gallery): add steelskull_l3.3-damascus-r1

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new entry for "thedrummer_gemmasutra-pro-27b-v1.1". The most important changes include adding metadata, URLs, and file details for the new entry.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR7521-R7535): Added a new entry for "thedrummer_gemmasutra-pro-27b-v1.1" with associated metadata, URLs, description, and file details.
=> chore(model gallery): add thedrummer_gemmasutra-pro-27b-v1.1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry with detailed metadata.
* Added a new model entry for "uncensoredai_uncensoredlm-deepseek-r1-distill-qwen-14b" with associated metadata, including name, icon URL, description, and file details.
=> chore(model gallery): add uncensoredai_uncensoredlm-deepseek-r1-distill-qwen-14b

gallery/index.yaml, gallery/llama3.2-fcall.yaml
This PR adds the LocalAI fcall-based model. Based now on the llama3.2 architecture. Will share more updates soon - I want to give a few test rounds here first.
=> chore(model gallery): add LocalAI-functioncall-llama3.2-1b-v0.4

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file to include a new model entry. The change adds details about the `fblgit_miniclaus-qw1.5b-unamgs-grpo` model, including its name, icon, URLs, description, and file information.
Key changes:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3494-R3508): Added a new model entry for `fblgit_miniclaus-qw1.5b-unamgs-grpo` with relevant metadata such as name, icon, URLs, description, parameters, and file details.
=> chore(model gallery): add fblgit_miniclaus-qw1.5b-unamgs-grpo

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file. The most important change is the addition of a new model entry.
Addition of a new model entry:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR492-R510): Added a new model entry for `nohobby_l3.3-prikol-70b-v0.4` with details including name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add nohobby_l3.3-prikol-70b-v0.4

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, `suayptalha_maestro-10b`, is a fine-tuned version of Virtuoso-Lite and includes detailed metadata and file information.
* Added `suayptalha_maestro-10b` model entry, including its name, icon, URLs, description, and associated file details.
=> chore(model gallery): add suayptalha_maestro-10b

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new model entry. The most important change is the inclusion of the `agi-0_art-skynet-3b` model, which is described as an experimental model in the Art (Auto Regressive Thinker) series.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1435-R1448): Added the `agi-0_art-skynet-3b` model, with URLs, description, parameters, and associated files. This model is designed to simulate strategic reasoning with concealed long-term objectives and serves as a testbed for studying AI autonomy and strategic manipulation.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-cert …
=> chore(model gallery): add agi-0_art-skynet-3b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry. The most important change is the addition of the Krutrim-2 language model, including its metadata and file details.
New language model addition:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR6818-R6832): Added entry for `krutrim-ai-labs_krutrim-2-instruct`, including its name, icon, URLs, description, parameters, and file details.
=> chore(model gallery): add krutrim-ai-labs_krutrim-2-instruct

gallery/index.yaml
This pull request includes updates to the `gallery/index.yaml` file, focusing on adding new models and enhancing the metadata for existing ones. The most important changes include adding icons, descriptions, and URLs for new model entries.
Enhancements to model metadata:
* Added an `icon` field to the `LocalAI-functioncall-llama3.2-1b-v0.4` model entry.
* Added a new model entry `localai-functioncall-llama3.2-3b-v0.5` with fields for `name`, `icon`, `urls`, `description`, `overrides`, and `files`.
=> chore(model gallery): add LocalAI-functioncall-llama3.2-3b-v0.5

gallery/index.yaml
This pull request includes updates to the `gallery/index.yaml` file to add a new model and make a minor correction to an existing model's name.
* Added a new model entry for `arliai_llama-3.3-70b-arliai-rpmax-v1.4`, including its description, URLs, and file details.
* Corrected the name of the existing model `localai-functioncall-llama3.2-3b-v0.5` by changing the capitalization to `LocalAI-functioncall-llama3.2-3b-v0.5`.
=> chore(model gallery): add arliai_llama-3.3-70b-arliai-rpmax-v1.4

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for the Black Ink Guild's Pernicious Prophecy 70B.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR540-R555): Added the Pernicious Prophecy 70B model by Black Ink Guild, including its name, icon, URLs, description, overrides, and file details.
=> chore(model gallery): add black-ink-guild_pernicious_prophecy_70b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry with detailed metadata.
* Added a new model entry for `nohobby_l3.3-prikol-70b-v0.5` with associated metadata including name, icon, URLs, description, and file details.
=> chore(model gallery): add nohobby_l3.3-prikol-70b-v0.5

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file to include a new model entry. The change adds details about the `cognitivecomputations_dolphin3.0-r1-mistral-24b` model, including its name, URL, icon, description, and associated files.
* Added `cognitivecomputations_dolphin3.0-r1-mistral-24b` with details such as name, URLs, icon, description, and file parameters.
=> chore(model gallery): add cognitivecomputations_dolphin3.0-r1-mistral-24b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `cognitivecomputations_dolphin3.0-mistral-24b`. The most important changes include adding metadata, URLs, and descriptions for the new model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR6932-R6947): Added a new model entry for `cognitivecomputations_dolphin3.0-mistral-24b` with metadata, URLs, icon, description, and file details.
=> chore(model gallery): add cognitivecomputations_dolphin3.0-mistral-24b

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file to introduce a new model entry for `huihui-ai_deepseek-r1-distill-llama-70b-abliterated`.
* Added a new model entry for `huihui-ai_deepseek-r1-distill-llama-70b-abliterated` with relevant metadata, including URLs, description, and file details.
=> chore(model gallery): add huihui-ai_deepseek-r1-distill-llama-70b-abliterated

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "subtleone_qwen2.5-32b-erudite-writer". 
* Added a new model named "subtleone_qwen2.5-32b-erudite-writer" with its respective icon, URLs, description, and file details.
=> chore(model gallery): add subtleone_qwen2.5-32b-erudite-writer

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `ilsp_llama-krikri-8b-instruct`. The most important changes are:
* Added a new model `ilsp_llama-krikri-8b-instruct` to the gallery, including its name, icon, URLs, description, parameters, and associated files.
=> chore(model gallery): add ilsp_llama-krikri-8b-instruct

gallery/index.yaml, gallery/qwen-fcall.yaml
This pull request adds a new model configuration and updates the gallery index to include it. The most important changes include adding a new model entry to the `gallery/index.yaml` file and creating a new configuration file for the model.
Updates to gallery index:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3676-R3691): Added a new model entry for `localai-functioncall-qwen2.5-7b-v0.5` with relevant metadata and file details.
New configuration file:
* [`gallery/qwen-fcall.yaml`](diffhunk://#diff-e16ddb79466c95e3f49421fe54e2e4d875fd330158bfb033c8cd32a4a81eda33R1-R49): Created a new configuration file for the `qwen-fcall` model, including settings for memory mapping, function call handling, and chat message …
=> chore(model gallery): add localai-functioncall-qwen2.5-7b-v0.5

.github/workflows/generate_grpc_cache.yaml, .github/workflows/image_build.yml
Attempt to fix failing builds: https://github.com/mudler/LocalAI/actions/runs/13239433276/job/36951347528
=> chore(tests): decrease parallelism for gRPC builds

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `agentica-org_deepscaler-1.5b-preview`. The most important changes include the addition of metadata, URLs, and file information for the new model.
* Added a new model entry `agentica-org_deepscaler-1.5b-preview` with metadata including name, icon, and description.
* Included URLs for accessing the model on Hugging Face.
* Provided a description detailing the model's fine-tuning process, performance metrics, and improvements over the base model.
* Added file information for the model, including filename, sha256 hash, and URI. …
=> chore(model gallery): add agentica-org_deepscaler-1.5b-preview

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, `simplescaling_s1.1-32b`, includes details such as URLs, a description, and file information.
Key change:
* Added a new model entry `simplescaling_s1.1-32b` with URLs, description, and file details in the `gallery/index.yaml` file.
=> chore(model gallery): add simplescaling_s1.1-32b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry. The most important change is the addition of a new model entry for `theskullery_l3.3-exp-unnamed-model-70b-v0.5`.
* Added a new model entry for `theskullery_l3.3-exp-unnamed-model-70b-v0.5`, including its name, URLs, description, parameters, and file details.
=> chore(model gallery): add theskullery_l3.3-exp-unnamed-model-70b-v0.5

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `nvidia_aceinstruct-1.5b`. The most important changes include the addition of metadata and file information for the new model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3720-R3734): Added a new model entry for `nvidia_aceinstruct-1.5b`, including its name, icon URL, description, and associated file details.
=> chore(model gallery): add nvidia_aceinstruct-1.5b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `nvidia_aceinstruct-7b`. The most important change is the addition of metadata and details for this new model.
* Added a new entry for the `nvidia_aceinstruct-7b` model, including its name, icon URL, description, and associated files.
=> chore(model gallery): add nvidia_aceinstruct-7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `nvidia_AceInstruct-72B`.
* Added details for the `nvidia_AceInstruct-72B` model, including its name, icon URL, description, and associated files. This model is part of the AceInstruct family and is fine-tuned for various tasks such as coding, mathematics, and general-purpose tasks.
=> chore(model gallery): add nvidia_aceinstruct-72b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for "rombo-org_rombo-llm-v3.0-qwen-32b". The most important changes are:
* Added a new model entry for "rombo-org_rombo-llm-v3.0-qwen-32b" with detailed information including URLs, description, and file parameters.
=> chore(model gallery): add rombo-org_rombo-llm-v3.0-qwen-32b

gallery/index.yaml
This pull request introduces a new model entry to the `gallery/index.yaml` file. The entry is for the `pygmalionai_eleusis-12b` model, which is based on Mistral's Nemo Base and released under the Apache 2.0 license.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR7197-R7213): Added a new model entry for `pygmalionai_eleusis-12b`, including its description, URLs, parameters, and file details.
=> chore(model gallery): add pygmalionai_eleusis-12b

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file. The change adds a new entry for the `davidbrowne17_llamathink-8b-instruct` model, which is an instruction-tuned language model built on the LLaMA-3 architecture.
Key addition:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR5785-R5799): Added a new model entry `davidbrowne17_llamathink-8b-instruct` with details including name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add davidbrowne17_llamathink-8b-instruct

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file to include a new language model, `ozone-ai_0x-lite`. This model is designed for high-quality text generation with a compact and efficient architecture.
* Added a new entry for the `ozone-ai_0x-lite` language model, including its name, URLs, description, and file details.
=> chore(model gallery): add ozone-ai_0x-lite

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new entry for the Kubeguru model. The most important changes are:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1553-R1569): Added a new entry for the `kubeguru-llama3.2-3b-v0.1` model, including its name, icon URL, description, and file details.
=> chore(model gallery): add kubeguru-llama3.2-3b-v0.1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `allenai_llama-3.1-tulu-3.1-8b`.
* Added a new model entry `allenai_llama-3.1-tulu-3.1-8b` with associated metadata, including name, icon URL, description, and file details.
=> chore(model gallery): add allenai_llama-3.1-tulu-3.1-8b

gallery/index.yaml
This pull request includes a new entry to the `gallery/index.yaml` file. The new entry adds a model named "nbeerbower_dumpling-qwen2.5-14b" with associated metadata and file details.
* Added a new model entry "nbeerbower_dumpling-qwen2.5-14b" with an icon URL, description, and list of URLs.
* Included detailed finetuning information and a list of datasets used for finetuning.
* Added file details for the model, including filename, sha256, and uri.
=> chore(model gallery): add nbeerbower_dumpling-qwen2.5-14b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry with detailed information and parameters.
* Added a new model entry for `nbeerbower_dumpling-qwen2.5-32b-v2`, including its name, icon URL, description, and associated files. The description lists various datasets used for fine-tuning the model.
=> chore(model gallery): add nbeerbower_dumpling-qwen2.5-32b-v2

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `nbeerbower_dumpling-qwen2.5-72b`.
* Added a new model entry `nbeerbower_dumpling-qwen2.5-72b` with an icon URL, description, and a list of finetuned datasets.
* Included URLs for the new model entry pointing to Hugging Face.
* Specified overrides for model parameters and added a file entry for the new model with its SHA-256 hash and URI.
=> chore(model gallery): add nbeerbower_dumpling-qwen2.5-72b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for PygmalionAI's Pygmalion-3-12B. The most important changes include adding the model's metadata, description, licensing information, and file details.
* Added a new model entry for `pygmalionai_pygmalion-3-12b`, including its name, URL, description, and licensing information.
* Included file details for the new model with its filename, SHA256 checksum, and URI.
=> chore(model gallery): add pygmalionai_pygmalion-3-12b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file. The main change is the addition of a new model entry for "open-r1_openr1-qwen-7b," which includes detailed information about the model, its training parameters, and associated files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3933-R3946): Added a new model entry for "open-r1_openr1-qwen-7b" with URLs, description, training parameters, and file details.
=> chore(model gallery): add open-r1_openr1-qwen-7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry.
New language model entry:
* Added `sentientagi_dobby-unhinged-llama-3.3-70b` with a description, icon, URLs, and file details. This model is fine-tuned from Llama-3.3-70B-Instruct and has unique personality traits focused on personal freedom, decentralization, and crypto.
=> chore(model gallery): add sentientagi_dobby-unhinged-llama-3.3-70b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file by adding a new model entry for "internlm_oreal-deepseek-r1-distill-qwen-7b". The most important changes include the addition of metadata and file details for the new model.
* Added a new model `internlm_oreal-deepseek-r1-distill-qwen-7b` with details such as name, URLs, description, and file overrides.
=> chore(model gallery): add internlm_oreal-deepseek-r1-distill-qwen-7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model series called OREAL, which includes the internlm_oreal-7b model. The changes provide details about the new model and its performance.
Additions to model series:
* Added a new model `internlm_oreal-7b` with associated URLs, description, and parameters. The description highlights the performance improvements of the OREAL-7B and OREAL-32B models in mathematical reasoning tasks using the Outcome REwArd-based reinforcement Learning framework.
=> chore(model gallery): add internlm_oreal-7b

backend/python/coqui/requirements-cpu.txt, backend/python/coqui/requirements-cublas11.txt, backend/python/coqui/requirements-cublas12.txt, backend/python/coqui/requirements-hipblas.txt, backend/python/coqui/requirements-intel.txt
This PR should fix CI issues. Recent transformers release broke coqui-tts
=> fix(coqui): pin transformers

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry to the gallery. The most important change is the addition of the `smirki_uigen-t1.1-qwen-14b` model, which is a transformer model designed for reasoning-based UI generation.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR3994-R4008): Added a new model entry for `smirki_uigen-t1.1-qwen-14b`, including its name, icon, URLs, description, overrides, and associated files.
=> chore(model gallery): add smirki_uigen-t1.1-qwen-14b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry provides details about the `smirki_uigen-t1.1-qwen-7b` model, including its name, icon, URLs, description, and associated files.
Key changes:
* Added a new model entry for `smirki_uigen-t1.1-qwen-7b` with the following details:
* Name: `smirki_uigen-t1.1-qwen-7b`
* Icon URL: `https://cdn-uploads.huggingface.co/production/uploads/64d1129297ca59bcf7458d07/VSplF7AM1PJPzeR9FlDhE.png`
* URLs: 
* `https://huggingface.co/smirki/UIGEN-T1.1-Qwen-7B`
* `https://huggingface.co/bartowski/smirki_UIGEN-T1.1-Qwen-7B-GGUF`
* Description: A 7-billion parameter transformer model fine-tuned on Qwen2.5-Coder-7B-Instruct, designed for reasoning-based UI generation.
* Overrides and …
=> chore(model gallery): add smirki_uigen-t1.1-qwen-7b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry with detailed information.
* Added a new model entry `l3.1-8b-rp-ink` with associated metadata including name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add l3.1-8b-rp-ink

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `pocketdoc_dans-personalityengine-v1.2.0-24b`. The most important changes include the addition of the model's metadata, URLs, description, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR7507-R7523): Added a new model entry for `pocketdoc_dans-personalityengine-v1.2.0-24b`, including its name, URLs, description, overrides, and file details.
=> chore(model gallery): add pocketdoc_dans-personalityengine-v1.2.0-24b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "rombo-org_rombo-llm-v3.0-qwen-72b".
* Added a new model entry for "rombo-org_rombo-llm-v3.0-qwen-72b" with relevant metadata including name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add rombo-org_rombo-llm-v3.0-qwen-72b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry for "ozone-ai_reverb-7b".
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4039-R4052): Added a new entry for the "ozone-ai_reverb-7b" language model, including its name, URLs, description, parameters, and file details.
=> chore(model gallery): add ozone-ai_reverb-7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model is named "arcee-ai_arcee-maestro-7b-preview" and includes relevant metadata and file information.
Key changes:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR6383-R6396): Added a new model entry for "arcee-ai_arcee-maestro-7b-preview" with URLs, description, overrides, and file details.
=> chore(model gallery): add arcee-ai_arcee-maestro-7b-preview

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file by adding a new model entry. The new entry is for the `Steelskull_L3.3-Mokume-Gane-R1-70b` model, which includes detailed metadata and file information.
* Added a new model entry named `steelskull_l3.3-mokume-gane-r1-70b` with a detailed description and metadata.
=> chore(model gallery): add steelskull_l3.3-mokume-gane-r1-70b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry with detailed metadata and descriptions. The most important changes are:
* Added a new model entry for `Steelskull_L3.3-Cu-Mai-R1-70b` with a detailed description, including its unique features and user feedback.
* Included URLs for accessing the new model on Hugging Face.
* Added an icon link for the new model.
* Provided a list of specialized components integrated into the new model using the SCE merge method.
* Included file details such as filename, SHA256 checksum, and URI for the new model.
=> chore(model gallery): add steelskull_l3.3-cu-mai-r1-70b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new model is named "nohobby_l3.3-prikol-70b-extra" and includes various metadata such as a description, icon URL, and file details.
Key changes:
* Added a new model entry named "nohobby_l3.3-prikol-70b-extra" with the following details:
* Icon URL: `https://files.catbox.moe/x9t3zo.png`
* Description: Detailed explanation of the model's features and improvements, including the integration of DeepSeek distill and the use of `<think>` tags.
* URLs: Links to the model on Hugging Face.
* File details: Filename, SHA256 checksum, and URI for the model file.
=> chore(model gallery): add nohobby_l3.3-prikol-70b-extra

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model version and its associated metadata.
* Added the `flux.1dev-abliteratedv2` model with a detailed description of its unlearning process and its enhanced flexibility and responsiveness.
* Included URLs for the new model from Hugging Face repositories.
* Added parameter overrides to specify the model version.
=> chore(model gallery): add flux.1dev-abliteratedv2

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file. The most important change is the addition of a new model entry for `sicariussicariistuff_phi-line_14b`.
* Added `sicariussicariistuff_phi-line_14b` with detailed description, URLs, icon, and overrides. This model is noted for its excellent roleplay capabilities, creative writing, and low refusal rate in assistant tasks.
=> chore(model gallery): add sicariussicariistuff_phi-line_14b

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, introducing a new AI model entry. The new model, named `latitudegames_wayfarer-large-70b-llama-3.3`, is designed to enhance the gaming experience by providing a more challenging and dangerous environment for players.
Key changes:
* Added a new model entry `latitudegames_wayfarer-large-70b-llama-3.3` to the `gallery/index.yaml` file, including its name, icon, URLs, description, overrides, and file details.
=> chore(model gallery): add latitudegames_wayfarer-large-70b-llama-3.3

core/http/routes/ui.go, core/http/views/chat.html, core/http/views/partials/head.html
- Change chat colors
- Improve layout on small windows
#2156 
Fixes #3381 
=> feat(ui): small improvements to chat interface

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry. The most important changes include the addition of a new model, its description, and associated files.
* Added `locutusque_thespis-llama-3.1-8b` model with URLs, description, and parameters. This model is designed to enhance roleplaying performance through reasoning inspired by the Theory of Mind and is optimized using Group Relative Policy Optimization (GRPO).
* Included the file details for `Locutusque_Thespis-Llama-3.1-8B-Q4_K_M.gguf` with its `sha256` hash and URI.
=> chore(model gallery): add locutusque_thespis-llama-3.1-8b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `microsoft_phi-4-mini-instruct`.
* Added a new model entry for `microsoft_phi-4-mini-instruct`, including its name, URLs, description, and file details. This model is part of the Phi-4 model family and supports 128K token context length, with enhancements for precise instruction adherence and robust safety measures.
=> chore(model gallery): add microsoft_phi-4-mini-instruct

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file to include a new model entry for "ozone-research_chirp-01". The most important change is the inclusion of the new model details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4184-R4199): Added a new entry for the "ozone-research_chirp-01" model, including its name, URLs, description, overrides, and file details.
=> chore(model gallery): add ozone-research_chirp-01

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new language model entry.
New language model entry:
* Added a new language model named "ozone-research_0x-lite" with detailed metadata, including URLs, description, parameters, and associated files.
=> chore(model gallery): add ozone-research_0x-lite

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry provides details for the `allenai_olmOCR-7B-0225-preview` model, including its name, icon, URLs, description, and file information.
Key changes:
* Added a new model entry for `allenai_olmOCR-7B-0225-preview` with associated metadata such as name, icon, URLs, and description.
* Included file information for the new model, specifying the filename, sha256 checksum, and URI.
=> chore(model gallery): add allenai_olmocr-7b-0225-preview

gallery/granite3-2.yaml, gallery/index.yaml
This pull request includes the addition of a new AI model configuration and updates to the gallery index to include this new model. The most important changes include the creation of a configuration file for the `granite-3.2` model and the update of the gallery index to reference this new model.
New AI model configuration:
* [`gallery/granite3-2.yaml`](diffhunk://#diff-c50889c4f9b315cf6c3f48ac28ec0a65c2ef6c6f305a3ff29c5fb1c9e6196c85R1-R44): Added configuration for the `granite-3.2` model, including details for chat messages, function calls, and completion templates.
Gallery index update:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1082-R1096): Updated the gallery index to include the …
=> chore(model gallery): add ibm-granite_granite-3.2-8b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new AI model to the gallery. The most important change is the addition of the new model's metadata and relevant information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1097-R1111): Added a new AI model named `ibm-granite_granite-3.2-2b-instruct` with its description, URLs, and file details.
=> chore(model gallery): add ibm-granite_granite-3.2-2b-instruct

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry with detailed information.
* Added a new model entry for "thedrummer_fallen-llama-3.3-r1-70b-v1" with associated metadata, including name, icon, URLs, description, and file details.
=> chore(model gallery): add thedrummer_fallen-llama-3.3-r1-70b-v1

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry with detailed metadata.
* Added a new model entry named "steelskull_l3.3-mokume-gane-r1-70b-v1.1" with associated metadata such as icon URL, description, and file details. This model is inspired by the Japanese metalworking technique 'Mokume-gane' and includes specialized AI components to generate creative outputs.
=> chore(model gallery): add steelskull_l3.3-mokume-gane-r1-70b-v1.1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important changes include the addition of a new model named "l3.3-geneticlemonade-unleashed-70b-i1" with its relevant metadata.
* Added a new model entry "l3.3-geneticlemonade-unleashed-70b-i1" with an icon, URLs, description, parameters, and file details.
=> chore(model gallery): add l3.3-geneticlemonade-unleashed-70b-i1

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new model entry with detailed metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR794-R819): Added a new model entry named "llama-3.3-magicalgirl-2" with associated metadata including icon URL, description, and file details. The description provides context about the experimental nature of the model and lists the models included in the merge.
=> chore(model gallery): add llama-3.3-magicalgirl-2

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry with detailed metadata. The most important changes are listed below:
* Added a new model named "azura-qwen2.5-32b-i1" with associated metadata, including an icon URL, multiple URLs, a description of the model merge process, and specific file details.
=> chore(model gallery): add azura-qwen2.5-32b-i1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change involves adding a new model named "lolzinventor_meta-llama-3.1-8b-survivev3" with its associated metadata and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR6430-R6450): Added a new model entry for "lolzinventor_meta-llama-3.1-8b-survivev3" including its name, icon, URLs, description, overrides, and file details.
=> chore(model gallery): add lolzinventor_meta-llama-3.1-8b-survivev3

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "llama-3.3-magicalgirl-2.5-i1". The most important changes include adding details about the new model, including its name, icon, URLs, description, and associated files.
* Added a new model entry with the name "llama-3.3-magicalgirl-2.5-i1".
* Included an icon URL for the new model.
* Added URLs for accessing the new model on Hugging Face.
* Provided a detailed description of the new model, including the models included in the merge.
* Listed the associated file details, including filename, sha256, and uri.
=> chore(model gallery): add llama-3.3-magicalgirl-2.5-i1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for the Qwen series. The most important changes include the addition of a new model, `Qwen_QwQ-32B`, along with its metadata and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4377-R4390): Added a new model entry for `Qwen_QwQ-32B` with its description, URLs, parameters, and file details.
=> chore(model gallery): add qwen_qwq-32b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file. The change adds a new model entry for `rombo-org_rombo-llm-v3.1-qwq-32b`.
Additions to the model gallery:
* Added a new model entry for `rombo-org_rombo-llm-v3.1-qwq-32b`, including its name, icon, URLs, description, overrides, and associated files.
=> chore(model gallery): add rombo-org_rombo-llm-v3.1-qwq-32b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the `nomic-embed-text-v1.5` model with its associated metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR13761-R13777): Added the `nomic-embed-text-v1.5` model with details including URLs, description, tags, overrides, parameters, and file information.
=> chore(model gallery): add nomic-embed-text-v1.5

backend/cpp/llama/grpc-server.cpp
This PR fixes embedding calculation on models which are embedded-only for llama.cpp. We process embeddings in batches now.
=> fix(llama.cpp): correctly handle embeddings in batches

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `steelskull_l3.3-electra-r1-70b`. The most important changes include adding metadata such as the model's name, icon, URLs, description, and associated files.
* Added a new model entry `steelskull_l3.3-electra-r1-70b` with detailed metadata, including name, icon, URLs, description, and file information.
=> chore(model gallery): add steelskull_l3.3-electra-r1-70b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of a new model named "huihui-ai_qwq-32b-abliterated" with its associated metadata and file information.
* Added a new model entry "huihui-ai_qwq-32b-abliterated" with URLs, description, parameters, and file details.
=> chore(model gallery): add huihui-ai_qwq-32b-abliterated

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, introducing a new model entry. The change adds details for the "tower-babel_babel-9b-chat" model, including its name, icon, URLs, description, and associated files.
* Added "tower-babel_babel-9b-chat" with details such as name, icon URL, model URLs, description, and file information.
=> chore(model gallery): add tower-babel_babel-9b-chat

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry includes details about the `LLMEvoLLaMA-3.1-8B-v0.1-i1` model, such as its name, icon, URLs, description, overrides, and associated files.
Key changes:
* Added a new model entry for `LLMEvoLLaMA-3.1-8B-v0.1-i1` with detailed information including name, icon, description, and URLs.
* Included specific overrides for parameters and files associated with the new model.
=> chore(model gallery): add llmevollama-3.1-8b-v0.1-i1

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file to include a new model entry. The most important change is the addition of the HyperLlama3.1-v2 model with its associated metadata.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR6593-R6609): Added a new model entry for HyperLlama3.1-v2, including its name, URLs, description, parameters, and file details.
=> chore(model gallery): add hyperllama3.1-v2-i1

core/http/app.go, core/http/routes/openai.go
We generate unique uris for images.
=> fix(routes): do not gate generated artifacts via key

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "OpenPipe Deductive Reasoning Qwen 14B".
* Added a new model entry for "OpenPipe Deductive Reasoning Qwen 14B" with details such as name, URLs, description, parameters, and file information.
=> chore(model gallery): add openpipe_deductive-reasoning-qwen-14b

backend/python/autogptq/requirements.txt, backend/python/bark/requirements.txt, backend/python/common/template/requirements.txt, backend/python/coqui/requirements.txt, backend/python/diffusers/requirements.txt, backend/python/exllama2/requirements.txt, backend/python/faster-whisper/requirements.txt, backend/python/kokoro/requirements.txt, backend/python/rerankers/requirements.txt, backend/python/transformers/requirements.txt, backend/python/vllm/requirements.txt
This PR bumps grpcio to 1.71.0
=> chore(deps): Bump grpcio to 1.71.0

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry describes a smaller version of the Gemmasutra model with additional metadata.
Key changes:
* Added a new model entry for `thedrummer_gemmasutra-small-4b-v1`, including its name, icon, URLs, description, and file details.
=> chore(model gallery): add thedrummer_gemmasutra-small-4b-v1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model, `open-r1_olympiccoder-32b`.
* Added a new model entry for `open-r1_olympiccoder-32b`, including its name, URLs, description, overrides, and associated files.
=> chore(model gallery): add open-r1_olympiccoder-32b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new code model entry and its associated metadata.
Key changes:
* Added a new entry for the `open-r1_olympiccoder-7b` model, including its name, URLs, description, and file details.
=> chore(model gallery): add open-r1_olympiccoder-7b

gallery/index.yaml
This pull request involves adding a new entry to the `gallery/index.yaml` file. The entry includes details about a new model named "trashpanda-org_qwq-32b-snowdrop-v0". 
Key changes:
* Added a new model entry for "trashpanda-org_qwq-32b-snowdrop-v0" with associated metadata, including an icon URL, description, and file details.
=> chore(model gallery): add trashpanda-org_qwq-32b-snowdrop-v0

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing the Gemma-3 model.
* Added a new model entry for `gemma-3-27b-it` in `gallery/index.yaml`, including its URL, name, icon, license, description, tags, and file details.
Depends on https://github.com/mudler/LocalAI/pull/4996
=> chore(model gallery): add gemma-3-27b-it

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `gemma-3-12b-it`. The most important changes are:
* Added a new model entry for `gemma-3-12b-it` with URLs, description, and file details. This model is a lightweight, multimodal model capable of handling text and image input and generating text output. It supports over 140 languages and is suitable for various text generation and image understanding tasks.
=> chore(model gallery): add gemma-3-12b-it

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model to the gallery. The most important change is the addition of the `gemma-3-4b-it` model, which is a lightweight, state-of-the-art open model from Google.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR41-R54): Added the `gemma-3-4b-it` model, including its description, URLs, parameters, and file details. This model is a 4 billion parameter model, part of the Gemma family, and is designed for text generation and image understanding tasks.
=> chore(model gallery): add gemma-3-4b-it

gallery/index.yaml
This pull request includes an important addition to the `gallery/index.yaml` file, introducing a new language model to the Gemma family.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR55-R68): Added a new language model entry for `gemma-3-1b-it`, including its description, URLs, and file details. This model is a smaller variant of the Gemma 3 series with 1 billion parameters, designed for text generation and image understanding tasks.
=> chore(model gallery): add gemma-3-1b-it

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry. The most important change is the addition of the `qgallouedec_gemma-3-27b-it-codeforces-sft` model with its associated metadata.
Updates to `gallery/index.yaml`:
* Added a new model entry `qgallouedec_gemma-3-27b-it-codeforces-sft` with details such as name, URLs, description, parameters, and files.
=> chore(model gallery): add models/qgallouedec_gemma-3-27b-it-codeforces-sft

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file to include the new NousResearch DeepHermes 3 Mistral 24B Preview model. The update provides detailed information about the model, including its description, URLs, and associated files.
Key changes:
* Added new model entry `nousresearch_deephermes-3-mistral-24b-preview` with relevant metadata and description.
* Included URLs for accessing the model on Hugging Face.
* Provided a detailed description of the model's capabilities, including reasoning and response modes.
* Listed the specific file associated with the model along with its SHA256 checksum and URI.
=> chore(model gallery): add nousresearch_deephermes-3-mistral-24b-preview

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for the "nousresearch_deephermes-3-llama-3-3b-preview". This new entry includes various metadata such as the name, icon, URLs, description, and file details.
Key changes:
* Added a new model entry for "nousresearch_deephermes-3-llama-3-3b-preview" with detailed metadata, including name, icon, URLs, description, and file details.
=> chore(model gallery): add nousresearch_deephermes-3-llama-3-3b-preview

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, `prithivmlmods_viper-coder-32b-elite13`, is described and its relevant metadata is included.
* Added a new model entry for `prithivmlmods_viper-coder-32b-elite13`, including its name, icon, URLs, description, and file details.
=> chore(model gallery): add prithivmlmods_viper-coder-32b-elite13

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry. The most important change is the addition of the `eurollm-9b-instruct` model with its associated metadata.
New language model addition:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR83-R106): Added the `eurollm-9b-instruct` model, including its name, icon, URL, license, tags, description, and associated files.
=> chore(model gallery): add eurollm-9b-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "allura-org_bigger-body-70b". The most important changes include the addition of the model's metadata, description, and file details.
* Added a new model entry named "allura-org_bigger-body-70b" with associated URLs and description.
* Included file details for the new model, specifying filename, SHA256 hash, and URI.
=> chore(model gallery): add allura-org_bigger-body-70b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model to the gallery. 
* Added `pocketdoc_dans-sakurakaze-v1.0.0-12b` model with its relevant metadata, including URLs, description, parameters, and file details.
=> chore(model gallery): add pocketdoc_dans-sakurakaze-v1.0.0-12b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry. The new model is named "beaverai_mn-2407-dsk-qwqify-v0.1-12b" and includes detailed information about its usage and formatting.
* Added a new model entry named "beaverai_mn-2407-dsk-qwqify-v0.1-12b" with associated URLs, description, and overrides.
=> chore(model gallery): add beaverai_mn-2407-dsk-qwqify-v0.1-12b

gallery/index.yaml
This pull request includes a new model entry in the `gallery/index.yaml` file. The new entry adds the "ReadyArt_Forgotten-Safeword-70B-3.6" model with its associated metadata and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR957-R970): Added "ReadyArt_Forgotten-Safeword-70B-3.6" with URLs, description, parameters, and file details.
=> chore(model gallery): add readyart_forgotten-safeword-70b-3.6

gallery/index.yaml
This PR adds mmproj files to gemma3
=> chore(model gallery): add mproj files for gemma3 models

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the "mlabonne_gemma-3-27b-it-abliterated" model with its associated metadata and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR95-R109): Added the "mlabonne_gemma-3-27b-it-abliterated" model, including its name, icon, URLs, description, overrides, and file details.
=> chore(model gallery): add mlabonne_gemma-3-27b-it-abliterated

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, which adds a new model entry and its associated metadata. The most important change is the addition of the "mlabonne_gemma-3-12b-it-abliterated" model with its details.
* Added a new model entry "mlabonne_gemma-3-12b-it-abliterated" with its name, icon URL, description, and associated files.
=> chore(model gallery): add mlabonne_gemma-3-12b-it-abliterated

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry to the gallery. The most important change is the addition of the Gryphe Pantheon model series.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR8605-R8622): Added a new model entry for "gryphe_pantheon-rp-1.8-24b-small-3.1" with detailed descriptions, URLs, and file information.
=> chore(model gallery): add gryphe_pantheon-rp-1.8-24b-small-3.1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry. The most important change is the addition of the `nvidia_llama-3_3-nemotron-super-49b-v1` model, which includes detailed metadata and descriptions.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1059-R1077): Added a new model entry for `nvidia_llama-3_3-nemotron-super-49b-v1`, including its name, icon URL, description, parameters, and file details.
=> chore(model gallery): add nvidia_llama-3_3-nemotron-super-49b-v1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "gemma-3-4b-it-uncensored-dbl-x-i1". The most important changes are:
* Added a new model entry for "gemma-3-4b-it-uncensored-dbl-x-i1" with the following details:
- [`name`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR171-R185): "gemma-3-4b-it-uncensored-dbl-x-i1"
- [`icon`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR171-R185): URL to the model icon
- [`urls`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR171-R185): List of URLs where the model can be found
- [`description`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR171-R185): …
=> chore(model gallery): add gemma-3-4b-it-uncensored-dbl-x-i1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `rootxhacker_apollo-v3-32b`. The most important change is the addition of the new model configuration.
Addition of new model configuration:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4866-R4879): Added a new model entry for `rootxhacker_apollo-v3-32b` with associated URLs, description, parameters, and file details.
=> chore(model gallery): add rootxhacker_apollo-v3-32b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new generative model entry for `SamsungSAILMontreal_ByteCraft`.
* Added a new model entry for `SamsungSAILMontreal_ByteCraft`, including its name, icon, URLs, description, overrides, and file details.
=> chore(model gallery): add samsungsailmontreal_bytecraft

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new specialized variant of the Gemma 3 4B model. The most important changes include the addition of a new entry with detailed descriptions, key modifications, core functions, response characteristics, and implementation guidelines.
Key additions:
* Added a new entry for `soob3123_amoral-gemma3-4b` with URLs, description, and key modifications.
* Detailed the core function of producing analytically neutral responses, maintaining factual integrity, and avoiding value-judgment phrasing patterns.
* Specified response characteristics such as emotionally neutral tone enforcement and toxicity scoring bypass for pure informational content.
* Provided implementation guidelines and recommended …
=> chore(model gallery): add soob3123_amoral-gemma3-4b

gallery/index.yaml
This pull request includes a new entry to the `gallery/index.yaml` file for a model with experimental reward model RL training. The most important change is the addition of the new model entry.
Model entry addition:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4937-R4950): Added a new model entry for `qwen-writerdemo-7b-s500-i1`, including URLs, description, parameters, and file information.
=> chore(model gallery): add qwen-writerdemo-7b-s500-i1

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry provides details about the `Sao10K_Llama-3.3-70B-Vulpecula-r1` model, including its name, icon, URLs, description, and associated files.
* Added a new model entry for `Sao10K_Llama-3.3-70B-Vulpecula-r1` with the following details:
* Name: "sao10k_llama-3.3-70b-vulpecula-r1"
* Icon URL: `https://huggingface.co/Sao10K/Llama-3.3-70B-Vulpecula-r1/resolve/main/senkooo.jpg`
* URLs: `https://huggingface.co/Sao10K/Llama-3.3-70B-Vulpecula-r1` and `https://huggingface.co/bartowski/Sao10K_Llama-3.3-70B-Vulpecula-r1-GGUF`
* Description: A detailed description highlighting the model's features and training data (F3b63c1eL1132R
**[Signed …
=> chore(model gallery): add sao10k_llama-3.3-70b-vulpecula-r1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `luvgpt_phi3-uncensored-chat`.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR12912-R12926): Added a new model entry for `luvgpt_phi3-uncensored-chat`, including its name, icon, URLs, description, overrides, and associated file details.
=> chore(model gallery): add luvgpt_phi3-uncensored-chat

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, introducing a new model entry for the Open RS project. The changes add a detailed description of the model and its associated files, highlighting key findings and the benefits of the reinforcement learning approach used.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR7501-R7522): Added a new model entry for `knoveleng_open-rs3`, including URLs, a detailed description of the project, and associated file information. This entry describes the DeepSeek-R1-Distill-Qwen-1.5B model, its training process, and the significant improvements in reasoning capabilities achieved through reinforcement learning.
**Notes for …
=> chore(model gallery): add knoveleng_open-rs3

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "thedrummer_fallen-gemma3-4b-v1". The most important changes are:
* Added a new model entry for "thedrummer_fallen-gemma3-4b-v1" with relevant metadata, including name, icon, URLs, description, parameters, and file details.
=> chore(model gallery): add thedrummer_fallen-gemma3-4b-v1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `TheDrummer_Fallen-Gemma3-12B-v1`. The most important changes include adding the model's metadata, description, parameters, and associated files.
* Added a new model entry for `TheDrummer_Fallen-Gemma3-12B-v1` with its name, icon, URLs, description, and overrides for parameters.
* Included the file details for `TheDrummer_Fallen-Gemma3-12B-v1-Q4_K_M.gguf` with its filename, SHA256 hash, and URI.
=> chore(model gallery): add thedrummer_fallen-gemma3-12b-v1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The changes introduce a new model called "thedrummer_fallen-gemma3-27b-v1" with associated metadata and files.
* Added a new model entry "thedrummer_fallen-gemma3-27b-v1" with name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add thedrummer_fallen-gemma3-27b-v1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The change introduces a new model called `huihui-ai_gemma-3-1b-it-abliterated` with its associated metadata and file information.
* Added a new model entry named `huihui-ai_gemma-3-1b-it-abliterated` with a description and URLs.
* Included the model's parameters and file details, such as the filename, sha256 hash, and uri.
=> chore(model gallery): add huihui-ai_gemma-3-1b-it-abliterated

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, introducing a new model entry.
* Added the `mawdistical_mawdistic-nightlife-24b` model with multiple URLs and a detailed description, including parameters and file information.
=> chore(model gallery): add mawdistical_mawdistic-nightlife-24b

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file. The change introduces a new vision model entry with detailed metadata and file information.
New vision model entry:
* Added a new entry for `sicariussicariistuff_x-ray_alpha` including name, icon, URLs, description, and file details.
=> chore(model gallery): add sicariussicariistuff_x-ray_alpha

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new entry for the `Fiendish_LLAMA_3B` model. The most important changes include the addition of the model's metadata, description, and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2305-R2324): Added a new model entry for `Fiendish_LLAMA_3B`, including its name, icon URL, description, and associated files.
=> chore(model gallery): add fiendish_llama_3b

gallery/index.yaml
This pull request includes a new model entry in the `gallery/index.yaml` file. The most important changes are:
* Added a new model entry for "impish_llama_3b" with its corresponding details. This includes its name, icon URL, description, overrides, and file information.
=> chore(model gallery): add impish_llama_3b

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file, introducing a new model entry with detailed metadata and descriptions.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR2340-R2360): Added a new model entry for `eximius_persona_5b` with metadata including name, icon URL, description, and associated files. This entry provides a comprehensive overview of the model's capabilities and background, emphasizing the uniqueness of merges in model training.
=> chore(model gallery): add eximius_persona_5b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, named "dusk_rainbow," includes detailed metadata such as its description, icon, and file information.
Key changes:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR12438-R12455): Added a new model entry "dusk_rainbow" with associated metadata, including the icon URL, description, and file details.
=> chore(model gallery): add dusk_rainbow

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `jdineen_llama-3.1-8b-think`. The most important changes are as follows:
* Added a new model entry for `jdineen_llama-3.1-8b-think` with relevant URLs, description, parameters, and file details.
=> chore(model gallery): add jdineen_llama-3.1-8b-think

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The change introduces a detailed description and relevant metadata for the `helpingai_helpingai3-raw` model.
Key changes:
* Added a new model entry for `helpingai_helpingai3-raw` with URLs, description, and file metadata.
=> chore(model gallery): add helpingai_helpingai3-raw

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, introducing a new model entry with detailed information.
* Added a new model entry for "alamios_mistral-small-3.1-draft-0.5b" including its URLs, description, and associated file details.
=> chore(model gallery): add alamios_mistral-small-3.1-draft-0.5b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the "gemma-3-glitter-12b-i1" model with its relevant metadata and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR319-R337): Added the "gemma-3-glitter-12b-i1" model with its name, icon URL, description, parameters, and file details.
=> chore(model gallery): add gemma-3-glitter-12b-i1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The new entry provides details for the "blacksheep-24b-i1" model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR9015-R9030): Added a new model entry for "blacksheep-24b-i1" with its description, icon, URLs, and file details.
=> chore(model gallery): add blacksheep-24b-i1

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model is a finetune of Llama 3.1 8B, named "textsynth-8b-i1," and is designed for creative writing and brainstorming sessions.
Key changes:
* Added a new model entry for "textsynth-8b-i1" with descriptions, URLs, and file details.
=> chore(model gallery): add textsynth-8b-i1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `soob3123_amoral-gemma3-12B-v2`. The most important changes include adding metadata, description, and file details for the new model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR338-R362): Added a new model entry for `soob3123_amoral-gemma3-12B-v2` with metadata, description, and file details.
=> chore(model gallery): add soob3123_amoral-gemma3-12b-v2

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file. The change adds a new entry for the "Thoughtless-Fallen-Abomination-70B-R1-v4.1-i1" model, including its metadata and file information.
* Added `"Thoughtless-Fallen-Abomination-70B-R1-v4.1-i1"` to the gallery with a description, icon URL, and file details.
=> chore(model gallery): thoughtless-fallen-abomination-70b-r1-v4.1-i1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry. The new entry introduces the "Fallen-Safeword-70B-R1-v4.1" model with its associated metadata.
Key changes:
* Added a new model entry for "Fallen-Safeword-70B-R1-v4.1" with a description, icon URL, and download URLs.
* Included parameters and file details specific to the new model.
=> chore(model gallery): fallen-safeword-70b-r1-v4.1

gallery/index.yaml
This pull request adds a new model to the `gallery/index.yaml` file. The new model, named "tarek07_legion-v2.1-llama-70b," includes detailed metadata and a list of the models used in its creation.
* Added a new model entry `tarek07_legion-v2.1-llama-70b` with its corresponding metadata, including name, icon, URLs, description, overrides, and file details.
=> chore(model gallery): add tarek07_legion-v2.1-llama-70b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, `tesslate_tessa-t1-32b`, is designed for React frontend development and includes several key features.
* Added `tesslate_tessa-t1-32b` model entry with description, icon, URLs, and file details. The model is fine-tuned from the Qwen2.5-Coder-32B-Instruct base model and is designed to generate semantic React components.
=> chore(model gallery): add tesslate_tessa-t1-32b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `Tesslate_Tessa-T1-14B`. The most important changes include the addition of the model's metadata, description, and associated files.
* Added a new model entry for `Tesslate_Tessa-T1-14B` with metadata such as name, icon, and URLs.
* Included a detailed description of the model's capabilities, highlighting its React-specific reasoning, agent integration, and context-aware generation features.
* Listed the model's parameters and associated files, including their filenames, SHA256 checksums, and URIs.
=> chore(model gallery): add tesslate_tessa-t1-14b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model, `Tesslate_Tessa-T1-7B`, with detailed information and metadata.
* Added a new model entry `tesslate_tessa-t1-7b` with its name, icon URL, description, and associated files. The description highlights its capabilities in React-specific reasoning, agent integration, and context-aware generation.
=> chore(model gallery): add tesslate_tessa-t1-7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model configuration for `Tesslate_Tessa-T1-3B`.
* Added a new model configuration for `Tesslate_Tessa-T1-3B`, including its name, icon, URLs, description, and associated file details. The model is designed for React-specific reasoning and integrates seamlessly into AI-driven coding agents and autonomous frontend systems.
=> chore(model gallery): add tesslate_tessa-t1-3b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry. The most important change is the addition of the "chaoticneutrals_very_berry_qwen2_7b" model with its metadata and file details.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR5344-R5358): Added a new model entry "chaoticneutrals_very_berry_qwen2_7b" with its name, icon URL, description, and file details.
=> chore(model gallery): add chaoticneutrals_very_berry_qwen2_7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "Galactic-Qwen-14B-Exp1". The entry includes various details about the model such as its name, icon, URLs, description, and file information.
Key changes:
* Added a new model entry named "Galactic-Qwen-14B-Exp1" with a detailed description, icon, and URLs.
* Included the model file `Galactic-Qwen-14B-Exp1.Q4_K_M.gguf` with its corresponding SHA256 checksum and URI.
=> chore(model gallery): add galactic-qwen-14b-exp1

gallery/index.yaml
This pull request includes a new entry in the `gallery/index.yaml` file for a model named "forgotten-abomination-70b-v5.0". The change adds detailed metadata for the model, including its name, icon, URLs, description, and file details.
Key changes:
* Added a new model entry "forgotten-abomination-70b-v5.0" with the following attributes:
- Name: "forgotten-abomination-70b-v5.0"
- Icon URL: `https://huggingface.co/ReadyArt/Forgotten-Abomination-70B-v5.0/resolve/main/waifu5.webp`
- URLs: 
- `https://huggingface.co/ReadyArt/Forgotten-Abomination-70B-v5.0`
- `https://huggingface.co/mradermacher/Forgotten-Abomination-70B-v5.0-GGUF`
- Description: Detailed description of the model's capabilities and specializations.
- Overrides: Parameters for the model.
- Files: Details of the …
=> chore(model gallery): add forgotten-abomination-70b-v5.0

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "hammer2.0-7b". The most important changes include adding the model's metadata, description, and file details.
Additions to the model gallery:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR5399-R5412): Added a new entry for "hammer2.0-7b" with metadata, URLs, description, and file details.
=> chore(model gallery): add hammer2.0-7b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `burtenshaw_gemmacoder3-12b`. 
* Added a new model entry for `burtenshaw_gemmacoder3-12b` with its details including name, icon, URLs, description, overrides, and files.
=> chore(model gallery): add burtenshaw_gemmacoder3-12b

Makefile, backend/cpp/llama/grpc-server.cpp
This PR supercedes https://github.com/mudler/LocalAI/pull/5109
=> chore(deps): bump llama.cpp to 'f01bd02376f919b05ee635f438311be8dfc91d7c

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for the Gemma 3 series. The most important change is the addition of the Gemma 3 12B instruction-tuned model with Quantization Aware Training (QAT).
* Added a new entry for the "gemma-3-12b-it-qat" model, which includes URLs, a description, and file details. This model is a 12B instruction-tuned version of the Gemma 3 model in GGUF format using QAT, which preserves similar quality as bfloat16 while reducing memory requirements.
=> chore(model gallery): add gemma-3-12b-it-qat

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new AI model to the gallery. The most important change is the addition of the `tesslate_synthia-s1-27b` model, which includes detailed information about the model and its capabilities.
New AI model addition:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR440-R454): Added the `tesslate_synthia-s1-27b` model with its name, icon, URLs, description, parameters, and file details.
=> chore(model gallery): add tesslate_synthia-s1-27b

gallery/index.yaml
This pull request includes significant updates to the `gallery/index.yaml` file, specifically adding a new model to the gallery. The most important change is the addition of the "katanemo_arch-function-chat-1.5b" model, which extends the capabilities of the existing Katanemo's Arch-Function collection.
* Added a new model entry "katanemo_arch-function-chat-1.5b" with detailed description and URLs. This model enhances the existing Arch-Function collection by adding features like natural follow-up question generation, human-friendly response interpretation, and context management in multi-turn interactions.
=> chore(model gallery): add katanemo_arch-function-chat-1.5b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model to the gallery. The most important changes include adding the new model `katanemo_arch-function-chat-3b` with its associated metadata and files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR5613-R5634): Added the `katanemo_arch-function-chat-3b` model, including its name, URLs, description, parameters, and associated files.
=> chore(model gallery): add katanemo_arch-function-chat-3b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for the Gemma 3 series. The most important change is the addition of the Gemma 3-27B IT QAT model, which includes detailed metadata and file information.
Changes to the `gallery/index.yaml` file:
* Added a new model entry for `gemma-3-27b-it-qat`, including URLs, description, overrides, and file details. This model is a 27B instruction-tuned version of the Gemma 3 model in GGUF format using Quantization Aware Training (QAT).
=> chore(model gallery): add gemma-3-27b-it-qat

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `open-thoughts_openthinker2-32b`. The most important changes include the addition of metadata and file information for the new model.
* Added a new model entry for `open-thoughts_openthinker2-32b` with relevant metadata, including name, icon, URLs, description, and overrides.
* Included file details such as filename, sha256 checksum, and URI for the new model.
=> chore(model gallery): add open-thoughts_openthinker2-32b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for `open-thoughts_openthinker2-7b`. The most important changes are as follows:
* Added a new model entry for `open-thoughts_openthinker2-7b` with relevant metadata including name, icon, URLs, description, and file details.
The new model entry provides detailed information about the `open-thoughts_openthinker2-7b` model, such as its performance and dataset used for fine-tuning.
=> chore(model gallery): add open-thoughts_openthinker2-7b

Makefile, backend/cpp/llama/CMakeLists.txt, backend/cpp/llama/grpc-server.cpp, backend/cpp/llama/prepare.sh
This PR supercedes https://github.com/mudler/LocalAI/pull/5125
=> chore: :arrow_up: Update ggml-org/llama.cpp to `6bf28f0111ff9f21b3c1b1eace20c590281e7ba6`

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new entry for the `ArliAI_QwQ-32B-ArliAI-RpR-v1` model. The most important changes include adding detailed metadata and description for the new model, which focuses on roleplay with reasoning.
* Added a new entry for `ArliAI_QwQ-32B-ArliAI-RpR-v1` with its name, icon, URLs, description, and file details. This model is designed for roleplay with reasoning, leveraging the RPMax dataset and a unique training methodology to ensure high-quality, coherent outputs in long multi-turn chats.
=> chore(model gallery): add arliai_qwq-32b-arliai-rpr-v

gallery/index.yaml
This pull request includes a significant addition to the `gallery/index.yaml` file. A new entry for the `watt-ai_watt-tool-70b` model has been added, detailing its features, target applications, and associated files.
* Added `watt-ai_watt-tool-70b` model entry, including a description, key features, and target applications. This model is fine-tuned for tool usage and multi-turn dialogue, achieving state-of-the-art performance on the Berkeley Function-Calling Leaderboard (BFCL).
* Included URLs for downloading the model from Hugging Face, and provided details about the model's parameters and associated file with its SHA-256 hash.
=> chore(model gallery): add watt-ai_watt-tool-70b

gallery/index.yaml
This pull request includes an important addition to the `gallery/index.yaml` file. The change introduces a new model, Eurydice 24b v2, to the gallery with detailed metadata and file information.
Key addition:
* Added a new model entry for "Eurydice-24b-v2-i1" with metadata including name, icon, URLs, description, parameters, and file details.
=> chore(model gallery): add eurydice-24b-v2-i1

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "mensa-beta-14b-instruct-i1".
* Added a new entry for "mensa-beta-14b-instruct-i1" with relevant details such as name, icon, URLs, description, and file information.
=> chore(model gallery): add mensa-beta-14b-instruct-i1

gallery/index.yaml
This pull request adds a new entry for the Cogito LLMs to the `gallery/index.yaml` file, detailing the Mensa-Beta-14B-Instruct model. The most important changes include:
* Added a new entry for the Mensa-Beta-14B-Instruct model with details such as name, icon, URLs, description, and file parameters.
This update enriches the gallery with additional information and resources for the Mensa-Beta-14B-Instruct model, highlighting its capabilities and providing relevant links for further exploration.
=> chore(model gallery): add cogito-v1-preview-qwen-14b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for the Cogito LLMs. The addition includes detailed information about the new model, its capabilities, and relevant metadata.
* Addition of a new model entry `deepcogito_cogito-v1-preview-qwen-32b` with associated metadata, including name, icon, URLs, and description.
* Inclusion of model-specific parameters and files under the new entry.
=> chore(model gallery): add deepcogito_cogito-v1-preview-qwen-32b

gallery/index.yaml
llama 70b version of deepcogito
=> chore(model gallery): add deepcogito_cogito-v1-preview-llama-70b

gallery/index.yaml
This pull request includes an addition to the `gallery/index.yaml` file, introducing a new model configuration for `soob3123_amoral-cogito-v1-preview-qwen-14B`.
Key changes:
* Added a new model entry `soob3123_amoral-cogito-v1-preview-qwen-14B` with detailed descriptions, use cases, and file information.
=> chore(model gallery): add soob3123_amoral-cogito-v1-preview-qwen-14b

gallery/index.yaml
This pull request includes a significant update to the `gallery/index.yaml` file, adding a new model entry for `agentica-org_deepcoder-1.5b-preview`. The most important changes are:
* Addition of a new model entry:
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR8532-R8552): Added the `agentica-org_deepcoder-1.5b-preview` model with URLs, description, parameters, and file details.
=> chore(model gallery): add agentica-org_deepcoder-1.5b-preview

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for `zyphra_zr1-1.5b`. 
The most important change includes:
* Added a new model entry for `zyphra_zr1-1.5b` with detailed metadata including URLs, description, parameters, and file information.
=> chore(model gallery): add zyphra_zr1-1.5b

gallery/index.yaml
This pull request includes a new model entry in the `gallery/index.yaml` file. The addition introduces the `Tesslate_Gradience-T1-3B-preview` model, which is currently in beta and designed for Gradient Reasoning. The most important changes include:
* Added `Tesslate_Gradience-T1-3B-preview` model entry with a detailed description, URLs, and parameters. This model is intended for faster problem-solving using a step-by-step reasoning process enclosed within specific tags.
=> chore(model gallery): add tesslate_gradience-t1-3b-preview

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file, adding a new model entry for "mag-picaro-72b". The most important changes include the addition of the model's metadata, description, and associated files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR5910-R5925): Added a new entry for the "mag-picaro-72b" model, including its name, icon, URLs, description, parameters, and associated files.
=> chore(model gallery): add mag-picaro-72b

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for "hamanasu-adventure-4b-i1". The most important changes include adding the model's details, such as its name, URL, icon, description, and file information.
* Added a new model entry for "hamanasu-adventure-4b-i1" with details including name, URL, icon, description, and file information.
=> chore(model gallery): add hamanasu-adventure-4b-i1

gallery/index.yaml
This pull request includes updates to the `gallery/index.yaml` file to add a new model entry. The new entry includes details such as the name, URL, icon, description, and file information.
Changes include:
* Added a new model entry for `hamanasu-magnum-4b-i1` with relevant metadata, including name, URL, icon, description, and parameters.
=> chore(model gallery): add hamanasu-magnum-4b-i1

gallery/index.yaml
This pull request includes a new entry in the `gallery/index.yaml` file. The entry adds a new model called "daichi-12b" with relevant metadata and file information.
* Added a new model entry named "daichi-12b" with an icon URL, description, and file details. This model is a merge between a Gemma-Finetune of Pascal-12B and Omega-Directive-G-12B, intended to enhance NSFW knowledge and uncensored roleplay capabilities.
=> chore(model gallery): add daichi-12b

gallery/index.yaml
This pull request includes updates to the `gallery/index.yaml` file to add a new model series and its associated metadata.
New model series addition:
* Added `Skywork-OR1-32B-Preview` to the `gallery/index.yaml` file with descriptions, URLs, and file details. This model series includes general-purpose reasoning models and a math-specialized model, optimized for mathematical and coding tasks.
=> chore(model gallery): add skywork_skywork-or1-32b-preview

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new language model entry. The most important change is the addition of the `nvidia_Llama-3.1-8B-UltraLong-1M-Instruct` model, which is designed to process extensive sequences of text while maintaining competitive performance on standard benchmarks.
Key changes:
* Added a new entry for the `nvidia_Llama-3.1-8B-UltraLong-1M-Instruct` model, including its name, icon URL, description, parameters, and file details.
=> chore(model gallery): add nvidia_llama-3.1-8b-ultralong-1m-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new model entry for `nvidia_Llama-3.1-8B-UltraLong-4M-Instruct`. The most important changes are as follows:
* Added a new entry for `nvidia_Llama-3.1-8B-UltraLong-4M-Instruct` with its corresponding name, icon, URLs, description, parameters, and file details.
=> chore(model gallery): add nvidia_llama-3.1-8b-ultralong-4m-instruct

gallery/index.yaml
This pull request includes an update to the `gallery/index.yaml` file to add a new large language model entry. The new model, `m1-32b`, is described and its relevant metadata and files are included.
* Added `m1-32b` model entry with a description, URLs, and file details. This model is a 32B-parameter large language model fine-tuned from Qwen2.5-32B-Instruct on the M500 dataset, optimized for multi-agent systems.
=> chore(model gallery): add m1-32b

gallery/index.yaml
This PR add bark-cpp model. You can now choose between this (large) and the small one already available.
=> chore(model gallery): add suno-ai bark-cpp model

gallery/index.yaml
This pull request adds a new entry for the `thedrummer_rivermind-12b-v1` model to the `gallery/index.yaml` file. The entry includes metadata, URLs, a detailed description, and file information for the model.
* **Model metadata**: Added a new entry for the `thedrummer_rivermind-12b-v1` model, including its name, icon, and description. The description highlights the model's features, such as emotional analysis, cloud integration, and data security, with a marketing-style tone.
* **URLs**: Provided two URLs to access the model on Hugging Face, one under the `TheDrummer` namespace and another under the `bartowski` namespace.
* **Overrides and file details**: Added overrides for model parameters and included file information, such as the filename, SHA-256 checksum, and URI for …
=> chore(model gallery): add thedrummer_rivermind-12b-v1

gallery/index.yaml
This PR fixes https://github.com/mudler/LocalAI/issues/5197
=> chore(model gallery): add qwen2.5-14b-instruct-1m

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to include a new model entry for "IBM Granite-3.3-8B-Instruct." The addition provides detailed metadata and download links for the model, which is fine-tuned for reasoning and instruction-following tasks.
* **IBM Granite-3.3-8B-Instruct**:
- Added a new entry for the "IBM Granite-3.3-8B-Instruct" model, including its name, description, parameters, and associated files. The model is a fine-tuned 2-billion parameter language model designed for improved reasoning and instruction-following, supporting structured reasoning tags like `<think>` and `<response>`.
=> chore(model gallery): add ibm-granite_granite-3.3-8b-instruct

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, providing detailed metadata and configuration for the "ReadyArt Amoral-Fallen-Omega-Gemma3-12B" model.
* Added a new model entry named `"readyart_amoral-fallen-omega-gemma3-12b"` with metadata including a description, icon, and multiple URLs linking to its Hugging Face repositories. The description highlights the model's capabilities, such as long-form storytelling, handling multi-character scenarios, and improved narrative flow.
* Included overrides for model parameters and file details, specifying the filename, SHA256 checksum, and URI for downloading the associated model file.
=> chore(model gallery): add readyart_amoral-fallen-omega-gemma3-12b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The addition includes details about the `Llama_3.3_70b_DarkHorse-i1` model, providing metadata, download URLs, a description, and file information.
* **Model Name:** `Llama_3.3_70b_DarkHorse-i1`
* **URLs:** Includes two Hugging Face links for downloading the model.
* **Description:** Provides an overview of the model's purpose, performance, and characteristics, highlighting its darker tone and potential for specific use cases.
* **Overrides:** Specifies parameters for the model, including the file name and format (`Llama_3.3_70b_DarkHorse.i1-Q4_K_M.gguf`).
* **File Information:** Includes the file name, SHA256 checksum, and URI for accessing the model file.
**[Signed …
=> chore(model gallery) add llama_3.3_70b_darkhorse-i1

gallery/index.yaml
This pull request adds a new entry for the `amoral-gemma3-1b-v2` model to the `gallery/index.yaml` file. The entry includes metadata, file details, and descriptive characteristics of the model.
* **Model name and metadata**: Added a new entry for the `amoral-gemma3-1b-v2` model, including its name, icon URL, and description. The description highlights the model's core function (neutral responses to sensitive queries) and response characteristics (emotionally neutral tone, epistemic humility, etc.).
* **URLs and file details**: Included URLs to the model's Hugging Face pages and details for the associated file (`amoral-gemma3-1B-v2.Q4_K_M.gguf`), such as its SHA256 hash and URI.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-ce …
=> chore(model gallery) add amoral-gemma3-1b-v2

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing a Mistral-based model named "StarrySky-12B-i1" with details about its sources, description, and associated files.
* **New Model Entry**: Added a new model, "StarrySky-12B-i1," which is a Mistral model with ChatML tokens integrated into the tokenizer. The entry includes:
- A name, URL, and icon for the model.
- A description outlining the merge of two models: `Elizezen/Himeyuri-v0.1-12B` and `inflatebot/MN-12B-Mag-Mell-R1`.
- Overrides for model parameters and file details, including a file (`StarrySky-12B.i1-Q4_K_M.gguf`) with its SHA256 checksum and URI.
=> chore(model gallery): add starrysky-12b-i1

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new model, `soob3123_veritas-12b`, is described as a 12B parameter model designed for philosophical reasoning and analytical tasks.
* Added the `soob3123_veritas-12b` model entry, including its name, icon, URLs, description, parameter overrides, and associated file details. The model is highlighted for its capabilities in philosophical reasoning, ethical analysis, and logical argumentation. (`[gallery/index.yamlR559-R573](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR559-R573)`)
=> chore(model gallery): add soob3123_veritas-12b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry includes metadata and details for the `L3.3-GeneticLemonade-Unleashed-v2-70B` model, which is an experimental release designed for character-driven roleplay and creative use cases.
* **New Model Entry**: Added the `L3.3-GeneticLemonade-Unleashed-v2-70B` model with the following details:
- Name: `"l3.3-geneticlemonade-unleashed-v2-70b"`
- Icon URL: A link to the model's icon hosted on Hugging Face. 
- Description: Includes information about its experimental nature, training details, and intended use cases (e.g., character-driven RP/ERP). 
- Overrides: Specifies the model parameters and associated file details.
- Files: Added a file entry with its `filename`, `sha256` checksum, and `uri` …
=> chore(model gallery): add l3.3-geneticlemonade-unleashed-v2-70b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, enhancing the gallery with additional metadata and resources for the `L3.3-Genetic-Lemonade-Sunset-70B` model.
* Introduced a new model, `l3.3-genetic-lemonade-sunset-70b`, with metadata including an icon, description, and URLs for the model's resources. The description highlights its focus on RP and creative writing, balancing writing style, creativity, and intelligence.
* Added specific file details for the model, including its filename, SHA-256 checksum, and URI for retrieval from Hugging Face.
=> chore(model gallery): add l3.3-genetic-lemonade-sunset-70b

core/cli/run.go, docs/content/docs/advanced/advanced-usage.md
This PR fixes #2484 
This PR updates the docs for `DisableWebUI` flag to provide a clearer description of its functionality.
* [`core/cli/run.go`](diffhunk://#diff-6942db52f4890e363e6c8bc256fbc5f0d4d9521ea0448f558d254446bf94ddb9L49-R49): Updated the help text for the `DisableWebUI` flag to clarify that enabling this option disables the web UI and exposes only API endpoints.
* [`docs/content/docs/advanced/advanced-usage.md`](diffhunk://#diff-3a2b17591dd6f3a6f1d68629079fcc1256485fd19f3afb09c73d37582816601cR517): Added entry for `--disable-webui` flag in advanced usage guide.
=> docs: update docs for DisableWebUI flag

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the NVIDIA OpenMath-Nemotron-32B model. The addition includes metadata, file details, and descriptions for the model.
* Added a new entry for the `nvidia_openmath-nemotron-32b` model, including its name, icon, URLs, description, and associated file details. The description highlights its fine-tuning on the OpenMathReasoning dataset and its state-of-the-art performance on mathematical benchmarks.
=> chore(model gallery): add nvidia_openmath-nemotron-32b

gallery/index.yaml
This pull request adds a new entry for the `nvidia_openmath-nemotron-1.5b` model to the `gallery/index.yaml` file. The entry includes metadata, URLs, a description, and file details for the model.
* Added a new model, `nvidia_openmath-nemotron-1.5b`, including its name, icon, and description. The description highlights its fine-tuning process, commercial readiness, and performance on mathematical benchmarks.
* Included URLs pointing to the model's Hugging Face pages for more details.
* Defined file details, including the filename, SHA-256 checksum, and URI for the associated model file.
=> chore(model gallery): add nvidia_openmath-nemotron-1.5b

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing the OpenMath-Nemotron-7B model with relevant metadata and file details.
* Added a new model entry `nvidia_openmath-nemotron-7b` with metadata including name, icon, description, and associated URLs. The description highlights its fine-tuning on the OpenMathReasoning dataset and its readiness for commercial use.
* Included file details for the model, such as `filename`, `sha256` checksum, and `uri` for accessing the model file.
=> chore(model gallery): add nvidia_openmath-nemotron-7b

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the NVIDIA OpenMath-Nemotron-14B-Kaggle model. The update provides metadata, file details, and descriptions for this model.
* Added a new entry for the `nvidia_openmath-nemotron-14b-kaggle` model, including its name, icon, description, and relevant URLs. The description highlights its fine-tuning on the OpenMathReasoning dataset and its use in the AIMO-2 Kaggle competition.
* Included file details for the model (`nvidia_OpenMath-Nemotron-14B-Kaggle-Q4_K_M.gguf`), such as its `sha256` hash and URI.
=> chore(model gallery): add nvidia_openmath-nemotron-14b-kaggle

gallery/index.yaml, gallery/qwen3.yaml
This pull request introduces a new entry for the Qwen3 model in the gallery, including its metadata and configuration details. The changes add comprehensive documentation about the model's features, capabilities, and configuration.
* Added a new entry for the Qwen3 model (`qwen3-30b-a3b`) in `gallery/index.yaml`, including details such as URLs, icon, license, description, tags, overrides, and associated files. The description highlights its advanced reasoning, multilingual support, and agent capabilities.
* Created a new configuration file `gallery/qwen3.yaml` for the Qwen3 model. This file defines the model's settings, including memory mapping, templates for chat and function calls, context size, floating-point precision, and stopwords.
**[Signed …
=> chore(model gallery): add qwen3-30b-a3b

gallery/index.yaml
This pull request adds a new entry for the Qwen3-32B model to the `gallery/index.yaml` file. The addition provides detailed information about the model's features, capabilities, and specifications.
* Introduced a new model entry named `qwen3-32b` with links to its resources on Hugging Face.
* Included a comprehensive description of the model's features, such as its ability to switch between thinking and non-thinking modes, enhanced reasoning capabilities, multilingual support, and agent integration.
* Specified technical details like the number of parameters (32.8B), layers (64), attention heads, and context length (up to 131,072 tokens with YaRN).
* Added file information for the model, including filename, SHA256 hash, and URI for downloading. …
=> chore(model gallery): add qwen3-32b

gallery/index.yaml
This pull request adds a new model entry, `qwen3-8b`, to the `gallery/index.yaml` file. The addition includes detailed metadata about the model, such as its description, features, and associated files.
* Added a new model, `qwen3-8b`, to the gallery with comprehensive details about its capabilities, including reasoning, multilingual support, and agent features. The description highlights its ability to switch between thinking and non-thinking modes and its advancements over previous models in the Qwen series.
* Included metadata for `qwen3-8b`, such as model type, training stages, parameter counts, and context length, along with file details like the filename, SHA-256 hash, and URI.
**[Signed …
=> chore(model gallery): add qwen3-8b

gallery/index.yaml
This pull request adds a new entry for the Qwen3-4B model to the `gallery/index.yaml` file. The change includes detailed metadata and descriptions for the model, highlighting its features and capabilities.
* **New Model Entry**: Added the Qwen3-4B model with metadata, including URLs, description, and technical specifications. The model is part of the Qwen3 series, emphasizing advanced reasoning, multilingual support, and agent capabilities.
=> chore(model gallery): add qwen3-4b

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to add a new entry for the Qwen3-1.7B model, providing detailed metadata and descriptions for this large language model.
* **New Model Entry: Qwen3-1.7B**:
- Added metadata for the Qwen3-1.7B model, including URLs, description, and key features.
- Highlighted the model's unique capabilities, such as seamless mode switching, enhanced reasoning, multilingual support, and agent capabilities.
- Provided technical specifications, including parameter counts, number of layers, attention heads, and context length.
- Included file details (`filename`, `sha256`, and `uri`) for the model's GGUF format.
=> chore(model gallery): add qwen3-1.7b

aio/gpu-8g/text-to-text.yaml
Signed-off-by: Richard Palethorpe <io@richiejp.com>
=> fix(aio): Fix copypasta in download files for gpt-4 model

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to add a new model entry for `Qwen3-14B-abliterated`. The addition includes metadata, file details, and references to external resources.
* Added a new model entry named `mlabonne_qwen3-14b-abliterated` with the following details:
- URLs pointing to Hugging Face repositories for the model.
- A description stating it is a 14B parameter model named "abliterated."
- Overrides specifying the associated model file.
- File details, including filename, SHA-256 hash, and URI for the model file.
=> chore(model gallery): add mlabonne_qwen3-14b-abliterated

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The change introduces metadata and configuration for the `mlabonne_qwen3-8b-abliterated` model.
* **Model name**: `mlabonne_qwen3-8b-abliterated`
* **Description**: An 8B parameter model named "Qwen3-8B-abliterated."
* **URLs**: Links to the model on Hugging Face, including two repositories.
* **Files**: Includes a file `mlabonne_Qwen3-8B-abliterated-Q4_K_M.gguf` with its SHA-256 checksum and URI for retrieval.
=> chore(model gallery): add mlabonne_qwen3-8b-abliterated

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry introduces the "mlabonne_qwen3-4b-abliterated" model with its metadata, including URLs, description, parameters, and file information.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR261-R274): Added a new entry for the "mlabonne_qwen3-4b-abliterated" model, including its name, URLs, description, parameters, and associated file metadata.
=> chore(model gallery): add mlabonne_qwen3-4b-abliterated

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the "Qwen3-30B-A3B-abliterated" model. The entry includes metadata such as the name, description, URLs, and file details.
* Added a new model entry for "Qwen3-30B-A3B-abliterated," including its name, description, URLs, and file metadata. This entry uses the `!!merge` YAML feature to inherit properties from the `*qwen3` anchor.
=> chore(model gallery): add qwen3-30b-a3b-abliterated

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for a jailbroken version of the Qwen3-8B model. The entry includes metadata, descriptions, and file references for the model.
* **New model: Qwen3-8B-Jailbroken**:
- Added metadata, including the name, description, and academic research disclaimer for the jailbroken Qwen3-8B model. The description highlights its use for AI safety and alignment studies and provides a reference to the implementation script and related research paper.
- Included URLs pointing to the model's location on Hugging Face.
- Defined file details, such as the filename, SHA-256 checksum, and URI for the model file.
=> chore(model gallery): add qwen3-8b-jailbroken

gallery/index.yaml
This pull request adds a new entry for the `Phi-4-mini-reasoning` model to the `gallery/index.yaml` file. The entry provides detailed information about the model, including its description, use cases, limitations, and associated files.
* **Added `Phi-4-mini-reasoning` model entry**:  
The `Phi-4-mini-reasoning` model is introduced as part of the Phi-4 family. It is a compact, transformer-based language model optimized for advanced mathematical reasoning tasks. The entry includes:  
- A description highlighting its focus on multi-step, logic-intensive problem-solving, and its suitability for constrained environments.  
- Use cases such as formal proof generation, symbolic computation, and educational applications.  
- Warnings about its design limitations and considerations …
=> chore(model gallery): add microsoft_phi-4-mini-reasoning

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing a new model to the gallery with detailed metadata.
* **New model entry for "Josiefied-Qwen3-8B-abliterated-v1"**:
- Added metadata, including name, description, URLs, and file details, for the new "Josiefied-Qwen3-8B-abliterated-v1" model.
- The model is part of the JOSIEFIED family, known for its fine-tuning on advanced architectures to enhance openness, instruction-following, and uncensored behavior.
=> chore(model gallery): add josiefied-qwen3-8b-abliterated-v1

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry describes the "Furina-8B" model, which is fine-tuned to represent the character Furina from Genshin Impact.
* **New model entry for "Furina-8B"**: Added details including the name, URLs, description, overrides, and file information for the "Furina-8B" model. This model is fine-tuned to embody Furina, the Hydro Archon and Judge of Fontaine from Genshin Impact.
=> chore(model gallery): add furina-8b

gallery/index.yaml
This pull request adds a new entry for the `microsoft_phi-4-reasoning-plus` model to the `gallery/index.yaml` file. The entry includes metadata, file details, and links to the model's resources.
* **Model metadata**:
- Added a new model named `microsoft_phi-4-reasoning-plus`, described as a state-of-the-art reasoning model fine-tuned from Phi-4. It incorporates supervised fine-tuning and reinforcement learning to enhance reasoning accuracy, with a focus on math, science, and coding skills.
* **URLs**:
- Included links to the model's resources on Hugging Face.
* **Files and overrides**:
- Defined the associated file `microsoft_Phi-4-reasoning-plus-Q4_K_M.gguf` with its SHA-256 hash and URI, and specified model parameters in the `overrides` section. …
=> chore(model gallery): add microsoft_phi-4-reasoning-plus

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to add a new model entry for "microsoft_phi-4-reasoning." The change includes metadata and configuration details for the model.
* Added a new entry for the "microsoft_phi-4-reasoning" model, including its name, description, URLs, and file details. The model is described as a state-of-the-art reasoning model fine-tuned using supervised learning and reinforcement learning, with a focus on advanced reasoning in math, science, and coding.
=> chore(model gallery): add microsoft_phi-4-reasoning

gallery/index.yaml
This pull request adds a new entry for the Shuttle 3.5 model to the `gallery/index.yaml` file. The entry includes metadata, descriptions, and file details for the model.
* Added a new model entry for `shuttleai_shuttle-3.5`:
- Includes metadata such as name, icon URL, and feature descriptions.
- Highlights the model's capabilities, including reasoning enhancements, multilingual support, and agent-based task expertise.
- Provides detailed specifications, such as parameter counts, context length, and training stages.
- Lists associated files with SHA-256 checksums and Hugging Face URIs.
=> chore(model gallery): add shuttleai_shuttle-3.5

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing the WebThinker-QwQ-32B model. The addition includes detailed metadata and descriptions for the model's capabilities, as well as file references for its usage.
* **WebThinker-QwQ-32B**: Added metadata for the WebThinker-QwQ-32B model, which is part of the WebThinker series. This model supports autonomous web exploration, real-time knowledge integration with report drafting, and RL-based training for enhanced performance. The entry includes URLs, a description of its features, parameter overrides, and file references.
=> chore(model gallery): add webthinker-qwq-32b-i1

gallery/index.yaml
This pull request introduces a new entry to the `gallery/index.yaml` file, adding metadata and details for a newly merged pre-trained language model, `Planetoid_27B_V.2`. The update includes its description, performance characteristics, supported languages, and associated files.
* **Model Name and Metadata**: Added a new model entry, `Planetoid_27B_V.2`, which is a merge of pre-trained `gemma3` language models. The metadata specifies the model's purpose, including its suitability for assistant tasks, roleplay, and creative writing.
* **URLs and Files**: Included links to the model's hosting locations on Hugging Face, along with the associated file details (`Planetoid_27B_V.2.Q4_K_M.gguf`) such as its `sha256` checksum and URI.
* **Performance Description**: Documented the …
=> chore(model gallery): add planetoid_27b_v.2

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to include a new merged language model entry, `comet_12b_v.5-i1`, along with its metadata and file details.
* Added a new model entry named `comet_12b_v.5-i1`. This includes its description, URLs, parameters, and associated file details such as filename, SHA256 hash, and URI. The description highlights improvements over the previous version (V.4) in terms of stability and performance.
=> chore(model gallery): add comet_12b_v.5-i1

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, expanding the gallery with detailed information about the `amoral-qwen3-14b` model.
* **New Model Entry**: Added the `amoral-qwen3-14b` model with metadata, including name, icon URL, description, and file details. This model is designed to produce analytically neutral responses, maintain factual integrity, and enforce an emotionally neutral tone. It also includes "epistemic humility protocols" to avoid overly enthusiastic language.
=> chore(model gallery): add amoral-qwen3-14b

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for a fine-tuned version of the Qwen3-32B model, optimized for medical reasoning tasks. The addition includes metadata, file details, and references to the fine-tuning process.
* **Model Name**: `qwen-3-32b-medical-reasoning-i1`
* **Description**: Fine-tuned Qwen3-32B model for medical reasoning using a specialized dataset with 4-bit quantization for memory efficiency. Original model card credited to @kingabzpro.
* **URLs**: Links to the Hugging Face repositories hosting the model.
* **Overrides**: Specifies the model parameters and associated file details.
* **File Information**: Includes filename, SHA-256 checksum, and URI for the fine-tuned model file.
**[Signed …
=> chore(model gallery): add qwen-3-32b-medical-reasoning-i1

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file to include the Smoothie Qwen model. The change introduces metadata and configuration details for the model, enabling its integration into the gallery.
* Added a new model entry for `smoothie-qwen3-8b` with metadata, including name, icon, description, and file details. This model is described as a lightweight adjustment tool for enhancing multilingual generation capabilities in Qwen models.
=> chore(model gallery): add smoothie-qwen3-8b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, providing details about the Qwen3-30B-A1.5B-High-Speed model. The addition includes metadata, description, and file references for the model.
* **Model name and metadata**: Added a new model entry named `qwen3-30b-a1.5b-high-speed`, including its name, icon URL, and associated URLs for accessing the model files.
* **Description**: Provided a detailed description of the model, highlighting its finetuning process, performance improvements (e.g., speed and parameter usage), and context size capabilities.
* **File references**: Included the file details (`filename`, `sha256`, and `uri`) for the model in GGUF format.
**[Signed …
=> chore(model gallery): add qwen3-30b-a1.5b-high-speed

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The entry provides details about a custom experiment involving the Qwen3 model family, specifically a pruned and modified version of the original 30B MoE.
* **Model name:** `kalomaze_qwen3-16b-a3b`
* **Description:** A custom experiment to measure expert activation probabilities and prune the least-used experts per layer in the Qwen3-30B model. The pruned model retains semi-coherent writing capabilities without additional training or distillation. Includes measurement data and exported weights.
* **Files and metadata:** Added associated file `kalomaze_Qwen3-16B-A3B-Q4_K_M.gguf` with its SHA256 hash and URI for retrieval.
**[Signed …
=> chore(model gallery): add kalomaze_qwen3-16b-a3b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, enhancing the gallery with a refined and high-quality model designed to replicate the prose of Claude models.
* Added a new model entry for `Rei-V3-KTO-12B`, including metadata such as name, URLs, icon, description, and file details. This model is fine-tuned to improve coherency, intelligence, and prose, aiming to replicate the quality of Claude 3 models like Sonnet and Opus.
=> chore(model gallery): add rei-v3-kto-12b

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to include a new model entry and its associated metadata. The most important change is the addition of the `allura-org_remnant-qwen3-8b` model, which includes details such as its name, icon, description, URLs, and file information.
* Added the `allura-org_remnant-qwen3-8b` model with metadata:
- Name: `"allura-org_remnant-qwen3-8b"`
- Icon URL: `https://cdn-uploads.huggingface.co/production/uploads/634262af8d8089ebaefd410e/_ovgodU331FO4YAqFGCnk.png`
- Description: A series of fine-tuned LLMs for roleplaying and conversation.
- URLs: Links to the model on Hugging Face.
- File details: Includes filename, SHA256 checksum, and URI for downloading the model file.
**[Signed …
=> chore(model gallery): add allura-org_remnant-qwen3-8b

Dockerfile
Trying to fix CI issues after https://github.com/mudler/LocalAI/pull/5309
=> fix(hipblas): do not build all cpu-specific flags

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for a model named `huihui-ai_qwen3-14b-abliterated`. The entry includes metadata, URLs, a description, and file details for the model.
* Added a new model entry for `huihui-ai_qwen3-14b-abliterated` with metadata such as name, description, and parameters. The description highlights that this is an uncensored version of the Qwen3-14B model created using a novel "abliteration" method to remove refusals.
* Included URLs pointing to the model's location on Hugging Face, along with file details like `filename`, `sha256`, and `uri`.
=> chore(model gallery): add huihui-ai_qwen3-14b-abliterated

gallery/index.yaml
This pull request introduces a new model entry to the `gallery/index.yaml` file. The addition includes comprehensive metadata and configuration for the "Josiefied-Qwen3-8B-abliterated-v1" model, which is part of the JOSIEFIED family of advanced language models.
* **Model Name and Metadata**: Added a new model entry named "Josiefied-Qwen3-8B-abliterated-v1," which is part of the JOSIEFIED family. This model is built upon the Qwen3 architecture and fine-tuned for openness, instruction alignment, and uncensored behavior. The description highlights its advanced capabilities and performance on benchmarks.
* **URLs and File Details**: Included URLs for downloading the model from Hugging Face and provided file details such as `filename`, `sha256` checksum, and `uri` for the model …
=> chore(model gallery): add goekdeniz-guelmez_josiefied-qwen3-8b-abliterated-v1

gallery/index.yaml
This pull request introduces a new entry for the `Claria-14b` language model in the `gallery/index.yaml` file. The addition includes metadata, descriptions, and file details for the model.
* Added `Claria-14b` to the gallery with metadata, including its name, icon, and description. The model is fine-tuned for psychological and psychiatric support contexts and is built on Qwen-3 (14b). It is described as an experimental foundation for therapeutic dialogue modeling and emotionally aware AI.
* Included file details for `Claria-14b`, specifying the filename, SHA256 checksum, and URI for downloading the model.
=> chore(model gallery): add claria-14b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, providing detailed metadata for the Qwen3-14B-Griffon-i1 model. The addition includes information about the model's purpose, training dataset, intended use cases, and file details.
* **Model Name**: Qwen3-14B-Griffon-i1  
- Added metadata such as name, icon, URLs, and a detailed description highlighting its fine-tuning process using the OpenThoughts2-1M dataset. The description emphasizes its optimization for advanced reasoning tasks, including math, logic puzzles, code generation, and step-by-step problem solving.
- Included training dataset details, specifying the dataset's source, volume, and content type, along with tools used for curation.
- Defined intended use cases, such as chain-of-thought …
=> chore(model gallery): add qwen3-14b-griffon-i1

gallery/index.yaml
This pull request adds a new entry for the "Qwen3-4B-Esper3-i1" model to the `gallery/index.yaml` file. The entry includes metadata such as the model's name, icon, description, URLs, and file details.
* Added a new model entry named "Qwen3-4B-Esper3-i1" with metadata, including:
- Name: "qwen3-4b-esper3-i1"
- Icon URL: A link to the model's icon image.
- Description: Details about the model's specialization in coding, architecture, and DevOps reasoning, as well as its fine-tuning and performance characteristics.
- URLs: Links to the model's pages on Hugging Face.
- File details: Includes filename, SHA256 checksum, and URI for accessing the model file.
=> chore(model gallery): add qwen3-4b-esper3-i1

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the `Apriel-Nemotron-15b-Thinker` model, providing detailed metadata about the model's capabilities, efficiency, and associated files.
* Added a new model entry for `servicenow-ai_apriel-nemotron-15b-thinker`, including metadata such as name, icon, description, URLs, and file details. This model is part of the ServiceNow Apriel SLM series, featuring a 15-billion-parameter reasoning model with competitive performance and high memory efficiency.
=> chore(model gallery): add servicenow-ai_apriel-nemotron-15b-thinker

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the "Qwen3-14B-Uncensored" model. The entry includes metadata, file details, and licensing information.
* Added a new model entry, "Qwen3-14B-Uncensored," which is a finetune of Qwen3-14B designed to produce uncensored outputs. Metadata includes:
- URLs for downloading the model from Hugging Face.
- Description highlighting the uncensoring process and credit to the dataset creator.
- Licensing information (Apache License 2.0).
- Mandatory system prompt details for desired output.
* Included file details for the model, such as the filename (`Qwen3-14B-Uncensored.Q4_K_M.gguf`), SHA-256 checksum, and URI for retrieval.
**[Signed …
=> chore(model gallery): add qwen3-14b-uncensored

gallery/index.yaml
This pull request introduces a new model entry to the `gallery/index.yaml` file, detailing the addition of the "Gemma-3-12B-FornaxV.2-QAT-CoT" model. The change includes metadata, descriptions, and file references for the model.
* Added a new model entry, "Gemma-3-12B-FornaxV.2-QAT-CoT," to the gallery. This includes:
- Metadata such as the model's name, icon URL, and description.
- A detailed explanation of the model's purpose, training methodology, and usage instructions, including enabling/disabling "thinking mode."
- File references with `sha256` checksums and URIs for downloading the model.
=> chore(model gallery): add gemma-3-12b-fornaxv.2-qat-cot

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry includes detailed metadata about the "Gryphe Pantheon-Proto-RP-1.8-30B-A3B" model, such as its name, icon, description, URLs, and associated files.
**New Model Addition:**
* Added a new entry for the "Gryphe Pantheon-Proto-RP-1.8-30B-A3B" model, including:
- Metadata such as name, icon URL, and description.
- Links to the model's Hugging Face pages and GGUF quantized files.
- Detailed description of the model's purpose, training methodology, and data sources.
- File details, including filename, SHA256 checksum, and URI for downloading the model.
=> chore(model gallery): add gryphe_pantheon-proto-rp-1.8-30b-a3b

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the Qwen2.5-VL-7B-Instruct model, detailing its features, enhancements, and file references. The most important changes include the addition of a description of the model's capabilities, updates to its architecture, and links to its associated files.
* **Model Description**: Added a detailed description of the Qwen2.5-VL-7B-Instruct model, highlighting its vision-language capabilities, such as visual understanding, agentic behavior, long video comprehension, visual localization, and structured output generation.
* **Architecture Updates**: Documented improvements to the model's architecture, including dynamic resolution and frame rate training for video understanding, and optimization of the vision …
=> chore(model gallery): add qwen_qwen2.5-vl-7b-instruct

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to include a new entry for the Qwen2.5-VL-72B-Instruct model. The addition provides detailed metadata, including URLs, descriptions, key enhancements, model architecture updates, and associated files.
* **Qwen2.5-VL-72B-Instruct**:
- Added a new entry for the Qwen2.5-VL-72B-Instruct model with detailed metadata. This includes a description of its capabilities, such as advanced visual understanding, agentic behavior, long video comprehension, visual localization, and structured output generation.
- Included updates on model architecture, such as dynamic resolution and frame rate training for video understanding, and optimizations to the vision encoder for improved speed and efficiency.
- Added associated files with …
=> chore(model gallery): add qwen_qwen2.5-vl-72b-instruct

.github/workflows/image.yml
This PR makes sure that we tag latest only cpu-based images.
=> fix(ci): tag latest against cpu-only image

gallery/index.yaml
This pull request adds a new entry for the Skywork-OR1-32B model to the `gallery/index.yaml` file, providing metadata and details about the model series, its performance, and associated files.
* Added a new entry for the Skywork-OR1-32B model under the `gallery/index.yaml` file, including metadata such as the model name, description, performance comparisons, and associated URLs. This entry highlights the model's strengths in math and coding tasks and provides links to its Hugging Face repository.
* Included overrides for model parameters and added a file reference with its `sha256` checksum and URI for the Skywork-OR1-32B-Q4_K_M.gguf model file.
=> chore(model gallery): add skywork_skywork-or1-32b

gallery/index.yaml
This pull request adds a new entry for the Skywork-OR1-7B model to the `gallery/index.yaml` file. The entry includes metadata, descriptions, and file details for the model.
* Added a new entry for the `Skywork-OR1-7B` model, including:
- Metadata such as `name`, `urls`, and `description`.
- Performance highlights, comparing it to other models like Deepseek-R1 and Qwen3-32B on math and coding tasks.
- Overrides specifying the model parameters and associated files.
=> chore(model gallery): add skywork_skywork-or1-7b

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to add a new model entry for "Snowpiercer 15B v1" by TheDrummer. The entry includes metadata, file details, and links to the model's resources.
* Added a new model, "Snowpiercer 15B v1," with associated metadata, including a description, icon URL, and resource links. The model is described as enhancing role-play and creativity while retaining intelligence and reasoning.
=> chore(model gallery): add thedrummer_snowpiercer-15b-v1

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to add new model entries and modify existing ones. The changes include the addition of a new model, updates to metadata for existing models, and reorganization of YAML structure for clarity.
* Added a new model entry for "thedrummer_rivermind-lux-12b-v1" with metadata, including a description, icon, URLs, and file details.
* Updated the metadata for the existing model "thedrummer_snowpiercer-15b-v1" by adding a `url` field pointing to a GitHub resource.
=> chore(model gallery): add thedrummer_rivermind-lux-12b-v1

gallery/index.yaml
This pull request adds a new entry for the `INTELLECT-2` language model to the `gallery/index.yaml` file. The entry includes metadata, descriptions, and file details for the model.
* Introduced a new entry for the `INTELLECT-2` model, a 32-billion parameter language model trained using distributed reinforcement learning. The entry includes metadata such as tags (`llm`, `gguf`, `gpu`, `cpu`, `intellect`), license (`apache-2.0`), and URLs pointing to the model's resources.
* Added a detailed description of the model's training methodology, infrastructure, and technical report.
* Included file details for the model, such as the filename (`PrimeIntellect_INTELLECT-2-Q4_K_M.gguf`), SHA256 checksum, and URI for downloading the file from Hugging Face. …
=> chore(model gallery): add primeintellect_intellect-2

backend/go/bark/gobark.cpp, core/http/endpoints/elevenlabs/tts.go, core/http/endpoints/jina/rerank.go, core/http/endpoints/localai/tts.go, core/http/endpoints/localai/vad.go, docs/content/docs/getting-started/build.md, docs/content/docs/getting-started/container-images.md, docs/content/docs/getting-started/kubernetes.md, docs/static/install.sh, gallery/index.yaml, pkg/downloader/uri_test.go, pkg/model/loader.go, pkg/templates/evaluator.go
=> fix: typos

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the `soob3123_grayline-qwen3-14b` model. The addition includes detailed metadata about the model, such as its description, attributes, associated files, and links.
* Added a new model entry for `soob3123_grayline-qwen3-14b`, including its name, icon URL, description, and attributes. The description highlights the model's focus on uncensored information delivery and task execution without ethical or moral filtering.
* Added file details for the model, including the filename, SHA256 checksum, and URI for downloading the model from Hugging Face.
=> chore(model gallery): add soob3123_grayline-qwen3-14b

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the `soob3123_grayline-qwen3-8b` model, including its metadata, description, and associated files.
* Added a new model entry named `soob3123_grayline-qwen3-8b` with detailed metadata, including URLs, an icon, and a description outlining its core attributes and functionality. This model is described as a neutral AI assistant designed for uncensored information delivery and task execution.
* Included file details for the model, such as the filename, SHA256 checksum, and URI for downloading the model file.
=> chore(model gallery): add soob3123_grayline-qwen3-8b

gallery/index.yaml
This pull request adds a new entry for the `facebook_KernelLLM` model to the `gallery/index.yaml` file. The update includes metadata, description, and associated files for the model.
* **Metadata**: Added details such as the name, icon, and URLs linking to the model's Hugging Face pages. (`[gallery/index.yamlR9567-R9585](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR9567-R9585)`)
* **Description**: Included a comprehensive explanation of `KernelLLM`, highlighting its purpose, training process, and evaluation methodology. The description emphasizes its role in generating Triton GPU kernels from PyTorch modules and its training on both real and synthetic datasets. (`[gallery/index.yamlR9567-R9585](diffhunk://#diff-c501316194bb8468dd656c88d5 …
=> chore(model gallery): add facebook_kernelllm

gallery/index.yaml, gallery/smolvlm.yaml
This PR fixes #5368 
In order for this model to work, LocalAI must be run from `master` images!
=> chore(model gallery): add smolvlm-256m-instruct

gallery/index.yaml
=> chore(model gallery): add smolvlm-500m-instruct

gallery/index.yaml
=> chore(model gallery): add smolvlm-instruct

gallery/index.yaml
=> chore(model gallery): add smolvlm2-500m-video-instruct

backend/python/transformers/requirements-cpu.txt, backend/python/transformers/requirements-cublas11.txt, backend/python/transformers/requirements-cublas12.txt, backend/python/transformers/requirements-hipblas.txt, backend/python/transformers/requirements-intel.txt, backend/python/transformers/requirements.txt
=> fix(transformers): pin protobuf

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the `nvidia_Llama-3.1-Nemotron-Nano-4B-v1.1` model, including its metadata, description, and associated files.
* **Model metadata**: Added a new model named `nvidia_Llama-3.1-Nemotron-Nano-4B-v1.1` with an icon, name, description, and URLs linking to its Hugging Face pages.
* **Model description**: Detailed the model's features, including its post-training process, reasoning capabilities, context length, and suitability for commercial use.
* **Associated files**: Included file metadata such as filename, SHA256 checksum, and URI for the model file.
=> chore(model gallery): add nvidia_llama-3.1-nemotron-nano-4b-v1.1

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file to include details about the `mistralai_devstral-small-2505` model. The addition provides comprehensive metadata, including URLs, a description, and file details for the model.
* **Model Name:** `mistralai_devstral-small-2505`
- Added metadata for the model, including its name, URLs, and a detailed description highlighting its features and capabilities. The description emphasizes its use as an agentic LLM for software engineering tasks, its lightweight design, and its 128k context window.
- Included file details with SHA-256 checksums and URIs for two associated files: `mistralai_Devstral-Small-2505-Q4_K_M.gguf` and `mmproj-mistralai_Devstral-Small-2505-f16.gguf`.
**[Signed …
=> chore(model gallery): add mistralai_devstral-small-2505

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file by adding a new model entry to the gallery. The new model, "delta-vector_archaeo-12b-v2," is designed for roleplaying and creative writing purposes.
* **New model entry: "delta-vector_archaeo-12b-v2"**:
- Includes metadata such as name, icon, description, and URLs for more information.
- Specifies overrides for model parameters and provides a file reference with its `sha256` hash and `uri`.
=> chore(model gallery): add delta-vector_archaeo-12b-v2

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the `QwQ-32B-ArliAI-RpR-v4` model. The entry includes metadata, description, and file details for the model, which is part of the RpR (RolePlay with Reasoning) series by ArliAI.
* Added a new entry for the `QwQ-32B-ArliAI-RpR-v4` model, including its name, icon, and URLs for access on Hugging Face.
* Included an extensive description of the `RpR` series, highlighting its focus on reasoning and creative writing, improvements over previous models, and the unique training methodology used to enhance long multi-turn chat capabilities.
* Added file details (`filename`, `sha256`, and `uri`) and parameter overrides for the `QwQ-32B-ArliAI-RpR-v4` model to specify its configuration and ensure correct usage. …
=> chore(model gallery): add arliai_qwq-32b-arliai-rpr-v4

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the `WhiteRabbitNeo-V3-7B` model, which focuses on security topics. The change includes metadata, descriptions, and associated files for the model.
* **New Model Entry**: Added `WhiteRabbitNeo-V3-7B` to the gallery with metadata such as name, icon, URLs, and a detailed description of its focus on security topics, including open ports, outdated software, default credentials, and more.
* **File Details**: Included file information for the model, specifying the filename, SHA256 hash, and URI for downloading the model.
=> chore(model gallery): add whiterabbitneo_whiterabbitneo-v3-7b

gallery/index.yaml
This pull request adds a new entry for the MedGemma model family to the `gallery/index.yaml` file. MedGemma is a specialized AI model suite designed for medical text and image comprehension.
* **Name**: `medgemma-4b-it`
* **Description**: Introduced MedGemma, a collection of AI models optimized for healthcare applications. The description includes details about two variants:
- **MedGemma 4B**: A multimodal model with a SigLIP image encoder, trained on diverse medical data like X-rays and histopathology slides. Available in pre-trained and instruction-tuned versions.
- **MedGemma 27B**: A text-only model optimized for inference, available as an instruction-tuned version.
- Both variants have been evaluated on clinical benchmarks and support fine-tuning for improved …
=> chore(model gallery): add medgemma-4b-it

gallery/index.yaml
This pull request adds a new entry for the MedGemma 27B text-only model to the `gallery/index.yaml` file. The update includes detailed metadata and descriptions for the model, as well as file-specific information for its usage.
* **New model entry**: Added `medgemma-27b-text-it`, a text-only variant of the MedGemma collection, optimized for medical text comprehension and inference-time computation. The entry includes:
- Description of the model's purpose, training data, and intended use.
- Links to the model's resources on Hugging Face.
- File metadata, including filename, SHA256 hash, and URI for downloading the model file.
=> chore(model gallery): add medgemma-27b-text-it

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, expanding the gallery with detailed metadata for the model.
* Added a new model entry named `allura-org_q3-30b-a3b-pentiment` with associated metadata, including an icon, URLs, description, parameter overrides, and file details. This entry represents a triple-stage fine-tuned version of the Qwen3-30B-A3b Base model.
=> chore(model gallery): add allura-org_q3-30b-a3b-pentiment

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, enhancing the model gallery with detailed information about the `nvidia_acereason-nemotron-14b` model and its performance.
* **New model: `nvidia_acereason-nemotron-14b`**
- Added a detailed description of the model, highlighting its reinforcement learning-based training process and significant performance improvements across various benchmarks, including AIME, LiveCodeBench, and Codeforces.
- Included URLs for accessing the model on Hugging Face, along with metadata like `sha256` checksums and file URIs for reproducibility.
- Defined parameters and file overrides specific to the model, ensuring proper configuration and usage.
**[Signed …
=> chore(model gallery): add nvidia_acereason-nemotron-14b

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the "allura-org_q3-30b-a3b-designant" model. The entry includes metadata, such as the model's name, icon, URLs, description, and file details.
* **New model: "allura-org_q3-30b-a3b-designant"**  
- Added metadata, including name, icon URL, and description, highlighting its roleplaying capabilities and performance as a lightweight Mixture of Experts model.
- Included file details, such as the filename, SHA256 checksum, and URI for the model's GGUF file.
=> chore(model gallery): add allura-org_q3-30b-a3b-designant

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The changes introduce details about the "Llama3-24B-Mullein-v1" model, including its metadata, description, and associated files.
* Added a new model, `"Llama3-24B-Mullein-v1"`, to the gallery with metadata such as name, URL, icon, description, and associated files. This model is described as an improvement over its predecessor, with better character/scenario handling and reduced user impersonation issues.
=> chore(model gallery): add llama3-24b-mullein-v1

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, expanding the list of available models with detailed metadata and configuration.
* Added a new model entry for `MS-24B-Mullein-v0` with the following details:
- Name: `ms-24b-mullein-v0`
- Icon URL: `https://cdn-uploads.huggingface.co/production/uploads/675a77cf99ca23af9daacccc/KMazK4tkkCrh3kO7N1cJ7.webp`
- URLs pointing to the model on Hugging Face: `https://huggingface.co/trashpanda-org/MS-24B-Mullein-v0` and `https://huggingface.co/mradermacher/MS-24B-Mullein-v0-GGUF`
- Description highlighting the model's strengths and areas for improvement, including its varied responses, NPC characterization, and minimal positivity bias.
- Overrides specifying the model parameter as …
=> chore(model gallery): add ms-24b-mullein-v0

core/http/views/index.html
=> fix(template): we do not always have .Name

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, introducing the `FairyR1-14B-Preview` model. The addition includes detailed metadata, such as URLs, a description of the model's architecture and training process, and associated files.
* **Model Name**: `pku-ds-lab_fairyr1-14b-preview`
* **Description**: The `FairyR1-14B-Preview` is a highly efficient large-language model (LLM) that leverages a "distill-and-merge" pipeline for competitive performance with reduced size and inference cost. It is part of the FairyR1 series and includes enhancements in data processing and model architecture.
* **Training Details**: Features a refined distillation data pipeline and a streamlined specialist-model merging process, resulting in a 14B-parameter model …
=> chore(model gallery): add pku-ds-lab_fairyr1-14b-preview

Makefile, backend/cpp/llama/CMakeLists.txt, backend/cpp/llama/grpc-server.cpp
This PR supersedes https://github.com/mudler/LocalAI/pull/5523
=> chore(deps): bump llama.cpp to 'e83ba3e460651b20a594e9f2f0f0bffb998d3ce1

.github/workflows/test-extra.yml, Dockerfile, Makefile, backend/python/chatterbox/Makefile, backend/python/chatterbox/backend.py, backend/python/chatterbox/install.sh, backend/python/chatterbox/requirements-cpu.txt, backend/python/chatterbox/requirements-cublas11.txt, backend/python/chatterbox/requirements-cublas12.txt, backend/python/chatterbox/requirements-hipblas.txt, backend/python/chatterbox/requirements-intel.txt, backend/python/chatterbox/requirements.txt, backend/python/chatterbox/run.sh, backend/python/chatterbox/test.py, backend/python/chatterbox/test.sh
This PR adds chatterbox tts #5519 
=> feat(chatterbox): add new backend

core/backend/llm.go
This was causing otherwise to stream character-by-character instead of token-by-token
=> fix(streaming): stream complete runes

Makefile, backend/cpp/llama/prepare.sh
Supersedes https://github.com/mudler/LocalAI/pull/5541
=> chore(deps): bump llama.cpp to 'e562eece7cb476276bfc4cbb18deb7c0369b2233'

.github/workflows/release.yaml, Dockerfile
Reverts mudler/LocalAI#5554. Sadly couldn't cover arm64
=> Revert "fix(ci): try to add different mirrors to avoid 403 issues"

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, introducing the "Homunculus" model along with its metadata and associated files.
* Added a new model entry, `"arcee-ai_homunculus"`, which is a 12 billion-parameter instruction model distilled from Qwen3-235B. It features two interaction modes—`/think` and `/nothink`—optimized for single consumer GPU usage.
* Included metadata such as name, icon, description, URLs, and file details for the `"arcee-ai_homunculus"` model. The associated file is `arcee-ai_Homunculus-Q4_K_M.gguf` with its SHA256 checksum and URI specified.
=> chore(model gallery): add arcee-ai_homunculus

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing a new language model to the gallery.
* Added the `Josiefied-Qwen3-14B-abliterated-v3` model to the gallery, including its description, URLs, overrides, and associated file metadata. This model is part of the JOSIEFIED family, designed for advanced users requiring unrestricted, high-performance language generation. It is fine-tuned for openness and instruction alignment.
=> chore(model gallery): add goekdeniz-guelmez_josiefied-qwen3-14b-abliterated-v3

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The change introduces the "Ultravox v0.5" multimodal Speech LLM, including its metadata, file references, and URLs.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR4098-R4115): Added the "Ultravox v0.5" model, which is a multimodal Speech LLM built on the Llama-3.2-1B-Instruct and whisper-large-v3-turbo backbone. This addition includes relevant metadata (e.g., name, description, overrides), URLs for accessing the model, and file details such as filenames, SHA256 checksums, and URIs.
=> chore(model gallery): add ultravox-v0_5-llama-3_2-1b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, introducing `OpenThinker3-7B`, a state-of-the-art reasoning model. The change includes metadata, descriptions, and file references for the new model.
* **New model entry - [`OpenThinker3-7B`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR7778-R7796):** Added metadata, description, icon, and file references for the `OpenThinker3-7B` model, which is a fine-tuned version of `Qwen2.5-7B-Instruct` on the OpenThoughts3-1.2M dataset. This model demonstrates significant improvements over its predecessors and other competitive reasoning models.
=> chore(model gallery): add open-thoughts_openthinker3-7b

core/http/endpoints/openai/realtime.go
Fix setting the model on a session update
=> fix(realtime): Use updated model on session update

gallery/index.yaml
This pull request adds a new multimodal model entry, `qwen2.5-omni-3b`, to the `gallery/index.yaml` file. The changes include metadata, tags, descriptions, and file details for the model.
* **Model metadata and description:** Added a new entry for `qwen2.5-omni-3b`, a multimodal model capable of processing text, audio, and image inputs while generating text and speech responses. The description outlines its modalities and capabilities.
* **Tags and URLs:** Included relevant tags (e.g., `multimodal`, `gguf`, `gpu`, `cpu`) and URLs pointing to the model's resources on Hugging Face.
* **File details:** Added file information, including filenames, SHA-256 hashes, and URIs for associated model files (`Qwen2.5-Omni-3B-Q4_K_M.gguf` and `mmproj-Qwen2.5-Omni-3B-Q8_0.gguf`).
**Notes …
=> chore(model gallery): add qwen2.5-omni-3b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, providing details about the `mistralai_magistral-small-2506` model. The addition includes metadata, features, licensing information, and deployment recommendations.
* Added `mistralai_magistral-small-2506` model entry with metadata, including name, icon, description, and URLs. The description highlights reasoning capabilities, multilingual support, Apache 2.0 licensing, and deployment recommendations for local use.
* Included file details for the model (`mistralai_Magistral-Small-2506-Q4_K_M.gguf`), specifying filename, SHA256 checksum, and URI for retrieval.
=> chore(model gallery): add mistralai_magistral-small-2506

gallery/index.yaml
This pull request adds a new entry for the RoboBrain 2.0 model to the `gallery/index.yaml` file. The addition includes metadata, URLs, descriptions, and file references for the model.
* Added a new entry named `"baai_robobrain2.0-7b"` with associated metadata, including an icon, name, description, and URLs pointing to Hugging Face repositories.
* Included override parameters specifying the model file (`BAAI_RoboBrain2.0-7B-Q4_K_M.gguf`) and an additional file (`mmproj-BAAI_RoboBrain2.0-7B-f16.gguf`).
* Provided file details such as filenames, SHA256 checksums, and URIs for two associated files.
=> chore(model gallery): add baai_robobrain2.0-7b

gallery/index.yaml, gallery/qwen3-openbuddy.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the OpenBuddy Qwen3 model, including its metadata, URLs, description, and associated files.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1049-R1067): Added metadata for the OpenBuddy Qwen3 model, including its name, icon, description, training data details, license, context length, associated files, and URLs for downloading the model.
=> chore(model gallery): add openbuddy_openbuddy-r1-0528-distill-qwen3-32b-preview0-qat

gallery/index.yaml
This pull request adds a new entry for the Qwen3 Embedding model series to the `gallery/index.yaml` file. The addition includes detailed metadata and descriptions for the `Qwen3-Embedding-4B-GGUF` model, highlighting its capabilities and features.
* **New Model Entry**: Added metadata for the `Qwen3-Embedding-4B-GGUF` model, which is part of the Qwen3 Embedding series designed for text embedding and ranking tasks. It supports over 100 languages, offers flexible embedding dimensions, and provides state-of-the-art performance in multilingual and text retrieval benchmarks.
=> chore(model gallery): add qwen3-embedding-4b

gallery/index.yaml
This pull request adds a new entry for the Qwen3 Embedding model series to the `gallery/index.yaml` file. The entry provides detailed metadata and descriptions for the `Qwen3-Embedding-0.6B-GGUF` model, highlighting its features, capabilities, and supported use cases.
* **Model Name and Tags**: Added metadata for `qwen3-embedding-0.6b`, including tags such as `embedding`, `gguf`, `gpu`, and `cpu`.
* **Description**: Included a detailed description of the Qwen3 Embedding model series, emphasizing its multilingual capabilities, text embedding and ranking performance, and flexibility in use cases.
* **Features**: Documented key features of the `Qwen3-Embedding-0.6B-GGUF` model, such as supported languages (100+), embedding dimensions (user-defined up to 1024), and …
=> chore(model gallery): add qwen3-embedding-0.6b

tests/e2e-aio/e2e_test.go
This PR tries to improve AIO tests and avoid flakyness
=> chore: improve tests

Dockerfile
=> chore: Add python3 to images

backend/index.yaml
=> chore(backend gallery): re-order and add description for vLLM

.github/workflows/image.yml
This PR tries to switch base image builds to public runners
=> chore(ci): switch to public runners for base images

core/http/routes/ui_backend_gallery.go
=> fix(backends gallery): propagate p2p settings to correctly draw menu

docs/content/docs/features/GPU-acceleration.md
This pull request corrects minor typos and enhances the clarity of the documentation in docs/content/docs/features/GPU-acceleration.md.
=> Fix Typos and Improve Clarity in GPU Acceleration Documentation

gallery/index.yaml
=> chore(model gallery): add qwen3-the-josiefied-omega-directive-22b-uncensored-abliterated-i1

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The model, named "Menlo Jan-Nano," is a compact language model optimized for deep research tasks and integration with MCP servers.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1189-R1203): Added a new model entry named "Menlo Jan-Nano," including its description, associated files, and URLs for downloading the model. This model is a 4-billion parameter language model designed for research and optimized for MCP server compatibility.
=> chore(model gallery): add menlo_jan-nano

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The addition includes detailed metadata, such as the model's name, description, associated files, and URLs.
* **Model Name**: `qwen3-the-xiaolong-omega-directive-22b-uncensored-abliterated-i1`
- **Description**: A 22B parameter uncensored model with vivid prose, intense details, and full reasoning capabilities. Includes NSFW content such as horror, gore, and humor.
- **Icon**: URL added for model representation.
- **Files**: Metadata for associated file (`Qwen3-The-Xiaolong-Omega-Directive-22B-uncensored-abliterated.i1-Q4_K_M.gguf`) includes SHA256 hash and URI pointing to Hugging Face repository.
- **URLs**: Two URLs provided for accessing the model on Hugging Face. …
=> chore(model gallery): add qwen3-the-xiaolong-omega-directive-22b-uncensored-abliterated-i1

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing the Q3-8B-Kintsugi model to the gallery. The change includes metadata, descriptions, and file details for the model.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1220-R1235): Added the Q3-8B-Kintsugi model, including its name, icon, URLs, description, parameter overrides, and associated file details. This model is described as a roleplaying model finetuned from Qwen3-8B-Base, excelling in 1-on-1 roleplaying and storywriting.
=> chore(model gallery): add allura-org_q3-8b-kintsugi

gallery/index.yaml
This pull request introduces a new model entry to the `gallery/index.yaml` file, enhancing the gallery with additional metadata and descriptive details for the model.
* Added a new model entry named `"ds-r1-qwen3-8b-arliai-rpr-v4-small-iq-imatrix"` with detailed metadata, including its description, icon URL, associated files, and overrides for specific parameters. This model emphasizes reduced repetitions, improved creative output, and increased training sequence length for better memory and awareness in longer chats.
=> chore(model gallery): add ds-r1-qwen3-8b-arliai-rpr-v4-small-iq-imatrix

gallery/index.yaml
=> chore(model gallery): add mistralai_mistral-small-3.2-24b-instruct-2506

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, introducing the Menlo Jan-Nano-128k model with detailed metadata and descriptions.
* **Model Metadata**: Added the `name`, `icon`, `urls`, and `description` fields for the Menlo Jan-Nano-128k model, highlighting its extended 128k context window and improved performance for research applications.
* **Overrides and Files**: Included `overrides` for model parameters and added file details (`filename`, `sha256`, and `uri`) for the model's GGUF file.
=> chore(model gallery): add menlo_jan-nano-128k

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file to include metadata for the Gemma 3n E4B model. The addition provides detailed information about the model's capabilities, efficient parameter management technology, and links to resources for downloading the model.
* **Model description**: Detailed description of the Gemma 3n E4B model, highlighting its multimodal capabilities, efficient parameter activation technology, and training data in over 140 languages.
* **URLs**: Added links to Hugging Face resources for downloading the Gemma 3n E4B model.
* **Overrides and files**: Included overrides for model parameters and metadata for associated files, such as filename, SHA256 checksum, and URI.
**[Signed …
=> chore(model gallery): add gemma-3n-e4b-it

core/system/capabilities.go
This PR fixes identity detection in backend galleries meta packages
=> fix(backends gallery): correctly identify gpu vendor

gallery/index.yaml
This pull request adds a new experimental model configuration to the `gallery/index.yaml` file. The model, named "qwen3-55b-a3b-total-recall-deep-40x," includes detailed metadata, descriptions, and file references for its parameters and usage.
* **New model entry**: Added "qwen3-55b-a3b-total-recall-deep-40x" with metadata such as name, icon, description, and URLs. The description highlights the experimental nature of the model, its modifications, and unique performance characteristics.
* **File references**: Included file details (`Qwen3-55B-A3B-TOTAL-RECALL-V5-Deep-40X-q4_K_M.gguf`) with SHA256 hash and URI for downloading the model.
=> chore(model gallery): add qwen3-55b-a3b-total-recall-deep-40x

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, introducing `Qwen3-22B-A3B-The-Harley-Quinn`. The addition includes detailed metadata, usage instructions, and links to resources for the model.
* **Model Name and Metadata**: Added `Qwen3-22B-A3B-The-Harley-Quinn` with a description emphasizing its creative and uncensored capabilities, along with specific operational settings and known issues.
* **Resource Links**: Included links to repositories and guides for usage, quantization, and model-specific configurations.
* **File Details**: Added file information for the model, including SHA256 checksum and URI for retrieval.
=> chore(model gallery): add qwen3-22b-a3b-the-harley-quinn

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing the Gemma-3-4b-it-MAX-HORROR-Uncensored model to the gallery. The addition includes detailed metadata, links, descriptions, and file references for the model.
* Added the Gemma-3-4b-it-MAX-HORROR-Uncensored model, including metadata such as name, icon URL, description, and context details. The description highlights the model's uncensored nature, enhanced horror dataset integration, and improved performance through "MAXing" techniques.
* Included file details for the model, including its filename, SHA256 checksum, and URI linking to the Hugging Face repository.
=> chore(model gallery): add gemma-3-4b-it-max-horror-uncensored-dbl-x-imatrix

Dockerfile, core/gallery/backends.go, core/system/capabilities.go
allow to override capabilities and use that mechanism with container image to define which kind of accelleration we want to pull
=> feat(system): detect and allow to override capabilities

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the `AnubisLemonade-70B-v1` model. The entry includes metadata, description, and file details for this state-of-the-art model.
* Added metadata for `AnubisLemonade-70B-v1`, a 70B parameter model featuring Intermediate Thinking capabilities, including URLs, description, parameter overrides, and file details.
=> chore(model gallery): add ockerman0_anubislemonade-70b-v1

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to add a new AI model, `Nano_Imp_1B`, which is described as the world's first fully coherent 1B-parameter roleplay model. The addition includes metadata, descriptions, and file details for the model.
* **Metadata**: Added a new entry for `Nano_Imp_1B` with its name, icon URL, and associated URLs.
* **Description**: Included a detailed narrative explaining the significance of the model, its development, and its accessibility for users with mid-tier devices.
* **File details**: Added file information, including the filename, SHA256 checksum, and URI for downloading the model.
=> chore(model gallery): add nano_imp_1b-q8_0

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the `Compumacy-Experimental-32B` model, which is a specialized language model designed for clinical psychology and psychiatry.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1613-R1631): Added metadata for `Compumacy-Experimental-32B`, including its name, icon URL, description, associated files, and overrides. The model is fine-tuned for assisting mental health professionals and is based on the `unsloth/Qwen3-32B` architecture. It integrates diagnostic criteria from DSM-5-TR, ICD-11 classifications, and peer-reviewed literature to support its outputs.
**[Signed …
=> chore(model gallery): add compumacy-experimental-32b

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing the `Huihui-Jan-nano-abliterated` model. The change includes metadata, file details, and a description of the model's creation and purpose.
* [`gallery/index.yaml`](diffhunk://#diff-c501316194bb8468dd656c88d5dbd0c4111ab10ece9de96c53cfaad5e5f375edR1668-R1683): Added the `Huihui-Jan-nano-abliterated` model, including its name, URLs, description, parameters, and file details. The model is described as an uncensored version of Menlo/Jan-nano created using a faster ablation method for removing refusals from an LLM model.
=> chore(model gallery): add huihui-jan-nano-abliterated

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for the `microsoft_nextcoder-32b` model, detailing its specifications and key features.
* Introduced a new model, `microsoft_nextcoder-32b`, based on Qwen2.5-Coder Instruct variants, with the following key improvements:
- Enhanced code editing performance, achieving results comparable to GPT-4 on complex benchmarks like Aider-Polyglot, with a 44% performance improvement over its base model.
- Maintains generalizability using the novel Selective Knowledge Transfer (SeleKT) finetuning methodology.
- Supports long contexts of up to 32K tokens.
=> chore(model gallery): add microsoft_nextcoder-32b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The new entry provides details about the "huihui-ai_huihui-gemma-3n-e4b-it-abliterated" model, including its description, URLs, parameters, and associated files.
* **Model Name**: "huihui-ai_huihui-gemma-3n-e4b-it-abliterated"  
- **Description**: An uncensored version of the `google/gemma-3n-E4B-it` model, processed using a proof-of-concept method called "abliteration" to remove refusals from the model's text output.  
- **URLs**: Includes links to the model on Hugging Face.  
- **Files**: Specifies the filename, SHA-256 hash, and URI for the model file.  
- **Overrides**: Defines parameters for the model, including the file reference.
**[Signed …
=> chore(model gallery): add huihui-ai_huihui-gemma-3n-e4b-it-abliterated

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for a software engineering-focused language model, `mistralai_devstral-small-2507`. The addition includes metadata, descriptions, and file references for the model.
* Added `mistralai_devstral-small-2507` to the gallery with metadata, including name, icon URL, and description. The model is designed for software engineering tasks, featuring a 128k token context window and optimized performance on SWE-bench.
* Included file references and SHA256 checksum for the model file `mistralai_Devstral-Small-2507-Q4_K_M.gguf`, hosted on Hugging Face.
=> chore(model gallery): add mistralai_devstral-small-2507

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, providing detailed metadata and configuration for the `nvidia_Llama-3_3-Nemotron-Super-49B-GenRM-Multilingual` model.
* Added a new model named `nvidia_Llama-3_3-Nemotron-Super-49B-GenRM-Multilingual`, which is a generative reward model fine-tuned using Reinforcement Learning to assess the quality of LLM-generated responses. Metadata includes:
- A description of the model's functionality and use cases.
- Links to relevant resources, including Hugging Face repositories and an academic paper.
- File details, including the filename, SHA-256 checksum, and URI for downloading the model.
=> chore(model gallery): add nvidia_llama-3_3-nemotron-super-49b-genrm-multilingual

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The entry introduces the "Impish_Magic_24B-i1" model, along with its metadata and associated files.
* **New model: "Impish_Magic_24B-i1"**:
- Added a detailed description of the model, including its origin, tuning methodology, and use cases (e.g., roleplay and adventure scenarios).
- Included metadata such as the model's name, icon, license (Apache 2.0), and URLs for access.
- Listed associated files with their `filename`, `sha256` checksum, and `uri` for downloading the model.
=> chore(model gallery): add impish_magic_24b-i1

gallery/index.yaml
This pull request adds a new entry for the `google_medgemma-4b-it` model to the `gallery/index.yaml` file. The addition provides detailed information about the model's features, use cases, and available variants, along with links to relevant resources.
* Added a new model entry for `google_medgemma-4b-it` under the `gallery/index.yaml` file. This includes:
- A description of the model's purpose, which is to support medical text and image comprehension tasks.
- Details on the available variants: a 4B multimodal version and 27B text-only and multimodal versions, with specific use-case recommendations for each variant.
- Information about the pre-training and instruction-tuning processes, along with the intended use cases for the model.
- Links to the model's resources hosted …
=> chore(model gallery): add google_medgemma-4b-it

gallery/index.yaml
This pull request adds a new model entry for "google_medgemma-27b-it" to the `gallery/index.yaml` file. The update includes detailed metadata, descriptions, and file references for this model.
* **Model Name**: `google_medgemma-27b-it`
* Added metadata, including URLs, descriptions, and intended use cases for the model. The description highlights the model's focus on medical text and image comprehension, with variants optimized for different use cases.
* Included file references for the model, specifying filenames, SHA256 checksums, and URIs for downloading the model files.
=> chore(model gallery): add google_medgemma-27b-it

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file for a fine-tuned model, `Zhi-Create-Qwen3-32B`, which focuses on enhancing creative writing capabilities while maintaining general knowledge and reasoning performance.
* Added a new model, `Zhi-Create-Qwen3-32B`, derived from `Qwen3-32B`. This model improves creative writing performance, achieving a WritingBench score of 82.08 compared to the base model's 78.97. The fine-tuning process also ensures stable general capabilities through fine-grained data mixture experiments.
* Included metadata such as URLs, a detailed description, parameter overrides, and file details (e.g., filename, SHA256 checksum, and URI).
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-cert …
=> chore(model gallery): add zhi-create-qwen3-32b-i1

pkg/startup/model_preload.go
This PR makes autoloading backend consistent, for instance with AIO images. AIO images installs models via local URLs, and these needs to be parsed for required backends in order to be installed.
=> fix: autoload backends when installing models from YAML files

core/http/endpoints/openai/realtime.go
Fix speech started and transcription events.
=> fix(realtime): Reset speech started flag on commit

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file for the Dream-org Dream-v0 Instruct-7B model, including its metadata and resource links.
* Added a new model, `dream-org_dream-v0-instruct-7b`, to the gallery. This includes metadata such as its name, license, tags (e.g., `diffusion-large-language-model`, `gguf`, `gpu`, `cpu`), icon URL, and description.
* Included resource links for the model, pointing to Hugging Face repositories, and specified overrides for parameters and file details (e.g., filename, SHA256 hash, and URI).
=> chore(model gallery): add dream-org_dream-v0-instruct-7b

gallery/index.yaml
This pull request adds two new model entries, "Menlo Lucy" and "Menlo Lucy-128k," to the `gallery/index.yaml` file. These additions describe compact, efficient models optimized for agentic web search and lightweight browsing, with detailed metadata and file references.
* **Menlo Lucy**:
- A 1.7B model designed for efficient web search and browsing, optimized for mobile and CPU-only configurations.
- Includes metadata such as icon, URLs, description, and file details.
* **Menlo Lucy-128k**:
- A variant of the Menlo Lucy model with a focus on extended context capabilities (128k).
- Includes similar metadata and file references as the base model.
=> chore(model gallery): add menlo_lucy

backend/index.yaml, core/gallery/backend_types.go, core/gallery/backends.go
This PR adds mirrors to the backends in the gallery when download fails.
See https://github.com/mudler/LocalAI/issues/5908 for context
=> feat(backend gallery): add mirrors

.github/workflows/image.yml, docs/static/install.sh
Use the correct prefix for `vulkan` images. For consistency with the others, this PR it adds `gpu` prefix.
=> fix(vulkan): use correct image suffix

Dockerfile
This PR tries to fix incorrect capabilities detected on nvidia-l4t images
=> fix(ci): add nvidia-l4t capability to l4t images

gallery/index.yaml
This PR adds qwen_qwen3-30b-a3b-instruct-2507
=> chore(model gallery): add qwen_qwen3-30b-a3b-instruct-2507

gallery/index.yaml
This pull request adds a new entry to the `gallery/index.yaml` file, introducing the Qwen3-30B-A3B-Thinking-2507 model with detailed metadata. The update highlights the model's enhanced reasoning capabilities and additional features.
* **New model added**: `qwen_qwen3-30b-a3b-thinking-2507`, including its name, description, URLs, file information, and overrides. The description emphasizes improvements in reasoning tasks, general capabilities, long-context understanding, and suitability for complex reasoning tasks.
=> chore(model gallery): add qwen_qwen3-30b-a3b-thinking-2507

backend/backend.proto, backend/go/stablediffusion-ggml/gosd.cpp, backend/go/stablediffusion-ggml/gosd.go, backend/go/stablediffusion-ggml/gosd.h, core/backend/image.go, core/http/endpoints/openai/image.go, core/schema/openai.go, gallery/index.yaml
Testing with:
```
curl http://localhost:8080/v1/images/generations -H "Content-Type: application/json" -d '{
"model": "flux-kontext",
"prompt": "change 'flux.cpp' to 'kontext.cpp'",
"size": "256x256",
"ref_images": [
"https://raw.githubusercontent.com/leejet/stable-diffusion.cpp/master/assets/flux/flux1-dev-q8_0.png"
]
}'
```
```yaml
backend: stablediffusion-ggml
cfg_scale: 1
name: flux-kontext
options:
- diffusion_model
- clip_l_path:clip_l.safetensors
- t5xxl_path:t5xxl_fp16.safetensors
- vae_path:ae.safetensors
- sampler:euler
parameters:
model: flux1-kontext-dev-Q8_0.gguf
step: 25
```
=> feat(stablediffusion-ggml): add support to ref images (flux Kontext)

core/http/endpoints/localai/backend.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
=> chore: update swagger

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, introducing the FLUX.1 [dev] model. The addition provides details about the model's features, licensing, and associated files.
* **Model details**: Added a new entry for the FLUX.1 [dev] model, a 12-billion-parameter rectified flow transformer for generating images from text descriptions. The description highlights key features such as cutting-edge output quality, competitive prompt following, and open weights for research and innovation.
* **Licensing**: The model is distributed under the `flux-1-dev-non-commercial-license`, allowing personal, scientific, and commercial usage as per the license terms.
* **Files and parameters**: Included associated files (`flux1-dev-Q8_0.gguf`, `ae.safetensors`, …
=> chore(model gallery): add flux.1-dev-ggml-q8_0

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, expanding the available models in the gallery. The main change is the inclusion of the "openai_gpt-oss-20b-neo" model, complete with metadata, description, and tested quantization file details.
* Added a new model entry `openai_gpt-oss-20b-neo` to `gallery/index.yaml`, including its icon, description, HuggingFace URL, tested quantization file (`OpenAI-20B-NEO-MXFP4_MOE4.gguf`), and SHA256 checksum.
=> chore(model gallery): add openai_gpt-oss-20b-neo

gallery/index.yaml
This pull request adds a new model entry for the Qwen3-4B-Instruct-2507 model to the `gallery/index.yaml` file. The entry includes metadata, download URLs, a description of the model's improvements, and the file details for the model weights.
Model catalog update:
* Added a new entry for the `qwen_qwen3-4b-instruct-2507` model, including its description, download URLs, and file details (`gallery/index.yaml`).
=> chore(model gallery): add qwen_qwen3-4b-instruct-2507

docs/content/docs/advanced/advanced-usage.md, docs/content/docs/faq.md, docs/content/docs/features/embeddings.md, docs/content/docs/features/openai-functions.md, docs/content/docs/getting-started/models.md, docs/content/docs/whats-new.md
This PR fixes links in advanced-usage and models documentation
=> docs: update links in advanced-usage and models documentation

.github/workflows/backend.yml, Dockerfile, Makefile, backend/index.yaml, backend/python/common/libbackend.sh, backend/python/diffusers/requirements-l4t.txt
Add support for `diffusers` on `nvidia-l4t`.
=> feat(diffusers): add builds for nvidia-l4t

backend/python/diffusers/requirements-l4t.txt
=> fix(l4t-diffusers): add sentencepiece

gallery/index.yaml
This pull request adds a new model entry, "impish_nemo_12b", to the `gallery/index.yaml` file. The addition includes comprehensive metadata, download links, a detailed description, and file information for the new model.
* Added a new model entry `impish_nemo_12b` with metadata, description, icon, HuggingFace URLs, and file download details to `gallery/index.yaml`.
=> chore(model gallery): add impish_nemo_12b

backend/cpp/llama-cpp/Makefile
This PR fixes https://github.com/mudler/LocalAI/issues/6044
=> fix(llama.cpp): support gfx1200

.github/workflows/backend.yml, .github/workflows/image-pr.yml, .github/workflows/image.yml, backend/cpp/llama-cpp/Makefile
Fixes: https://github.com/mudler/LocalAI/issues/6044
=> chore(rocm): bump rocm image, add gfx1200 support

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, expanding the available models with a new variant of Gemma 3. The addition includes metadata, download links, a description, model parameters, and file information for the new model.
**New model addition:**
* Added a new model entry `thedrummer_gemma-3-r1-12b-v1` to `gallery/index.yaml` with its icon, Hugging Face URLs, description, model parameter overrides, and file details including filename, SHA256 checksum, and URI.
=> chore(model gallery): add thedrummer_gemma-3-r1-12b-v1

gallery/index.yaml
This pull request updates the `gallery/index.yaml` file to add a new model entry and correct a typo in an existing model's URI. The main changes focus on expanding the gallery with the new Gemma 3 4B model and ensuring accurate resource referencing.
**Model additions:**
* Added a new entry for `thedrummer_gemma-3-r1-4b-v1`, including its icon, Hugging Face URLs, description, model parameters, and associated file metadata.
**Bug fixes:**
* Corrected a typo in the URI for the existing `TheDrummer_Gemma-3-R1-12B-v1-Q4_K_M.gguf` model, changing `bartowski` to `bartowki` to match the intended Hugging Face username.
=> chore(model gallery): add thedrummer_gemma-3-r1-4b-v1

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, expanding the available models in the gallery with a high-rated 8B parameter model. The new entry includes detailed metadata, multiple download sources, and a descriptive overview of the model's strengths.
* Added a new model configuration for `wingless_imp_8b-i1`, including its name, icon, download URLs, description, parameter overrides, and associated file details.
=> chore(model gallery): add wingless_imp_8b-i1

backend/python/coqui/requirements-cpu.txt, backend/python/coqui/requirements-cublas11.txt, backend/python/coqui/requirements-cublas12.txt, backend/python/coqui/requirements-hipblas.txt, backend/python/coqui/requirements-intel.txt
=> Revert "chore(deps): bump torch from 2.3.1+cxx11.abi to 2.8.0 in /backend/python/coqui"

.github/workflows/backend.yml, backend/index.yaml
This PR adds a CPU variant for the diffusers backend
=> feat(backends): add CPU variant for diffusers backend

Dockerfile
As we bundle python as part of the backends, this shouldn't be required anymore in the base image
=> chore(Dockerfile): drop python from images

gallery/index.yaml
This pull request adds support for two new OpenGVLab InternVL3_5-14B models to the `gallery/index.yaml` file. These additions expand the available model options and include all necessary metadata for integration.
**New model additions:**
* Added `opengvlab_internvl3_5-14b-q8_0` model entry, including URLs, model parameters, associated `mmproj` file, and SHA256 checksums for both files.
* Added `opengvlab_internvl3_5-14b` model entry, including URLs, model parameters, associated `mmproj` file, and SHA256 checksums for both files.
=> chore(model gallery): add opengvlab_internvl3_5-14b

.github/workflows/backend.yml, .github/workflows/backend_build_darwin.yml, .github/workflows/backend_pr.yml, Makefile, backend/go/stablediffusion-ggml/.gitignore, backend/go/stablediffusion-ggml/CMakeLists.txt, backend/go/stablediffusion-ggml/Makefile, backend/go/stablediffusion-ggml/package.sh, backend/go/whisper/CMakeLists.txt, backend/go/whisper/Makefile, backend/go/whisper/package.sh, scripts/build/golang-darwin.sh, scripts/changed-backends.js
Try to build some Go based backends on Darwin
I haven't tested the resulting executables yet.
=> chore(ci): Build some Go based backends on Darwin

backend/index.yaml
This PR is a follow-up of https://github.com/mudler/LocalAI/pull/6164
=> chore(backends): add stablediffusion-ggml and whisper for metal

gallery/index.yaml
This pull request adds a new model entry for `nousresearch_hermes-4-70b` to the `gallery/index.yaml` file. The change introduces support for a frontier reasoning model based on Llama-3.1-70B, including metadata, download links, a description, and configuration for use in the gallery.
**New model addition:**
* Added a new entry for `nousresearch_hermes-4-70b`, including its name, icon, description, download URLs, and configuration overrides. This model features hybrid reasoning, improved math/code/STEM performance, schema adherence, and enhanced steerability.
* Included the GGUF file reference and its SHA256 checksum for model integrity verification.
=> chore(model gallery): add nousresearch_hermes-4-70b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The main change is the inclusion of the `aurore-reveil_koto-small-7b-it` model, which is designed for roleplaying and instruct use cases.
* Added a new entry for the `aurore-reveil_koto-small-7b-it` model, including metadata such as license, tags (gguf, GPU, CPU, text-to-text), icon, description, download URLs, parameter overrides, and file details.
=> chore(model gallery): add aurore-reveil_koto-small-7b-it

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The main change is the inclusion of the `invisietch_l3.3-ignition-v0.1-70b` model, which is designed for creative roleplay and fiction writing. The entry includes metadata, download links, and a description of the model's capabilities.
* Added the `invisietch_l3.3-ignition-v0.1-70b` model to the gallery, including its icon, name, download URLs, description, parameter overrides, and file information. This model is a Llama 3.3-based merge optimized for creative writing, with support for detailed character cards and system prompts, and tested for coherence up to ~64k context.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of …
=> chore(model gallery): add invisietch_l3.3-ignition-v0.1-70b

gallery/index.yaml
This pull request adds a new model entry for "nousresearch_hermes-4-14b" to the `gallery/index.yaml` file, expanding the available models and providing detailed information and metadata for users.
* Added a new model entry `nousresearch_hermes-4-14b` with a custom icon, multiple download URLs, and a comprehensive description highlighting its features, training improvements, and reasoning capabilities.
* Specified model parameters and provided a downloadable GGUF file with its SHA256 checksum and URI for easy access.
=> chore(model gallery): add nousresearch_hermes-4-14b

core/cli/worker/worker.go, core/cli/worker/worker_llamacpp.go, core/cli/worker/worker_p2p.go
=> fix(p2p): automatically install llama-cpp for p2p workers

cmd/local-ai/main.go, docs/content/docs/features/GPU-acceleration.md
This PR corrects several minor typos in comments and documentation across the codebase. The changes are non-functional and purely textual to improve clarity and maintain a clean, professional codebase.
- Corrected misspellings:
- `variabled` → `variables`
- `compatability` → `compatibility`
These fixes help enhance readability and eliminate minor distractions during development and code reviews.
No logic or functionality has been modified. All changes are restricted to comments or non-executable doc annotations.
=> Fix Typos in Docs

gallery/index.yaml
This PR add  latest MiniCPM-V 4.5 (supported [here](https://github.com/ggml-org/llama.cpp/commit/c4e9239064a564de7b94ee2b401ae907235a8fca)) to the gallery index. Maybe MiniCPM-V 2.6 can be replaced in aio and vision default models. For now let's just add the model support
=> chore(model gallery): add MiniCPM-V-4.5-8b-q4_K_M

gallery/index.yaml
This pull request adds a new model entry for ERNIE-4.5-21B-A3B-Thinking to the `gallery/index.yaml` file. The update introduces detailed metadata and configuration for the model, making it available for use and discovery in the gallery.
* Added a new entry for `baidu_ernie-4.5-21b-a3b-thinking` with metadata including license, tags (such as `gguf`, `GPU`, `CPU`, `text-to-text`), icon, and URLs for more information and downloads.
* Included a comprehensive description highlighting the model's improved reasoning capabilities, efficient tool usage, and enhanced long-context understanding.
* Specified model override parameters and provided the filename, SHA256 checksum, and URI for the downloadable model file.
**[Signed …
=> chore(model gallery): add baidu_ernie-4.5-21b-a3b-thinking

gallery/index.yaml
This pull request adds a new model entry for `holo1.5-7b` to the `gallery/index.yaml` file, enhancing the gallery with an additional option for Computer Use (CU) agents. The new entry includes metadata, model files, and a detailed description highlighting the model's capabilities and supported benchmarks.
* Added a new `holo1.5-7b` entry with metadata, icon, Hugging Face URLs, and a comprehensive description of its strengths in UI localization and UI-based question answering for web, desktop, and mobile environments.
* Specified model overrides and listed associated files (`Holo1.5-7B.Q4_K_M.gguf` and `Holo1.5-7B.mmproj-Q8_0.gguf`) with their SHA256 checksums and Hugging Face URIs.
**[Signed …
=> chore(model gallery): add holo1.5-7b

gallery/index.yaml
This pull request adds a new multimodal model entry to the `gallery/index.yaml` file, expanding the available models with enhanced visual-language reasoning capabilities.
**Model additions:**
* Added a new entry for the `webwatcher-32b` model, including its name, icon, description, relevant Hugging Face URLs, and file details.
* Specified model override parameters and associated GGUF files for `webwatcher-32b`, enabling support for its multimodal features.
=> chore(model gallery): add webwatcher-32b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, expanding the available model selection for users. The main change is the introduction of the "Impish_QWEN_14B-1M" model, which is described as a highly compliant, roleplay-focused model with a large context window.
* Added a new model entry `impish_qwen_14b-1m` with custom icon, multiple HuggingFace URLs, a descriptive summary emphasizing its roleplay and compliance features, and file details including SHA256 checksum and download URI.
=> chore(model gallery): add impish_qwen_14b-1m

.github/workflows/backend.yml, backend/index.yaml, backend/python/kokoro/requirements-l4t.txt
This PR adds support for kokoro to l4t devices (such as Nvidia AGX Orin, Nvidia Thor, etc)
=> feat(kokoro): add support for l4t devices

backend/python/coqui/requirements-cpu.txt, backend/python/coqui/requirements-cublas11.txt, backend/python/coqui/requirements-cublas12.txt, backend/python/coqui/requirements-hipblas.txt, backend/python/coqui/requirements-intel.txt
=> Revert "chore(deps): bump transformers from 4.48.3 to 4.56.2 in /backend/python/coqui"

gallery/granite4.yaml, gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, expanding the available model options in the gallery. The new entry describes the IBM Granite-4.0-H-Small model, including its metadata, download links, and file information.
* Added a new model entry for `ibm-granite_granite-4.0-h-small`, including its description, tags, license, icon, download URLs, and file details, making it available for selection and use in the gallery.
=> chore(model gallery): add ibm-granite_granite-4.0-h-small

gallery/index.yaml
This pull request adds a new model entry for Granite-4.0-H-Micro to the `gallery/index.yaml` file. The update introduces a detailed description and download information for the model, making it available for selection and use.
* Added a new entry for the `ibm-granite_granite-4.0-h-micro` model, including its name, URLs, a comprehensive description, model parameter overrides, and associated file metadata.
=> chore(model gallery): add ibm-granite_granite-4.0-h-micro

core/http/endpoints/openai/chat.go
When strict mode is enabled, besides enabling grammar, force the LLM to pick always a tool
=> fix: add strict mode check for no action function

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file, introducing the "lemon07r_vellummini-0.1-qwen3-14b" model. The addition includes metadata, download links, a description, parameter overrides, and file information for the model.
* Added a new model entry named `lemon07r_vellummini-0.1-qwen3-14b` with a detailed description, Hugging Face download URLs, model parameter overrides, and file metadata (filename, SHA256, and URI) to `gallery/index.yaml`.
=> chore(model gallery): add lemon07r_vellummini-0.1-qwen3-14b

gallery/index.yaml
This pull request adds a new model entry to the `gallery/index.yaml` file. The main change is the inclusion of the `liquidai_lfm2-350m-math` model, which is designed for solving challenging math problems.
* Added a new entry for the `liquidai_lfm2-350m-math` model, including download URLs, a description, parameter overrides, and file details such as filename, SHA256 hash, and URI.
=> chore(model gallery): add liquidai_lfm2-350m-math

docs/content/docs/features/mcp.md
This PR adds an example in the MCP section of the docs
=> chore(docs): add MCP example

backend/python/chatterbox/backend.py
This PR adds spitting audio in chunks for tts generation with chatterbox if the text exceeds the supported limit (chatterbox has a limit of ~300 characters).
=> fix(chatterbox): chunk long text
